### ISSUE TITLE
Not compatible with Daydream.

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#10]
Hi just to let you know that your application is not fully compatible with the Google PIXEL and Daydream Headset.

I have seen a pop up to tell me that's incompatible.

That's just for feedback if you want to update your app :)

Cheers

**Comment by manbod** [comment]
Hi, thanks for feedback. Our Viro Media testbed app is compatible with Cardboard on Android and iOS for development purposes. To test your app with a Daydream headset, you will need to build your app using Android Studio. Instructions for setting up Android studio can be found here http://docs.viromedia.com/docs/installing-viro-android
