### ISSUE TITLE
extrusionDepth in ViroText renders wrong when it located inside of ViroFlexView

### ISSUE THREAD

**Issue by illlama** [viromedia/viro#1002]
- [v] Review the documentation: https://docs.viromedia.com/
  - [v] Search for existing issues: https://github.com/viromedia/viro
  - [v] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on? 17
3. Version: ^2.23.0 / ^0.72.5
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc) iPhone14Pro

## Description
When the ViroText is located inside of ViroFlexView, 3D text runs wierd.
```jsx
<ViroFlexView
      onDrag={(positionValue) => handlePositionState(positionValue)}
      onPinch={(pinchState, scaleFactor) => handleScaleState(pinchState, scaleFactor)}
      position={positionState}
      rotation={rotation}
      height={6}
      width={7}
      scale={[scaleState, scaleState, scaleState]}
    >
        <ViroText
          text={restoreNewLinesAndTabs(text)}
          materials={[`${colorName}Main`, `${colorName}Main`, `${colorName}Sub`]}
          style={{
            flex: 1,
            fontFamily: fontFamily,
            fontSize: 70,
            fontWeight: '700',
            textAlign: 'center'
          }}
          extrusionDepth={7}
        />
  </ViroFlexView>
```
if I remove ViroFlexView, it renders fine.
But I should use ViroText twice inside of a view.
Do you know why this issue occurs?

## Reproducible Demo
![IMG_8973](https://github.com/viromedia/viro/assets/13018853/bb9b34dd-9d3d-4b2f-bd38-09bf726c67bb)

Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by jerryCh254** [comment]
How are you getting it closed?
