### ISSUE TITLE
React Native AR Gaze interaction

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#101]
Is there possible to use Gaze interaction with objects in React Native AR? Would really like to show some extra information on an object when the user points the camera at it.

**Comment by dthian** [comment]
Hey Carl, thanks for your great suggestion! Unfortunately, we currently do not natively support gazing interaction callbacks for AR, but will definitely consider adding that feature in upcoming releases.

One possibility, is that you might be able to achieve a similar effect through the combination of appending a physics body to your 3dObject, and then performing a hit test from the camera. However, note that this is a very involved, and untested alternative that may not work.

**Comment by cjrorvik** [comment]
I see! Will definitely have a look at how I can make it work with physics to a a 3dObject. Would really appreciate the gaze interaction! Do you know approximately at what time that will be added? Weeks or months?

**Comment by cjrorvik** [comment]
That would be great! 😄

**Comment by achuvm** [comment]
Hi @cjrorvik,

With our latest release https://docs.viromedia.com/v2.2.0/docs/releases we have enabled `onHover` callbacks in AR which uses the center of the camera.

Let us know if you have any other issues!

**Comment by cjrorvik** [comment]
Works great @achuvm ! Thanks :) Just have one little suggestion. Maybe it could be possible to set how large you want the diameter of the gaze interaction to be? Works well now, but it would be nice I could make the center a little bit bigger :)
