### ISSUE TITLE
Android on windows - black screen and content not loaded as per sourcecode

### ISSUE THREAD

**Issue by jsklepek** [viromedia/viro#105]
Hi, 

I have just finished "Quick Start (**Windows**)"

project setup, device connected, npm start.
When I open viro app following is happening to me:

When I enter IP I get to screen say Hello World Andy! **with black background**
I am expecting to see completely different text because I edited the HelloWorldScene.js and changed text and image. If I switch back to old image it is also black and text is not corresponding to source code. 

Note.
phone and laptop are on same network (I am developing normally RN apps...)

Thanks,
Jonas

**Comment by jsklepek** [comment]
this is what I see if I run it using react-native run-android
![screenshot_20171206-161935](https://user-images.githubusercontent.com/15360449/33668911-5899a7ce-daa1-11e7-89eb-3477090fa1b0.png)

**Comment by jfbguy** [comment]
Could you say what you did to fix this. I have this issue right now as well.

**Comment by dthian** [comment]
Hey jfbguy, have you put in the API_KEY for your viro app? If so, could you try clearing the cache of the app and restarting it on the phone?
