### ISSUE TITLE
NativeModules.VRTNodeModule.getNodeTransform is not a function

### ISSUE THREAD

**Issue by draperunner** [viromedia/viro#109]
I am using `getTransformAsync` on a `Viro3DObject`, but I get the warning 
> TypeError: NativeModules.VRTNodeModule.getNodeTransform is not a function

I am using react-native version 0.50.3 and react-viro 2.1.0, running on a Samsung 8.

**Comment by VikAdvani** [comment]
Hi @draperunner, this is a known bug on Android. This will be fixed in our next release.

**Comment by achuvm** [comment]
Hi @draperunner,

This issue is now fixed in our Viro React v2.2.0 release:
https://docs.viromedia.com/v2.2.0/docs/releases

Let us know if you have any other issues!

**Comment by draperunner** [comment]
Great! I am currently not using `getTransformAsync`, so I'll just close this issue and re-open if I have problems in the future.
