### ISSUE TITLE
Does viro support to get asset from the WEB?

### ISSUE THREAD

**Issue by johnzhou1** [viromedia/viro#11]
Does viro support to get assets such as 3D object, pano-pic, pano-video from the web?

Or we must store all the assets in local storage?

**Comment by VikAdvani** [comment]
Hi @johnzhou1,
Yep, Viro does support using assets from the web, you do not need to store all your assets locally.  I've listed some of examples of how do this for various asset types below.

3DObject example using a web asset:
 ```
<Viro3DObject source={{uri:"https://s3-us-west-2.amazonaws.com/viro/heart.obj"}}
          position={[-1.7 , -4.3 , -4.65]}
          rotation={[0,0,0]}
          scale={[1.8 , 1.8  , 1.8]} />
```

Image example using web asset:
```
 <ViroImage  position={[0, 1, -3]}
            source={{uri:"https://s3-us-west-2.amazonaws.com/viro/Explorer/360_horseshoe.jpg"}} />

```

Video using web asset: 
```
 <Viro360Video 
          source={{uri:"https://example.com/myvideo.mp4"}}  />

```
Hope that helps!

**Comment by johnzhou1** [comment]
That's great! Thanks a lot.

**Comment by harpalgupta** [comment]
Hi this sounds relevant to our project can you show us an example using other remote assets to go with the OBJ (mtl, png) we have unable to get these working, we get a white object but using the same files locally in res directory works fine.

Thanks in advance

**Comment by dam00n** [comment]
This might be an asset file name or file structure issues. See this issue for more details -> https://github.com/viromedia/viro/issues/488

**Comment by silvainSayduck** [comment]
FYI, the docs might need to be updated, as it states [here](https://docs.viromedia.com/docs/3d-objects) that:

> 3D models must be loaded from the application bundle.
![](https://i.imgur.com/WWLlLrQ.png)

This would have been a dealbreaker for me, so I'm pleased to see that it is not the case :)

(And it's also missing that glTF is now supported I guess)

**Comment by dam00n** [comment]
Thanks for the call out. Docs have been updated.

**Comment by masierraf** [comment]
> Hi this sounds relevant to our project can you show us an example using other remote assets to go with the OBJ (mtl, png) we have unable to get these working, we get a white object but using the same files locally in res directory works fine.
> 
> Thanks in advance

Did you find some solution?, Im getting same issue

**Comment by georgecirilo** [comment]
Hello. Since glTF files specifies it's asset relative path within the file, how are we supposed to get them referenced when downloading from the server? Should we make a local copy of all of them or there is a more dynamic way of doing this?
