### ISSUE TITLE
[QUESTION] Render AR object only after scaning a specific picture / shape

### ISSUE THREAD

**Issue by stajics** [viromedia/viro#110]
The task i am trying to complete is to render a simple object in AR view but only after scanning a specific picture or a shape. For example scanning a red triangle on a pice of paper would render a shape above it.

Can somebody with more experience in AR point me on how hard / easy (or possible) that is? Not looking for a implementation , just a general guideline.

**Comment by VikAdvani** [comment]
Hi @stajics, 

You can use an image tracking cloud or client service that can give you a 2d bounding box of the object you are trying to recognize. Then if you know the actual size of the object and the FOV(field of view) of the camera on the device you can use those variables with some math to project a point in 3d space which you can use to anchor your objects near or around the actual object.

We are looking into ways to make this easier within the Viro platform. But for now, the above should give you a starting point for implementing your use case.

**Comment by stajics** [comment]
Thanks for the answer.

Can I get those variables using Viro platform components now? Or i will need to tinker with the native code too?

**Comment by VikAdvani** [comment]
Hi @stajics, 
You'll have to use a client service or cloud service to provide you a 2d bounding box of the image you want recognized.  Regarding the FOV, you would need to write a native module to get this.

**Comment by dam00n** [comment]
Closing this issue, please reopen if the solution provided did not work or you need additional assistance on this topic.
