### ISSUE TITLE
Lighting for ViroFlex

### ISSUE THREAD

**Issue by rafthedeveloper** [viromedia/viro#114]
Are there any examples of how to apply a spotlight to a ViroFlex object?

**Comment by VikAdvani** [comment]
Hi @rafthedeveloper, 

The default lighting model for every component is 'Constant' for all objects in the scene, which will light the object evenly. To make the component respond to lights you'd have to add a material that defines the lighting model of the component. 

To light a ViroFlexView,  you'll need to add a material to the ViroFlexView and its children so it can receive the light. Sample below:


An example in your render function will look like:
```
  <ViroSpotLight
            innerAngle={5}
            outerAngle={40}
            direction={[0,0,-1]}
            position={[0, 0, -.5 ]}
            color="#ff0000"
            castsShadow={true}
            shadowNearZ={.1}
            shadowFarZ={6}
            shadowOpacity={.9}
            intensity={1500}
            attenuationStartDistance={5}
            attenuationEndDistance={10}
          />
        <ViroFlexView materials="test_material" style={styles.containerHorizontal} position={[-2, 0, -3]} width={3} height={2} transformBehaviors={"billboard"} >
          <ViroImage materials="test_material" style={{flex:1}} source={{uri: "http://wiki.magicc.org/images/c/ce/MAGICC_logo_small.jpg"}} />
          <ViroImage materials="test_material" style={{flex:1}} source={{uri: "http://wiki.magicc.org/images/c/ce/MAGICC_logo_small.jpg"}} />
        </ViroFlexView>

```

The materials will be defined after your class like following:
```
ViroMaterials.createMaterials({
  test_material: {
    shininess: 2.0,
    lightingModel: "Blinn",
    diffuseColor: "#ffffff"
  }
});

```
The above assigns the material 'test_material' to each component to the ViroFlexView so it responds to the light. The lightingModel that'll be used is Blinn and the material color is white #ffffff. 

You can learn more here about our lighting models here: 
https://docs.viromedia.com/docs/3d-scene-lighting

Let me know if you have any more questions. Thanks!

**Comment by dam00n** [comment]
Closing issue as solution was provided.
