### ISSUE TITLE
How to change rotation of Viro360Image

### ISSUE THREAD

**Issue by RickyHa** [viromedia/viro#116]
<Viro360Image
          rotation={[0, 90, 0]}
          source={{ uri: 'https://d36tnp772eyphs.cloudfront.net/blogs/1/2006/11/360-panorama-matador-seo.jpg' }}
          onSwipe ={() =>
/* Change this image rotation at here*/
          }
        />

**Comment by dthian** [comment]
Hey @RickyHa, we've actually answered this question at https://github.com/viromedia/viro/issues/103, with a few code samples have been given on that issue that should be helpful as well. 

In efforts to focus our support in one place, please feel free to post any questions on that issue if you have any problems implementing this feature.

**Comment by dam00n** [comment]
Closing this issue as a solution has been provided. Please reopen if you are having problems.
