### ISSUE TITLE
Share your thoughts on upcoming releases

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#119]
Hi! 

Could it be possible for you guys to share on your website, or here, what features you are working on and what we can look forward to in upcoming releases? And maybe also and estimated release date. Would really appreciate that so that we are not trying to hack around to make something work if it will be included in an upcoming release 😄 

That would be great! Keep up the good work!

**Comment by dam00n** [comment]
Hi @cjrorvik, this is a good idea. Let me sync up with the team and see what is the best way to report/communicate this. Will update this issue once we have a plan of action. Thanks - Danny

**Comment by cjrorvik** [comment]
That would be awesome! :D

**Comment by dam00n** [comment]
We will be sharing more details when possible on our slack and in our release notes. Those seem like the best places to keep developers updated.
