### ISSUE TITLE
On tracking initialized

### ISSUE THREAD

**Issue by rafthedeveloper** [viromedia/viro#121]
From these docs: https://docs.viromedia.com/docs/viroarscene

> Function called when the AR system has properly initialized. Until this function is called, the camera position is

The sentence is incomplete, is this [0,0,0]?

**Comment by manbod** [comment]
Hi Rafael,
Thanks for reaching out pointing this incomplete documentation! I have updated the documentation as well, but to answer your question, the camera position is unset / not in sync with the coordinated system until onTrackingInitialized is called. It is set at [0,0,0] at the moment onTrackingInitialized is called.

Thanks!

**Comment by rafthedeveloper** [comment]
Awesome!

One more question, I'm able to add objects to the scene before its initialized and I'm placing them in front of the user, how is this possible if it hasn't been initialized yet?

**Comment by manbod** [comment]
Hi Rafael,
Great question. This is explained on this page here https://docs.viromedia.com/docs/augmented-reality-ar. Specifically this section.

> When the user first enters the AR experience, the camera will remain at [0,0,0] while underlying AR system gets its bearing. After a few moments, the camera tracking will complete, the developer should receive a callback on onTrackingInitialized in ViroARScene, and the camera should now track the user's movements around their world.

So to answer your question -  nothing changes *with* the camera per se, it’s the nodes / objects in the scene that would move as the camera moves (before init) vs (after init) objects moving/tracking with points in the world.

Hope that explains the setup process.

Thanks!

**Comment by rafthedeveloper** [comment]
@manbod 

Yup, answers my question perfectly, thank you so much!
