### ISSUE TITLE
Add non ViroArNode component as child to ViroArScene 

### ISSUE THREAD

**Issue by dokwon** [viromedia/viro#123]
Hi, 

How do you add a non-ViroARNode component to a ViroArScene?

For example, I am trying to get a TextInput to appear on user click, but am having trouble adding it as a child to the arscene.

**Comment by achuvm** [comment]
Hi @dokwon,

Unfortunately this is not possible, however, you can simply overlay components on top of the `Viro(AR)SceneNavigator` in the `App.js` file.

An example of this can be found on this issue where a "crosshair" is being added to AR in the form of a React Native component: https://github.com/viromedia/viro/issues/107

If you need to be able to pass data/functions/etc in/out of the ViroARScene, take a look at this question: https://github.com/viromedia/viro/issues/62. You can pass functions that trigger the appearance of the `TextInput` into your `Viro(AR)SceneNavigator` and they'll appear in your `Viro(AR)Scene` as `this.props.<key>` and you can simply invoke them there.

Let us know if a small example would help

Andy
