### ISSUE TITLE
Understanding the output of ViroARScene.getCameraOrientationAsync()

### ISSUE THREAD

**Issue by dokwon** [viromedia/viro#124]
ViroARScene has a method async getCameraOrientationAsync(): This function is used to fetch the current Camera's orientation.Return ValueDescriptionorientationan object that contains the camera's position, rotation, forward vector and up vector as number arrays | orientation

But when I print the return value of ViroArScene.getCameraOrientationAsync(), i get: 
 { _40: 0, _65: 0, _55: null, _72: null }

How should I understand this output?

**Comment by dthian** [comment]
Hi, as mentioned in [here](https://docs.viromedia.com/docs/viroscene#methods) getCameraOrientationAsync returns a dictionary of items: 

> an object that contains the camera's position, rotation, forward vector and up vector as number arrays.

Here is an example on how you can use it: 

```
this.refs["arscene"].getCameraOrientationAsync().then((orientation) => {
var forward = orientation.forward;
});
```

**Comment by dam00n** [comment]
Closing this issue as answer was provided
