### ISSUE TITLE
Properly consuming events

### ISSUE THREAD

**Issue by rafthedeveloper** [viromedia/viro#125]
Hi,

I'm having an issue with the following scenario:

- My scene has a click listener
- Each one of my nodes have a drag listener and a click listener

Whenever I drag a node, it triggers a click event on itself at the end of the drag and it bubbles up to the scene and triggers that click handler as well. I want to prevent this, what is the best way in approaching this?

**Comment by achuvm** [comment]
Hi @rafthedeveloper,

If you want to stop events from bubbling, then you can simply add a click listener that does nothing to the component that's also being dragged.

Let us know if this makes sense.

Thanks,

Andy

**Comment by rafthedeveloper** [comment]
Ah, I have that in place, seems to work. Thanks!
