### ISSUE TITLE
Error install react-viro in Windows 10.

### ISSUE THREAD

**Issue by peacemind** [viromedia/viro#126]
I followed the Quick Start (Window) to install react-viro and error message as follow:

/////
H:\GitProject\reactNative\arvr\viro\ViroSample>npm install -S -E react-viro

> weak@1.0.1 install H:\GitProject\reactNative\arvr\viro\ViroSample\node_modules\weak
> node-gyp rebuild

H:\GitProject\reactNative\arvr\viro\ViroSample\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\GitProject\reactNative\arvr\viro\ViroSample\node_modules\weak
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
ViroSample@0.0.1 H:\GitProject\reactNative\arvr\viro\ViroSample
`-- react-viro@2.2.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
////

Any idea how to fix this problem?

Thanks.

**Comment by achuvm** [comment]
Hi @peacemind,

It looks like the PYTHON env variable wasn't set correctly in your case as shown in this line:

gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

If you installed python through chocolatey by following the instructions on the React Native (setup)[https://facebook.github.io/react-native/docs/getting-started.html], then I believe that the prompt did request that you restart your computer for python to fully install.

If not, then here's a link to a stackoverflow question with the same issue:
https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies

Let us know if this solves your issue!

**Comment by peacemind** [comment]
Hi, I installed Python 2.7 with Chocolatey and restart PC.  After I installed react-viro again, I got following error message:

///
H:\GitProject\reactNative\arvr\viro\ViroSample>npm install -S -E react-viro

> weak@1.0.1 install H:\GitProject\reactNative\arvr\viro\ViroSample\node_modules\weak
> node-gyp rebuild


H:\GitProject\reactNative\arvr\viro\ViroSample\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在這個方案中一次建置一個專案。若要啟用平行組建，請加入 "/m" 參數。
MSBUILD : error MSB3428: 無法載入 Visual C++ 元件 "VCBuild.exe"。若要修正這個問題，請1) 安裝 .NET Framework 2.0 SDK，2) 安裝
Microsoft Visual Studio 2005，或 3) 將元件位置加入至系統路徑 (如果元件安裝在別的位置)。 [H:\GitProject\reactNative\arvr\viro\Viro
Sample\node_modules\weak\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\GitProject\reactNative\arvr\viro\ViroSample\node_modules\weak
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
ViroSample@0.0.1 H:\GitProject\reactNative\arvr\viro\ViroSample
`-- react-viro@2.2.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

H:\GitProject\reactNative\arvr\viro\ViroSample>
///
Thanks for the support

**Comment by achuvm** [comment]
Hi @peacemind,

This looks like an issue with the `node-gyp` package.

According to a related issue here: https://github.com/oracle/node-oracledb/issues/302

It looks like you can either:

1)  install Visual Studio 2015 and run `npm install -g --msvs_version=2015` from within `ViroSample`

OR

2) you can install the `windows-build-tools` through `npm` with `npm install --global --production windows-build-tools` and then run `npm install` in `ViroSample`

Let us know if that doesn't work for you.

**Comment by peacemind** [comment]
Hi @achuvm ,
I following the first option and still got the error message. So, I try the second option and it installed react-viro without error.  Thanks for the solutino.

Then, I did 'npm start' and run the Viro Media App for iOS.  I enter the testbad with ngrok ip address to download to my ipad 5,  I choose the AR experience but only the camera running on my ipad.  No "360 degree photo of a beach with the text "Hello World!"".  What's wrong?

**Comment by achuvm** [comment]
Hi @peacemind,

Have you added your Api key under `ViroSample/App.js`?

**Comment by peacemind** [comment]
this is my api key "835127A5-6A77-49D6-9CB2-27F481C2052D"

**Comment by achuvm** [comment]
Hi @peacemind,

This could be because AR isn't supported on your iPad, you need to have a device with an A9 Chip or up.

http://www.redmondpie.com/ios-11-arkit-compatibility-check-if-your-device-is-compatible-with-apples-new-ar-platform/

Does VR work for you? 

Thanks,

**Comment by peacemind** [comment]
I have ipad 5th, iOS 11 should support the AR.  I already run the EXPO sample AR on my ipad and it work.

**Comment by achuvm** [comment]
Hi @peacemind,

In AR you should only see text that changes from "Initializing..." to "Hello World!". The background should simply be the video from the camera.

**Comment by peacemind** [comment]
Hi,   After Vrio download the package, i got the menu to choose the VR or AR experience.  I choose the AR. It open the camera.  I didn't see the "initializing..." info.
James
 

    On Tuesday, January 2, 2018, 4:53:03 PM MST, achuvm <notifications@github.com> wrote:  
 
 
Hi @peacemind,

In AR you should only see text that changes from "Initializing..." to "Hello World!". The background should simply be the video from the camera.

**Comment by achuvm** [comment]
Hi @peacemind,

Do you see at least the"Hello World" text? Or do you only see the camera view? 

The "Initializing..." text will be replaced by "Hello World" once the AR session has initialized.

**Comment by peacemind** [comment]
No. I did not see The "Initializing..." text or "Hello World".  Only the camera view on my ipad.
 

    On Tuesday, January 2, 2018, 5:05:01 PM MST, achuvm <notifications@github.com> wrote:  
 
 
Hi @peacemind,

Do you see at least the"Hello World" text? Or do you only see the camera view?

The "Initializing..." text will be replaced by "Hello World" once the AR session has initialized.

**Comment by achuvm** [comment]
Hi @peacemind,

That's very strange. Does the `render()` function in your `ViroSample/js/HelloWorldSceneAR.js` look like the following?

```
  render() {
    return (
      <ViroARScene onTrackingInitialized={this._onInitialized} >
        <ViroText text={this.state.text} scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
      </ViroARScene>
    );
  }
```

**Comment by peacemind** [comment]
Yes. The code are the same.  I just play demo in the Viro Media App and both AR and VR are running on my ipad.  
 

    On Tuesday, January 2, 2018, 5:26:30 PM MST, achuvm <notifications@github.com> wrote:  
 
 
Hi @peacemind,

That's very strange. Does the render() function in your ViroSample/js/HelloWorldSceneAR.js look like the following?
  render() {
    return (
      <ViroARScene onTrackingInitialized={this._onInitialized} >
        <ViroText text={this.state.text} scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
      </ViroARScene>
    );
  }

**Comment by achuvm** [comment]
Hi @peacemind,

We've tested this on our end and it seems to work on the iPad, iPhone and Android devices we have here.

Can you try re-creating a Viro workspace and re-running the instructions? Maybe something got improperly set up due to the issues you ran into earlier?

Thanks,

**Comment by peacemind** [comment]
Thanks.  It's working now after I re-creating the project.
 

    On Tuesday, January 2, 2018, 6:55:01 PM MST, achuvm <notifications@github.com> wrote:  
 
 
Hi @peacemind,

We've tested this on our end and it seems to work on the iPad, iPhone and Android devices we have here.

Can you try re-creating a Viro workspace and re-running the instructions? Maybe something got improperly set up due to the issues you ran into earlier?

Thanks,

**Comment by peacemind** [comment]
Thanks.  It's working now after I re-creating the project.

**Comment by achuvm** [comment]
Glad we got it working, we'll update the docs with the issue you ran into.

Let us know if you run into any other issues!
