### ISSUE TITLE
Error message when run the 'ViroARSampleApp".

### ISSUE THREAD

**Issue by peacemind** [viromedia/viro#127]
when run "npm start" for ViroARSampleApp", the error message as follow
///
H:\GitProject\reactNative\arvr\viro\ViroARSampleApp>npm start

> ViroSampleAR@0.0.1 prestart H:\GitProject\reactNative\arvr\viro\ViroARSampleApp
> ./node_modules/react-viro/bin/run_ngrok.sh

'.' 不是內部或外部命令、可執行的程式或批次檔。

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ViroSampleAR@0.0.1 prestart: `./node_modules/react-viro/bin/run_ngrok.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ViroSampleAR@0.0.1 prestart script './node_modules/react-viro/bin/run_ngrok.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ViroSampleAR package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/react-viro/bin/run_ngrok.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ViroSampleAR
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ViroSampleAR
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     H:\GitProject\reactNative\arvr\viro\ViroARSampleApp\npm-debug.log

H:\GitProject\reactNative\arvr\viro\ViroARSampleApp>
////

Any idea?

**Comment by achuvm** [comment]
Hi @peacemind,

Yeah sorry, that project was created on OSX which uses the ngrok script.

If you open up the `package.json` file at the root of the directory, you can simply delete the `"prestart" : "./node_modules/react-viro/bin/run_ngrok.sh",` line and it should work with just the IP address.

Thanks,

**Comment by peacemind** [comment]
Thanks.  It work.

**Comment by Nethmee** [comment]
I cannot seem to find the  ngrok url which  s supposed to be printed in the terminal when npm start is executed

**Comment by bimix** [comment]
> I cannot seem to find the ngrok url which s supposed to be printed in the terminal when npm start is executed

have you managed to find it meanwhile?

**Comment by Aarlington** [comment]
> > I cannot seem to find the ngrok url which s supposed to be printed in the terminal when npm start is executed
> 
> have you managed to find it meanwhile?

I don't think ngrok is supported anymore.
