### ISSUE TITLE
Add iOS Support for ViroSpatialSound

### ISSUE THREAD

**Issue by domvon** [viromedia/viro#133]
Hi team, 

Just tried ViroSpatialSound for the first time. I basically copied and pasted the example [here](https://docs.viromedia.com/v2.2.0/docs/audio) and set the source to an mp3 file I have.  The minDistance and maxDistance don't seem to work (on iOS 11.2.1). The sound played with the same volume regardless of my position....and I moved around at least 20 meters. Any idea? Have you seen issues before? Thanks.

**Comment by domvon** [comment]
Just noticed it's not yet supported on iOS. Lmk if there are any plans to support it. Thanks.

**Comment by dam00n** [comment]
Google Resonance added support for Spatial Sounds on iOS toward the end of 2017. It is on our backlog and we do plan to support it. Will update this issue once we do our planning and have a date for release.

**Comment by dam00n** [comment]
Support for Spatial Audio on iOS was added in the latest release of ViroReact 2.4. Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

Let us know if you have any issues

**Comment by domvon** [comment]
Awesome, thanks!

-Dom
