### ISSUE TITLE
How to convert FBX to VRX inside app itself ?

### ISSUE THREAD

**Issue by KiranSNagarajaiah** [viromedia/viro#134]
Hi 

I want to know how i can convert fbx file to vrx file in android app programmatically.
Please let me know the steps.

Thank you

**Comment by radvani** [comment]
Hi @KiranSNagarajaiah, currently there is no way to convert from FBX to VRX within an app programmatically. This is because the FBX SDK (for reading FBX files) is too large to include in an app. We're looking into supporting other non-proprietary formats (e.g. gITF) in the near future.

**Comment by KiranSNagarajaiah** [comment]
Hi **@radvani** Thanks for your response , Please let me know is there any plugin available for such conversion so that we can integrate that inside. Thank you in advance.

**Comment by dam00n** [comment]
GLTF support was added in ViroReact 2.7
