### ISSUE TITLE
Plane detection offset

### ISSUE THREAD

**Issue by trikko** [viromedia/viro#137]
Using viro on android native, it seems that planes are detected with a small offset.
I placed a model and a plane inside onAnchorFound at position 0,0,0 and this is the result: 

![screenshot_20180115-105346](https://user-images.githubusercontent.com/647157/34937250-77c39774-f9e4-11e7-8bee-d41f76221a23.png)
![screenshot_20180115-105357](https://user-images.githubusercontent.com/647157/34937249-77aa1bf0-f9e4-11e7-84c3-6f8f21e7557c.png)

I'm using a google pixel 2.

**Comment by achuvm** [comment]
Hi @trikko,

There are 2 possible explanations for this:

1. The 3D model has a slight vertical offset (although if you place a plane at the same place, you should be able to tell)
2. ARCore is returning those slightly offset values, the technology isn't perfect.

As far as we know, Viro is not adjusting/modifying the raw ARCore values. However, if you do notice that Viro consistently places the objects higher than other ARCore applications, do let us know and we can investigate more.

Thanks!

**Comment by trikko** [comment]
If I use pixel 2 camera with ar stickers, it places models correctly on planes. Plane detection using virocore + arcore has a slightly offset the most of times. Is android camera using a different version/technology?

Here the same plane detected by android camera:
![tst](https://user-images.githubusercontent.com/647157/34978759-96a49cea-fa9f-11e7-9085-721f0dccf68b.gif)

**Comment by achuvm** [comment]
Interesting, Viro's currently on Arcore Preview 1 but we're looking to get out our update in the next few days with Arcore Preview 2 support which hopefully will perform better.

Thanks,

**Comment by dam00n** [comment]
@trikko wanted to see if you are still seeing this offset issue in ViroReact 2.3? Hopefully the update to ARCore Preview 2 helped.

**Comment by dam00n** [comment]
Closing this issue as we are not seeing it on our end. Please reopen if you are still experiencing the problem so we can investigate further.
