### ISSUE TITLE
minSdkVersion implications

### ISSUE THREAD

**Issue by itchingpixels** [viromedia/viro#138]
Hi!

We're thinking of implementing a AR module to an existing Android app.
The docs state that minSdkVersion needs to be at least 23 - but we're intending to support previous Android versions, where we simply would not show anything AR related.

Would using a lower minSdkVersion, while not initializing Viro on older Androids would be sufficient? Or do we need to take extra steps to not to exclude a large part of our existing users?

Thank you!

**Comment by VikAdvani** [comment]
Hi @itchingpixels, 
Viro should compile and work with minSDKVersion 21 which supports opengl ES 3.0. So what you describe should work. So you should be able to lower to 21(with AR disabled for lower versions). Let us know if this helps, thanks!
