### ISSUE TITLE
 Scene click coordinates on cardboard

### ISSUE THREAD

**Issue by dam00n** [viromedia/viro#14]
I'm looking to capture the click/tap coordinates on 360 degree scene image because I want the user to be able to position and build 2D or 3D objects on the fly. The scene has an onClick function (_onClick(source)) but there are no coordinates. The onTouch looked like it had potential but it's not supported on Cardboard. Is there a way to capture the cardboard click position on the scene? It looks like I could get the value from the onTouch event if I used a different system like Daydream.

**Comment by VikAdvani** [comment]
You are correct we don't give the exact position of the collision in the onClick callback yet, however we do provide the forward vector of the controller or reticle. Using <ViroController> you can scale the forward vector by x distance to get a position in 3d space that represents where the user clicked on the scene.

Below is some example code, which on a scene click, takes the forward vector from the controller and draws a box in 3d space where the user clicked. The will box will be drawn 8 meters away from where the users reticle is pointing.

Hopefully the below will achieve what you want for now! If you any additional questions let us know. Thanks!
```
import {
  ViroScene,
  ViroMaterials,
  ViroController,
  ViroBox,
} from 'react-viro';

var currentBoxes = [];
var DropTest = React.createClass({
  getInitialState() {
    return {
        boxes:[],
    };
  },

  render: function() {
    return (
     <ViroScene onClick={this._onSceneClick}>
        <ViroController ref="controller" reticleVisibility={true} controllerVisibility={true} />
        {currentBoxes}
     </ViroScene>
    );
  },

  _onSceneClick() {
    this.refs["controller"].getControllerForwardAsync().then((position) => {
        var collisionPoint = [];
        collisionPoint[0] = position[0] * 8;
        collisionPoint[1] = position[1] * 8;
        collisionPoint[2] = position[2] * 8;
        currentBoxes.push(<ViroBox position={collisionPoint} materials="whiteClear" />);
        this.setState({
            boxes: currentBoxes,
        });
    });
  },
});

ViroMaterials.createMaterials({

  whiteClear : {
    diffuseColor : "#aaaaaa33"
  },
});

module.exports = DropTest;
```
