### ISSUE TITLE
Use ViroARPlane and other Viro Objects on a static photo

### ISSUE THREAD

**Issue by weswes** [viromedia/viro#140]
I would like to be able to use all viro capability for AR but on a static photo (of the real world).
Is it possible ?

**Comment by dam00n** [comment]
Hi @weswes, you can add a 360 photo to your AR scene. This will make the background of your scene into that 360 photo. Is that what you are looking for?

https://docs.viromedia.com/docs/viro360image

**Comment by weswes** [comment]
Not exactly, I would like to use a non 360 photo just to use the same capabilities of adding 3D objects on it than with the camera.

**Comment by dam00n** [comment]
Thanks for the clarification. Sounds like you want to use markers/image tracking. We do not support that natively yet, but are working on it. We are tracking the feature here -> https://github.com/viromedia/viro/issues/78

Let us know if this is still not the feature you are requesting and if you can provide more details.

**Comment by dam00n** [comment]
Closing this issue as we are tracking the feature request here -> https://github.com/viromedia/viro/issues/78
