### ISSUE TITLE
How can I access model and camera matrices ?

### ISSUE THREAD

**Issue by pritasam** [viromedia/viro#142]
Hi, 
I have a webview where I am showing my 3D model. I want to use Viro ar  kit to track plane and then send the model and camera matrices  to webview to render(Show) model....How can I access these matrices ?

Thanks,

**Comment by radvani** [comment]
Hi @pritasam, we currently don't have a way to access the model and camera matrices directly. However, ViroScene has a method getCameraOrientationAsync that can be used to get the camera's position, rotation, forward vector, and up vector. You can use those to reconstruct a camera matrix.
