### ISSUE TITLE
ViroText fontWeight?

### ISSUE THREAD

**Issue by draperunner** [viromedia/viro#143]
Hi!

I would like to have some text bold. I tried specifying `fontWeight: '600'` in my ViroText's style object, but apparently that is not a supported property.

Is there a way for me to achieve this in v2.2.0, or might it come in an upcoming release?

**Comment by VikAdvani** [comment]
Hi @draperunner,

Currently fontWeight isn't a supported property. However, we plan to add this in a future release.
For now, on iOS at least you  can usually append "-Bold" to the font you are trying to use.

Below are a list of fonts supported in React Native that have the bold postfix:
https://github.com/react-native-training/react-native-fonts

Let me know if you have any more questions. Thanks!

**Comment by draperunner** [comment]
Thanks. We had success using the fonts from the link you provided with "-Bold" appended. But we were not able to use our own custom font, although it is split in `xxx-Bold.otf`, `xxx-BoldItalic.otf`, and so on.

We'll make do with one of the custom fonts for now!

**Comment by dam00n** [comment]
We added FontWeight for ViroText in ViroReact v2.5.1. Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

API Reference -> https://docs.viromedia.com/docs/virotext2#section-style-and-weight

**Comment by draperunner** [comment]
Awesome! Looks like a great release. We'll test the fontWeight as soon as we upgrade.
