### ISSUE TITLE
Unsupported top level event type "onDragViro" dispatched

### ISSUE THREAD

**Issue by AppPear** [viromedia/viro#145]
Hi, I tried to implement dragging into a Viro3DObject, and it drags although an error pos-up as soon as I start dragging it saying "Unsupported top level event type "onDragViro" dispatched". Any ideas how could I solve this?

Thanks Andras

 ![](http://oi66.tinypic.com/2hpsidd.jpg)

**Comment by achuvm** [comment]
Hi @AppPear,

Thanks for reporting this issue.

This looks like an issue on Android devices with React Native v0.50.3 and up:
https://github.com/facebook/react-native/issues/16522

We've tested and have verified that Viro works with React Native v0.49.3, so you can try downgrading. The link above does seem to mention that later versions of React Native may work, but again, we've only tested against v0.49.3.

We'll look into updating to support newer React Native for our next release.

Thanks,

**Comment by AntoniaBe** [comment]
Hi,

I'm also getting this error message. Any updates?
I'm using React Native v0.55.1

thanks

**Comment by achuvm** [comment]
Hi @AntoniaBe,

This looks like a bug on our platform, a workaround you can do is to simply import a `ViroNode` and then add an empty `<ViroNode />` component to your scene.

That should load most, if not all, the events and get around this issue.

We'll fix this again in our next release!

Thanks,
