### ISSUE TITLE
Position of ViroFlexView differs on Android and iPhone

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#149]
It seems like position of ViroFlexVIew, at least, for nested ViroFlexView seems to differ on iPhone 8 and a Samsung S8 in the AR space.

**Comment by VikAdvani** [comment]
Hi @cjrorvik, can you give some example code for how your flexview is structured? This way we can reproduce what you are seeing. If possible, screenshots would help as well 👍 

Thanks!

**Comment by dam00n** [comment]
Hi @cjrorvik are you still seeing this issue? If you can provide more details we can look into it. Otherwise let us know if you are no longer experiencing the issue.

**Comment by cjrorvik** [comment]
Hi! Looks kind of similar on both iPhone and Android now. So I think we can just close it. I'll specify more in detail if we still experiencing it ;)
