### ISSUE TITLE
Any method to support flv live stream in current viro

### ISSUE THREAD

**Issue by AaronTYZ** [viromedia/viro#150]
By the latest react-viro v2.3.0，flv live stream seems not supported.Otherwise, it is supported well by exoplayer.
Any method to make viro support that， such as replacing some depandecies libs or config modifing?
Any plan to support flv live stream in the funture?

Great repect for the framework^_^

**Comment by dthian** [comment]
Thanks @AaronTYZ! :D

I'm currently not aware of any FLV support within Exoplayer natively. Could you pease point us to the source or a link to where you might see this format being supported? Much thanks!

**Comment by AaronTYZ** [comment]
Thanks for ur reply

Its our private live stream which needs directed granted.Can I have ur public network ip，so my mate can open permissions for you?
On the other hand, We have tested that in expo player r2.6.1 before where flv live stream is well supported.

I think it will be good if we can take mail exchange^0^

**Comment by AaronTYZ** [comment]
@dthian

**Comment by AaronTYZ** [comment]
Hi @dthian ,we have found and solved the problem.Thats because exoplayer r2.2.0 not support flv live stream due to a small bug in it.We fixed the bug, and recompile and it works:D

Viro is good, but I think it will be better if not depend on the special version of exoplayer or gvr, or give some guide for users to upgrade exoplayer and gvr as they need on the website😄

**Comment by dthian** [comment]
Hi @AaronTYZ, thanks for looking into this! It sounds like upgrading the Exoplayer to the latest may solve the lack of FLV support. We'll test this, and then if so consider upgrading Exoplayer in upcoming releases of Viro. I'll update this thread once with more details soon.

Out of interests, what was the patch you applied to r2.2.0, and how were you able to apply and recompile it with viro?

**Comment by AaronTYZ** [comment]
@dthian hi, the bug is caused by AMFType judge where they throw exception when the type equals ECMA_ARRAY in function "ParsePayload", what is fixed in r2.6.1 and can be easily found by comparing the source codes😄

To achive this, we just repackage the fixed exoplayer to a local aar file, and recomplie it from local "libs".
At first we tried replace the depandency in build.gradle of r2.6.1, but there seems many other depandencies which may leads compile error or APP coredump.I cant solve the complex depandencies, so I had to try to view the source code- -

**Comment by kikakkz** [comment]
Exoplayer 2.2.0 throw exception to an unimportant FLV meta error. In new exoplayer, it's ignored, ^_^.  AaronTYZ is my brother, ^_^
