### ISSUE TITLE
3D Object Tracking - Feature Request

### ISSUE THREAD

**Issue by dam00n** [viromedia/viro#151]
Feature request for 3D Object tracking in AR. Will update this issue once we have more info on progress.

**Comment by gmcdaniel-espi** [comment]
This is needed. Thank you.

**Comment by dam00n** [comment]
We recently released beta support for ARKit 2.0 (developer preview). This provides ViroReact developers with early access to ARKit 2.0 features including ARKit's Object Marker feature. You will not be able to publish apps using ARKit 2.0 until Apple releases it to the public. This is a developer preview for iOS only.

Installation instructions and notes here -> https://docs.viromedia.com/v2.9.0/docs/enable-arkit-20-beta-features
