### ISSUE TITLE
Text disappears with textLineBreakMode="justify" on Android

### ISSUE THREAD

**Issue by draperunner** [viromedia/viro#153]
Hi!

We have a ViroText that disappears on Android, using react-viro v2.3.0, when using `textLineBreakMode="justify"`. It shows if we use any of the other `textLineBreakMode`s or omit the prop. On iOS, it shows fine with `"justify"`.  

The text is the inner one in this structure:
```
<ViroNode
         viroTag={id}
         key={id}
         position={position}
         physicsBody={{
                   type: 'dynamic',
                   mass: 100,
                   friction: 900,
                   shape: {
                         type: 'sphere',
                         params: [shapeSize],
                   },
           }}
           transformBehaviors={["billboardY"]}
       >
           <Viro3DObject
                   source={objSource}
                   resources={[mtlSource]}
                   onHover={ (e) => this.onHover(nearby, e)}
                   height={objectSize}
                   length={objectSize}
                   width={objectSize}
                   type="OBJ"
           />
           <ViroFlexView
                   position={[0, iconTextPosition, 0]}
                   width={5}
                   height={10}
           >
                   <ViroText
                         text="This is the awesome text that does not show with textLineBreakMode justify"
                         style={styles.lightText}
                         textLineBreakMode="justify"
                         scale={textScale}
                   />
          </ViroFlexView>
</ViroNode>
```

**Comment by draperunner** [comment]
Seems like `textLineBreakMode="justify` works when the ViroText has a specified `height`! If there's no height specified, the text does not show. If using another `textLineBreakMode` without a height specified, only the first line shows. This behavior seems a bit unpredictable. Should it not just fill up to the width and height of its parent? The wrapping ViroFlexView with `height={10}` is quite large.

Anyway, adding a `height` prop works for us!

**Comment by dam00n** [comment]
@draperunner glad you were able to get it to work. Added an issue to our backlog to see if we can make this behavior more consistent.
