### ISSUE TITLE
Cannot get FBX to show up

### ISSUE THREAD

**Issue by starantino** [viromedia/viro#157]
I have done all the conversions and put all files in the correct path, i just get nothing with the vrx format--the obj seems to work, but I cant get a vrx to work except for the one included with the demo. Is there a specific fbx version I should save as or something I am missing? Is it a scale issue? OBJ is exported from the same file--scale seems fine. OS 10.13.2, Most current version of Viro

```javascript
      <ViroARScene onTrackingInitialized={this._onInitialized} >
        <ViroText text={this.state.text} scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
        <ViroAmbientLight color={"#aaaaaa"} />
        <ViroSpotLight 
        innerAngle={5}
        outerAngle={90}
        direction={[0,-1,-.2]}
        position={[0,3,1]}
        color="#ffffff"
        castsShadow={true} />
        <Viro3DObject
          source={require('./res/inventLogo/inventLogo3.vrx')}
          resources={[require('./res/inventLogo/baked_beauty_polySurfaceShape1.png'),
                      require('./res/inventLogo/baked_tpAmbient_polySurfaceShape1.png'),
                      require('./res/inventLogo/baked_tpIndirectIllumination_polySurfaceShape1.png')]}
          position={[0, 0, -2]}
          scale={[1, 1, 1]}
          type="VRX" 
        />
      </ViroARScene>
```

**Comment by starantino** [comment]
Brought fbx into blender then scaled it up and it then worked, seems to be something with scaling from maya. Looks like I will have to play around with settings more.

**Comment by dam00n** [comment]
@starantino glad you were able to get it to work. Here is a guide/tutorial our 3D artist made detailing his process 3D modeling -> https://blog.viromedia.com/https-blog-viromedia-com-asset-pipeline-optimizing-3d-models-ar-vr-arkit-arcore-d0fb61627aaf

**Comment by starantino** [comment]
Perfect thank you!

**Comment by starantino** [comment]
One note as well as to why I couldn't get a FBX to export properly in MayaLT for use in conversion to VRX--File Type needs to be set to ASCII to work properly otherwise it wont convert properly. You will be able to tell it doesn't convent properly from FBX to VRX if the file size of the VRX is something like 24 bytes, it should read something like 350kb.
![untitled](https://user-images.githubusercontent.com/13489240/35581260-44f77654-05b9-11e8-86d7-9f620010fbc7.jpeg)

**Comment by starantino** [comment]
May be something worth noting in Docs, it took me a while to figure this out.

**Comment by dam00n** [comment]
Thanks for the heads up @starantino. Will look it this and update documentation as needed.
