### ISSUE TITLE
RUN SETUP-IDE.SH SCRIPT failed

### ISSUE THREAD

**Issue by Polaris00418** [viromedia/viro#158]
Hi, viro devs!
when i RUN SETUP-IDE.SH SCRIPT, i got this error "> [!] Unable to find a specification for `GVRKit (= 1.100.0)` depended upon by  #`ViroKit`"

here are what i have faced!

 $ ./setup-ide.sh --ios
==== Running iOS Setup Script ===
running with verbose logging
Analyzing dependencies
Fetching podspec for `ViroKit` from `../node_modules/react-viro/ios/dist/ViroRenderer/`
Fetching podspec for `ViroReact` from `../node_modules/react-viro/ios/`

> [!] Unable to find a specification for `GVRKit (= 1.100.0)` depended upon by  #`ViroKit`

/Users/KHC/.rvm/gems/ruby-2.4.1/gems/atomos-0.1.1/lib/atomos.rb:8:in `atomic_write': undefined method `tmpdir' for Dir:Class (NoMethodError)
	from /Users/KHC/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.5/lib/xcodeproj/project.rb:354:in `save'
	from proj_add_shell_script.rb:21:in `<main>'

**Comment by achuvm** [comment]
Hi @Polaris00418,

That's strange, it looks like CocoaPods can't find the dependency.

Can you try running `pod repo update` and then run `pod install` within `<Project>/ios`.

Let us know if that works for you.

**Comment by Polaris00418** [comment]
Hi @achuvm !
thanks for your immediate response. I was able to solve issue through referring this URL;
https://cocoapods.org/pods/GVRKit

yeah mainly it was "pod install"!
You are right!
thanks again!!

but now i have faced another error when building the xcode porject of virosampleapp.
maybe I will have to post new issues?
************
ld: warning: ignoring file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/lib/libViroReact.a, missing required architecture x86_64 in file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/lib/libViroReact.a (2 slices)
ld: warning: ignoring file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/ViroRenderer/ViroKit.framework/ViroKit, missing required architecture x86_64 in file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/ViroRenderer/ViroKit.framework/ViroKit (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_VRTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
******
apreciate if you help me again ;)

**Comment by Polaris00418** [comment]
yes pod install was solution !!!
thanks
