### ISSUE TITLE
error testing in a Huawei NXT-L09 (Mate 8)

### ISSUE THREAD

**Issue by mromerocastro** [viromedia/viro#16]
SyntaxError: Unexpected token '<' (http://http://f3d3c9c4.ngrok.io/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1)

**Comment by achuvm** [comment]
Hi @mromerocastro,

It looks like in the testbed app you're typing in `http://f3d3c9c4.ngrok.io` instead of simply `f3d3c9c4.ngrok.io`. Otherwise, I was able to connect to your scene by using our Viro Media app's testbed feature and using `f3d3c9c4.ngrok.io`.

Thanks,
Andy

**Comment by mromerocastro** [comment]
thank you for your help, is already working
