### ISSUE TITLE
./setup-ide.sh script fails for iOS init

### ISSUE THREAD

**Issue by NWeid1** [viromedia/viro#160]
I'm getting errors on step 4 of this guide: https://docs.viromedia.com/docs/starting-a-new-viro-project-1

Here is my output:

Pod installation complete! There are 2 dependencies from the Podfile and 9 total pods installed.
Traceback (most recent call last):
	2: from proj_add_shell_script.rb:1:in `<main>'
	1: from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- xcodeproj (LoadError)
Add: ":NSAppTransportSecurity:NSAllowsArbitraryLoads" Entry Already Exists
Add: ":NSCameraUsageDescription" Entry Already Exists

How can I resolve this? Thanks!

Edit: To add to this, this doesn't prevent my . xcworkspace file from being generated, and I can still open this in Xcode - BUT I am getting build errors (''config.h' file not found' in mutex.h) that I'm assuming are caused by the error above.

**Comment by achuvm** [comment]
Hi @NWeid1,

That's a strange error you're getting, our script does those two values to the `Info.plist` file, but the default project (from React-Native) shouldn't have them. As a result, one of the following possibilities might've caused the issue:

1. They were already present in an existing project
2. The `./setup.sh --ios` script was run twice (this is our bad, we don't handle errors very well).
3. You're using a newer React Native version (what version of `react-native` do you see in your `package.json` file?).

In any case, you mentioned that the `.xcworkspace` file was created (CocoaPods creates this), so if it works it should be fine. However, you mentioned you got an error `'config.h' not found` in `mutex.h`. This is an error with React, to resolve the issue:

1. In the Terminal, navigate to `<YourProject>/node_modules/react-native/third-party/glog-0.3.4`
2. Run `../../scripts/ios-configure-glog.sh`
3. Glog is configured and the required config.h header file is created for Xcode to find

The issue/solution is documented here:
https://github.com/facebook/react-native/issues/14382

Let us know if you run into any issues or if that doesn't fix it!

**Comment by coicoichip** [comment]
i everyone .... i have bug  *'config.h' file not found* but i run `../../scripts/ios-configure-glog.sh`. it didn't work and in teminal show 
`Vuongs-MacBook-Pro:glog-0.3.4 vuonghaithanh$ ../../scripts/ios-configure-glog.sh
../../scripts/ios-configure-glog.sh: line 7: xcrun: command not found
../../scripts/ios-configure-glog.sh: line 7: xcrun: command not found
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
/Users/vuonghaithanh/WebstormProjects/testreact/node_modules/react-native/third-party/glog-0.3.4/missing: Unknown `--is-lightweight' option
Try `/Users/vuonghaithanh/WebstormProjects/testreact/node_modules/react-native/third-party/glog-0.3.4/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc...  -arch armv7 -isysroot 
checking whether the C compiler works... no
configure: error: in `/Users/vuonghaithanh/WebstormProjects/testreact/node_modules/react-native/third-party/glog-0.3.4':
configure: error: C compiler cannot create executables
See `config.log' for more details`
pls help me how to fix
`react-native-cli: 2.0.1
react-native: 0.53.3
`

**Comment by achuvm** [comment]
Hi @coicoichip,

It looks like the error you're experiencing when running the command is due to the lack of `xcrun` on your MacBook. 

Try running `which xcrun` within your terminal to see if it exists. If it doesn't you may want to try installing the XCode command-line tools with the following command: `xcode-select --install`.

The latest Viro has only been tested with React-Native 0.49.3, so you can try downgrading back down to that.

Thanks,

**Comment by dam00n** [comment]
Closing issue as solution has been provided. Please reopen if you are still having issues.
