### ISSUE TITLE
Viromedia android app, AR sample not working

### ISSUE THREAD

**Issue by peterel** [viromedia/viro#161]
Hi,

Your AR sample of your app works on an iPhone 8 but not on an s8. It never starts, just crashes. The other samples (not using vr headset) also seem to require the back button which get hidden on the s8, at least for these samples. Not sure how/possible to navigate back after starting the other samples. So,

What devices should/could one expect for viro to support with regards to AR at least?

Thanks.

**Comment by dam00n** [comment]
Hi @peterel thanks for letting us know about the issues on the samples. We will look into it on our S8. Do you know what model S8 you have? Here is a list of ARCore supported devices from Google -> https://developers.google.com/ar/discover/

Viro supports the same devices ARKit and ARCore support:

ARKit - iOS devices that use A9 chips or higher

- iPhone 6s and 6s Plus
- iPhone 7 and 7 Plus
-iPhone SE
- iPad Pro (9.7, 10.5 or 12.9) – both first-gen and 2nd-gen
- iPad (2017)
- iPhone 8 and 8 Plus
- iPhone X

ARCore -> https://developers.google.com/ar/discover/
(linking to ARCore site as device support continually updates)

**Comment by peterel** [comment]
Hi,

@dam00n, thanks for a quick response. I have a Galaxy S8, model SM-G950F.

Have you been able to replicate the issue on your s8?

Alright, so your framework/platform would then support all devices that have the Arkit or ARCore. Sounds good :)

Thanks

**Comment by peterel** [comment]
@dam00n Hi, any news on this? Ive tried reinstalling the app with same results. Thanks

**Comment by achuvm** [comment]
Hi @peterel,

Have you installed the `arcore-preview2.apk`? https://developers.google.com/ar/develop/java/getting-started#prepare-device

It's required right now because ARCore's still in developer preview.

If that doesn't work for you, can you see if you can capture some error logs through Android logcat? (either through command line or Android Studio).

As for your issue with the back button, it's something we're looking into specifically for Samsung devices as Samsung hides the back button when in "full-screen" (Pixel devices seem to work). For now, you'll have to press on the virtual home button to get out.

Let us know if this works for you!

**Comment by peterel** [comment]
Hi @dam00n,

Hmm, not sure I follow. Will all users of a Galaxy s8 need to download the arcore-preview.apk to get any app developed on the Viro framework to work?

Also, did you get it to work on your S8?

Thanks.

**Comment by dam00n** [comment]
Yes, it is working on our S8 devices.

Right now ARCore is in developer preview and is not available for public release. When ARCore goes public, the APK will be available in the play store. This is not a limitation of the Viro framework but is the current state of ARCore. See this ARCore github issue for more details -> https://github.com/google-ar/arcore-android-sdk/issues/45

**Comment by peterel** [comment]
Thanks for your response @dam00n .

Ok, just so Im clear. Anyone that develops any app that uses ARCore would have this issue on a Galaxy S8 model SM-G950F (the one I have)? Or is the case that anyone that develops any app that uses ARCore would have this issue, regardless of phone?

**Comment by dam00n** [comment]
Is the issue you are referring to -> the requirement to download ARCore apk?

For the period when ARCore is in developer preview, anyone that develops an app that uses ARCore on an ARCore supported device (currently S7, S8, Note 8, Pixel, Pixel 2). The reason I asked you about your S8 model is that some S8 models are not supported yet as you can see in the original link I sent regarding supported devices.

When ARCore goes live to the public, we assume that ARCore.apk will be available via the Google play store and that it would only need to be downloaded the first time a user tries to use any ARCore app. But we don't know what the exact plans are. You should ask ARCore distribution/installation questions on the ARCore github issues if you want more information as we only know what is publicly stated in forums like the link we shared.

**Comment by myhendry** [comment]
I have a similar issue using my Samsung S7 Edge. VR sample works fine. But when I select the AR sample, app just crashes

**Comment by myhendry** [comment]
When I tried to create and run my own  sample AR app using react-viro, I only see a Hello World text and the background is black

**Comment by dam00n** [comment]
S7 Edge (SM-G935) does not appear to be supported by ARCore at this time. https://developers.google.com/ar/discover/#supported_devices

Are you able to download ARCore preview app from Google Play?

**Comment by myhendry** [comment]
Hi Danny,

i tried. Galaxy S7 Edge cant download the preview ARCore preview app from Google Play. Looks like i have to source for an alternative device. Thanks anyway for ya guidance. React Viro rocks! :)

**Comment by dam00n** [comment]
@myhendry there is a library someone created called ar-core-for-all that allows use of ARCore on unsupported devices. This is a 3rd party tool and is not officially supported. Here is a github link that describes how to integrate it -> https://github.com/viromedia/viro/issues/113

**Comment by myhendry** [comment]
Thanks Danny

**Comment by Maazpatel111** [comment]
I was trying to run Black panther Augmented Image sample App on OnePlus 3t but it will show only the black screen. I didn't any error log. I am trying to run virocore with an android studio. 
The same sample app is working OnePlus 6 devices. Can you please help me on this?

**Comment by dam00n** [comment]
Is your OnePlus 3t running Android 8?
