### ISSUE TITLE
OVRDebug on device is not working

### ISSUE THREAD

**Issue by vinodkhandelwal** [viromedia/viro#163]
Hi...I am just using your basic VR application. I am able to build with gvrDebug and deployed on actual device and its working. When i build using ovrDebug option for gearVR, its building and getting installed on device. But On running the application i am getting a white screen only. 

I am using Samsung galaxy S7 Edge.

**Comment by manbod** [comment]
Hey Vinod,

By white screen do you mean this screen, that I have attached below? Sometimes / or on some devices it shows only a plain white screen. If you wanted to test on a gear vr without the gear headset, you have to set the developer mode to ON in the gear VR service app. In case you aren't aware, you can do so by opening *app manager -> Gear VR Service -> Storage -> Manage Storage -> Developer Mode -> Toggle On. 

<img src="https://user-images.githubusercontent.com/24463620/36185009-e5e41896-10eb-11e8-986c-a3e7a87050fc.png" width="320"/>

Keep in mind though, for OVR, Gear VR has a requirement for specific type of App signing. And you may get another exception down the line. In developer Gear VR builds you need a signature file, called osig in your code base. Follow the steps outlined [here](https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-submission-sig-file/) to generate your osig file

**Comment by dam00n** [comment]
Closing issue as solution has been provided. Please reopen if you are still running into issues
