### ISSUE TITLE
Display a non-VR/AR 3D scene?

### ISSUE THREAD

**Issue by funkyfourier** [viromedia/viro#166]
Is it possible to display a 3D scene in a non-VR/AR context? That could have multiple uses, for example as a preview function for the user to select models to put in an AR- or VR-scene.

I am thinking about something like sketchfab's viewers. For example:

https://sketchfab.com/models/fe439dc012d9439890e6baf4765b992f

**Comment by dam00n** [comment]
Hi @funkyfourier, we currently do not support 3D scenes in ViroReact. We do offer this feature in ViroCore (our Java platform). This is on our backlog and we have marked it as a priority. Will update this issue once we have more information on dates/releases.

**Comment by dam00n** [comment]
Hi @funkyfourier this feature has been added to ViroReact v2.5.1 Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

API Reference -> https://docs.viromedia.com/docs/viro3dscenenavigator

**Comment by funkyfourier** [comment]
Thanks! Looking forward to trying it!
