### ISSUE TITLE
OBJ and MTL not included in prod build for Android

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#169]
We are trying to building our Android ARCore feature as a release, but it doesn't seems like the MTL and OBJ files are being included. Works fine in dev-mode for Android and for dev and release iPhone.

Ex. from our code
```
import icon from '../assets/3d/icon.obj'
import material from '../assets/3d/material.mtl'

  <Viro3DObject
                        source={icon}
                        resources={[material]}
                        type="OBJ"
                    />

```

And in our rn-cli.config.js
```
  getAssetExts() {
        return [
            'obj',
            'mtl',
        ]
    }
```

**Comment by dam00n** [comment]
For React Native Android, you might have to "require" all the assets associated with the obj as well (mtl, png, etc) rather than import, so they are pulled in during the release bundle phase.

<Viro3DObject source={require('../assets/3d/icon.obj')}
           resources={[require('../assets/3d/material.mtl')]}
                      type="OBJ" />

**Comment by cjrorvik** [comment]
Tried it out now @dam00n .. Wasn't a big success 😕 Must be something with the bundling in some way. Works fine when the Android is connected, but the 3dObjects are gone when I disconnects the phone. So a bit hard to debug. I managed to get a crash log from Crashlytics though.. 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.viromedia.bridge.component.node.control.VRT3DObject.onPropsSet(VRT3DObject.java:174)
       at com.viromedia.bridge.component.VRTViroViewGroupManager.onAfterUpdateTransaction(VRTViroViewGroupManager.java:73)
       at com.viromedia.bridge.component.VRTViroViewGroupManager.onAfterUpdateTransaction(VRTViroViewGroupManager.java:21)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:35)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:233)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1010)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:981)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:957)
       at android.view.Choreographer.doCallbacks(Choreographer.java:734)
       at android.view.Choreographer.doFrame(Choreographer.java:667)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

We are also using multiple different icons so also need a way to differentiate the different sources and resources that we are requiring in. 

Could there might be a path issue when using _require_ ? 🤔

Until now we'll just host the obj and mtl files on a server and fetch them from there, for the Android users.

**Comment by VikAdvani** [comment]
Hi @cjrorvik, this does seem like a packaging issue. How are you building to production? If you are building release through Android studio, the packaging will not pick up your .mtl and obj files correctly. 

You'll need to build to release through command line in order for the files to be packaged correctly. 
Try packaging by running the following from your project root:
```react-native run-android --variant=gvrRelease```

Let me know if this works :)

**Comment by cjrorvik** [comment]
Hi @VikAdvani ! Thanks for your reply! --variant=gvrRelease seems to work correctly when running we we are building through command line. So that's nice :) Problem is that we are deploying through Fastlane and that includes a gradle build. 

```
    desc "Deploy staging version of app"
    lane :staging do |options|
        prepare_build(envfile:".env.staging", keystore: "nativeapp.jks")

        gradle(
            task: 'assemble',
            project_dir: "android/",
            build_type: 'Release'
        )
    end
```

Do you think it would be possible to do a build for Android with Fastlane? That would be great!

**Comment by manbod** [comment]
Hi @cjrorvik ,
It is definitely possible to do an Android build using Fastlane. We rely on Fastlane ourselves for our viro internal builds.

Above, did you mean --variant=gvrRelease built it correctly for you guys? In that case, try modifying your fastlane lane to (add `flavor` to your gradle task)
```ruby
    desc "Deploy staging version of app"
    lane :staging do |options|
        prepare_build(envfile:".env.staging", keystore: "nativeapp.jks")

        gradle(
            task: 'assemble',
            project_dir: "android/",
            flavor: "Gvr",
            build_type: 'Release'
        )
    end
```
Looking at our fastlane lane, we simply have it as:
```ruby
  desc "Build GVR release tests"
  lane :gvr_release_test do
    gradle(task: "assembleGvrRelease")
  end
```
Above single line for gradle action in fastlane, seems to work just fine for us.

If doing the above does not resolve the issue for you, I would then look at your gradle configuration. Most likely your gradle setup could be an issue.
1. What does your `$ which gradle` command return to you on your command line?
2. When you run your build as `./gradlew assembleGvrRelease`, do you see gradle even running `bundleGvrReleaseJsAndAssets` step? When you run your `fastlane staging` or `./gradlew assembleGvrRelease` commands, you should see terminal output as follows
```
[15:58:54]: ▸ :app:bundleGvrReleaseJsAndAssets
[15:58:54]: ▸ Loading dependency graph, done.
[15:58:54]: ▸ warning: the transform cache was reset.
[15:59:18]: ▸ bundle: start
[15:59:18]: ▸ bundle: finish
[15:59:18]: ▸ bundle: Writing bundle output to: **/build/intermediates/assets/gvr/release/index.android.bundle
[15:59:18]: ▸ bundle: Done writing bundle output
[15:59:18]: ▸ bundle: Copying XXX asset files
[15:59:19]: ▸ bundle: Done copying assets
```
3. Lastly, check in your `android/app/build/intermediates` -> Do you see an assets folder? Does it have the right contents?
If you don't see the above logs during your build or don't see assets in your intermediates, then your gradle commands are not bundling your assets at all, and that should help you narrow down your gradle build issues.
If the above is the case for you, a few things that have helped us in the past when we ran into similar RN (not)bundling issues:
```
Android Studio > Preferences > Build, Execution, Deployment > Compiler > 
[Uncheck] Configure on demand
```
That should result in Android Studio adding the following like to your global `gradle.properties` file
```
org.gradle.configureondemand=false
```
Android studio and gradle defaults to true, so that seems to mess up RN builds sometimes as per
https://github.com/facebook/react-native/issues/7258 &
https://github.com/facebook/react-native/issues/9612

Let us know if this unblocks you. :)

**Comment by manbod** [comment]
Hey @cjrorvik ,
Just wanted to check - what version of React-Native are you trying to run your app with? Could you paste contents of your package.json?

Thanks,

**Comment by cjrorvik** [comment]
Thanks for your reply @manbod !

I tried to use  ```flavor: "Gvr"``` but it says: 
```
* What went wrong:
Task 'assembleGvrRelease' not found in root project '_projectName_'. Some candidates are: 'assembleRelease'.?
 ```
I do not quite understand where these task names are being set. What exactly is a assembleGvrRelease task, and are there any places to read more about it? 

We are currently using React Native v.0.52.2
Gradle version: 4.6

**Comment by manbod** [comment]
Hi @cjrorvik 
The `assembledGvrRelease` was guessed taskname after reading that `--variant=gvrRelease` works correctly for you. You can read more about how task names are put together on [here](https://developer.android.com/studio/build/build-variants.html). Also, you can see all the task names that your build configuration supports/generates by running this command `gradle tasks` or `./gradlew tasks` depending on whether you use gradle wrapper.

As for the `NullPointerException` you are seeing -> All our recent past releases have been compatible and well tested with React Native v.0.49.3 -> [Viro React Releases](https://docs.viromedia.com/docs/releases). We would test and bump our React Native compatibility version in a future upcoming release. Until then, a work around may be to bump your react-native version down to v.0.49.3, if that's a possibility for you. Keep in mind, you would also need to lower React's appropriate version. (You would see a warning on the lines of ```npm WARN peerDependencies The peer dependency react@~R included from react-native...``` where R is the version you are missing.

**Comment by jlyonsmith** [comment]
For Googlers:  The problem turned out to be the version of React Native - it must be 0.49.3 for Viro 2.4/2.5  Apparently the RN bundle process puts files in different locations after 0.49.  Viro is working on a release to support RN 0.55 and above.

**Comment by dam00n** [comment]
This issue has been fixed in our latest release, ViroReact 2.6.0. We now support RN 0.55.1. Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

Closing this issue. Please reopen if you still have issues.

**Comment by draperunner** [comment]
Seems like there is some issue with assets on Android again? When we bundle for release, icons appear grey, or not at all. In debug mode they show as expected. 

When loading from URL, the assets show as expected.

We are on React Native v0.55.3 and react-viro 2.7.3.

**Comment by dthian** [comment]
Hey @draperunner, sounds like it may be an issue with how you are pulling in assets that then manifests itself in a release build. Could you share the Viro3DObject code you are using, and as well as the corresponding resources? Thanks!

**Comment by dthian** [comment]
Hey @draperunner, the path to the model assets listed above may not be resolving correctly in release builds. Instead of importing, could you use the 'require' implementation to ensure that the paths to these resources are also resolved correctly in release?

It would be something along the lines like [this sample](https://github.com/viromedia/viro/blob/master/js/HumanBody/MainScene.js#L43).

Please do let us know if that has worked for you or not. Thanks!

**Comment by draperunner** [comment]
Yes, I tried that, as Danny suggested in the first comment on this issue, but sadly it does not work either.

**Comment by dthian** [comment]
Hey @draperunner, thanks for your reply! A quick question here - do you have any other assets that are also named "bus" or "busMaterial" that is not apart of the Viro3DObject? In react release builds, resources with the same "clash" with each other, and thus your bus, or bustMaterial resource. may be overwritten by something else. Thanks!
