### ISSUE TITLE
Black Screen with Hello World

### ISSUE THREAD

**Issue by Filipe-tb** [viromedia/viro#170]
Whenever I try to run the app through the TestBed app, all it appears is a black screen with "Hello World!" in VR mode.
I got it working once, but not anymore.
I already tried using both the ngrok and IP methods (while on the same network).
I also have the api key set in App.js in the sharedProps variable.
It seems like it isn't fetching anything from the package manager.

![image](https://user-images.githubusercontent.com/34278220/36848697-ef771b4a-1d59-11e8-9623-8f96e56943de.png)

For the example above, I would put bfbb2827.ngrok.io to try to connect.
I already tried clearing the cache.

Am I missing something? Thanks!

**Comment by dam00n** [comment]
Hi @Filipe-tb sorry you are running into issues. Have you tried reloading (shaking the device -> dev menu pops up -> tap reload)? Here is a testbed app page we just added to help you diagnose issues -> https://docs.viromedia.com/docs/develop-with-viro

If you are still having problems, can you provide more informations?
1. iOS or Android and device model
2. Are your ViroReact version and testbed version the same?

**Comment by Filipe-tb** [comment]
Hello @dam00n ,
Tried to shake and reload, but it doesn't work (I guess it's because there is no actual app running). It looks like it's a default app. In fact, I can type a random string instead of my ip or rgnok link and the VR Hello World! app still comes up.

1. Android (Samsung Galaxy S7 - 7.0)
2. Yes. Both 2.4.0.

**Comment by Filipe-tb** [comment]
Just a quick update. I got it working finally. I had to setup Gear VR, etc.
Don't know if it was concidence or not... But if this was the case, I wonder why it worked once before.

Cheers!

**Comment by dam00n** [comment]
Glad you were able to get it to work and thanks for the heads up on how you were able to do it. We will take a look to see if we can make our documentation more clear. Let us know if you have additional questions.
