### ISSUE TITLE
IsARSupportedOnDevice returns true on LG G6

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#171]
Seems like the utils function IsARSupportedOnDevice returns true on a LG G6 phone, but it does not support ARCore. https://developers.google.com/ar/discover/ .

Are there any ways to check the types of phones that returns true from the IsARSupportedOnDevice function?

**Comment by VikAdvani** [comment]
Hi @cjrorvik, you could use something like this React Native module:https://github.com/rebeccahughes/react-native-device-info to extract more device info like the model type and manufacturer. 

You can also modify our check and create your own native module. The method ```isARSupportedOnDevice``` wraps the following Android Java native code:
```
/**
     * Checks if ARCore is compatible with the target device. This does <i>not</i> indicate whether ARCore is
     * installed. If this method returns false, attempts to create {@link ViroViewARCore} will throw
     * an exception.
     *
     * @param context The {@link Context} of your application.
     * @return True if the current device is compatible with ARCore.
     */
    public static boolean isDeviceCompatible(Context context) {
        ArCoreApk.Availability availability = ArCoreApk.getInstance().checkAvailability(context);
        Log.i(TAG, "ARCore availability check returned [" + availability   + "]");
        if (availability == ArCoreApk.Availability.UNSUPPORTED_DEVICE_NOT_CAPABLE) {
            return false;
        }
        else {
            return true;
        }
    }
```

We return ```true``` on every value of ArCoreApk.Availability flag except UNSUPPORTED_DEVICE_NOT_CAPABLE. If you write your own native module to check, you may want to return false for UNKNOWN_ERROR or UKNOWN_CHECKING.

Here's a list of all possible return values: https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk.Availability

Hopefully the above can help you mitigate. 

I've added a bug in our backlog so we can look into this.

**Comment by dam00n** [comment]
We made some modifications to our unsupported device logic in ViroReact v2.5.1 which should improve this issue. Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases
