### ISSUE TITLE
Is Viro-React Open Source?

### ISSUE THREAD

**Issue by WillGeller** [viromedia/viro#173]
Thank you for building this, I'm finding the examples and API to be very robust and the framework looks promising.

I'm trying to understand the BSD 3-Clause license. It seems like the Viro-React components are not developed in the open on GitHub. So I am wondering how one would go about modifying, expanding upon or building new components to use with the current ones. Also how is the API key used and why is it needed to run the app locally. Is there any plans to expand into a paid usage license that one would run into if they were to build an app on Viro-React?

**Comment by dam00n** [comment]
Hi @WillGeller, thanks for positive feedback on ViroReact, appreciate it and hope you build something great.

The Viro platform is not open source. But is free to use with no limits on distribution. Our license is located here -> https://docs.viromedia.com/docs/license

You can modify ViroReact components for your own project as needed, but at this time we do not accept pull request though it is something we will continually evaluate.

The API key is used for basic internal metrics and to guard against possible license violations.

You can email me directly at dmoon@viromedia.com if you have additional questions or concerns.

**Comment by WillGeller** [comment]
Thanks for clarifying. I think that is enough info to run on!

**Comment by HarshitMadhav** [comment]
I did receive an email yesterday which said: "Viro is going Open Source!". So, hopefully, they are going open source now.
