### ISSUE TITLE
Invariant Violation: Native component for "VRTText" does not exist

### ISSUE THREAD

**Issue by robinv8** [viromedia/viro#176]
environment: windows.
After the project is initialized, the exception is run.

**Comment by llf22282776** [comment]
@robinv8 
see the issue [177](https://github.com/viromedia/viro/issues/177)

**Comment by Bryantrf** [comment]
This's the problem that I'm having

Invariant Violation: requireNativeComponent: "VRT360Image" was not found in the UIManager.

**Comment by prakashsaran** [comment]
i just create a react-viro project using 

> **react-viro init helloword**

and second i run project inside 

> **react-native run-android**

app run successfully and show below screen 

![Screenshot_2020-01-05-20-56-36](https://user-images.githubusercontent.com/36918911/71782382-56581300-2fff-11ea-9b2c-b681b11ce3c8.png)


when i click on **AR button**, i am showing below ERROR screen
![Screenshot_2020-01-05-20-56-48](https://user-images.githubusercontent.com/36918911/71782475-2b21f380-3000-11ea-99a7-839760a4f3b7.png)


and   on click **VR button** show below ERROR screen 
![Screenshot_2020-01-05-20-57-02](https://user-images.githubusercontent.com/36918911/71782462-16456000-3000-11ea-9876-ae76c9ab21d5.png)

**what`s going wrong ?**

**please someone help me**
