### ISSUE TITLE
[Feature Request] GLTF Format Support

### ISSUE THREAD

**Issue by nishantdande** [viromedia/viro#178]
Hi,
I know Viro core does not support GLTF format but is there any way to use viro's OpenGl ES render. I will take care of parsing GLTF and want to use Viro's renderer to render 3D model.

**Comment by radvani** [comment]
Hi @nishantdande, you can load any model that is in our gzipped VRX format. VRX is a protobuf format; I've attached the specification [here](https://github.com/viromedia/viro/files/1804955/Nodes.proto.txt). If you manage to convert GLTF into VRX (you'll have to use protoc to generate the files needed to create the protobuf), then you just have to gzip the resultant VRX file and load it into your application using Object3D.loadModel(), setting the Type to FBX.

We're planning glTF support for a future release.

**Comment by VikAdvani** [comment]
Static GLTF models are now supported in v2.7 -> See release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

GLTF w/ animations coming soon :)

**Comment by ChristianNormann** [comment]
Are there any updates on when there will be GLTF support for animations and baked in cameras?

**Comment by dam00n** [comment]
Skeletal animations for GLTF was added in ViroReact 2.8.1

We do not have a timeframe for baked in camera. It is on our backlog but has not been requested until now. Can you give us more details on how you would utilize the feature so we can prioritize accordingly?

**Comment by ChristianNormann** [comment]
Nice with the animations implementation. I didn't see that in the documentation.
How do GLTF stack up against VRX then? Do they have the same features at the moment?

I need an animation that looks like you "dig in the ground".
After many talks with my motion designers, we have come to the conclusion, that we need a camera pointing at the location of the animation object, so we can use the feed of the camera as the texture for the animation object.

The effect of "digging in the ground" can e.g. be seen in this app: https://itunes.apple.com/us/app/arrrrrgh/id1299548311?mt=8.

If you think there are any other ways to achieve the effect with ViroReact than with GLTF baked in camera, I would be thrilled to hear from you.
