### ISSUE TITLE
How to build a AR Android App without Gear/DayDream/Oculus Targeting

### ISSUE THREAD

**Issue by dominicrico** [viromedia/viro#179]
Hey,

I'm tying to build the SampleAR App where you can place a Mug, Flowers or Smily somewhere in the room. I have know that there a two different types of build settings in gradle file (GVR/OVR). But what if I don't need any of the given VR Solutions like Gear or Daydream and just want a standalone app? 

Thanks for your help!

**Comment by achuvm** [comment]
Hi @dominicrico,

If you select GVR and simply use a `ViroARSceneNavigator` it will work just fine. If you select OVR and use it on a Samsung device, then the device will immediately jump into GearVR mode (but still show AR).

Thanks,
