### ISSUE TITLE
Video goes black after a few seconds playing

### ISSUE THREAD

**Issue by leocavalcante** [viromedia/viro#18]
Right, so a was able to replace the image from the sample to a 360 video that a have.
The surprise is that the video plays nice for a few seconds, but then it goes black, the sound still on, the UI too (the gear icon and the line in the middle), but the video stops showing up.
Any ideias?

Running the Cardboard mode on a S7.

Thanks.

**Comment by VikAdvani** [comment]
Hi @leocavalcante! Are you using the testbed app with an ngrok endpoint? The video can go black since ngrok limits the amount of connections per minute that can travel to its tunnel. Since you are using android, you can use adb to reverse tether the device to your phone and use 127.0.0.1 to connect via the testbed app. 

More info here: http://docs.viromedia.com/docs/troubleshooting#installing-adbandroid-only

Let us know if the above doesn't fix it!

**Comment by leocavalcante** [comment]
Hi @VikAdvani 
I'm not using TestBed. I'm compiling the app with `react-native run-android`.

**Comment by VikAdvani** [comment]
Hi @leocavalcante, is the video local or remote on a server? Also, did you your Viro API key in index.android.js?

**Comment by leocavalcante** [comment]
Its local `require('./res/video.mp4')`. Yes, API key added.

**Comment by VikAdvani** [comment]
Hi @leocavalcante, I've reproduced the test using Viro360Video component with a local video using an S7 phone and it seems to be working.

Is there a way you can share the video with us to reproduce? What is the resolution of your video? Is it a stereoscopic video or mono? Does the entire screen go black(ie text still shows) or just the video?

Finally, can you cut and paste the JS code so I can take a look? Thanks!

**Comment by leocavalcante** [comment]
Hi @VikAdvani 

This is the code for `App.js`

```js
import React from 'react'
import { ViroSceneNavigator, ViroScene, Viro360Video } from 'react-viro'

class VideoScene extends React.Component {
  render() {
    return (
      <ViroScene>
        <Viro360Video
          source={require('./res/video.mp4')}
        />
      </ViroScene>
    )
  }
}

export default class App extends React.Component {
  render() {
    return (
      <ViroSceneNavigator apiKey="<My key properly set, but hiding it here>"
        initialScene={{ scene: VideoScene }}
      />
    )
  }
}
```

And the `index.android.js`:
```js
import React from 'react'
import { AppRegistry } from 'react-native'
import App from './App'

AppRegistry.registerComponent('ViroSample', () => App)
```

Video here:
https://drive.google.com/file/d/0B3MDNcJfWIa9VFZRYnRWYlhvOEE/view?usp=sharing

It is a Brazilian Porsche Cup Lap:
https://www.youtube.com/watch?v=e_dTUTkAirc

**Comment by VikAdvani** [comment]
Hi @leocavalcante, I just took your code and video and everything works fine! When I changed my key to an invalid one then I reproduced your issue. Can you make sure the key is typed correctly, with the dashes included? The key param should look like the following: 
apiKey="7FFFEEEE-CCCC-1111-AAAA-BBBBBBBBCCCC"
I can also vend you a new key if needed and we can try that.

**Comment by leocavalcante** [comment]
Oh, sorry, my bad. Just check out the Welcome email to get the key again and the key on the code got an one more letter, maybe from a typo. Now its corrected and working fine!
Thank you very much for you attention!

**Comment by VikAdvani** [comment]
No worries, glad to hear it's working! If you have any other questions let us know 👍
