### ISSUE TITLE
[IOS] xCode build failed

### ISSUE THREAD

**Issue by Tankerxyz** [viromedia/viro#183]
xCode version: 9.3 beta_4
react-native version: 0.49.3
react-viro version: 2.4.0

```
duplicate symbol __ZN3fLI9FLAGS_novE in:
    /Users/tanker/IdeaProjects/ViroSample/ios/Pods/GVRSDK/Libraries/libGVRSDK.a(vlog_is_on_8d2e7d29c7bb2e5dfa3670dcea4320a0.o)
    /Users/tanker/Library/Developer/Xcode/DerivedData/ViroSample-cidxnjuwwhmpcadbfxcwbqaiechz/Build/Products/Debug-iphoneos/libReact.a(vlog_is_on.o)
duplicate symbol __ZN3fLI7FLAGS_vE in:
    /Users/tanker/IdeaProjects/ViroSample/ios/Pods/GVRSDK/Libraries/libGVRSDK.a(vlog_is_on_8d2e7d29c7bb2e5dfa3670dcea4320a0.o)
    /Users/tanker/Library/Developer/Xcode/DerivedData/ViroSample-cidxnjuwwhmpcadbfxcwbqaiechz/Build/Products/Debug-iphoneos/libReact.a(vlog_is_on.o)
ld: 2 duplicate symbols for architecture arm64
```

I can't test my AR app with ARKit 1.5.
Any Ideas how can I resolve this?

**Comment by achuvm** [comment]
Hi @Tankerxyz,

The error you're seeing is not something that we've seen on our end (we've tested with both `GVR` and `React`).

Can you first try cleaning your project (do a `Clean Build Folder...` not just a `Clean`) and rebuilding your project?

If that doesn't work, can you post your `/ios/Podfile.lock` file so we can take a look?

Thanks,

**Comment by Tankerxyz** [comment]
@achuvm I fixed it
https://github.com/facebook/react-native/issues/18022#issuecomment-372760977

**Comment by Hless** [comment]
I know this issue has long been closed and all, but this possibly has something to do with not using `use_frameworks!` in your Podfile. For anyone experiencing the same issue, following the guide on the page below fixed my issue:

https://docs.viromedia.com/v2.14.0/docs/no_use_frameworks
