### ISSUE TITLE
How to add Interaction UI for AR Scene ?

### ISSUE THREAD

**Issue by mkharibalaji** [viromedia/viro#188]
Hi All,
         Is there any tutorial on implementing Interaction UI with AR ?

**Comment by VikAdvani** [comment]
Hi @mkharibalaji, you can look at this AR Sample that demonstrates a full cross platform AR app made in Viro React. The app mixes  React components for UI purposes with AR interactions:
https://github.com/viromedia/ViroARSampleApp

Hopefully that helps!
