### ISSUE TITLE
How to use ViroImage and ViroVideo in AR (viroReact)?

### ISSUE THREAD

**Issue by mkharibalaji** [viromedia/viro#189]
Hi Team, 
          I am not able to implement viroImage and ViroVideo in AR using viroReactARScene.Any tutorial to follow ?

I tried using the ARSample as below to render and i don't see anything,

`  <View style={localStyles.outer} >
        <ViroARSceneNavigator style={localStyles.arView} apiKey="XXXXXXXXXXXXXX"
          initialScene={{scene:InitialARScene, passProps:{displayObject:this.state.displayObject}}}  viroAppProps={this.state.viroAppProps}
        />

        {this._renderTrackingText()}

        {renderIf(this.state.isLoading,
          <View style={{position:'absolute', left:0, right:0, top:0, bottom:0, alignItems: 'center', justifyContent:'center'}}>
            <ActivityIndicator size='large' animating={this.state.isLoading} color='#ffffff'/>
          </View>)
        }

        <View style={{position: 'absolute',  left: 0, right: 0, bottom: 77, alignItems: 'center'}}>
          <TouchableHighlight style={localStyles.buttons}
            onPress={this._onDisplayDialog}
            underlayColor={'#00000000'} >
            <Image source={require("./js/res/btn_mode_objects.png")} />
          </TouchableHighlight>
        </View>
        <View style={{position: 'absolute', backgroundColor:"#ffffff22", left: 30, right: 30, top: 80, alignItems: 'center'}}>
          <ViroVideo
              source={require("./js/res/test1.mp4")}
              loop={true}
              position={[0,2,-5]}
              scale={[2, 2, 0]}
           />
        </View>
      </View>`

**Comment by dam00n** [comment]
You need to use Viro components within a ViroARScene for AR. Here are examples on Github here -> https://github.com/viromedia/viro/tree/master/js

The ViroMediaPlayer example is for VR but can easily be adjusted for AR.

We also have tutorials on our blog located here -> https://blog.viromedia.com/tagged/react-native

**Comment by JP6720** [comment]
Thanks @dam00n
