### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by leocavalcante** [viromedia/viro#19]
Trying the guide on http://docs.viromedia.com/docs/starting-a-new-viro-project-1

First, it didn't worked out-of-the-box, I had to delete `node_modules` and run `yarn`.
But now the error is this:
![screen shot 2017-06-19 at 20 07 27](https://user-images.githubusercontent.com/183722/27309626-72f6fa3c-552b-11e7-93ff-832fff0e1ca2.png)

It seams like it isn't founding the dependencies properly. Something I did wrong? Just followed the steps on the guide.

XCode 8.3.3
macOS 10.12.1
node 8.1.0
yarn 0.24.5
pod 1.2.1

**Comment by VikAdvani** [comment]
Hi @leocavalcante. Did you run setup-ide.sh ios first? That runs cocoapods and installs the necessary dependencies.

If you did run the setup-ide script for iOS, then make sure you are opening the .xcworkspace file and not the .xcodeproj. The .xcworkspace file has the proper dependencies to compile while the .xcodeproj does not. 

Below shows what your .xcworkspace file should look like when in Xcode( ViroSampleVideoTest would be named your project name):
<img width="276" alt="screen shot 2017-06-19 at 4 34 06 pm" src="https://user-images.githubusercontent.com/14915233/27310143-07b2ac30-550d-11e7-991d-08976e66b19f.png">

Let us know if the above doesn't work :)

**Comment by leocavalcante** [comment]
Yes, I did ;/

Steps were:
```shell
react-viro init HelloViro
cd HelloViro
./setup-ide.sh ios
open ios/HelloViro.xcworkspace
```
Could see `HelloViro` and `Pods` folders.
But when running got: 
```
'React/RCTBundleURLProvider.h' file not found
```
Figured out that it isn't on `node_modules`, so a deleted it and ran `yarn`.
Now getting the error below.

I ran `./setup-ide.sh ios` again:
```
==== Running iOS Setup Script ===
running with verbose logging
pwd
Analyzing dependencies
Fetching podspec for `ViroReact` from `../node_modules/react-viro/ios/`
Downloading dependencies
Using ViroReact (1.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
Add: ":NSAppTransportSecurity:NSAllowsArbitraryLoads" Entry Already Exists
Add: ":NSCameraUsageDescription" Entry Already Exists
```
Reopened Xcode using the workspace file, ran Clean then Run again, same two errors.

**Comment by VikAdvani** [comment]
Try the following, goto Product->Scheme->Edit Scheme. Make sure parallelize build is checked off, and that React is above the HelloViro target. 

So it it should look like the following:
<img width="896" alt="screen shot 2017-06-19 at 5 17 04 pm" src="https://user-images.githubusercontent.com/14915233/27311090-71f25658-5513-11e7-8482-ee0ba3459bf6.png">

If the scheme looks like the above with ViroSampleVideoTest replaced with HelloViro, then try building. Let's see if that works. If it doesn't let me know.

**Comment by leocavalcante** [comment]
Yeah, it looks like your SS:
![screen shot 2017-06-19 at 21 27 57](https://user-images.githubusercontent.com/183722/27311650-c0f68a06-5538-11e7-9907-ad4dbbc12b72.png)
Ps.: created a `HoViro` to retry the steps.

But Im clicking on the Play button (Run I guess, Xcode newbie here) not on Build.

**Comment by VikAdvani** [comment]
Ahhh, I reproduced the issue. The issue is we don't support the software simulator. Where it says iphone 7 plus above, you'll need to change the target to an actual physical device. Plug an iphone into your mac via a lightening connector, then you'll need to select the iphone in the top left next to the play button. When you select the iphone target the top left of your screen shoud like the following:
<img width="457" alt="screen shot 2017-06-19 at 5 52 57 pm" src="https://user-images.githubusercontent.com/14915233/27311774-2a7b5e3c-5518-11e7-9f96-f6f8b17386be.png">

Now try running and everything should work!

**Comment by leocavalcante** [comment]
Hmm, okay. I'll continue my journey tomorrow using a colegue's iPhone.
Thank you very much again for you patience and attention!!

**Comment by VikAdvani** [comment]
No prob, let us know tomorrow if you still have issues :)

**Comment by leocavalcante** [comment]
Hey @VikAdvani, me again! xD
Now trying on an iPhone device it removed only one of the errors, the first one.

The other: `clang: error: linker command failed with exit code 1 (use -v to see invocation)` still there. I Googled it and saw that it could be any kind of problem! But if have any ideias do help me out...

**Comment by leocavalcante** [comment]
Aha! Did it by setting `Enable bitcode` to `No`.
Cheers!

**Comment by VikAdvani** [comment]
Hi @leocavalcante, glad it works!
