### ISSUE TITLE
Object disappear beyond 100 meter (2.4.0)

### ISSUE THREAD

**Issue by domvon** [viromedia/viro#194]
Not sure if this is a bug or a new setting I missed, but objects (e.g. ViroBox) placed beyond 100 meter from origin don't show up in the AR Scene anymore. For example they are visible at [0, 0, 20] but invisible at [0, 0, 100]. Any idea? Thanks.

**Comment by dam00n** [comment]
Hi @domvon were you able to place objects at [0,0,100] prior to v2.4? We can take a look to see if this is a regression but wanted to verify that this is behavior that changed in v2.4. Thanks

**Comment by domvon** [comment]
Hi @dam00n , yes this definitely worked fine in 2.2, but stopped working for us since upgrading to 2.4. Thanks

**Comment by dam00n** [comment]
This issue has been fixed in ViroReact v2.5.1, release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases
