### ISSUE TITLE
Unclear documentation: performARHitTestWithPoint(x:number, y:number)

### ISSUE THREAD

**Issue by AppPear** [viromedia/viro#195]
Hi, I tried to use `performARHitTestWithPoint`, but I was constantly getting off results. I used: 
```typescript
performARHitTestWithPoint(evt.nativeEvent.locationX, evt.nativeEvent.locationX)
```

That is the wrong way of using it as performARHitTestWithPoint doesn't work with @1 scale so in order to get proper results I needed to use the following way: 
```typescript
performARHitTestWithPoint(evt.nativeEvent.locationX * PixelRatio.get(), evt.nativeEvent.locationX * PixelRatio.get())
```

For saving time for others you might want to include this in the documentation.

Thanks!

**Comment by dam00n** [comment]
Hi @AppPear, thanks for the heads up. Will take a look and update where appropriate.
