### ISSUE TITLE
setup-ide.sh error with GVRAudioSDK (= 1.120.0)

### ISSUE THREAD

**Issue by mypark** [viromedia/viro#197]
I ran setup-ide.sh on a freshly initialized project and got the following error

Unable to find a specification for `GVRAudioSDK (= 1.120.0)` depended upon by `ViroKit`

**Comment by achuvm** [comment]
Hi @mypark,

Looks like your Cocoapods repo hasnt been updated recently.

Try `pod repo update` before performing a `pod install`.

Let us know if that works!

**Comment by mypark** [comment]
yup that did it!
