### ISSUE TITLE
Fuse button

### ISSUE THREAD

**Issue by atlance01** [viromedia/viro#2]
In the documentation, there's mention of a Fuse button (http://docs.viromedia.com/docs/designing-for-mobile)

But I'm not seeing anything in the docs on how to actually implement one. Am I missing it or is it missing from the docs?

Thanks!

**Comment by manbod** [comment]
Thanks for filing this issue. 

We are currently working on adding support for fuse functionality through our APIs. In the meantime, you can achieve fuse like functionality using onHover() on any component and [timer](https://github.com/reactjs/react-timer-mixin).

**Comment by atlance01** [comment]
Ah very cool! Thanks for the link.

I'm really liking Viro so far - it was super easy to get up and going.
