### ISSUE TITLE
Preset GrvViewerParams

### ISSUE THREAD

**Issue by leocavalcante** [viromedia/viro#20]
Hi folks,
First of all, thank you very much @VikAdvani for the help in the last days. We have managed to develop an awesome cardboard experience for both Android and iOS, everybody on the agency are going nuts with crazy ideias :smile: So also, thank you all for providing this amazing platform.

One of our ideias envolves delivering for each end-user a cardboard headset and a link to app on the stores. So we are wondering if its possible to define through Viro a default set of headset params (the same as we would deliver) so the user can skip the QR mapping process. How can we accomplish that? Didn't found anything like these on the docs.

Cheers.

**Comment by VikAdvani** [comment]
Hi @leocavalcante, that's great to hear! Excited to hear that you got everything working as intended! 💯 

As for defining a default headset, as of now, in the current platform there isn't a way to do this. However, this is something we can investigate and get back to you on. We'll need to do a bit of digging to see if this is possible.

**Comment by leocavalcante** [comment]
Cool!
We did a little search on Cardboard SDK and found [HeadMountedDisplayManager](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/HeadMountedDisplayManager) and [GvrViewerParams](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrViewerParams) don't know if Viro could give GrvView access to handle it naively or provide a ViroReact+react-viro bridge to set this up in JavaScript.
Our ideia is to not just change headset vendors, but the possibility to fully set the possible parameters so we can adjust it even better (then the vendor, lol) for the Cardboard lenses and sizes we are going to distribute within the app.

Glad to hear you are going to dig into.

**Comment by dam00n** [comment]
We looked into this and it does not appear this is something we can do on the Viro side. Here is a link to how you can register a headset and get a QR code -> https://wwgc.firebaseapp.com/

Sorry for the delay in response, was hoping that this functionality would be available in an update to GVR. Let us know if you found anything and we can take a look.
