### ISSUE TITLE
how to prevent onDrag event automatically dragging object + And not have the gyroscope to control the view of the user

### ISSUE THREAD

**Issue by dominicrico** [viromedia/viro#200]
Hi there,

if I add an `onDrag` property the and object it is automatically dragged around when I start dragging.
How do I prevent this behavior? I want to implement my own dragging function that does something different as I don't need to drag objects around.

I want to show different panorama images, but I don't want the gyroscope to control the view of the user. Therefore I added an ARScene with a Sphere and Image Material, if there is another solution for this, then let me know.

Thank you in advance!

**Comment by dthian** [comment]
Hi @dominicrico,

Quick question - is this for AR or VR?

**"I want to implement my own dragging function that does something different as I don't need to drag objects around."**
- If you want don't want to drag objects around, then don't set the dragging function for a given Node. What exactly is the behavior that you have in mind with regards to user interaction with the 3D scene? I think you might be mixing the idea of "dragging behavior" vs " reacting to Android Touch Gestures", where Android Gesture APIs may better fit your use case. 

**"I want to show different panorama images, but I don't want the gyroscope to control the view of the user."**
- If you don't want the gyroscope to control the user's view, i would suggesting using an activity with a [ViroViewScene](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewScene.html) instead, as the Camera there does not react to the device's rotation like VR or AR. Your solution of adding an ARScene and Sphere + Image Material will not work as a mitigation.

**Comment by dominicrico** [comment]
Hey @dthian,

this is more like an Panorama Image/Video player/viewer than real AR/VR application. FYI: I use the react lib for my project.

I tried adding an Android Gesture Recognizer but it doens't work if there is an Viro component. I don't know what I'm doing wrong there, without a Viro component the Recognizer works as expected.

Is there an ViroViewScene equivalent for the react lib? 

Thanks for your help!

**Comment by dthian** [comment]
Hey @dominicrico,

Apologies, I was thinking of ViroCore upon mentioning ViroViewScene - we should have a react lib equivalent in the next release of ViroReact, of which is coming up very, very soon (most likely this week) :) I'll update this thread once the update is out. Ideally, using the ViroReact's ViroViewScene should solve the problems you are experiencing above, with your own Gesture Recognizers.

**Comment by dominicrico** [comment]
Hey @dthian,

can't wait for the update ;) Thanks again!

**Comment by dthian** [comment]
Hey @dominicrico, we've actually just [released ViroReact 2.5.1 ](https://docs.viromedia.com/docs/releases#section-new-features)! This should contain the [Viro3DSceneNavigator](https://docs.viromedia.com/docs/viro3dscenenavigator) (a ViroViewScene counterpart)  that you'll need as mentioned above. 

Do let us know if you have any issues or questions.

**Comment by dominicrico** [comment]
Hey @dthian, aweseome! Thank you for the info and help!

**Comment by luyx2412** [comment]
It's still same issue with onDrag event automatically dragging object, How can resolve this problem?
Thanks

**Comment by dthian** [comment]
Hey @luyx2412, one thing you can try is using onTouchDown, Move, and Up events to simulate drag events on your own through the [ViroController](https://docs.viromedia.com/docs/virocontroller).
