### ISSUE TITLE
[Feature Request] Notification callback for PreloadingSounds

### ISSUE THREAD

**Issue by dthian** [viromedia/viro#201]
First, if I'm trying to have multiple audio files playing simultaneously (ViroSpatialSound component), is there a way for me to access a callback for when those files have loaded, so I can play them all simultaneously? Currently they seem to load lazily and play whenever they've been loaded, so they all start at different times.

**Comment by dam00n** [comment]
This issue has been fixed in our latest release, ViroReact 1.6.0. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/3d-objects#section-loading-3d-objects

Let us know if you still have issues.
