### ISSUE TITLE
[Bug] Playing two ViroSpatialSound simultaneously goes out of sync. 

### ISSUE THREAD

**Issue by dthian** [viromedia/viro#202]
If I try and play two  preloaded "ViroSpatialSound" elements, they are out of sync.

**Comment by rupertparry** [comment]
Definitely interested in a fix for this as soon as it's feasible. To give you an idea of the problem, when I play two ViroSpatialSound components, they each start at a very different time. Sometimes this is as much as 10-15 seconds. In fact, sometimes it happens with just a single ViroSpatialSound element. It's very difficult to have an event in AR coincide with spatial audio if there's a huge delay in hearing the sound.

**Comment by dam00n** [comment]
This issue has been fixed in our latest release, ViroReact 1.6.0. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/3d-objects#section-loading-3d-objects

Let us know if you still have issues.
