### ISSUE TITLE
Viro AR example broken and/or out-of-date

### ISSUE THREAD

**Issue by jlyonsmith** [viromedia/viro#204]
Your examples that show how "eject" a ViroAR project and build native iOS and Android apps are out-of-date in that they don't refer to current versions of the Apple, Android and React Native tools.  I was in fact unable to get [ViroARSampleApp](https://github.com/viromedia/ViroARSampleApp) to work.

I've created an up-to-date example that details all the sometimes painful steps that you must go through to get a React Native ejected and working with Viro.  Most of the issues are to do with React Native continuously breaking support for CocoPods and `use_frameworks!`.  

You can find the example at [TestViroAR](https://github.com/jlyonsmith/TestViroAR).  Please feel free to share and/or submit enhancements.  I'd like to get that boring white cube shaded...

**Comment by dam00n** [comment]
Thanks @jlyonsmith for sharing your steps and code with us. Will share with others who run into similar issues. We are upgrading to a newer version of RN in our next release, so hopefully some of these issues go away. Will also take a look at our implementation to see if there are mitigation we can do on our end.

**Comment by dam00n** [comment]
We upgraded to RN 0.55.1 with our latest release -> ViroReact 2.6.0. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/3d-objects#section-loading-3d-objects

This resolved most of the issues. Closing this issue but please reopen if you are still having issues. Thanks for your help.
