### ISSUE TITLE
3D Object not showing up

### ISSUE THREAD

**Issue by peterel** [viromedia/viro#206]
Hi folks,

Trying to get a 3D object to show. Adapted the HelloWorld Virosample app as below but cant seem to get anything up. The model is in order (viewing it both on Meshlab and Xcode). Texture and obj are in same folder and ambient light is added. Any clue?

```
return (
		<ViroARScene onTrackingInitialized={this._onInitialized} >
		<ViroText text={this.state.text} scale={[0.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
		<ViroAmbientLight color="#FFFFFF" />
		<Viro3DObject
	    source={require('./res/model.obj')}
            resources={[require('./res/model.obj.mtl'),
			require('./res/model.jpg')]}
            position={[0, 0, -1]}
            scale={[1, 1, 1]}
            type="OBJ"
		/>
		</ViroARScene>
	);
```

**Comment by saboteur111** [comment]
Hi, @peterel, can you double check if your mtl file is named model.obj.mtl? Whenever mtl files are exported, they usually don't include the .obj extension.

**Comment by peterel** [comment]
@saboteur111 Thanks for your reply. Indeed it is. See attached screenshot. I had a suspicion that something was off here too but changing the filename to exclude the .obj made no difference either. Any other ideas would be appreciated.

<img width="259" alt="screen shot 2018-04-02 at 22 10 17" src="https://user-images.githubusercontent.com/24371993/38213774-c3b3a7bc-36c2-11e8-859d-ef766021be16.png">

**Comment by saboteur111** [comment]
Could u post your obj and textures here and I can take a look?

**Comment by peterel** [comment]
Sure, thanks!

[obj etc.zip](https://github.com/viromedia/viro/files/1871243/obj.etc.zip)

**Comment by dam00n** [comment]
Hi @peterel try the follow to set up your obj

```
...

<Viro3DObject source={require('./res/rock/obj/model.obj')}
         position={[1, 0, -1]}
         scale={[1, 1, 1]}
         type="OBJ"
         materials="face"
         />
      </ViroARScene>
    );
  },

});

ViroMaterials.createMaterials({
  face: {
    shininess : 2.0,
    lightingModel: "Blinn",
    diffuseTexture: require('./res/rock/obj/model.jpg'),
  },
});```

**Comment by peterel** [comment]
@dam00n Great, it works, thanks! Im not sure what shininess/lightingModel and diffuseTexture does but I guess I can look that up in the docs. Closing.

Best,

Peter

**Comment by ranjanpoudel1234** [comment]
Hi @dam00n , could I send you my model somewhere so you could check it for me as well ? I have it all setup similar to above, some models are working, but this one specific model is not showing up. Weird thing is, if I use different obj but use the texture of this problem model, the texture applies fine in that working model.

**Comment by Mukhammadsharif** [comment]
SyntaxError: /Users/mukhammadsharif/Projects/Archie/assets/skull/12140_Skull_v3_L2.obj: Unexpected token (1:0) I can't load 3d objects .obj and .mtl
