### ISSUE TITLE
setup-ide.sh not running correctly

### ISSUE THREAD

**Issue by bryantAXS** [viromedia/viro#212]
I'm trying to setup a viro react project to use XCode. When I run the setup-ide.sh script I'm getting these errors:

```
==== Running iOS Setup Script ===
running with verbose logging
sed: can't read s/VIRO_PROJECT_NAME/virodemo/g: No such file or directory
Analyzing dependencies
[!] Unable to find a target named `VIRO_PROJECT_NAME`, did find `virodemo`, `virodemoTests`, `virodemo-tvOS`, and `virodemo-tvOSTests`.
Add: ":NSAppTransportSecurity:NSAllowsArbitraryLoads" Entry Already Exists
Add: ":NSCameraUsageDescription" Entry Already Exists
sed: can't read s/VIRO_PROJECT_NAME/virodemo/g: No such file or directory
```

Before running the script I went through and updated all the `VIRO_PROJECT_NAME` placeholders in the codebase. Any thoughts?

**Comment by achuvm** [comment]
Hey @bryantAXS,

Yeah our script is looking for those `VIRO_PROJECT_NAME` placeholder text and is failing because it doesn't/hasnt found them.

I'm curious if the script kept on running regardless of the error.

On the other hand, you can undo your manual changes or simply create a new project.

We have a story in our backlog to make the scripts more resilient.

Thanks,

**Comment by bryantAXS** [comment]
Thanks @achuvm 

Just to confirm, I should be running the install script before updating those placeholders?

Thank you!

**Comment by achuvm** [comment]
@bryantAXS,

The `setup-ide.sh` script updates those placeholders themselves. Just curious, does our documentation ask the user to update those placeholders? It may be that we have outdated instructions.

Thanks!

**Comment by bryantAXS** [comment]
Hmm, actually it might not explicitly say that. I think I might have been reading into it too much. It mentions replacing the `API_KEY_HERE` but maybe not the `VIRO_PROJECT_NAME` placeholder.

Thanks!

**Comment by achuvm** [comment]
Ahh okay, good to know!

Let us know if you run into any other issues

**Comment by bryantAXS** [comment]
It looks like running the script even while leaving the `VIRO_PRJECT_NAME` still is giving some errors

```
==== Running iOS Setup Script ===
running with verbose logging
sed: can't read s/VIRO_PROJECT_NAME/virodemo/g: No such file or directory
Analyzing dependencies
[!] Unable to find a target named `VIRO_PROJECT_NAME`, did find `virodemo`, `virodemoTests`, `virodemo-tvOS`, and `virodemo-tvOSTests`.
sed: can't read s/VIRO_PROJECT_NAME/virodemo/g: No such file or directory
```

**Comment by achuvm** [comment]
Did you setup the project using the following commands:

1. `react-viro init virodemo`
2. `cd virodemo`
3. `./setup-ide.sh --ios`

Thanks,

**Comment by bryantAXS** [comment]
Yep those exact steps

**Comment by achuvm** [comment]
Interesting, when you go to `virodemo/ios/`.

Do you see a file named `Podfile`?

The script that is run is at `virodemo/node_modules/react-viro/bin/ios-setup.sh`

Thanks,

**Comment by bryantAXS** [comment]
Yep the `Podfile` is in there...

https://cl.ly/0G0G2L3O450I

**Comment by achuvm** [comment]
Hmm, can you try running this command from `virodemo/`?

`cp node_modules/react-viro/ios/dist/podFile/Podfile ios/ && sed -i '' "s/VIRO_PROJECT_NAME/virodemo/g" ios/Podfile`

This will pull the file over and copy it into the `ios` directory, then run the swap command.

I'm curious if running this manually works or errors out (is it possible you don't have bash?)

Thanks,

**Comment by bryantAXS** [comment]
That command gave me:

```
sed: can't read s/VIRO_PROJECT_NAME/virodemo/g: No such file or directory
```

**Comment by achuvm** [comment]
Hmm, I'm thinking it's a mismatch of sed versions:

https://stackoverflow.com/questions/43171648/sed-gives-sed-cant-read-no-such-file-or-directory?rq=1&utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Unfortunately `sed` doesn't have a `--version` option on OSX.

I wonder if you run the command I gave you above without the `''` after `-i` if that'll work:

```cp node_modules/react-viro/ios/dist/podFile/Podfile ios/ && sed -i '' "s/VIRO_PROJECT_NAME/virodemo/g" ios/Podfile```

Can you also run `which sed` and `bash --version`? Also what MacOS version are you running?

Thanks

**Comment by bryantAXS** [comment]
```$ which send
/usr/local/bin/sed
$ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin17.0.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
OSX: 10.13.3

**Comment by bryantAXS** [comment]
That `sed` copy command works, but he install script still spits out a `sed` error when running.

```
==== Running iOS Setup Script ===
running with verbose logging
sed: can't read s/VIRO_PROJECT_NAME/virodemo/g: No such file or directory
Analyzing dependencies
[!] Unable to find a target named `VIRO_PROJECT_NAME`, did find `virodemo`, `virodemoTests`, `virodemo-tvOS`, and `virodemo-tvOSTests`.
Add: ":NSAppTransportSecurity:NSAllowsArbitraryLoads" Entry Already Exists
Add: ":NSCameraUsageDescription" Entry Already Exists
sed: can't read s/VIRO_PROJECT_NAME/virodemo/g: No such file or directory
```

**Comment by achuvm** [comment]
Hey @bryantAXS,

Yeah, to make it work for now, you'll have to update the setup script before running it.

The file is located at `virodemo/node_modules/react-viro/bin/ios-setup.sh` and you'll need to replace every invocation of `sed` with `usr/bin/sed` (the default system version).

We'll update our setup script to account for this case.

Thanks!

**Comment by bryantAXS** [comment]
Just to follow up, I updated those `sed` invocations within the `node_modules` dir and the install went smoothly 👍

**Comment by dam00n** [comment]
Closing this issue, let us know if you run into other problems.
