### ISSUE TITLE
Rotation in object 3D

### ISSUE THREAD

**Issue by Kevinmenar** [viromedia/viro#218]
Hi! I have a problem, I am trying to rotate a component and  after I set a animation from Maya. When I do the last animation, the 3dObjects moves to a different position that I set it. I guess  when I did the rotation animation, my axis y,z changed. I am trying to change the axis component, but I do not know how

**Comment by saboteur111** [comment]
You could try to create a new group with your animated object and rotate or you may have to redo and re-keyframe the animation again. You could try asking Maya Animation-related forums for some help from animators. This may help: http://forums.cgsociety.org/archive/index.php?t-781361.html

**Comment by Kevinmenar** [comment]
Hi @saboteur111, thanks for your answer. I am not sure that you said me, I am rotating the object with viroAnimation until that the object has been clicked, when it finished I need to run the next animation from maya and preserve the current state. If I create a new object, I will lost the current state of my animation

**Comment by dam00n** [comment]
@Kevinmenar thanks for the video, that helps visualize the issue. It seems, based on my viewing of the video, that the maya animation of the cube does not return to its initial position. Meaning it starts at say, [0,0,0] but finishes at [0,-1,1] or something like that. Can you make the maya animation return to its starting point.

Also can you paste your Viro3Dobject animation code for the component and the ViroAnimation code here so we can take a look. If you are will to share the model, that would be helpful also. You can email it to us at support@viromedia.com and we can repro on our end and look into it more.

**Comment by Kevinmenar** [comment]
Hi @dam00n , I sent you a email with the code of my dice.

**Comment by VikAdvani** [comment]
Closed due to inactivity. Reopen if needed.
