### ISSUE TITLE
Quizz

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#22]
Hello 

I was wondering if you think that making a quiz will be easy to do with your plateform ?
Thanks for your help

**Comment by achuvm** [comment]
Hi @Zirconiumirish,

Yes, a game could be easily built with our platform since we support Images, Text and 3DObjects with touch events.

If there are any other components you want/need, feel free to let us know and we'll try to accommodate/find alternatives.

Thanks,

**Comment by Zirconiumirish** [comment]
Cool thanks for the answer

**Comment by Zirconiumirish** [comment]
Hello another question I would like to use the drag features but don't really understand how it works.
Do you have any demos which is using this features as an example ?

Thanks

**Comment by dthian** [comment]
To make an object draggable, you would just need to assign a callback to the onDrag property of the control. There should be a small code snippet sample at http://docs.viromedia.com/docs/events demonstrating how onDrag events can be assigned to a ViroImage control.

**Comment by Zirconiumirish** [comment]
Just find it thanks
