### ISSUE TITLE
ViroReact v.2.5.1 that includes support for x86_64 architecture doesn’t seems to build to successfully

### ISSUE THREAD

**Issue by dam00n** [viromedia/viro#220]
Tried to test the new ViroReact v.2.5.1 that includes support for x86_64 architecture. _Enables the iOS simulator_  But it doesn’t seems to build to successfully. We’re getting:

❌  fatal error: lipo: -remove's specified would result in an empty fat file

** BUILD FAILED **

The following commands produced analyzer issues:
    Analyze Base/RCTModuleMethod.mm
(1 command with analyzer issues)

The following build commands failed:
    PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks build/Build/Intermediates.noindex/*projectName*.build/Debug-iphonesimulator/*projectName*.build/Script-56B600998EAC79E7AF04CD4F.sh
(1 failure)

**Comment by dam00n** [comment]
This issue has been fixed in our latest release, ViroReact 2.6.0. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/3d-objects#section-loading-3d-objects

Please re-open is you are still having issues

**Comment by KimAM** [comment]
I'm having the same issue with ViroReact 2.6.1. (Deleted node_modules before reinstalling and double checked package.json that I got the latest version)

I get these warnings during build:

> ⚠️  ld: ignoring file /Users/kimmartinsen/Projects/Entur/entur-clients/node_modules/react-viro/ios/dist/lib/libViroReact.a, missing required architecture x86_64 in file /Users/kimmartinsen/Projects/Entur/entur-clients/node_modules/react-viro/ios/dist/lib/libViroReact.a (2 slices)
> ⚠️  ld: ignoring file /Users/kimmartinsen/Projects/Entur/entur-clients/node_modules/react-viro/ios/dist/ViroRenderer/ViroKit.framework/ViroKit, missing required architecture x86_64 in file /Users/kimmartinsen/Projects/Entur/entur-clients/node_modules/react-viro/ios/dist/ViroRenderer/ViroKit.framework/ViroKit (2 slices)

Then finally:

> ❌  fatal error: lipo: -remove's specified would result in an empty fat file
> ** BUILD FAILED **

When checking libViroReact.a with lipo I get the following output

$ `lipo -info ../../node_modules/react-viro/ios/dist/lib/libViroReact.a`

> Architectures in the fat file: ../../node_modules/react-viro/ios/dist/lib/libViroReact.a are: armv7 arm64

**Comment by radvani** [comment]
Thanks for reporting this; we've resolved the issue and the next release of ViroReact will include a Universal framework (arm64 and x86_64) for use on both device and simulator.

**Comment by KimAM** [comment]
Sounds great, thanks! 😊

**Comment by VikAdvani** [comment]
Hi @KimAM, this should be fixed in  our latest major release v2.7 -> See release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases
