### ISSUE TITLE
Unable to load in iOS: Application virodemo has not been registered.

### ISSUE THREAD

**Issue by bryantAXS** [viromedia/viro#222]
Fresh install, just configured to XCode and built the app for the first time. Getting the error:

`Application virodemo has not been registered`

It mentions to kill the package manager and restart `$ npm start` in the project's root folder, which I did. Same result. Any thoughts there?

**Comment by achuvm** [comment]
At the root of your project, you should have an `index.js` file, does it look like the following?

```
import { AppRegistry } from 'react-native';
import App from './App.js';

AppRegistry.registerComponent('virodemo', () => App);

// The below line is necessary for use with the TestBed App
AppRegistry.registerComponent('ViroSample', () => App);
```

It looks like your app is looking for a component named `virodemo`, but one hasn't been registered in Javascript.

**Comment by bryantAXS** [comment]
Ah shoot ok, that makes sense. We're in `react-native` world now. I thought it was still a Viro specific error.

Thank you!

**Comment by achuvm** [comment]
Yep, although do let us know if for some reason our setup steps result in you still needing to modify files or perform a few other steps to get it working.
