### ISSUE TITLE
Integrating viromedia with React Native Projects

### ISSUE THREAD

**Issue by Ahmednagyyy** [viromedia/viro#223]
Hello guys,

I'm trying to Integrating viromedia with new React Native Project but the doc. it doesn't help at all here is the Link of the official doc for what I need.
https://docs.viromedia.com/docs/integrating-with-react-native-projects

but as you see It's useless.

I Used the samples and its good, but I don't need the sample anymore I want to create my own project without download viromedia app to run my app on it. 

All I need is steps about how to install and integrate Viro-media with a new react native project, I'm willing to purchase a license but I can't  while I'm not able to use it on my own.

Thanks in advance.

**Comment by VikAdvani** [comment]
Hi @Ahmednagyyy, you can follow our guide here that shows how do that for Android:
https://docs.viromedia.com/docs/integrating-existing-projects-android

And for iOS do the following for a React Native project you set up:
1) Add react-viro to package.json - Make sure react version is 0.49.3
2) run npm install.
3) a. Unzip the following zip file in your project root
     b. Run chmod +x  setup-ide.sh to make it executable.
     c. Run setup-ide.sh --ios on the project root.

Note: If you have a new RN project you can run setup-ide.sh --android for android as well. 
I've attached the setup-ide.sh script for you here.

[setup-ide.sh.zip](https://github.com/viromedia/viro/files/1900719/setup-ide.sh.zip)

**Comment by dam00n** [comment]
@ttDemon it is possible you have a RN/Android issue. Check out this thread, there might be some solutions in there that help -> https://github.com/facebook/react-native/issues/14952

**Comment by ttDemon** [comment]
@dam00n @VikAdvani  I tried to create a new project react native, installed under the instructions for Android, but when running the project appears error:

Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 67470 into a non-jumbo instruction!

I have searched for fix but not fix yet, i use Window 10. Pls help me!

**Comment by dam00n** [comment]
There are a couple stackoverflow thread that list a couple solution you might try for this issue

https://stackoverflow.com/questions/33717886/errorexecution-failed-for-task-apptransformclasseswithdexfordebug

And a new thread

https://stackoverflow.com/questions/26093664/dexexception-cannot-merge-new-index-65536-into-a-non-jumbo-instruction

**Comment by ttDemon** [comment]
@dam00n thank you for confirm!
I'm making 360 videos. How can I watch 360 videos without glasses, which means I want to remove the glasses from the screen?

**Comment by ttDemon** [comment]
@dam00n Thanks for confirm.
Have you ever watched watch livestream 360? Will Viro allow watch livestream 360 video witch tag video360?

**Comment by dam00n** [comment]
Viro utilizes Exoplayer (Android) and AVPlayer (iOS) so it is possible to render HLS Streams in your projects with Viro. We have not ourselves worked with livestreaming video but there are multiple developers on the Viro platform that are working on building apps that include livestreaming.

**Comment by mypark** [comment]
looking at the setup ide script for ios - is it replacing the podfile and AppDelegate.m?  If so it would be overwriting the existing code there no?

**Comment by ttDemon** [comment]
@dam00n 
How can I watch 360 ​​when rotating the phone.  What props or method can I use?

**Comment by mypark** [comment]
@dam00n not really an issue per se - just a question about whether it overwrites those files - because existing projects might have custom code in there that a developer would have to re-apply.  If you can confirm that it overwrites - than it just means that would need to be noted in the instructions for a 
 future time.

**Comment by dam00n** [comment]
@mypark the setup ide script for iOS does overwrite. But it is intended to be used only for new projects. Thanks for the heads up. We will update our documentation where appropriate.

**Comment by ttDemon** [comment]
@dam00n 
I can not watch video 360 when I rotate the phone, I try to run example Hello world of you but also not watch 360. I run on Samsung A8. I do not know why.

**Comment by dam00n** [comment]
@ttDemon we need more information to repro this issue. 

1. Can you share a code snippet for the video?
2. What video are you using? Can you send us the link or file so we can test?
3. Does the video play but you can not rotate the phone to watch other parts of the video?

If you have the Viro testbed app, can you try the third option, Viro Media Player -> Tap No -> tap on screen to bring up player controllers -> tap on 360 -> does the 360 video play and can you rotate your phone to watch?

**Comment by VikAdvani** [comment]
Hi @ttDemon the Samsung A8 does not have a gyroscope which explains why you are unable to see the movie rotate as you rotate the the device :)

**Comment by amandeepmittal** [comment]
How to access `ngrok` while integrating Viro with react native on running the command `npm start`? It does not show up.
![Screenshot 2019-03-22 at 4 31 12 PM](https://user-images.githubusercontent.com/10234615/54818788-174f1000-4cc0-11e9-8bd3-a2469af01a6c.png)

**Comment by Shoaib009** [comment]
open a new command prompt and write ipconfig in the terminal than take the ipv4 and paste at the place of ngrok it will work

**Comment by Shoaib009** [comment]
@amandeepmittal 
![err](https://user-images.githubusercontent.com/42305085/55315544-f471e800-5485-11e9-9181-d706c444a40f.PNG)

**Comment by amandeepmittal** [comment]
@Shoaib009 Thanks! It did work.

**Comment by Goussaka** [comment]
Helllo, how can I add viro inside project react native v 0.60+ !
