### ISSUE TITLE
Questions about Velocity proprety in Physics Body

### ISSUE THREAD

**Issue by llf22282776** [viromedia/viro#224]
I want to give an  initial velocity  to the object and because of  gravity influence ,the object can do parabolic motion.

but when i give the velocity  to the object and enable gravity ,the gravity  did't work 
here is the code:
![1](https://user-images.githubusercontent.com/22473894/38711448-50afbbfa-3ef8-11e8-977c-70dcffd4b844.jpg)

could you please give me some advice about how to make object do parabolic motion

**Comment by dthian** [comment]
Hey @llf22282776, applying an acceleration (like gravity) on a rigid body also affects that body's velocity output. Thus, when you forcefully set your own velocity, you will override any physics that are applied to this body (hence gravity equations are effectively nullified). 

You can view more information about the physics properties [here](https://docs.viromedia.com/docs/physics).

If you want to "launch" objects in a parabolic motion, i would suggest applying an[ impulsive force](https://docs.viromedia.com/docs/physics#section-impulsive-forces-and-motion) on an object in the direction you wish to launch it. 

[Here](https://github.com/viromedia/viro/blob/master/js/ARPhysicsSample/BasicPhysicsSample.js#L186) is an example where we apply an impulse force on an object, with a force direction originating from the controller (controller forward).

Do let us know if you have any additional questions.

**Comment by dam00n** [comment]
Closing this issue as solution was provided. Please re-open if you have any follow up.
