### ISSUE TITLE
Issue when Archiving with XCode: Enum values with underlying type 'NSInteger' should not be used as format arguments

### ISSUE THREAD

**Issue by bryantAXS** [viromedia/viro#225]
I'm archiving my app for upload to a testbed environment. Along the way I'm getting the error:

```
Enum values with underlying type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead.
```

within the library file RCTCacheKeyForImage line 28

Screenshot of the issue: https://cl.ly/0n1U2f0S0H0F

**Comment by achuvm** [comment]
Hi @bryantAXS,

Unfortunately this is an emergent with the version of React Native we're using and the latest Xcode. Feel free to click that "Fix" button in the error which will automatically add the cast.

This might error a few more times in React Native's (RCT*) code, but unless you wipe away your `node_modules/react-native` directory, you'll only need to do it once.

Our next update should bump up the React Native version to one which doesn't have this error.

Thanks!

**Comment by bryantAXS** [comment]
Ok, thanks. Any idea when the next update should be live?

Are all of these other issues in RCTText also related to your original answer?

https://cl.ly/1e3P0O2p191B

**Comment by achuvm** [comment]
Hi @bryantAXS,

We haven't seen those RCTText errors before. Are you on React-Native 0.49.3? 

Our next update should come within the next few days to a week (dependent on testing, App Store review, etc).

Thanks,

**Comment by dam00n** [comment]
@bryantAXS our latest release, ViroReact 2.6.0, has been upgraded to RN 0.55.1.  Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/3d-objects#section-loading-3d-objects

Let us know if you are still have issues after upgrading
