### ISSUE TITLE
Support for THREEjs

### ISSUE THREAD

**Issue by robertjuh** [viromedia/viro#227]
Is there any way to use THREE.js within a ViroARScene?

I'll post the conversation i had with @dam00n below.

**Comment by robertjuh** [comment]
> Robert 
>
>@dmoon any way to use THREEjs in ViroARSCene?
> 
> **dmoon** 7 days ago
> 
> I don’t believe that threejs works with Viro, though we have not tried it.
> 
> **robert** 7 days ago
> 
> You reckon it would be a useful addition for the future?
> 
> I'm currently testing react-native-webgl out
> 
> **dmoon** 7 days ago
> 
> We are looking into web support. Is there something in particular about threejs or are you more interested in web support in general. Also are you doing AR?
> 
> **robert** 7 days ago
> 
> My goal is to reuse a part of the code of a threeJS webapplication
> 
> I basically want the model that is created in three (quite a bit of complex code so it is undesirable to rewrite all in react-native) presented in AR
> 
> **robert** 7 days ago
> 
> it's currently offline so i cant show it. But it's possible to edit this model with some options and teh model will update.
> 
> Basically, the end goal is that there will be zero local assets within the app. Everything is handled through some API, the model is constructed in THREE, and the (edited) model is displayed in AR
> 
> **dmoon** 7 days ago
> 
> Thanks for the additional context. Expo is open source, so there may be options to pull over the component you are interested in and bind it to Viro somehow (but you might have already tried that).
> 
> **robert** 6 days ago
> 
> I tried to normally install it alongside Viro and gradually tried to fix all errors i got, but got a new one each time so eventually i gave up, but i dont know if i tried correctly as i only had 1 day of experience with expo

**Comment by tetreault** [comment]
Why not use Expo if you want to reuse Three code? I've made some demos easily with `expo-three`

**Comment by radvani** [comment]
Three.js support is not planned.
