### ISSUE TITLE
Unexpected Character (Image files)

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#23]
I'm having a issue when building my project with an unexpected character do you know what happened ?

Thanks

**Comment by achuvm** [comment]
Hi @Zirconiumirish,

I found a thread with reports of the same issue: https://github.com/facebook/react-native/issues/6691

Some potential solutions from the thread are:
- clear your watchman cache `watchman watch-del-all`
- restart your packager w/ reset cache, ie. re-run `npm start --reset-cache`
- re-export/rename/re-download your image file
- ensure your file path has no spaces (ie. `Users/workspace/bad path/react-viro` would not work)

Let us know if you still have the issue. If you do still have an issue, feel free to attach some code and the image and we'll see if we can reproduce it.

Thanks,

**Comment by Zirconiumirish** [comment]
All done thanks for your help
