### ISSUE TITLE
ViroARScene has no propType for native prop VRTARScene.onTrackingUpdateViro of native type BOOL

### ISSUE THREAD

**Issue by SyedKabeer** [viromedia/viro#235]
Trying to run viro-sample app from git. 

In Android all i can see is VR with HelloWorld. Even after changing the boolean value at line 44, when I try to run AR **I can still see only VR with Hello World!**

In iPhone VR examples runs fine but when try to run AR this happens in iPhone 7s - OS 11.3 

![image-1](https://user-images.githubusercontent.com/1648750/39033887-d29f44c4-44a6-11e8-9851-54f9b1d20c9a.jpg)

**Comment by SyedKabeer** [comment]
Working in iPhone when Changed  **react viro version** from 2.4.0 to 2.5.1 and that changed the deprecated methods (ViroSurface to ViroQuad)

Android still same issue. Cant see anything except black VR surface with **Hello World!**
Android camera permissions are given and API key is also same as iOS.
Installed ArCore apk also. Some help would be much appreciated.

**Comment by dam00n** [comment]
Hi @SyedKabeer, for the iOS deprecated methods, change any ViroSurface to ViroQuad and that yellow box should go away.

Re: Android - what device are you using. Depending on the device, OS and Daydream support, there are minor changes you might have to make. Take a look at our Testbed page -> https://docs.viromedia.com/docs/develop-with-viro

If you are still having issue please let us know

**Comment by SyedKabeer** [comment]
@dam00n 

In iPhone it is working all fine. Android has issues, same code which runs in iOS doesn't run in Android Device (Samsung S7 Edge).

Please refer the image below. This is what I see all the time for AR or VR.

![device-2018-04-23-104345](https://user-images.githubusercontent.com/1648750/39104483-87361b4a-46e3-11e8-9743-6f0c79411d97.png)

**Comment by SyedKabeer** [comment]
@manbod 

I did enable hot reloading I got the below error. I did all the fixes listed in the image below.
Doesn't solve the issue.

![screenshot_20180423-123941](https://user-images.githubusercontent.com/1648750/39107266-c1ebbcc6-46f3-11e8-9012-b61170d3f6e7.png)

**Comment by dam00n** [comment]
@SyedKabeer are you able to reload (not hot reload) just reload?

Also, Android devices running Nougat OS (or higher) w/ Cardboard must set debug={true} on SceneNavigator

Seems like the initial scene is being cached as @manbod mentioned. Let us know if the above helps, if not you can try clearing your cache and/or deleting the testbed from your device and reinstalling.

**Comment by SyedKabeer** [comment]
I tried clearing cache and reinstalling testbed many times, problem doesn't seems to solve.

SceneNavigator means **ViroSceneNavigator** right ?? Because i tried changing the debug value that doesn't work either.

Please refer screenshot below.
![screen shot 2018-04-25 at 6 30 38 pm](https://user-images.githubusercontent.com/1648750/39240612-e4b7657e-48b6-11e8-91c1-ec65f5ba4acf.jpg)

**Comment by manbod** [comment]
Hi @SyedKabeer ,
Sorry to hear you're running into issues. We'll need a little more info on why you are running into issues.

What version of the testbed app are you running? (The activity where a black screen loads up when you enter the local ip / ngrok url, it should say React-Viro version at the bottom of the page - It should say React-Viro version 2.6.0)
Can you paste the "dependencies" block code snippet from your package.json? (The react-viro version there should say version 2.6.1)
Can you paste your App.js contents here as well?
If you are upgrading from 2.5.1 -> make sure you remove your node modules and run npm install again.

Let us know, and we can dive deeper into your issue.

Thanks!

**Comment by VikAdvani** [comment]
Closed due to inactivity. Reopen if needed.

**Comment by tetreault** [comment]
After running the clean command in xcode and trying to build the app again, magically most of the build errors go away except one now: 

<img width="581" alt="screenshot 2018-11-26 15 27 08" src="https://user-images.githubusercontent.com/5934354/49040297-2bf71d80-f190-11e8-94a9-e321b6de8110.png">

It's just odd to have any errors at all when running in the testbed app as this project ran in testbed without errors when I last left off with it a week+ ago.

**Comment by tetreault** [comment]
Following up here -- @dthian helped me out in the viro slack. Was a very simple fix, I just needed to upgrade to v2.12.0 of Viro-React! 👍
