### ISSUE TITLE
How to use react-viro in react-native init <project name>

### ISSUE THREAD

**Issue by devalensio** [viromedia/viro#236]
i have a problem when import { ViroARScene, ViroText } from 'react-viro' and we are not using react-viro init --verbose

However when run in ios with xcode, there is a error message: VRTTtext does not exist

I already tried to follow the instruction:
1. npm install -S -E react-viro --ignore-scripts
2. ./node_modules/react-viro/bin/javascript-setup.sh <project_name> false where project name is the name of your project (it should match react-viro init <project_name>)
3. cp ./node_modules/react-viro/bin/setup-ide.sh .
4. chmod +x setup-ide.sh
5. mkdir bin
6. cp ./node_modules/react-viro/bin/ViroFBX bin

*we also already install rubby and CocoaPods but still there is a problem
"Requiring unknown module 493. if you are sure the module is there, try restaring Metro Bundler. You may also want to run 'yarn' or 'npm install'

But i already npm install by (deleting node modules --> npm install --> reload xcode)

Thank you

**Comment by achuvm** [comment]
Hi @devalensio,

The minimum amount of work you need to do is outlined in this gist: https://gist.github.com/achuvm/a085121a46fe8d9f6e0c9a20c5ef5dd2

These are some of the changes that are automatically applied when running the `./setup-ide.sh --ios` script which is outlined in our documentation page: [Set up Xcode with ViroReact
](https://docs.viromedia.com/docs/starting-a-new-viro-project-1) 

Although, you mention the error you see is `VRTTtext does not exist`. I'd like to confirm that's a typo in your post above (and not the actual error you see).
