### ISSUE TITLE
Can't load .vrx on require function

### ISSUE THREAD

**Issue by dody87** [viromedia/viro#237]
I have a problem trying to load AR sample .vrx file. It seems to be not loaded correctly.

`15:56:45 [exp] Unable to resolve "./res/emoji_smile/emoji_smile.vrx" from "viromedia/ARSample/helloWorldScene.js"
`

**Comment by VikAdvani** [comment]
I replied error to another issue but I'm repeating here:
Hi @dody8,  how did you init the AR Sample? Are you using expo(we don't work with expo) or did you use react-viro init? Can you verify:

1) The file is in the proper path ./res/emoji_smiile/emoji_smile.vrx.
2) Your rn-cli.config.js in the project root has the following below getAssetRoots():
getAssetExts() {
    return ["obj", "mtl", "JPG", "vrx", "hdr"];
  },
