### ISSUE TITLE
TypeError: Cannot set property 'viroAppProps' of undefined

### ISSUE THREAD

**Issue by llf22282776** [viromedia/viro#239]
These days i went on a trip and when i come back ,i found viro has been upgraded.
 
But i cannot run my viroProject again after upgradeing then viro to 2.6.0 version

the error  as follows ：
![1](https://user-images.githubusercontent.com/22473894/39093861-e4fb1702-4658-11e8-8893-42d480cb207c.jpg)

Here is the code (run quite well in 2.5.x version)：
![2](https://user-images.githubusercontent.com/22473894/39093869-0e04ab36-4659-11e8-985a-2b4501696613.jpg)

If the way to pass props to ViroScene is changed,please tell me the newest way to do that .

**Comment by llf22282776** [comment]
@dthian @dam00n @achuvm 
Sorry for @ again.

Now i cannot go back to 2.5.1 and the app cannot work at all .

Torrow we will show this project as a teamwork,

please give me some advices ,really urgent

**Comment by dam00n** [comment]
Did you upgrade your React Native to v0.55.1?

Upgrade instructions in the release notes:
https://docs.viromedia.com/docs/releases

**Comment by achuvm** [comment]
Hi @llf22282776,

Have you considered building through Android Studio/Xcode? That will allow you to build your app without needing to use our testbed application.

The instructions for that can be found here:

Android Studio: https://docs.viromedia.com/docs/installing-viro-android
Xcode: https://docs.viromedia.com/docs/starting-a-new-viro-project-1

Let us know if you need help with this.

Thanks!
