### ISSUE TITLE
Physics: When using ViroQuad with ViroBox and Physics, the box appears to fall through the quad

### ISSUE THREAD

**Issue by dam00n** [viromedia/viro#242]
The code below is a ViroBox that falls and a ViroQuad that represent a floor. The box should land on the quad but instead falls through

<ViroBox
        position={[0, 2, -1]}
        scale={[0.2, 0.075, 0.2]}
        physicsBody={{
        useGravity:true,
        type: "Dynamic",
        enabled: true,
        mass:1,
        }}
        />

      <ViroQuad
        position={[0, -.5, -1]}
        materials={["blue"]}
        rotation={[-90, 0, 0]}
        height={2}
        width={2}
        physicsBody={{
        type: "Kinematic",
        mass:0,
        }}
        />

**Comment by dthian** [comment]
This is fixed in ViroReact v2.7.0, closing.
