### ISSUE TITLE
ARImageMarker Documentation

### ISSUE THREAD

**Issue by parideis** [viromedia/viro#244]
Hi,
in the first code example under https://docs.viromedia.com/docs/viroarimagemarker there is a closing '}‘ for the scale prop missing. 

Besides that I really like how good image recognition works and I'm exciting to see more android devices getting added. 😃

**Comment by dam00n** [comment]
Hi @parideis, thanks for the correction. Documentation has been update. Excited to see what you build with image recognition. We have additional sample code demos on Github if you want to try those out also. 

Tesla Logo Demo -> https://github.com/viromedia/viro/tree/master/js/ARCarDemo
Black Panther Movie Poster Demo -> https://github.com/viromedia/viro/tree/master/js/ARPosterDemo
