### ISSUE TITLE
AR Portal doesn't render correctly

### ISSUE THREAD

**Issue by Thomas101** [viromedia/viro#245]
ReactViro version: 2.5.1 & 2.6.0
Device: 2018 iPad
iOS Version: 11.3

Created a new project with the example code from the [How to build AR Portals in 5 mins](https://blog.viromedia.com/how-to-build-ar-portals-in-5-mins-w-react-native-viro-ar-b939850def94) tutorial, but the portal renders incorrectly. The portal doesn't show the portaled world within it, nor does the texture paint to the portal model. If you walk through the portal the 360 panorama does then render correctly, the portal model still has no texture.

![img_0006](https://user-images.githubusercontent.com/103586/39240912-1f9b1c92-487d-11e8-970b-6e8e94530ad6.PNG)

**Comment by dam00n** [comment]
Hi @Thomas101, I just tried the AR Portal example again on ViroReact 2.6.0 and it worked fine for me. Based on your screenshot, it seems like your materials (portal_ship_normal.png, etc) are not in the correct location. Are they in the same directory as portal_ship.vrx?

**Comment by dam00n** [comment]
Do other FBX/VRX 3D models work for you? Here are some we offer that you can try -> https://docs.viromedia.com/docs/assets#3d-objects

Trying to see if this is specific to ship portal issue or a 3D object issue. Assuming you are just using the tutorial code, but can you paste it below, so I can try it out on my end. Can't repro on my machine.

**Comment by Thomas101** [comment]
Yeah wow emoji works okay. If you need any more info want to try anything else let me know :)

![img_0008](https://user-images.githubusercontent.com/103586/39249261-2856723c-4896-11e8-9453-3e86ef7c9827.PNG)

```jsx
return (
      <ViroARScene>
        <ViroAmbientLight color={"#aaaaaa"} influenceBitMask={1} />

        <ViroSpotLight
            innerAngle={5}
            outerAngle={90}
            direction={[0,-1,-.2]}
            position={[0, 3, 1]}
            color="#aaaaaa"
            castsShadow={true}
            />

        {/* Node that contains a light, an object and a surface to catch its shadow
            notice that the dragType is "FixedToWorld" so the object can be dragged
            along real world surfaces and points. */}
        <ViroNode position={[-.5, -.5, -.5]} dragType="FixedToWorld" onDrag={()=>{}} >

          {/* Spotlight to cast light on the object and a shadow on the surface, see
              the Viro documentation for more info on lights & shadows */}
          <ViroSpotLight
            innerAngle={5}
            outerAngle={45}
            direction={[0,-1,-.2]}
            position={[0, 3, 0]}
            color="#ffffff"
            castsShadow={true}
            influenceBitMask={2}
            shadowMapSize={2048}
            shadowNearZ={2}
            shadowFarZ={5}
            shadowOpacity={.7} />

          <Viro3DObject
              source={require('./emoji_wow/emoji_wow.vrx')}
              position={[0, .2, 0]}
              scale={[.2, .2, .2]}
              type="VRX"
            lightReceivingBitMask={3}
            shadowCastingBitMask={2}
            transformBehaviors={['billboardY']}
            resources={[require('./emoji_wow/emoji_wow_diffuse.png'),
                       require('./emoji_wow/emoji_wow_specular.png'),
                       require('./emoji_wow/emoji_wow_normal.png')]}/>

          <ViroQuad
            rotation={[-90,0,0]}
            width={.5} height={.5}
            arShadowReceiver={true}
            lightReceivingBitMask={2} />

        </ViroNode>
      </ViroARScene>
    )
```

**Comment by dam00n** [comment]
Actually can you copy and paste your portal code? That is the one I want to copy onto my end and see if I get the same problem. Thanks

**Comment by Thomas101** [comment]
Sure, no problem. If would help, do you want the entire project? Happy to zip it up and send it across if that helps.

This is my `HelloWorldSceneAR.js` from the sample project...

```jsx
'use strict';

import React, { Component } from 'react';

import {StyleSheet} from 'react-native';

import {
  ViroARScene,
  ViroText,
  ViroConstants,
  ViroAmbientLight,
  ViroPortalScene,
  ViroPortal,
  Viro3DObject,
  Viro360Image,
  ViroSpotLight,
  ViroNode,
  ViroQuad
} from 'react-viro';

export default class HelloWorldSceneAR extends Component {

  constructor() {
    super();

    // Set initial state here
    this.state = {
      text : "Initializing AR..."
    };

    // bind 'this' to functions
    this._onInitialized = this._onInitialized.bind(this);
  }

  render() {
    return (
      <ViroARScene>
        <ViroAmbientLight color="#ffffff" intensity={200}/>
        <ViroPortalScene passable={true} dragType="FixedDistance" onDrag={()=>{}}>
          <ViroPortal position={[0, 0, -1]} scale={[.1, .1, .1]}>
            <Viro3DObject source={require('./portal_res/portal_ship/portal_ship.vrx')}
              resources={[require('./portal_res/portal_ship/portal_ship_diffuse.png'),
                          require('./portal_res/portal_ship/portal_ship_normal.png'),
                          require('./portal_res/portal_ship/portal_ship_specular.png')]}
              type="VRX"/>
          </ViroPortal>
          <Viro360Image source={require("./portal_res/360_island.jpg")} />
        </ViroPortalScene>
      </ViroARScene>
    )
  }

  _onInitialized(state, reason) {
    if (state == ViroConstants.TRACKING_NORMAL) {
      this.setState({
        text : "Hello World!"
      });
    } else if (state == ViroConstants.TRACKING_NONE) {
      // Handle loss of tracking
    }
  }
}

var styles = StyleSheet.create({
  helloWorldTextStyle: {
    fontFamily: 'Arial',
    fontSize: 30,
    color: '#ffffff',
    textAlignVertical: 'center',
    textAlign: 'center',  
  },
});

module.exports = HelloWorldSceneAR;
```

**Comment by Thomas101** [comment]
@dam00n found out what it is! Using the model and assets from the [tutorial page](https://blog.viromedia.com/how-to-build-ar-portals-in-5-mins-w-react-native-viro-ar-b939850def94) shows the behaviour. Using the model and assets from the [assets page](https://docs.viromedia.com/docs/assets) it works. Not sure what the difference between the two are.

Where did you grab your assets from?

**Comment by dam00n** [comment]
Glad that is it working now. I grabbed assets from the tutorial page and it worked for me. Maybe a wonky download? Will look into it more from our end to see if we need to update the tutorial zip file. Thanks for confirming it works now.

**Comment by tomasmigone** [comment]
Hi, im having the same issue in here.
It works fine on android on debug mode (running 'npm start').
if i build it for release it shows the portal as grey, tried both on android and ios.

I did try using the assets from the assets page as suggested but still having the same issue.

This is the error message i get on xcode for example. Looks like its searching for the files on a different directory, but i don't know how to modify that. Any clues?
`
2018-12-18 16:03:28.584277-0300 ViroSample[1605:466758] [ApiKeyMetrics] Attempt 1, performing request type 2 in 0 seconds
2018-12-18 16:03:28.614113-0300 ViroSample[1605:466759] Task <4D03E870-1D95-4566-9A1E-B89A98489E16>.<1> finished with error - code: -1100
2018-12-18 16:03:28.617990-0300 ViroSample[1605:466759] HTTP request [file:///var/containers/Bundle/Application/0D262A8B-EABE-4058-84E0-42FB77B4FE18/ViroSample.app/assets/res/portal/portal_archway/portal_entry.png] unsuccessful [status code 0]
2018-12-18 16:03:28.618049-0300 ViroSample[1605:466540] "FBX failed to load diffuse texture [portal_entry.png]"
Attempted to set an invalid set of interpolated points for the Particle Emitter!: Invalid argument
`

**Comment by VikAdvani** [comment]
Hi @tomasmigone, can I see the Javascript code for how you specified the portal? It's important for release builds to include the resources tag for the textures you are using. For example:

```
<Viro3DObject source={require('./portal_res/portal_ship/portal_ship.vrx')}
              resources={[require('./res/portal/portal_portal_archway/portal_netry.png')]}
```

**Comment by tomasmigone** [comment]
Hi, 
I solved the issue by converting the model into GLB format. I don't have the original code at hand at this moment, but i'm pretty sure that all files were properly added on the resources tag.
