### ISSUE TITLE
Viro3dSceneNavigator move world with device

### ISSUE THREAD

**Issue by Thomas101** [viromedia/viro#246]
Hi,

When using the `<ViroVRSceneNavigator />` the world moves around as the device moves. Is it possible to enable this behaviour when using a `<Viro3DSceneNavigator />` without needing to listen to gyro events and rotate the scene manually?

It would be really helpful for displaying 360 panorama images without support for a headset and having support for things like `onClick` without needing to centre in the crosshairs.

**Comment by Thomas101** [comment]
Thanks @dam00n already given the vrModeEnabled a try - wasn't aware of the rectileVisibility prop though.

Is there any way to interact with objects in the ViroVRSceneNavigator scene on a touch basis? From what I can see, only `onClick` and `onHover` work when the crosshairs move over an object, but as for dragging objects or just tapping the scene without targetting the events don't seem to fire.

**Comment by dam00n** [comment]
This issue might help -> https://github.com/viromedia/viro/issues/14
