### ISSUE TITLE
How can I explicitly retrieve the position of a dynamic physics body

### ISSUE THREAD

**Issue by dam00n** [viromedia/viro#249]
Hey all, we've been trying out ViRo for a multiplayer AR game, works very nicely. I have a question though: if i want to explicitly retrieve the position of a dynamic physics body, how would I proceed?

**Comment by dthian** [comment]
The position of a physics body is effectively the position of the node. Thus, you might be able to call getTransformAsync on a viro control to get that information.

https://docs.viromedia.com/v2.1.0/docs/viroview#methods

```
this.boxRef.getTransformAsync().then((transform) => {
        var pos = transform.position;
        // Do stuff with position
      });
```
