### ISSUE TITLE
Issues "Fetching JS Bundle"

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#25]
Hi, I'm experienceing couple of problems recently .

I launched the npm start command from root directory.
I'm launching my app on the phone, enter the ip adress of my computer and check that both are on the same network.

The terminal say : "Loading dependency graph, done"
My phone has a black screen and say "Fetching JS Bundle"

I didn't have error message

I already try to restart with --no-caches.

Thanks for your help.

**Comment by VikAdvani** [comment]
Hi @Zirconiumirish,
Are you using an iPhone or Android phone? This issue likely means your phone is unable to connect to your desktop. This sometimes happens on local networks as the IP assigned to your phone may not be able to reach the IP on your computer even though you are on the same network. To get around this, if you are using Android, you can reverse tether your phone and use localhost to connect to your desktop using android adb.

If you are using an iPhone through XCode you can use the ngrok endpoint that pops in terminal when you run the project in XCode or when you run 'npm start' to run the package server.

Here's some more info on using ngrok and installing adb for reverse tethering(if you are using android):
http://docs.viromedia.com/docs/troubleshooting#6-i-get-an-an-error-cant-connect-to-development-se

If the above doesn't work, let us know the phone you are using and we'll help you figure it out :)

**Comment by Zirconiumirish** [comment]
Hi it's fixed just have to update my Java version ^^
Thanks
