### ISSUE TITLE
Viro360Video source doesn't starts and the middle point view of video

### ISSUE THREAD

**Issue by intimateo** [viromedia/viro#251]
I have a 360 video that I want the start point of view of it be from the middle but it starts from the left, and also in the code example works idem

**Comment by dam00n** [comment]
Do you want to rotate the video? You can do that on the Y axis by adding something like this to Viro360Video component -> rotation={[0,90,0]}

Not sure what you mean by code example works idem?

**Comment by intimateo** [comment]
it works! thanks a lot
