### ISSUE TITLE
 Warning: Native component for "VRTVRSceneNavigator" does not exist

### ISSUE THREAD

**Issue by ankits47b** [viromedia/viro#252]
Warning: Native component for "VRTVRSceneNavigator" does not exist
Warning: Native component for "VRTScene" does not exist
Warning: Native component for "VRT360Image" does not exist
Warning: Native component for "VRTText" does not exist

**Comment by dam00n** [comment]
Hi @ankits47b can you provide more information on when you saw this error. Were you going the Getting Started? What step were you on? We need more information to provide assistance:

1. What device are you using?
2. What are you trying to do with Viro?
3. Did you run through the Getting Start instructions completely -> https://docs.viromedia.com/docs/quick-start

**Comment by VikAdvani** [comment]
Hi @ankits47b,
This is usually a result of not running the setup-ide.sh script when you create a new react-viro project. Are you running from Android studio or Xcode? Also, Viro does not work with any software simulator so make sure to run it on an actual device. 

If you created a new project run   ```./setup-ide.sh``` --all from the project root to properly setup your Android and XCode environments. 

If you are adding Viro to an existing project then follow one of the guides below:
Integrating with Existing RN App: https://docs.viromedia.com/v2.6.1/docs/integrating-with-react-native-projects

Integrating with Existing iOS App: https://docs.viromedia.com/docs/integrate-project-with-viro

Integrating with Existing Android App: https://docs.viromedia.com/docs/integrating-existing-projects-android

If you are still running into issues let us know!

**Comment by ankits47b** [comment]
Thanks @VikAdvani ,
