### ISSUE TITLE
use_framework flag in pod install makes viro incompatible with react-native-maps

### ISSUE THREAD

**Issue by mypark** [viromedia/viro#254]
I suppose this is more of an issue with react-native-maps https://github.com/react-community/react-native-maps/issues/2202 but I'm hoping that someone could help with a workaround.

I have a viro react project that I'd also like to use maps with, and react-native-maps throws a build error when the use_framworks flag is enabled on the podfile.

https://stackoverflow.com/questions/50032255/pod-install-error-react-rctview-h-file-not-found-with-react-native-maps-and-u

Disabling it creates a runtime error on Viro.  I thought I saw a discussion somewhere that says that the use_frameworks restriction could be removed from Viro at some point.  I also thought I saw something that said the latest beta of XCode will support swift libraries.

Is there any way to get these two libraries to work well together?

Using 

   "react": "16.3.1",
    "react-native": "0.55.1",
    "react-viro": "2.6.1"

**Comment by dam00n** [comment]
https://github.com/viromedia/viro/issues/274#issuecomment-389004933

Here is a possible work around to use frameworks you might want to try
