### ISSUE TITLE
video doesn't reproduce any sound

### ISSUE THREAD

**Issue by intimateo** [viromedia/viro#256]
I'm using Viro360Video component, it plays video very well but doesn't reproduce any sound even I added prop volume={1.0}
Note: i'm just testing on ios, I haven't test on android yet

**Comment by intimateo** [comment]
I think the problem is I’m using react-router-flux for navigation for my app and I just call Virovrnavigator in the video view, because when I test with the code thats come with the installation it worked the sound.
I mean i just use viro in one view of my app

**Comment by dam00n** [comment]
Ah, that is interesting. Not as familiar with react-router-flux, but please let us know if you think the core audio issue is with Viro and we can take a look

**Comment by intimateo** [comment]
May you think it is silly but the issue it was because the phone is in silent mode in iOS.

**Comment by dam00n** [comment]
No problem. I am going to close this issue. Let us know if you have any other issues.
