### ISSUE TITLE
[DOC] ViroQuad Example Code Error & UI AR

### ISSUE THREAD

**Issue by parideis** [viromedia/viro#258]
Hello,
in the example is a comma "," missing between the 0 and -5 in the position array. :)
https://docs.viromedia.com/docs/viroquad#section-example-use-

Is https://github.com/viromedia/ViroARSampleApp still the best way to implement an UI which overlays the AR Scene? Our UI only needs to change this.state properties.

**Comment by dam00n** [comment]
@parideis thanks, ViroQuad documentation has been updated.

Yes, ViroARSampleApp is the best starting point for implementing an UI that overlays an AR scene. Let us know if you are having any specific issues.

**Comment by parideis** [comment]
Thank you for letting us know. :)
