### ISSUE TITLE
Base app size for iOS and Android

### ISSUE THREAD

**Issue by briancalvium** [viromedia/viro#263]
We are looking into using this instead of Unity and I was surprise to find the base app size seems to be ~20MB on iOS. Does that match with what you would expect? This was using the sample hello world app with the texture require removed, archived and exported via Xcode. Very cool project by the way!!

**Comment by VikAdvani** [comment]
Hi @briancalvium, did you try and remove debug symbols from the app to see if that brings it down? 

React Viro is about 5 megs + our immediate dependencies(GVR, AWS) brings us to about 10mg. Perhaps the other 10 megs are from React Native itself or other RN native modules. You can try and remove some of the React dependencies or modules such as RCTAnimation to bring it down some more. 

We'll continue to work on bringing down total size on our end.
