### ISSUE TITLE
black screen with hello text only

### ISSUE THREAD

**Issue by spyshow** [viromedia/viro#265]
hi all 

im trying to install and run viro-react on windows machine and i followed the Quick Start (Windows) tutorial but when i lunch "npm start" it give me that 
` React Packager ready
Loading dependency graph, done.`

and on the viro media app i enter my local ip but it give me a black screen ( vr mode ) and hello text and an error ( image in the attachment) 
![screenshot_20180502-234414_viro media](https://user-images.githubusercontent.com/188788/39548726-c444dbc8-4e5b-11e8-8fc8-cf8483c38339.jpg)

my mobile is s8+ with Arcore installed 
i tried log to 127.0.0.1:8081 and it givr me 
`React Native packager is running.
Visit documentation`

so i think it's ok .

so what is the problem ?

**Comment by VikAdvani** [comment]
Hi @spyshow, can you try reaching http://192.186.0.168:8081/status from your device's mobile browser? You should see the same message 'React Native packager is running'. If you don't then your device is unable to reach your IP. You can use ngrok instead to create a tunnel on your machine or adb to connect to your machine via localhost. 

Here is more info on using adb with android to connect to your device: https://docs.viromedia.com/docs/troubleshooting#6-i-get-an-an-error-cant-connect-to-development-se

Let us know if the above suggestions don't work. Thanks!

**Comment by spyshow** [comment]
It give me packger is running but now i see hello text in vr mode but with
black screen without background like attachment

**Comment by spyshow** [comment]
It give me packger is running but now i see hello text in vr mode but with
black screen without background like attachment

![screenshot_20180503-101733_viro media](https://user-images.githubusercontent.com/188788/39565265-9d425ef4-4eb7-11e8-9723-af38cde08044.jpg)

**Comment by achuvm** [comment]
Hi @spyshow,

This is unfortunately a "feature" in React Native that we'll fix in our next release where React Native uses some cached files.

Try "reloading" the app by shaking the device and when the developer menu appears, tap on "reload".

If that menu doesn't appear, then you'll need to connect your device to your computer and run the following command `adb shell input text 'rr'`.

Thanks,

**Comment by spyshow** [comment]
the menu does appear but when I hit reload the same error in the past picture appears that the development server returned 404 error .... when i go to http://192.186.0.168:8081/status it gives me "packager is running"

**Comment by VikAdvani** [comment]
Hi @spyshow,
1) To confirm you tried going to  http://192.186.0.168:8081/status on your mobile browser, not your desktop?
2)In the testbed app, what version are you running? You can tell by tapping 'Enter Testbed' and it shows what 'react-viro' version the testbed app is compatible with.

3)Finally can you send me the package.json for your project? Perhaps you are using an incompatible version of Viro React or React Native.

**Comment by VikAdvani** [comment]
Hi @spyshow,
Do ensure it's not an IP issue did you try using adb and typing 'localhost:8081' into the testbed app?

**Comment by spyshow** [comment]
hi vik 

1- yes I tried it on my mobile 
2- React-Viro v2.6.0
3- 
[package.zip](https://github.com/viromedia/viro/files/1976315/package.zip)

**Comment by VikAdvani** [comment]
Hi @spyshow,
I think I see the problem. You are using an older version of React Native that is not compatible with React Viro 2.6.0.

To upgrade do the following. Modify the package.json to have the following react and react-native versions:
```
"react": "16.3.1",
"react-native": "0.55.1",
```
Then reinstall your node modules. In your project root do ```rm -rf nod_modules && npm install```.

Start your package server with ```npm start```. Now try running the testbed app and try connecting to your package server. 

For new projects make sure you install the latest version of the react-viro cli. You can do this by running ```npm install -g react-native-cli```. For future projects the new cli will create your project with the correct react and react native versions in the package.json.

Attached is a full file of how the package.json file should look like:
```
{
  "name": "Your Project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.1",
    "react-viro": "2.6.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "^4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Let me know if this helps or if you are still having trouble. Thanks :)

**Comment by spyshow** [comment]
thanks man it's good now and i can choose ar or vr mode  (which i couldn't before )
