### ISSUE TITLE
How to do surface detection in ViroReact?

### ISSUE THREAD

**Issue by linuissac** [viromedia/viro#267]

**Comment by dam00n** [comment]
Hi @linuissac, you can detect surfaces using 

- ViroARPlane -> https://docs.viromedia.com/docs/viroarplane
- ViroARPlaneSelector -> https://docs.viromedia.com/docs/viroarplaneselector

Here is a tutorial on our blog that show how to use these surface detection components -> https://blog.viromedia.com/how-to-build-an-interactive-ar-app-in-5-mins-w-react-native-viro-ar-e420147e1612
