### ISSUE TITLE
3D object loaded with out texture

### ISSUE THREAD

**Issue by spyshow** [viromedia/viro#268]
Hi all

i downloaded more than 3 3d objects from different sites and try to use them inside my app but they always appares without texture ( some of them include .obj and .mtl and some include .obj, .mtl and .jpg) i always put all files in same folder and requier them inside my code like the examples 
```javascript
<Viro3DObject
 source={require('./res/salt/Salt.obj')}
   resources={[
   require('./res/salt/Salt.mtl'),
   require('./res/salt/folds3.jpg'),
   require('./res/salt/paper2.jpg'),
   require('./res/salt/peper.jpg'),
   require('./res/salt/salt.jpg'),
   require('./res/salt/Wood_oak4.jpg')
 ]}
 position={[0, 0, 0]}
 scale={[0.002, 0.002, 0.002]}
 type="OBJ"
/>
```
i tried also seeing them via autodesk FBX review but same problem ...

**Comment by dam00n** [comment]
Hi @spyshow, if the textures are not visible using FBX Review than they probably won't be visible in Viro. It is likely that the material are not assigned correctly on these models.

Check out this blog post by our 3D artist on how to best create/export 3D models -> https://blog.viromedia.com/https-blog-viromedia-com-asset-pipeline-optimizing-3d-models-ar-vr-arkit-arcore-d0fb61627aaf

Also, here are some free 3D assets you can try that we offer -> https://docs.viromedia.com/docs/assets#3d-objects

Lastly, if you want to email (support@viromedia.com) the models, we can take a look at them just to double check on what the issue might be.

**Comment by saboteur111** [comment]
Hi @spyshow,
So I took a look at the salt model and here are the issues I discovered:
-Overall, this model is not originally created for real-time use. It's what I consider a basic model made for pre-rendering where the buyer needs to be knowledgable how to still do extra work to make it work. I noticed there was a final render image included where one would expect it to look like, but this will require manual tweaking of the models (turbosmooth) and creating new PBR textures for it.
-There are no textures assigned to the objects except for the napkin and salt inside the bottles. This goes to my previous point where you will need to UV and apply them manually and re-export the models.
-Please follow my guide above to help what kind of models to purchase. Most importantly, make sure they're ready for real-time use.
