### ISSUE TITLE
How to only show Content of one ViroARImageMarker

### ISSUE THREAD

**Issue by parideis** [viromedia/viro#270]
Hello,

I have multiple ViroARImageMarker with different targets. As soon as one Marker gets detected, the 3D objects of the previous detected ImageMarker should not be shown.
Is there a way to get the the **target** name in **_onAnchorFound** , or something similar?

**Comment by achuvm** [comment]
Hi @parideis,

`onAnchorFound` does return an `Anchor` object: https://docs.viromedia.com/v2.6.1/docs/viroarscene#anchor

You should be able to use `anchorId` to differentiate between different `Anchors`. On the other hand, each `ViroARImageMarker` itself has an `onAnchorFound` function too that you can use to disable all the other ones.

**Comment by achuvm** [comment]
@parideis,

It depends what you want to do, you can conditionally render your nodes, or remove the `ViroARImageTracker` completely.

ie.
```
<ViroARScene>
  <ViroARImageMarker>
    {this._getObject}
  </ViroARImageMarker>
<ViroARScene>

_getObject() {
  if (this.state.isActive) {
    return (<Viro3DObject />)
  }
}
```

**Comment by achuvm** [comment]
Hi @parideis,

The `onAnchorFound|Updated|Removed` for a particular `ViroARImageMarker` should only get called for that particular component. Therefore by keeping track of which one has its `onAnchorFound` callbacks, you know which one has been "found".

**Comment by parideis** [comment]
@achuvm thank you very much for the fast reply! :)
I'll try it out.
