### ISSUE TITLE
iOS debug js remotely crashes after viro integrated into project

### ISSUE THREAD

**Issue by khuzammark** [viromedia/viro#271]
Before integrating Viro into our iOS application, debugging remotely works fine, after integrating, debug js remotely crashes app with error:

Connection to http://localhost:8081/debugger-proxy?role=client timed out. Are you running node proxy? If you are running on the device, check if you have the right IP address in 'RCTWebSocketExecutor.m'

Xcode gives nw_connection_get_connected_socket  Connection has no connected handler

**Comment by VikAdvani** [comment]
Hi @khuzammark, I've tested this on our end and it seems to work with IP (without using ngrok). Are you sure your device can connect to your IP? The debug message should be printing out the IP not 'localhost'. The fact that it's printing out localhost means it can't find the bundle host via IP. What version of Viro React and React Native are you using?

**Comment by khuzammark** [comment]
@VikAdvani thanks for the reply, im using react-viro: 2.6.1 & react-native: 0.55.1

**Comment by VikAdvani** [comment]
Hi @khuzammark, I'm unable to repro this. Are you able to to connect to the package server with the debugger turned off?

**Comment by khuzammark** [comment]
Thanks for the help, figured it out. Router issue not an app issue.
