### ISSUE TITLE
Permission for Microphone requested on Android

### ISSUE THREAD

**Issue by grahamyesfit** [viromedia/viro#279]
```
react: 16.3.2
react-native: 0.55.4
react-viro: 2.6.1
Device: LGLS990 (Android)
```

After I added Viro VR to my 2D React app, a user complained that the App was asking permission to use the microphone. This is despite me having added these to the manifest:

```
<uses-feature android:glEsVersion="0x00030000" android:required="false" tools:node="remove" tools:replace="required" />
<uses-feature android:name="android.hardware.sensor.accelerometer" android:required="false" tools:replace="required" />
<uses-feature android:name="android.hardware.sensor.gyroscope" android:required="false" tools:replace="required" />
<uses-feature android:name="android.hardware.camera" android:required="false" tools:replace="required" />
<uses-feature android:name="android.hardware.microphone" android:required="false" tools:replace="required" />
```

When I look at our store entry on Google Play, these required permissions were added:

```
android.permission.NFC,
android.permission.RECORD_AUDIO,
```

These are the specs of the user's phone who reported the issue:

```
Android Device: LGLS990
Android OS version: 5.0.1
```

I don't know if the issue is limited to this particular device or if any other users experienced it, this is the only user that I know of who reported it.

Is there something I can do to remove the permission requirement for the microphone? Note, I'm not using AR.

**Comment by achuvm** [comment]
Hi @grahamyesfit,

You can remove permissions by adding this to your manifest:

```
<manifest ... xmlns:tools="http://schemas.android.com/tools">
    ...
    <uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/>
    ...
</manifest>
```

I grabbed it from this link:
https://stackoverflow.com/questions/31616334/how-to-remove-specific-permission-when-build-android-app-with-gradle

The permissions come from our library as the recording video API's do take advantage of the feature, however, as long as you don't plan on/need to use that API, you can disable the permissions.

The NFC permission comes from the GVR (Google VR) library for Daydream support, as long as you aren't using VR, feel free to remove those permissions too.

Let us know if you have any other questions!

Thanks,

**Comment by grahamyesfit** [comment]
Hi @achuvm, you're a star, thank you. I'll be supporting VR eventually (when I get the iOS side of things figured out :) ), so for now, I'll exclude NFC also.

**Comment by grahamyesfit** [comment]
Hi @achuvm, I noticed this in my build output:

`uses-feature#android.hardware.microphone@tools:required was tagged at AndroidManifest.xml:22 to replace other declarations but no other declaration present`

Is this because the corresponding `uses-feature` is in Viro, not my manifest? Does this warning mean this statement will be ignored, and the microphone feature will still be requested?

**Comment by achuvm** [comment]
Hi @grahamyesfit,

I'm not aware of a message like that popping up, but might it be related to the lines you added above:

```
<uses-feature android:name="android.hardware.microphone" android:required="false" tools:replace="required" />
```

I looked at our manifests, it doesn't look like we have a `uses-feature` for the `android.hardware.microphone` so that's probably why it's complaining that you're attempting to override a line that doesn't exist.

Thanks,

**Comment by grahamyesfit** [comment]
Thanks @achuvm, that makes sense. I'll remove the ones that are giving out a warning. I think just having these in will achieve what I want:

```
<uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/>
<uses-permission android:name="android.permission.NFC" tools:node="remove"/>
```
