### ISSUE TITLE
Minimum scale value of Viro Image

### ISSUE THREAD

**Issue by niallfarrell91** [viromedia/viro#281]
Can you sent a min scale for what an object i.e ViroImage will set to before it displays.
For my AR scene I have a number of POIs, some are far away and I only want them to shrink to only a  certain level so that they remain clickable.
Is this possible and what would I set?

**Comment by manbod** [comment]
Hi @niallfarrell91 ,
Thanks for reaching out. We don't have a minimum value for scale on objects. For your use case, you would need to set a minimum scale value in your application logic depending on the size of your ViroImage, and the location - how far away they are from the user. It is definitely possible, but you would need to play with / try a few values for `scale` and `position` to come up with values that work for your application.

Thanks,
-
Manish
