### ISSUE TITLE
ViroReact : Multiple Image Marker Recognition not working

### ISSUE THREAD

**Issue by linuissac** [viromedia/viro#284]
Hello i'm trying to do multiple image marker recognition in ViroReact . The position of  augmented card(Image) is not proper. What i'm expecting is after detecting each marker , the card should be in exact position of the marker. The position of 1st augmented card is proper with respect to the marker , on detecting the next marker the 2nd  card will be in the same position of 1st one.

`<ViroARScene>

        <ViroAmbientLight color="#ffffff" intensity={200}/> 
       
		<ViroARImageMarker target={"poster"} onAnchorFound={this._onAnchorFound} pauseUpdates={this.state.pauseUpdates}>

		 <ViroNode position={[0,0,0]} scale={[0,0,0]} rotation={[270,0,0]} dragType="FixedToWorld" onDrag={()=>{}}  animation={{name:"scaleModel", run:this.state.playAnim,}}>

              <ViroImage
               height={0.5}
                width={0.5}
                source={require('./res/black.jpg')} />

		</ViroNode>

		</ViroARImageMarker>

		<ViroARImageMarker target={"poster2"} onAnchorFound={this._onAnchorFound} 
                pauseUpdates={this.state.pauseUpdates}>

		<ViroNode position={[0,0,0]} scale={[0,0,0]} rotation={[270,0,0]}dragType="FixedToWorld" 
              onDrag={() =>{}}
               animation={{name:"scaleModel", run:this.state.playAnim}}>

             <ViroImage 

              height={0.5}

             width={0.5}

          source={require('./res/PEACO.jpg')}/>

           </ViroNode>

		</ViroARImageMarker>
          ........
          ...
          ViroAnimations.registerAnimations({

    scaleModel:{properties:{scaleX:0.5,scaleY:0.5, scaleZ: 0.5},

                  duration: 1000,
				  },
               });`

This is what i'm getting.
![img_3106](https://user-images.githubusercontent.com/29809987/40053096-a0875b64-585d-11e8-8fc4-e97f51de938d.PNG)
Any help would be really appreciable.Thank you

**Comment by parideis** [comment]
How does your `ViroARTrackingTargets` look like?
Try changing the [orientation](https://docs.viromedia.com/docs/viroartrackingtargets#section-properties) of your target.

**Comment by linuissac** [comment]
No i just solved it by removing animation for the second node. Now it is working perfect. But i don't think its a permanent solution. What do i do if i need animation for all component?I tried by changing the orientation , but no use. I would like to know more about animations.Is there any docs available , other than the one mentioned in viro's official site?

**Comment by dam00n** [comment]
These are the animation docs we have

Developer Guide -> https://docs.viromedia.com/docs/animation

API Ref -> https://docs.viromedia.com/docs/viroanimations

Each component that is animatable will have an animate prop listed in the respective API ref under optional props.
