### ISSUE TITLE
stopping camera in Ipad

### ISSUE THREAD

**Issue by hhong0326** [viromedia/viro#285]
takes time a little bit, soon camera scene is stoped...

and if pull down status bar, again playing scene, but will be soon stop again.

only stoped in Ipad..

It's do not stop in Iphone

**Comment by manbod** [comment]
Hi @hhong0326 ,
We'd be happy to help. We'll need more information from you for us to be able to look at your issues.
1. What iPad are you using?
2. What OS is installed on the iPad?
3. Are you testing a standalone app or through our testbed ViroMedia app?
4. Are you testing a debug version of your app or release?
5. What do you mean by camera mean stopped? Does the screen go blank? Does the app crash?
6. Have you looked at device logs? The logs don't say anything wrong with your app when it stops? If not, can you try the debug version of the app to see the logs? If you cannot find what's wrong with the logs, share them with us so we can take a look.
7. Lastly, share relevant code snippets so we can take a look / reproduce the bug on our end.
8. Share app screenshots of what you mean by stopping.
