### ISSUE TITLE
Mp3 not being loaded - ViroSound and SpatialSound not working

### ISSUE THREAD

**Issue by Djinne** [viromedia/viro#287]
Hi guys,

When I use ViroSound on the ios test bed it plays for a split second before cutting out.
ViroSpatialSound doesn't play at all.
rn-cli.config.js has:  return ["wav","mp3","mp4", "JPG", "vrx", "hdr"];

```
IOS BUILDING TO RELEASE ERROR: 
File does not exist: /private/var/mobile/Containers/Data/Application/B1B778FD-F7F1-4C73-B54E-3FCA76A1659F/tmp/cheer.mp3
```

I have also tried 
`import resolveAssetSource from "resolveAssetSource";
ViroSound.preloadSounds({
  "cheer" : resolveAssetSource(require("./js/res/cheer.mp3"))
});`
then 
`<ViroSound paused={false} muted={false} source={"cheer"} loop={true} volume={1.0}/>`
Kind regards
Djinne

**Comment by Djinne** [comment]
Hey,

It seems to work fine with an URI, was worried the request wouldn't cache but it seems to work fine and caches.

Kind regards
Djinne

**Comment by dthian** [comment]
Thanks @Djinne,great to hear that you are unblocked. 

So to confirm, the uri approach of loading a ViroSound works, but when using the "require" syntax it does not? 

Also, can you confirm the device type name and it's OS model that you are using?

Much thanks!
