### ISSUE TITLE
Detect when Viro3DObject is off screen when using ViroARImageMarker

### ISSUE THREAD

**Issue by richardvclam** [viromedia/viro#289]
Can anyone provide any insight on how to detect when a spawned `Viro3DObject` has moved off-screen? I've tried attaching an `onAnchorRemoved` method to `ViroARImagemarker`, but the method never gets called. I've spent a couple of hours going through the documentation, but there doesn't appear to be any examples or mentions of such.

Any help would be greatly appreciated!

**Comment by VikAdvani** [comment]
HI @richardvclam, currently there is no way to detect this. Can you describe your use case more so we can help you mitigate?

**Comment by richardvclam** [comment]
Thanks, @VikAdvani, for replying.

We have two use cases.
1) If the user looks away from the 3D object for a period of time, we would like the object to disappear.
2) We would like to display a video on the image marker. If the user looks away, the video would either stop playing or disappear. Additionally, we would also like the reverse. If the user had looked away and back at the stopped video, the video would start playing again. 

Hope that helps!

**Comment by VikAdvani** [comment]
Hi @richardvclam,
1) You can likely use the onHover event which will give a similar result. It'll trigger when the user moves on and off the object. When it moves off you can set a timer, and then on timer end, fade out the object. 

2) For this you can also use onHover on the video itself. When the user hovers on the video start playing and when the hovers off stop playing the video. 

In AR, the onHover event triggers based on what object intersects at the center of the screen. 

Hopefully, this helps you achieve your use case. Let me know if this helps or you need me to explain more. Thanks!

**Comment by richardvclam** [comment]
This should be more than enough to get us where we need. Thanks, @VikAdvani!
