### ISSUE TITLE
Does Viro360Video support 'embedded' mode?

### ISSUE THREAD

**Issue by ttDemon** [viromedia/viro#295]
Hi guy,

I want to watch video360 with "embedded" mode , how do I do it?

**Comment by ttDemon** [comment]
I wanted the new video to be nonVrMode (mono) and stored in a 6: 9 size view, with a fullscreen button, a cardboard like googleVR. If I press the fullscreen button, it will be in fullscreen mode, press the cardboard button in cardboard mode. 
I tried creating a toggle button on cardboard mode based on props vrModeEnabled. It switches from 'mono' to 'Vr mode' ok, but when pressed again to switch from 'Vr mode' to 'mono', I do not see the video displayed, only a black screen.

I tried run app on Android, react-native:'0.54.3', react-viro:'2.6.1'

**Comment by minh198** [comment]
@ttDemon @dam00n  I'm also problems like this ==>  switches vrModeEnabled state from 'false' to 'true' ok, but when pressed again to switch vrModeEnabled state from 'true' to 'false', I do not see the video displayed, only a black screen.

**Comment by manbod** [comment]
@ttDemon The video that you have stored in a 6:9 size view is a normal 2D video correct? In that case you need to use our [<ViroVideo>](https://docs.viromedia.com/docs/virovideo-2-compare) component when you want to render that 6:9 video, and then switchover to using `<Viro360Video>` when the user presses a "VR" button. We do this in our Test Bed app [App Store link](https://itunes.apple.com/us/app/viro-media/id1163100576?mt=8) **/** [Play Store link](https://play.google.com/store/apps/details?id=com.viromedia.viromedia&hl=en_US). Checkout the *Viro Media Player* experience in the app.

Thanks
