### ISSUE TITLE
ViroReact : Animation

### ISSUE THREAD

**Issue by linuissac** [viromedia/viro#296]
Hello,
 I've tried this sample app [https://blog.viromedia.com/add-snapchat-ar-lenses-to-any-app-w-react-native-viro-ar-9d4053769782](url). Now i'm trying to do some custom animations in this model. I've given walking animation to this model via 'mixamo'. What I'm expecting is can I give custom animations along with the default animation?
1). If there is a predefined map or location can i move /walk this model to specified directions?
2).Suppose I want to move the model straight about 10 m and after that it should turn right and turn back and return to starting position . 
Is this kind of action possible?How to specify this in my code? How do i call the custom  animations other than the default animation in a vrx/fbx file?

**Comment by dam00n** [comment]
Hi @linuissac, what you are describing might be possible depending on your animations. Animations embedded into models (like walking or dancing) can not be customized through the Viro animation component.

**Comment by dthian** [comment]
Hey @linuissac, you should be able to achieve the requested animation above with Viro. Really, there is two main kinds of animation you would want to play:
1) The Skeletal animation of your fbx model - in this case a "walking" animation. On best practices of importing 3D animations, take a look at [this](https://blog.viromedia.com/https-blog-viromedia-com-asset-pipeline-animating-3d-characters-for-ar-vr-arkit-arcore-c7aff566bcf8).
2) The translation of the model itself (moving the model 10m, turning, etc). 

For (1), you can refer to [this](https://docs.viromedia.com/v2.6.1/docs/3d-objects#section-skeletal-animation) on how to play the walking skeletal animation for your character, it should be pretty straight forward. 

For (2), you can then simply place your 3D model in a ViroNode and animate the location of that parent node. Please refer to our [animation guide](https://docs.viromedia.com/docs/animation) where we demonstrate how to register, play, loop and chain animations. This should help you achieve the above effect of chaining "moving forward straight about 10m" and turning right after, etc.

Hope that helps! Let us know if you experience any problems with the above.

**Comment by linuissac** [comment]
Thanks for your reply ! I am left with one more query though. In a ViroNode, the properties I have is scale, rotate, position; where position property contains XYZ. Is that the same thing as the "location of that parent node"? If so, I already tried animating it the following way, and it felt like I had no control over where the character would appear.

 '       <ViroNode position={[1,1,1]} scale={[1,1,1]} dragType="FixedToWorld" onDrag={()=>{}}> 
          <Viro3DObject /> </ViroNode>'

 Say, If I have a corridor that goes straight for 10 meters and then it goes right for another 10 meters; If I want to walk a  character along this path, where should I begin? Apparently, animating the XYZ position results in an animation that I can't see to have control over as to where it would begin.

**Comment by dthian** [comment]
Hey @linuissac, yup you are correct in assuming the viroNode is the parent node which encapsulates your 3D model.

Firstly, i would remove the dragType and onDrag properties from the parent node as we are already moving this node through animation. If we allow yet additional movement overrides with onDrag in addition to the animation movement, you may get undesired and conflicting results. **If you do need to drag the object around**, I strongly recommend to keep **drag** and **animation play back** as separate distinct, mutually exclusive states (user drags object, lets go, and then drag is disabled and animation is enabled).

With regards to the issue above, could you share your animation code (I only see the ViroNode component code above). There should be two parts: 1) The animation property in your ViroNode above and 2) The Animation itself that you have registered with ViroAnimations.registerAnimations. This will help us better diagnose your issue and why it may not be working.

Lastly if you are planning to animate an object's position, there should be two ways to do it: 
1) Additive position placement - Always animates an object +N(vec3) distance from a given start location. Animations **occur relative to a node's starting place.** 
2) Absolute position placement - Always animates an object from the node's current location to an **fixed end location.** 

Option (1) is useful if whenever you'd like to start animations relative to that location (for example dragging an object to a new location and then animating it). As seen below, that's annotated with the "+=", it can also be "-=" respectively. 
```
ViroAnimations.registerAnimations({
  moveRight:{properties:{positionX:"+=0.3"}, duration: 10000}
});
```

Option (2) is useful whenever you'd like to have a fixed animation to always end at a known location in the world:
```
ViroAnimations.registerAnimations({
  moveRight:{properties:{positionX:1, positionY:0, positionZ:1}, duration: 10000}
});
```

**Comment by linuissac** [comment]
Okay so what I understood is I should give animation to the parent node and the default 
animation(within model) should be called within the  'Viro3Dobject' . I will paste some portion of my code below.

`    <ViroARScene>
      <ViroAmbientLight color="#ffffff" intensity={200}/>

      <ViroNode position={[0, -1, -2]}  >
      <ViroSpotLight
          innerAngle={5}
          outerAngle={25}
          direction={[0,-1,0]}
          position={[0, 5, 0]}
          color="#ffffff"
          castsShadow={true}
          shadowMapSize={2048}
          shadowNearZ={2}
          shadowFarZ={7}
          shadowOpacity={.7}
         />
         <ViroNode animation="straightWalk">
        <Viro3DObject
        source={require('./res/ice_cream/walking.vrx')}
        resources={[require('./res/ice_cream/icecreamman_diffuse.png'),
        require('./res/ice_cream/icecreamman_normal.png'),
         require('./res/ice_cream/icecreamman_specular.png')]}
         position={[0,0,0]}
         scale={[.5, .5, .5]}
         type="VRX"
         onClick={this._onTappedModel}
          animation={{name: "01", 
		run:this.state.runAnimation,
		loop:true,
		}}
               />
              </ViroNode>
         <ViroSurface
        rotation={[-90, 0, 0]}
        position={[0, -.001, 0]}
        width={2.5} height={2.5}
        arShadowReceiver={true}
      />
      </ViroNode>

      </ViroARScene>
       );
         }
...
..
     ViroAnimations.registerAnimations({
     moveStraight:{properties:{positionZ:"+=0.3"}, duration:1000},
         walkStraight:{properties:{translateZ: "+=0.3"}, duration: 1000},
      straightWalk:[
      ["moveStraight"],
      ["walkStraight"]
           ]
            });
`
Am I doing correct? Or else am I able to write `animation` property for node?If not , then where do I call the animation that i've done within `ViroAnimations.registerAnimations`?

**Comment by dthian** [comment]
Hey @linuissac, that looks roughly correct. Calling an animation property on the node should be the same as calling an animation on a 3D model. Here is an example:

```
<ViroNode
                  position={[0, -1, -2]}    
                  scale={[.1, .1, .1]}
                  animation={{name:'loopRotate',
                             run:true,
                             loop:true}} />
```
Let us know if the above doesn't work for you. Thanks!

**Comment by VikAdvani** [comment]
Closed due to inactivity. Reopen if needed.
