### ISSUE TITLE
Highlight recognized image

### ISSUE THREAD

**Issue by Tamiyadd** [viromedia/viro#297]
Hi, i wan't to highlight a recognized image through `ViroARImageMarker` and `onAnchorFound` by putting a rectangle hover the image, but `ViroArPlane` does not position itself correctly hover my image. 
How can i achieve that? 
I want the rectangle to be same size of my image. It's possible?

in swift you can achieve that with this simple lines of code

```
   let plane = SCNPlane(width: referenceImage.physicalSize.width,
                         height: referenceImage.physicalSize.height)
    let planeNode = SCNNode(geometry: plane)
    planeNode.opacity = 0.25
   
    planeNode.eulerAngles.x = -.pi / 2
   
    planeNode.runAction(self.imageHighlightAction)
```

thanks

**Comment by manbod** [comment]
Hi @Tamiyadd ,
Thanks for reaching out. Can you explain more what you mean by `but ViroArPlane does not position itself correctly hover my image`? Can you share your code snippet where you are trying this? Did you try getting the `width`, `height` & `position`, `rotation` of the Anchor given in `onAnchorFound`? Pasting our `anchor` object's docs for reference here https://docs.viromedia.com/v2.7.0/docs/viroarscene#anchor

**Comment by manbod** [comment]
Hi @Tamiyadd ,
Thanks for pointing that out. We should probably make it clear in our documentation. You are right in that `anchor` object returns `width` and `size` for `ViroARPlane` objects. In the case of `ViroARImageMarker`, `onAnchorFound` should give you the parameters for the detected image "plane" in the scene. Let us know if this works for your use case.

Thanks!

**Comment by Tamiyadd** [comment]
Unfortunately the info returned by the `anchor` object are not sufficient to place a `ViroQuad` hover the image :( or maybe I'm not able to do it

```
 {_.map(this.objectsArray, function(el) {
          const marker = el.marker;
          return (
            <ViroARImageMarker
              target={marker}
              key={marker}
              pauseUpdates={_this.state.animateQuad === marker}
            >
              <ViroQuad
                onHover={(isHovering, position, source) =>
                  _this.onHover(isHovering, position, source, el.variable, marker)
                }
                materials={['whiteColor']}
                position={[0, 0, 0]}
                width={el.width}
                height={el.height}
                opacity={0.09}
                rotation={[-90, 0, 0]}
                animation={{
                  name: 'animateQuad',
                  loop: false,
                  run: _this.state.animateQuad === marker,
                  onFinish: () => _this.finishAnimation(marker),
                }}
              />
            </ViroARImageMarker>
          );
        }
```

now i'm doing in this way but it's not reliable

**Comment by manbod** [comment]
Hi @Tamiyadd ,
Can you try using <ViroImage> instead of <ViroQuad> to "highlight" the recognized image? That would be more reliable. Your code would looks something like below

```javascript
<ViroARImageMarker
              target={marker}
              key={marker}
              pauseUpdates={_this.state.animateQuad === marker}
              onAnchorFound={this._onAnchorFound}
            >
              <ViroImage 
                       height={this.state.height}
                       width={this.state.width}
                       position={this.state.position}
                       rotation={this.state.rotation}
                       source={{your image uri here}}
                        ...whatever else you might need here 
                         .../>

            </ViroARImageMarker>

_onAnchorFound(anchor) {
    this.setState({
      width: anchor.width,
      height: anchor.height,
      position: anchor.position
    });
}
```

As you see above, you'll rely on the width, height, position, rotation of the `anchor` passed in `onAnchorFound(anchor)` to set the correct height, widht, position of the image.

**Comment by Tamiyadd** [comment]
there something strange, how can this work if the `onAnchorFound` anchor in `ViroARImageMarker` does not return width and height? :(

**Comment by manbod** [comment]
Hi @Tamiyadd,
Sorry for the delay in responding(the team was away for a couple of conferences last week). I confirmed in our own implementation on `ViroARImageMarker`.  Currently the way that the ViroARImageMarker works is that the developer knows the physical width/height of the marker and provides it as a parameter into the component itself (https://docs.viromedia.com/docs/ViroARImageMarker). As such, it is assumed that the developer knows the physical width/height (in meters) of their marker in the real world and the platforms (ARKit/ARCore) simply return the position (center) of the marker.

Apologies for the incorrect guidance earlier. You can get around the `onAnchorFound` not returning `width/height` by using the measured width  / height parameters in meters along with the position of the center returned in the callback.

Hope this helps. Let us know if this still doesnt work for you.

**Comment by Tamiyadd** [comment]
solved using physical size to set width/height
