### ISSUE TITLE
Is there any maximum size for the 360pictures ?

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#3]
Hi when i'm trying to upload a 360 pictures it show me an error in the terminal.
It seems that it check the width and height in the index.js located here : ViroSample/node_modules/image-size/lib/index.js

Is there any modification to do on that file ?

Thanks for your help

**Comment by manbod** [comment]
Hi, thanks for filing this issue. You should not need to modify anything in node_modules/image-size/lib/index.js. We do not have a maximum size limit for 360 images. Can you please provide us with what error you are seeing in the terminal?

**Comment by Zirconiumirish** [comment]
Thanks for the answer :)

it happend on some files, maybe because there are note perfect 1:2 ratio no ?

Here is terminal screen 
![screen](https://cloud.githubusercontent.com/assets/26435962/24361123/6d574aa0-1309-11e7-83de-6042505f8510.jpeg)

Thanks for your help

**Comment by manbod** [comment]
What format / extension images are you trying ? We do not impose a strict 1:2 ratio for 360 images. We support asset types mentioned here http://docs.viromedia.com/docs/importing-assets#supported-assets. Keep in mind the extensions are case sensitive. For example, 'JPG' is not supported as an extension by default, while 'jpg' is

Can you share one of the images that's causing the error? We'd like to test it on our end to root cause the issue.

**Comment by Zirconiumirish** [comment]
I'm trying basic .jpg extension
![test](https://cloud.githubusercontent.com/assets/26435962/24362242/7d5a9670-130c-11e7-842e-7eefffb977c6.jpg)

Thanks for your help.

Cheers

**Comment by manbod** [comment]
Hi, seems like the image type determined by it's JFIF marker is unsupported by [image-size](https://github.com/image-size/image-size) lib which is a module used by react native. Pasting the supported types from their module (types/jpg.js):
```
// NOTE: we only support baseline and progressive JPGs here
// due to the structure of the loader class, we only get a buffer
// with a maximum size of 4096 bytes. so if the SOF marker is outside
// if this range we can't detect the file size correctly.

// TO-DO: handle all JFIFs
var validJFIFMarkers = {
  'ffdb': '0001010101', // Samsung D807 JPEG
  'ffe0': '4a46494600', // Standard JPEG
  'ffe1': '4578696600', // Camera JPEG, with EXIF data
  'ffe2': '4943435f50', // Canon EOS-1D JPEG
  'ffe3': '',           // Samsung D500 JPEG
  'ffe8': '5350494646', // SPIFF JPEG
  'ffec': '4475636b79', // Photoshop JPEG
  'ffed': '50686f746f', // Adobe JPEG, Photoshop CMYK buffer
  'ffee': '41646f6265'  // Adobe JPEG, Unrecognised (Lightroom??)
};
```

**Comment by manbod** [comment]
Hi! We tried re-saving the image as jpg (Using Preview on Mac) and resizing the image to 8000 x 2825. The 360 image works after resizing. There seems to be an upper limit for the image sizes in the image-size library used by react. We'll update our documentation accordingly.

![github3](https://cloud.githubusercontent.com/assets/24463620/24368380/d282b8a2-12e5-11e7-9787-c1d1c389f04a.jpg)

Thanks!

**Comment by Zirconiumirish** [comment]
Hi Thanks for investigate

I really appreciated.

Have a Great day

Michael
