### ISSUE TITLE
ViroARSceneNavigator/ViroVRSceneNavigator from SideMenu based app

### ISSUE THREAD

**Issue by saad-ansari** [viromedia/viro#301]
Hi,

Currently i'm working on an application which has side menu and there are list of mix of different types of scene like ARScenes , VRScenes and normal scenes like List, contact us, about us.

This is how i have created app structure.

Any sample would be great.

```
 const Drawer = DrawerNavigator(
  {
    Home: { screen: Home },
    SignUpScreen : {screen: SignUpScreen},
    HelloWorldScene : {screen: HelloWorldScene},
    HelloWorldSceneAR : {screen: HelloWorldSceneAR}
  },
  {
    initialRouteName: "Home",
    contentOptions: {
      activeTintColor: "#e91e63"
    },
    contentComponent: props => <SideBar {...props} />
  }
 );

  const AppNavigator = StackNavigator(
  {
    Drawer: { screen: Drawer },
    SignUpScreen : {screen: SignUpScreen},
    HelloWorldScene : {screen: HelloWorldScene},
    HelloWorldSceneAR : {screen: HelloWorldSceneAR},
  },
  {
    initialRouteName: "Drawer",
    headerMode: "none"
  }
  );

  export default () =>
  <Root>
    <AppNavigator />
  </Root>;
```

Thank you!

**Comment by manbod** [comment]
Hi @saad-ansari ,
Can you specify what problem are you facing? We have samples for both AR and VR scenes here https://github.com/viromedia/viro/tree/master/js. We don't have samples for how to structure your app for Drawer. For that we would recommend searching on react-native forums.

Thanks,

**Comment by saad-ansari** [comment]
Hi @manbod 

Thanks for the response. The only problem i'm facing is how to push from normal scene means not a  ViroScene to the AR/VR ViroScene. Like...

this.props.navigation.navigate(NormalScene) to ViroARSceneNavigator(ARScene)

Thanks,

**Comment by dam00n** [comment]
Hi @saad-ansari, here is a link to a sample app with Normal Scene and Viro Scene. -> https://github.com/viromedia/ViroARSampleApp

Let us know if that helps or if you are still having issues.
