### ISSUE TITLE
onClick, onTouch, ... Events in Viro3DSceneNavigater

### ISSUE THREAD

**Issue by dominicrico** [viromedia/viro#306]
Would be aweseome if you could give us touch and click events in a non-VR/AR Scene. 

PanResponder is super inaccurate in a 360Image.

Thanks for your help

**Comment by manbod** [comment]
Hi @dominicrico ,
Are you seeing that the touch / click events don't work at all for you in `Viro3DSceneNavigator` ? On object / nodes? Or on the background scene? You should be getting callbacks for onClick, onClickState, onDrag, etc. https://docs.viromedia.com/docs/viroscene . What do you mean by PanResponder? We are working on getting out the ability to pan a scene / camera in an upcoming release. 

Thank you.

**Comment by dominicrico** [comment]
Sorry, ignore this. I found my mistake... This works as expected. Thanks for your help.

**Comment by Peege151** [comment]
...what was your mistake?

**Comment by dominicrico** [comment]
@Peege151 sorry I don't know it anymore... It's almost 2 years since the post and the library may changed.

**Comment by Peege151** [comment]
No worries! I ended up using onClickState which worked.  I think I may have had an absolute see through container blocking events.
