### ISSUE TITLE
getBoundingBoxAsync returning 0 for all values

### ISSUE THREAD

**Issue by bryantAXS** [viromedia/viro#307]
I'm loading a fairly complex `.glb` [file](https://sketchfab.com/models/ec516ba32f03403f97954472c5d4b2cf) and calling `getBoundingBoxAsync` after it loads. About a quarter of the time, all of the boundingBox values are returning 0.

![ss 2018-05-30 at 7 00 40 am](https://user-images.githubusercontent.com/367604/40719112-fc026d28-63d7-11e8-948f-a1090454ee32.png)

Here's a snippet where the issue is happening. You'll notice I'm calling getBoundingBoxAsync within the callback for the objects onLoadEnd method.

```
/**
   * When our object has loaded
   */
  _onLoadEnd() {
     console.log("OBJ loading has finished");

     var self = this;

     this.refs.objectNode.getBoundingBoxAsync().done(function(obj){

       var boundingBox = obj.boundingBox;

       var difference = function(a, b){
         return Math.abs(a - b);
       };

       console.log("bounding box difference");
       console.log(obj);

       var xLength = difference(boundingBox.minX, boundingBox.maxX);
       var zLength = difference(boundingBox.minZ, boundingBox.maxZ);
       var scale = self._getScale(xLength, zLength, self.state.planeWidth, self.state.planeHeight)

       console.log("setting scale", scale);

       self.setState({
         objectX: xLength,
         objectZ: zLength,
         scale: scale
       });

     });

  }
```

**Comment by dam00n** [comment]
Hi @bryantAXS, is this occurring with the same model you emailed us a couple days ago (residential building)? If this is occurring with a different model, can you email us that one (with the bounding box issue) so we can take a look

**Comment by bryantAXS** [comment]
@dam00n yeah this is probably a similar and related problem. In this case it was a different model, but I think it's the same issue. Closing!
