### ISSUE TITLE
clone of googles just a line using viro react

### ISSUE THREAD

**Issue by mayankgenie** [viromedia/viro#313]
Is there a way to create a clone of googles just a line app with viro react

**Comment by VikAdvani** [comment]
Hi @mayankgenie, you can develop an app somewhat similar in Viro React using the ViroPolyline component in combination with ViroARScene's onCameraARHitTest callback. Basically, as the camera moves around, you can use the current hit test point to place add a point to the polyline(effectively drawing the line in AR space).

Let me know if this helps or you need more clarification :)

**Comment by mayankgenie** [comment]
Thanks and is there an API to create video of the AR scene post drawing? I am very new to AR just learning how things work here.

**Comment by dam00n** [comment]
http://docs.viromedia.com/docs/viroarscenenavigator

Under ViroARSceneNavigator there is a method startVideoRecording

**Comment by irene-hakes** [comment]
can you give more information on how to use the onCameraARHitTest? It is unclear in the documentation as to how it is used. I am looking to do something similar as mayankgenie
thanks!

**Comment by VikAdvani** [comment]
Hi @irene-hakes, 

Below is an example how to use ```onCameraARHitTest```. 
In your render method add a callback to the ViroARScene:
```
render: function() {
<ViroARScene  onCameraARHitTest={this._onCameraARHitTest} >
       <ViroPolyline position={[0,0,-2]} points={this.state.points} thickness={this.state.thickness}
          materials={"white"} />
</ViroARScene>
}
```

The onCameraARHitTest method may look like the following:
```
  _onCameraARHitTest(results) {
      if(results.hitTestResults.length > 0) {
        for (var i = 0; i < results.hitTestResults.length; i++) {
            let result = results.hitTestResults[i];
            if (result.type == "ExistingPlaneUsingExtent" || result.type == "FeaturePoint") {
               this.setState({
                   points: this.state.points.push(result.transform.position);
               });
               break;
           } 
        }
     }
  },
```

The initial state would look like(we start with 1 point):
```
  getInitialState() {
    return {
      points:[[0,0,0]],
      thickness: .05,
    };
  }
```
In the example above we add to the polyline as we find more hit points. More documentation on ARHitTestResult return type is here:
https://docs.viromedia.com/docs/viroarscene#arhittestresult
