### ISSUE TITLE
videos in android in purple color

### ISSUE THREAD

**Issue by newbot23** [viromedia/viro#32]
We have an issue with android playback - video gets purple colored. 
![screenshot_2017-08-24-14-26-01-891_com viromedia viromedia](https://user-images.githubusercontent.com/12700508/29823990-b5c79772-8ce9-11e7-9211-3a4612038934.png)
We don't have the same issue on iOS.

**Comment by dam00n** [comment]
Hi, are you seeing this issue with all video assets on Android or only that specific video? If you have not yet, can you try using another video and seeing if the purple still happens.

Also what Android device are you testing this on? Is it across multiple devices or one specific device?

This information will help us track down the issue.

**Comment by newbot23** [comment]
We have tested on following devices: 
HTC One, Android 5.0
Xiaomi redmi 4a, Android 6.0.1 MMB29M
Asus Google Nexus 7 (2013), Android 6.0.1 MOB30X

We have not found any video that works properly yet. 
We have this issue even in Viro Media App from Google Play with "Viro Media Player" - 2nd item in the list.

**Comment by newbot23** [comment]
Hi @dthian would you please have a look at this issue? It still persists, let me know please if you need additional information from us!

**Comment by dthian** [comment]
Hi @newbot23, I am able to reproduce this issue on a LG Nexus 5 and will be looking into this now.

**Comment by dthian** [comment]
Hey @newbot23, we are able to reproduce this on a LG Nexus. This is a tricky bug that sounds like a hardware issue, isolated to a specific set of phones. We'll update this thread as soon as we have more information.

**Comment by newbot23** [comment]
Hi @dthian it's nice to hear that it is reproducible! Let me know please if you have any questions. So now the device list with the issue looks like this: 
* redmi 4a 
* redmi 4x
* nexus 7 2013
* htc one m7

**Comment by dam00n** [comment]
This issue has been fixed in the ViroReact 2.3 release. Upgrade instructions and release notes here -> https://docs.viromedia.com/docs/releases

Let us know if you continue to see the issue.
