### ISSUE TITLE
Changing the chromaKeyFilteringColor has no effect

### ISSUE THREAD

**Issue by dam00n** [viromedia/viro#320]
i encountered a problem, changing the chromaKeyFilteringColor has no effect. Even if i set the chromaKeyFilteringColor to "#FF0000" (red) Viro renders green as transparent and not red for example.

```ViroMaterials.createMaterials({
  chromaKeyFilteredVideo : {
    chromaKeyFilteringColor: "#FF0000"
  },
});```

**Comment by radvani** [comment]
This has been fixed for our forthcoming release.

**Comment by radvani** [comment]
This should now work as expected in ViroReact 2.8.0.
