### ISSUE TITLE
Transparent video filtering color is always green

### ISSUE THREAD

**Issue by WookieFPV** [viromedia/viro#322]
Expected behavior:
the chromeKeyFilteringColor is used to display a similar colors as transparent.

Actual behavior:
Changing the chromeKeyFilteringColor has no effect on the color that is used for filtering.
Only Green is displayed as transparent.

I used ViroReact 2.7.3 to display a Video shot with a Green screen.
Tested on IOS 11.3.1 (IPhone) and on Android 8 (Huawei P20) with the ViroMedia App.

**Comment by WookieFPV** [comment]
duplicated issue #320

**Comment by radvani** [comment]
This should now work as expected in ViroReact 2.8.0.
