### ISSUE TITLE
Unable to Switch ViroVideo between Multiple ViroARImageMarker

### ISSUE THREAD

**Issue by mkharibalaji** [viromedia/viro#323]
Hi Team,
      Could you please help me switch  between videos using ViroARImageTracker,I tried onAnchorFound and onAnchorRemoved but not able to switch the videos.Please find the sample code that i am using

Say I have 3 Image Markers and I wanted to Play video accordingly and on switching Markers I need to play the other video.

For Ex :
`
     <ViroARScene>
      <ViroAmbientLight color="#ffffff" intensity={200}/>
        <ViroARImageMarker target={"1"} onAnchorFound={this._onAnchorFound} onAnchorRemoved={this._onAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
          <ViroNode position={[0, -.1, 0]} scale={[1,1,1]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
            <ViroVideo
              source={require('./res/1.mp4')}
              loop={true}
              position={[0, 3.9, -45]} scale={[44, 22, 1]}
              materials={["chromaKeyFilteredVideo"]}
              />
          </ViroNode>
        </ViroARImageMarker>
        <ViroARImageMarker target={"2"} onAnchorFound={this._onAnchorFound} onAnchorRemoved={this._onAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
          <ViroNode position={[0, -.1, 0]} scale={[0,0,0]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
            <ViroVideo
              source={require('./res/eagle.mp4')}
              loop={true}
              position={[0.2,0.2,0]}
              scale={[1, 1, 0]}
              />
          </ViroNode>
        </ViroARImageMarker>
        <ViroARImageMarker target={"3"} onAnchorFound={this._onAnchorFound} onAnchorRemoved={this._onAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
          <ViroNode position={[0, -.1, 0]} scale={[0,0,0]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
            <ViroVideo
              source={require('./res/3.mp4')}
              loop={true}
              position={[0.2,0.2,0]}
              scale={[1, 1, 0]}
              />
          </ViroNode>
        </ViroARImageMarker>
      </ViroARScene>
`
Any Sample Code provided would be great.

Thanks & regards,
Hari

**Comment by manbod** [comment]
Hi @mkharibalaji ,
Thanks for reaching out. For something like your use case, you'll rely on using different functions to be executed on respective `onAnchorFound` callbacks for each `ViroImageMarker`. For example,
```
<ViroARImageMarker target={"1"} onAnchorFound={this._onFirstAnchorFound} onAnchorRemoved={this._onFirstAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
<ViroNode position={[0, -.1, 0]} scale={[1,1,1]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
<ViroVideo
source={require('./res/1.mp4')}
loop={true}
position={[0, 3.9, -45]} scale={[44, 22, 1]}
materials={["chromaKeyFilteredVideo"]}
/>

<ViroARImageMarker target={"2"} onAnchorFound={this._onSecondAnchorFound} onAnchorRemoved={this._onSecondAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
<ViroNode position={[0, -.1, 0]} scale={[0,0,0]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
<ViroVideo
source={require('./res/eagle.mp4')}
loop={true}
position={[0.2,0.2,0]}
scale={[1, 1, 0]}
/>
```
Pay attention to `_onFirstAnchorFound` and `_onSecondAnchorFound` above. And then depending on where the video is being played. You would need to rely on setting `state` in these `_on(X)AnchorFound` methods. Something to the effect of
```
_onFirstAnchorFound() {
this.setState({
      videoSource : {require('./res/1.mp4')}
    })
}
```
Which will change your `ViroVideo` code to
```
<ViroVideo
source={this.state.videoSource}
loop={true}
position={[0.2,0.2,0]}
scale={[1, 1, 0]}
/>
```
This way, the `ViroVideo` component will render the correct switched video when the respective 1st, 2nd, 3rd anchor is found.

Hope this helps.

Best,

**Comment by mkharibalaji** [comment]
Hi @manbod ,
          Thanks.When I did I am able to see multiple videos on the same screen getting played.i.e., For each of the targets their respective videos are getting played.How to have one single video source getting switched for multiple markers.As you can see that I am having for each ViroARImageMarker an enclosed ViroVideo that's why each video is getting triggered on for each Marker.

Could you please help me on to play a single video source switched for multiple Markers.

**Comment by manbod** [comment]
Hi @mkharibalaji ,
Where do you want this single "Video Player" component to be located? Do you want this to be in front of one of the three markers? Or somewhere else altogether? You'll need to compose your own scene depending on **where** you want the video to show. Assuming you want the video to be playing in front of the **first** marker, then your code will look something like 
```javascript
<ViroARImageMarker target={"1"} onAnchorFound={this._onFirstAnchorFound} onAnchorRemoved={this._onFirstAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
<ViroNode position={[0, -.1, 0]} scale={[1,1,1]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
<ViroVideo
source={this.state.videoSource}
loop={true}
position={[0, 3.9, -45]} scale={[44, 22, 1]}
materials={["chromaKeyFilteredVideo"]}
/>

<ViroARImageMarker target={"2"} onAnchorFound={this._onSecondAnchorFound} onAnchorRemoved={this._onSecondAnchorRemoved} pauseUpdates={this.state.pauseUpdates}/>
```
With setting state in these _on(X)AnchorFound methods as stated earlier.
```javascript
_onFirstAnchorFound() {
this.setState({
      videoSource : {require('./res/1.mp4')}
    })
}

_onSecondAnchorFound() {
this.setState({
      videoSource : {require('./res/2.mp4')}
    })
}
```
Now let's assume you want to show each of the video, in front of the corresponding marker, but only one at a time, then you would rely on a react-native construct for doing **conditional rendering** as explained [here](https://atticuswhite.com/blog/render-if-conditionally-render-react-components/). Look at how to implement the `renderIf` function in react-native. And then adjust your `ViroImageMarker` code as below
```javascript
<ViroARImageMarker target={"1"} onAnchorFound={this._onFirstAnchorFound} onAnchorRemoved={this._onFirstAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
renderIf(this.state.detectedMarker == 1,<ViroNode position={[0, -.1, 0]} scale={[1,1,1]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
<ViroVideo
source={require('./res/1.mp4')}
loop={true}
position={[0, 3.9, -45]} scale={[44, 22, 1]}
materials={["chromaKeyFilteredVideo"]}
/>)

<ViroARImageMarker target={"2"} onAnchorFound={this._onSecondAnchorFound} onAnchorRemoved={this._onSecondAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
renderIf(this.state.detectedMarker == 2,<ViroNode position={[0, -.1, 0]} scale={[0,0,0]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
<ViroVideo
source={require('./res/eagle.mp4')}
loop={true}
position={[0.2,0.2,0]}
scale={[1, 1, 0]}
/>)
```
Notice above, the `renderIf` usage around `ViroNode`. And you set the state again in the `_on(x)AnchorFound` as below
```javascript
_onFirstAnchorFound() {
this.setState({
      detectedMarker: 1,
      videoSource :  {require('./res/1.mp4')}
    })
}

_onSecondAnchorFound() {
this.setState({
      detectedMarker: 2,
      videoSource : {require('./res/2.mp4')}
    })
}
```
Hope this helps. It really depends on what your use case (where you want your `ViroVideo` component) is.

Thanks,

**Comment by mkharibalaji** [comment]
Thanks a lot @manbod.Wonderful Explanation.We can close this issue.
