### ISSUE TITLE
Cannot read property 'setJSMaterials' of undefined

### ISSUE THREAD

**Issue by ChibiMora** [viromedia/viro#324]
Hi,

I keep getting this error in my ios app, not really sure how to resolve it:

```
Cannot read property 'setJSMaterials' of undefined

Function.createMaterials
    ViroMaterials.js:71:20
<unknown>
    HelloWorldSceneAR.js:68:14
loadModuleImplementation
    require.js:214:4
guardedLoadModule
    require.js:148:11
_require
    require.js:132:2
<unknown>
    App.js:33:21
loadModuleImplementation
    require.js:214:4
guardedLoadModule
    require.js:148:11
_require
    require.js:132:2
<unknown>
    index.js:2
```

Any help would be appreciated.

Thanks

**Comment by VikAdvani** [comment]
HI @ChibiMora,
Are you running on Android using Android Studio or on iOS with XCode? Or are you getting this eror using the Viro Testbed App? Usually this can occur if react-viro wasn't installed properly on your project and the native modules can't be found.

**Comment by reyapr** [comment]
i have the same problem

**Comment by dam00n** [comment]
@reyapr can we get more info from you to repro this issue. What version of react-viro are you using? Are you running on Android using Android Studio or on iOS with XCode? Or are you getting this error using the Viro Testbed App? Usually this can occur if react-viro wasn't installed properly on your project and the native modules can't be found.

**Comment by reyapr** [comment]
i'm running Android with react native cli

react-viro 2.7.3

**Comment by VikAdvani** [comment]
Hi @reyapr, for a new project you should install viro with the react-viro cli as our cli does some setup steps to ensure viro will build properly. And with react-viro cli you can run a setup-ide script that modifies the gradle files for android to ensure the project builds correctly.

What command did you run to install the react-viro package? If you are installing to an existing project you'll need to  follow these steps here:
https://docs.viromedia.com/docs/integrating-existing-projects-android

Let me know if that helps or you need more info. Thanks :)

**Comment by faisal3413** [comment]
Hi,

I'm also getting this issue. I'm trying to run sample project, it works fine with testbed app but giving error while trying to run on iOS device with xCode.

xCode version : 9.4.1
iOS: 11.4

Please let me know how to solve this issue. Testbed app takes too much time to load and its adding delays in development .
![img_2ffa9075570f-1](https://user-images.githubusercontent.com/20745843/42318770-b8543bea-8058-11e8-9ca5-28e9e8a6fa2e.jpeg)

**Comment by VikAdvani** [comment]
Hi @faisal3413,
1) Did you create your project running 'react-viro init'??
2) Did you run the script './setup-ide --all' in your project directory?
3) If you did 2), what was the output of that script, can you cut and paste that here?
4) Did you modify the sample code in anyway? 

Thanks!

**Comment by faisal3413** [comment]
Hi @VikAdvani,

Sorry for delayed response as I was using testbed app to continue development.

I missed to run the script './setup-ide.sh --all'
I tried again and followed the guide to setup viro with xcode and I got it working successfully.

Any one coming to this thread should follow the guide below and hopefully things will turn around.
https://docs.viromedia.com/docs/starting-a-new-viro-project-1

Library is very good, keep the great work up !

Thanks

**Comment by faisal3413** [comment]
If you still get some build errors after following the guide, make sure you open the xcworkspace instead of xcodeproj as viro react is using coca pods.

**Comment by Ayzekberk** [comment]
i have same problem. I try to examine viro community examples ARDrivingCar but i couldn't succeed to build it. I did everything step by step but same error happened for me..

I cloned this project;
https://github.com/ViroCommunity/samples/tree/main/ARDrivingCar

**Comment by Ayzekberk** [comment]
> 2\. ./setup-ide --all

what does ./setup-ide --all running mean. When i ran in terminal that command terminal says 
`no such file or directory: ./setup-ide`

**Comment by Ayzekberk** [comment]
> Hi @faisal3413,
> 
> 1. Did you create your project running 'react-viro init'??
> 2. Did you run the script './setup-ide --all' in your project directory?
> 3. If you did 2), what was the output of that script, can you cut and paste that here?
> 4. Did you modify the sample code in anyway?
> 
> Thanks!

Hi @VikAdvani

what does run the script './setup-ide --all' mean ?
i try to build an existing project so i don't see any setup-ide file in my root directory

**Comment by monkeyK1n9** [comment]
Hello everyone.

I have the same error. Any solution yet? I am stuck

**Comment by Serdar17** [comment]
> Hello everyone.
> 
> I have the same error. Any solution yet? I am stuck

Did you get to fix this error?

**Comment by monkeyK1n9** [comment]
Hello @Serdar17 , I have a work around.

This error comes when I use a recent react native version (0.70) especially with expo (sdk >= 45).

To solve my issue, I am using just the starter-kit provided by Viro ([here](https://github.com/ViroCommunity/starter-kit)).
The expo-viro-starter-kit does not for me, it produces similar errors (VRTText missing).

So I would advice, you use the starter-kit.

Special remarks:
1- You will need to change your `/android/build.gradle` file to this (see below), because of the recent Maven and jcenter changes in gradle (see blog post [here](https://blog.gradle.org/jcenter-shutdown)) or else, it might not work:

```js
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
    }
    repositories {
        google()
        // mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        exclusiveContent {
            filter {
               includeGroup "com.facebook.react"
            }
            forRepository {
                maven {
                   url "$rootDir/../node_modules/react-native/android"
                }
            }
        }
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        // maven { url 'https://www.jitpack.io' }
        jcenter()
    }
}
```

2- You can rename your app following this nice [tutorial](https://youtu.be/v3X7RKvy_8I) or try the answers in the stackoverflow questions [here](https://stackoverflow.com/questions/32830046/renaming-a-react-native-project)

There you go, you are good to go. It worked for me. Hope it might help

**Comment by Nziranziza** [comment]
I am using expo just followed the installation guide with expo and go this error

**Comment by victorgalvez56** [comment]
> I am using expo just followed the installation guide with expo and go this error

same

**Comment by pafa7a** [comment]
> I am using expo just followed the installation guide with expo and go this error

same

**Comment by LouisSyfer** [comment]
same issue

**Comment by ManuSense** [comment]
Same issue

**Comment by rahuldasgupta** [comment]
Same error still +1

**Comment by thekevinbrown** [comment]
Another issue was created on the new repo here: https://github.com/NativeVision/viro/issues/282

**Comment by subin1rai** [comment]
![IMG_6512](https://github.com/user-attachments/assets/2221340b-fe30-4370-bf6f-c028de0de6ca)
Same error i am using expo, anyone fixed this error ?

**Comment by Sadman95** [comment]
> ![IMG_6512](https://private-user-images.githubusercontent.com/131991730/386846811-2221340b-fe30-4370-bf6f-c028de0de6ca.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NzQzMjEsIm5iZiI6MTczMzU3NDAyMSwicGF0aCI6Ii8xMzE5OTE3MzAvMzg2ODQ2ODExLTIyMjEzNDBiLWZlMzAtNDM3MC1iZjZmLWMwMjhkZTBkZTZjYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxMjIwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzJkMTE4NzIyYjkyMGViYjI2NmYzYzA0ZmIxZjlkOTAwOGMxYzExZTlhNWNjM2JhMjliZjJjNjlkYjM2NjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OL4627HJUz4oWQERmMHNOQEr86FY0teSx6DP9ozZA9Q) Same error i am using expo, anyone fixed this error ?

same error I am also facing

**Comment by desenvjackson** [comment]
same error I am also facing

**Comment by DaiFudo** [comment]
same error I am also facing
