### ISSUE TITLE
Image with some transparent areas

### ISSUE THREAD

**Issue by Tamiyadd** [viromedia/viro#325]
Hi, i'm trying to show a png, that have some transparent area, in ViroImage but it places a white layer (it seems rgba(255,255,255,0.2)) under the image. 
How can i make the transparent png areas also transparent in AR? thanks

**Comment by dthian** [comment]
Hey @Tamiyadd, just wanted to check in with the above to see if we can help - did you manage to resolve your issue? Thanks!

**Comment by Tamiyadd** [comment]
hi @dthian i've closed the issue because i've used another image but i think the problem is still there. If you use png images in ViroImage the empty areas are filled with a white background with opacity (0.2)

**Comment by mridul911** [comment]
hi @dthian @Tamiyadd i am also facing same issue can anyone guide me ??
