### ISSUE TITLE
This app is incompatible to your device.

### ISSUE THREAD

**Issue by HLneoh** [viromedia/viro#328]
Hi, my phone cannot download ViroMedia app as it states "this app is incompatible to your device".
My phone is android 5.1. (Vivo Y31)
Does ViroMedia only allow for the supported devices listed in ArCore to be downloaded?

**Comment by dam00n** [comment]
Viro Media app requires devices to have GPU's that support OpenGL ES 3.0 and above. That might be the issue with your device.

**Comment by HLneoh** [comment]
Thanks for the response. 

May I know is my phone still able to set up android studio with viro react if it does not support OpenGL ES 3.0 and above?
