### ISSUE TITLE
Waypoint system in real world augmented reality

### ISSUE THREAD

**Issue by saad-ansari** [viromedia/viro#333]
i'm looking for a solution where i have to define a for my object to follow in real world AR.

For example i have defined a path from my desk to my  colleague's desk so then that object will follow that path. 

Thank you.

**Comment by VikAdvani** [comment]
Hi @saad-ansari,
This is definitely possible using Viro. You can see this github issue https://github.com/viromedia/viro/issues/131

On how to convert lat/long points into real world AR cords to enable wayfinding in AR.

**Comment by dam00n** [comment]
Closing this issue as solution was provided.
