### ISSUE TITLE
Place Object or Text always in front of Camera

### ISSUE THREAD

**Issue by AntoniaBe** [viromedia/viro#334]
Hi all,

is it possible to place an object or text always in front of the camera? So when I move my device, the object/text would always be in sight. 

thanks!

**Comment by radvani** [comment]
This is now supported in ViroReact 2.8.0 via the `ViroCamera` component.

**Comment by VikAdvani** [comment]
Hi @AntoniaBe,
Yep both are possible. To place a text or any object relative to  the camera just do the following for an AR Scene:
```
<ViroARCamera>
            <ViroText position={[0, 0, -6]} text={"Menu Text"}
                    width={2} height={2} />
 </ViroARCamera>
```
For VR, simply use```ViroCamera```. You an put as many children as you want under the camera. This will position the objects relative to the camera at all times. 

To position objects in world space simply put them outside of the camera tag as you would usually.

**Comment by AntoniaBe** [comment]
hi @VikAdvani,

thanks for the example! I used ViroCamera before, but now it makes sense.
But when I use the example you provided, I get the following error screen:
![screenshot_20180706-211352_virosample-ar 1](https://user-images.githubusercontent.com/15321778/42396409-d2f09e58-8161-11e8-92fe-2ee25ef17ce8.jpg)

When I remove the child, I don't get an error screen.

**Comment by AntoniaBe** [comment]
Hi @VikAdvani ,

thanks for the fast reply! I did update to 2.8 and I'm not using the testbed app, I built it on my android device. I tried to remove the node_modules folder and run npm install for the second time, but I still get the error above.

**Comment by VikAdvani** [comment]
Hi @AntoniaBe,
I was able to repro the issue. We just launched Viro React 2.8.1 with a fix. Try upgrading to the latest. That should work. If it doesn't let me know!

**Comment by AntoniaBe** [comment]
Hi @VikAdvani ,

thanks for the update, it works perfectly now! :)
