### ISSUE TITLE
[Quiestion] Download remote 3d files?

### ISSUE THREAD

**Issue by rborn** [viromedia/viro#335]
Hi,

Is it possible to download the 3d models in the app and not to embed them within the app?
The docs say `3D models must be loaded from the application bundle. ` but this is not so practical for many cases.

Thank you 🤗

**Comment by dam00n** [comment]
Yes, this is possible. You can use a url for your asset -> {uri:"http://example.org/myobject.obj"}

https://docs.viromedia.com/docs/viro3dobject

Let us know if you run into issues

**Comment by rborn** [comment]
Oh, sorry, somehow I missed that. Thank you.
