### ISSUE TITLE
[iOS] - Camera permission for ViroVRSceneNavigator

### ISSUE THREAD

**Issue by Charlynux** [viromedia/viro#337]
Hello,

The first time, I run a view with "ViroVRSceneNavigator" on iOS, the app requests an access to camera.
It seems legit for AR, but for VR ?

Could you explain the reason ? 
(Under certain circumstances, it seems to lock camera access to other components.)

Thank you !

**Comment by dam00n** [comment]
@Charlynux for VR, cardboard headset require calibration using a QR code printed on the headset. Therefore, GVR (Google VR) requires camera permissions.

**Comment by Charlynux** [comment]
Thanks for the explanation !
