### ISSUE TITLE
ARSceneNavigator not destroyed even after switching the View

### ISSUE THREAD

**Issue by mkharibalaji** [viromedia/viro#341]
Hi Guys,
           I created a new project using viro-cli using Virocore 2.7.3.In the sample project created i wanted a normal view to come back from the ARScene Navigator,so followed the below steps,

in **App.js**
```
_getExperienceselector{
     <View style={localStyles.outer} >
        <View style={localStyles.inner} >

          <Text style={localStyles.titleText}>
            Choose your desired experience:
          </Text>

          <TouchableHighlight style={localStyles.buttons}
            onPress={this._getExperienceButtonOnPress(AR_NAVIGATOR_TYPE)}
            underlayColor={'#68a0ff'} >

            <Text style={localStyles.buttonText}>AR</Text>
          </TouchableHighlight>

          <TouchableHighlight style={localStyles.buttons}
            onPress={this._getExperienceButtonOnPress(VR_NAVIGATOR_TYPE)}
            underlayColor={'#68a0ff'} >

            <Text style={localStyles.buttonText}>VR</Text>
          </TouchableHighlight>
        </View>
      </View>
}
_getARNavigator() {
    return (
       <View style={{flex:1}}>
        <ViroARSceneNavigator ref={ARScene_REF} {...this.state.sharedProps} initialScene={{scene: InitialARScene}} onExit={this._exitViro}/>
        <View style={{position: 'absolute',  left: 0, right: 0, top : 20,width:80, alignItems: 'center'}}>
              <TouchableHighlight onPress={this._exitViro} >
                <Text style={{ fontSize: 18, color: 'white' }}>&#60;&nbsp;Back</Text>
              </TouchableHighlight>
        </View>
      </View>
    );
  }

  **_exitViro()** {
    this.setState({
      navigatorType : UNSET
    })
  }
```
**HelloWorldSceneAR.js**
I have a ViroVideo Playing a mp4 video triggered by a ViroARImageMarker

Let's say I am playing the Video with music and once i click the back button as per the getARNavigator it successfully returns back but i hear the music still playing behind.

**Comment by dthian** [comment]
Thanks @mkharibalaji, two quick questions: 

1) You have verified that getARNavigator() is no longer called / rendered in your app?
2) could you share the code of your InitialARScene that contains the video you are playing? Feel free to send it to us via support@viromedia.com if needed.

Much thanks!

**Comment by mkharibalaji** [comment]
Hi @dthian ,
         I had attached the code and sent it to the support email.

Thanks for the support.

**Comment by oOMoeOo** [comment]
+1 I'm experiencing the same problem. You can also this issue when displaying the feature points, navigating back and then again opening the ar screen. The feature points are displayed as transparent squares instead of opaque circles.

**Comment by dthian** [comment]
Hey @oOMoeOo, do you mean you have confirmed a scene Navigation leak? Or that a visual bug with the feature points where the circles become transparent squares - Please file a separate bug if this is the case so that we don't conflate this github issue here.

**Comment by dthian** [comment]
Hey @mkharibalaji, thanks for your reply. Can you double check if you've sent your message to the right email? I can't seem to find it in our @support. Also, please feel free to directly message me in Slack if need be as well, thanks!

**Comment by mkharibalaji** [comment]
@dthian - Could you please give your slack id.I have sent the email again with the github no. as attachment

**Comment by mkharibalaji** [comment]
Hi @dthian,
           Thanks for the wonderful support on slack and found the problem to be with ScrollView which once wrapped by a View got it resolved.

so wecan close this issue.

**Comment by JoaquinBuxo** [comment]
I've exactly the same error! In my case works perfectly in Android, but when I tested on iOS  and I back from the view camera I hear the music still playing behind.

How did you solve it? I tried to look for it in slack, but I haven't found it

> Hi Guys,
> I created a new project using viro-cli using Virocore 2.7.3.In the sample project created i wanted a normal view to come back from the ARScene Navigator,so followed the below steps,
> 
> in **App.js**
> 
> ```
> _getExperienceselector{
>      <View style={localStyles.outer} >
>         <View style={localStyles.inner} >
> 
>           <Text style={localStyles.titleText}>
>             Choose your desired experience:
>           </Text>
> 
>           <TouchableHighlight style={localStyles.buttons}
>             onPress={this._getExperienceButtonOnPress(AR_NAVIGATOR_TYPE)}
>             underlayColor={'#68a0ff'} >
> 
>             <Text style={localStyles.buttonText}>AR</Text>
>           </TouchableHighlight>
> 
>           <TouchableHighlight style={localStyles.buttons}
>             onPress={this._getExperienceButtonOnPress(VR_NAVIGATOR_TYPE)}
>             underlayColor={'#68a0ff'} >
> 
>             <Text style={localStyles.buttonText}>VR</Text>
>           </TouchableHighlight>
>         </View>
>       </View>
> }
> _getARNavigator() {
>     return (
>        <View style={{flex:1}}>
>         <ViroARSceneNavigator ref={ARScene_REF} {...this.state.sharedProps} initialScene={{scene: InitialARScene}} onExit={this._exitViro}/>
>         <View style={{position: 'absolute',  left: 0, right: 0, top : 20,width:80, alignItems: 'center'}}>
>               <TouchableHighlight onPress={this._exitViro} >
>                 <Text style={{ fontSize: 18, color: 'white' }}>&#60;&nbsp;Back</Text>
>               </TouchableHighlight>
>         </View>
>       </View>
>     );
>   }
> 
>   **_exitViro()** {
>     this.setState({
>       navigatorType : UNSET
>     })
>   }
> ```
> 
> **HelloWorldSceneAR.js**
> I have a ViroVideo Playing a mp4 video triggered by a ViroARImageMarker
> 
> Let's say I am playing the Video with music and once i click the back button as per the getARNavigator it successfully returns back but i hear the music still playing behind.
