### ISSUE TITLE
How to run this sample project directly as an android app without using testbed app?

### ISSUE THREAD

**Issue by HLneoh** [viromedia/viro#342]

**Comment by dam00n** [comment]
http://docs.viromedia.com/docs/installing-viro-android

**Comment by HLneoh** [comment]
Thanks for the response. 

But my problem is that there is no android folder in this github sample project, thats why I cannot run 'react-native run-android'. 

Can somebody help please?

**Comment by manbod** [comment]
Hi @HLneoh ,

As you correctly pointed out, our github sample project is just a collection of JS sample code that devs can try out via the testbed app. For running any of the sample JS code examples as a standalone android app, you would need to go through instructions mentioned [here](https://docs.viromedia.com/docs/installing-viro-android) and copy the JS folder (or relevant js and resource files) from the sample project over to your stand alone app code base. Edit your App.js and index.js accordingly (adjusting names of the copied over examples in the app registry in index.js)

Let us know if you run into further questions while following the android tutorial.

Thanks,

**Comment by HLneoh** [comment]
Hi, @manbod. Thanks for your comment. 

I have tried to follow the quick start (Windows). In "Start Your Packager Server" step, it should appear ngrok endpoint if I ain't mistaken. 

However, I could not get the ngrok endpoint after running "npm run" as shown in below. 

![1](https://user-images.githubusercontent.com/25906607/42287962-568dd212-7feb-11e8-8d46-724b73e6eb35.PNG)

**Comment by HLneoh** [comment]
@manbod 
My phone is incompatible to download viro media app as it has no OpenGL 3.0 and above. 
Is my phone able to set up android studio with viro react and run this sample project as an android app?

**Comment by HLneoh** [comment]
Can somebody help please?
