### ISSUE TITLE
ViroText inside ViroARImageMarker won't render

### ISSUE THREAD

**Issue by Stenkilde** [viromedia/viro#343]
Hey guys, I am working on a small prototype with reading "Image markers" similar to this 
https://twitter.com/mortenjust/status/1009426050365952001

The idea is you scan an image and show text next to it.

However, I can't seem to get ViroText to render insane the ImageMarker components. Having my text outside will make it render (which isn't quite what I want to accomplish)

I also tried throug an ArPlane with text inside which didn't change anything either. Looks like it's only possible to work together with 3D objects. Am I missing something super crucial?

I am using the Testbed and a Pixel 2 for the testing

**Comment by achuvm** [comment]
Hi Stenkilde,

We tried this on our end and it seems to work, here's our code (the marker is attached):

```
'use strict';

import React, { Component } from 'react';

import {StyleSheet} from 'react-native';

import {
  ViroARScene,
  ViroText,
  ViroARImageMarker,
  ViroARTrackingTargets,
} from 'react-viro';

export default class HelloWorldSceneAR extends Component {
  render() {
    return (
      <ViroARScene >
        <ViroARImageMarker target={"ben"}}>
          <ViroText text={"Hello World"} scale={[.2, .2, .2]}
            position={[0, .1, 0]} rotation={[-90, 0, 0]} style={styles.helloWorldTextStyle} />
        </ViroARImageMarker>
      </ViroARScene>
    );
  }
}

var styles = StyleSheet.create({
  helloWorldTextStyle: {
    fontFamily: 'Arial',
    fontSize: 30,
    color: '#ffffff',
    textAlignVertical: 'center',
    textAlign: 'center',  
  },
});

ViroARTrackingTargets.createTargets({
  "ben" : {
    source : require('./res/ben.jpg'),
    orientation : "Up",
    physicalWidth : 0.157 // real world width in meters
  },
})

module.exports = HelloWorldSceneAR;
```

The one tricky thing is that the positive Y vector will come "up" off of the recognized image, so if you don't rotate your `ViroText` component by `[-90, 0, 0]`, it'll be standing on the image as opposed to lying down. 

The marker we used: 
![ben](https://user-images.githubusercontent.com/21074927/42177292-0d36ca30-7de1-11e8-849d-3b20be59b38d.jpg)

**Comment by Stenkilde** [comment]
Hmm, this is weird haha. I also had position set. I copy pasted what you had (used my marker) and everything worked fine. Only difference is basically your ViroARTrackingTargets.createTargets({)} is below the component. Oh well, I might have done some super stupid stuff.

Thanks for the quick answer!

**Comment by achuvm** [comment]
Very curious, but glad it works!

If you ever figure out what was causing the issue, let us know!

**Comment by krishanjangir** [comment]
@achuvm  I tried your code but it's not working.

Could you please brief me how 'ViroARImageMarker' works.  Is this necessary that when the same image in the source of 'ViroARTrackingTargets' found while tracking,  'ViroARImageMarker' function works.
In your example when 'ben.jpg' found by camera ViroARImageMarker triggers the method ?

**Comment by achuvm** [comment]
Hi @krishanjangir,

The `ViroARImageMarker` works in that whatever is placed within the component is not rendered until the provided `target` is found.

Thanks,

**Comment by krishanjangir** [comment]
@achuvm  

In my case 'ViroARImageMarker' is not rendered.

I am testing it on "react": "16.3.1", "react-native": "0.55.3" And android 9.0
I want image 3 meters away from user so i have changed it 'position={[0, 0, -3]} '
Below is my render method.

    render() {
      return (
      <ViroARScene >
        <ViroARImageMarker target={"ben"}}>
          <ViroText text={"Hello World"} scale={[.2, .2, .2]}
            position={[0, 0, -3]} rotation={[-90, 0, 0]} style={styles.helloWorldTextStyle} />
        </ViroARImageMarker>
      </ViroARScene>
      );
    }

**Comment by krishanjangir** [comment]
> Hi @krishanjangir,
> 
> The `ViroARImageMarker` works in that whatever is placed within the component is not rendered until the provided `target` is found.
> 
> Thanks,

@achuvm  Sorry but i have no idea how the target will found, is this a image recognition type something ? In viro example we can see when camera found the 'Tesla' car it open the 3D image of car.
     https://github.com/viromedia/viro/tree/master/js/ARCarDemo
What if in above example the logo in ipad screen is of BMD, will 'ViroARImageMarker' detects that target and opens the 3D tesla car ?

Could you please share any video of your sample application.

Actually i am developing an application in which i have multiple videos around user. i want to play one by one when user hover on any of the video.

If you can help me on my question that would be great help.
https://github.com/viromedia/viro/issues/472

**Comment by achuvm** [comment]
Hi @krishanjangir,

Yes, this is image recognition, so if/when the target image appears in the camera view, the underlying AR system will detect the image and the components under the `ViroARImageMarker` will be rendered relative to that target image in AR.

If you take a look at the ARCarDemo, the target image is this one: https://github.com/viromedia/viro/blob/master/js/ARCarDemo/res/logo.png

If you want to use your own image, then simply add a new image and refer to it within the `ARCarDemo.js` file.
