### ISSUE TITLE
Appearance of feature points change when reopening an ar screen.

### ISSUE THREAD

**Issue by oOMoeOo** [viromedia/viro#346]
Hi,

in my application i display the feature points to give the user a visual feedback while scanning the environment. Feature points are shown as solid white circles. Every time i leave the ar screen and come back again the feature points are displayed as semi-transparent white squares. The only way to change this behavior is to completely remove the app from the iPhone cache and the reopen it.

**Testing environment:**
I tested the behavior on an iPhone 7 and iPhone X, both with iOS 11.4 and the latest Viro React version. I use react-navigation for navigating between screen.

**Simple test case**
Create a small app with two screens A and B with B using the ViroARSceneNavigator. Use navigate to start the ar experience and enable the feature points. The feature points will be displayed correctly. Then use navigation.goBack() to get back to A and reopen the ar screen. The feature points will be displayed differently.

![correct-feature-points](https://user-images.githubusercontent.com/5557362/42261454-a2cd6206-7f68-11e8-8b65-0568e4558c36.png)
![incorrect-feature-points](https://user-images.githubusercontent.com/5557362/42261466-a9abd5bc-7f68-11e8-99bf-90ddc2b84221.png)

Is this a known issue and if not, could you please check it?

Regards
Moe

**Comment by dthian** [comment]
Hey @oOMoeOo, thanks for reaching out! Yup this is a legit bug, I've filed a bug on our backlog to tackle it. Is this issue considered a ship blocker for you? Thanks!

**Comment by oOMoeOo** [comment]
Hey @dthian, yes, that's a ship blocker because switching between ar and non ar screen is a common usecase in our application. Thanks!

**Comment by dthian** [comment]
Thanks @oOMoeOo, we'll have a fix in our next upcoming release. This issue will be updated once that has been released.

**Comment by dthian** [comment]
Hey @oOMoeOo, this has been fixed in the latest release. Please update to the latest to resolve this issue [here](https://virocore.viromedia.com/docs/releases). Thanks!
