### ISSUE TITLE
[Question]  diff file to modify Android gradle and manifest files

### ISSUE THREAD

**Issue by HLneoh** [viromedia/viro#347]
What is the difference between red color and blue color of AndroidManifest.xml as shown in picture below?

Should I modify my AndroidManifest.xml based on red color or blue color? (I want to setup android studio to viro react to run the "Hello World" VR sample)

![capture](https://user-images.githubusercontent.com/25906607/42329615-ac9cdc76-80a3-11e8-81d6-5174ff0800d4.PNG)

**Comment by VikAdvani** [comment]
Hi @HLneoh, 
You'd want to remove the red lines in your gradle files if they are there and add the green lines.

**Comment by HLneoh** [comment]
@VikAdvani Thanks for the comment. 

I have two questions:

1. I cannot find "a/android/app/src/ovr/AndroidManifest.xml" in the Hello World project folder. I cannot add the code as shown in below to the file. How can I solve this problem?
![1](https://user-images.githubusercontent.com/25906607/42392075-24944710-8184-11e8-86c0-9e84cb9b6aab.PNG)

2. I have tried to remove the red lines and add the green lines in my gradle file (Except for the code in question 1 above). When I tried to sync my project, it fails to sync the project and appears the messages below.

![1](https://user-images.githubusercontent.com/25906607/42392166-81cba414-8184-11e8-9aec-77d3d81bfd8d.PNG)

When I tried to upgrade the plugin to version 3.1.2, it appears the error as below. 

![1](https://user-images.githubusercontent.com/25906607/42392504-ac17f38e-8185-11e8-9a34-2c4381da7e09.PNG)

Can somebody help please?
