### ISSUE TITLE
Curved Surface Marker Detection on Bottle - Video Swagging

### ISSUE THREAD

**Issue by mkharibalaji** [viromedia/viro#348]
Hi Team,
            I am struggling to fix the swagging of the ViroMaterial Video on top of the bottle where it doesn't sit still.
```
        <ViroARImageMarker target={"X"} 
        onAnchorFound={anchor => this._onAnchorFound(anchor)} 
        onAnchorUpdated={anchor => this._onAnchorUpdated(anchor)} 
        onAnchorRemoved={this._onAnchorRemoved} pauseUpdates={this.state.pauseUpdates}>
        {(!this.state.showVideo ? <ViroNode></ViroNode> :
             <ViroNode  position={[0.0,0.0,-.008]} scale={[0.1,0.1,0.1]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>
                <ViroAmbientLight color="#ffffff" intensity={200}/>
                <Viro3DObject
                  source={require('./res/wine_label1.obj')}
                  materials="bottle_video"
                  type="OBJ"
                  position={[0.0,-0.8,0.0]}
                  scale={[0.59,0.65,0.8]}
                  onDrag={()=>{}}
                />
                 <ViroMaterialVideo ref={VIDEO_1141_REF} material={"bottle_video"} paused={!this.state.show1141Video} loop={false}></ViroMaterialVideo>          
             </ViroNode>
        )}
        </ViroARImageMarker>
```
I am not able to play the video steadily.It swaggs when i move and doesn't sit on top of the bottle.
I will send the video in private.

**Comment by manbod** [comment]
Hi @mkharibalaji ,

Do send a video capture of the bug that you are seeing. But just to be clear -> Viro (and underlying ARKit and ARCore) only support image markers on flat surfaces. Your mileage may vary while trying to detect image markers on curved surfaces. One workaround that I can think of, depending on what your marker is, may be try using a small portion of the curved image as the marker? If that's possible, select a portion of the curved image, that would appear somewhat "flat" for reliable image recognition?

Let us know if that works for you. 

Cheers,

**Comment by mkharibalaji** [comment]
Hi @manbod ,
          You are correct,so far I had took the small portion of the Flat surface as marker and the detection looks good.But the Video keeps on swagging when i move the mobile slow or fast irrespective of speed.
           I had shared the video privately to your slack id as it is one of our Client's work.Once shipped I can make it public.Please do let me know if you require the code that i can share.

**Comment by dthian** [comment]
Anther possible mitigation is to pause updates on the ViroARImageMarker. You can set the "pauseUpdates" props to false to stop the ViroARImageMarker from updating as it finds new orientation points on the bottle, so as to stop the "swagging" or "repositioning"

Ideally you could stop updates as soon as it has found a position on the bottle. The downside to this is that the first found position may not be the most accurate one.

Another approach is to allow the user to "lock" the video whenever the user determines the video is in the "best orientation". 

You can see the pauseUpdates API [here](https://docs.viromedia.com/docs/viroarimagemarker).
