### ISSUE TITLE
Is package working with latest react-native version (0.56.0)?

### ISSUE THREAD

**Issue by godofmadness** [viromedia/viro#350]

**Comment by dam00n** [comment]
ViroReact 2.8.1 (latest release) is compatible with RN 0.55.1

Every react-viro release has a `Compatible with React Native` version. This means that we have extensively tested ViroReact to work with that version of react-native. While older or newer versions of react-native may work with Viro, there may be issues or differences that cause ViroReact to not work properly with older or newer versions of react-native -> https://docs.viromedia.com/docs/releases
