### ISSUE TITLE
[Question] When viro will be compatible with ARKit 2.0?

### ISSUE THREAD

**Issue by oOMoeOo** [viromedia/viro#351]
Hi,

a few weeks ago apple launched the ARKit 2 beta version and i'm very excited about the new image tracking and persistent ar session features. Do you guys already work on the integration of those features and if yes when do you plan to release a compatible viro version?

Thanks for this awesome library
Moe

**Comment by dam00n** [comment]
Hi @oOMoeOo, we are working on ARKit 2.0 support now. We just started so we don't have a date yet, but will update this github issue with more info when we have it.

**Comment by oOMoeOo** [comment]
@dam00n This is awesome! Thanks!

**Comment by dam00n** [comment]
We added beta support for ARKit 2.0 as of ViroReact 2.9

ARKit 2.0 and iOS 12 are currently in developer preview and thus is also in developer preview for Viro. 

Here are instructions for enabling ARKit 2.0 features in beta (developer preview) -> https://docs.viromedia.com/docs/enable-arkit-20-beta-features

Will update this issue again when ARKit 2.0 goes live to the public

**Comment by kesha-antonov** [comment]
iOS is officially out!

**Comment by dam00n** [comment]
ViroReact v2.11.0 supports ARKit 2.0 public launch. 

Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

**Comment by ChristianNormann** [comment]
I cannot see any support for ARKit 2 Persistent AR. Is this somehow supported? If not, is it on your roadmap?

Thank you for some nice work!

**Comment by dam00n** [comment]
Hi @ChristianNormann, we do not support ARKit 2.0 Persistent AR at this time. It is on our roadmap but we don't have a date for when the feature will be available. Created a new issue to track this request and will updated it when we have more info -> https://github.com/viromedia/viro/issues/477
