### ISSUE TITLE
ViroSkyBox with color set to white or #FFFFFF renders as grey

### ISSUE THREAD

**Issue by shaneahern** [viromedia/viro#354]
The ViroSkyBox I have in my scene in the following code with color set to #FFFFFF is yeilding a background that is a light grey rather than solid white. Other colors seem to work. If I set the color=red in the same code, for example, the backround renders as solid red.
```
<ViroScene
  ignoreEventHandling
>
  <ViroAmbientLight color="white" intensity={1000} />
  <ViroSkyBox color="#FFFFFF" />
  <ViroNode
    position={[0, 0, 0]}
    ignoreEventHandling
  >
    <ViroOrbitCamera position={[cameraX, 0, cameraZ]} focalPoint={[0, 0, 0]} active />
    <Viro3DObject
      ignoreEventHandling
      scale={[scale, scale, scale]}
      position={[0, -0.5, 0]}
      rotation={[0, 0, 0]}
      source={{ uri: modelUrl }}
      type="VRX"
      animation={{
        run: true,
        loop: true,
        delay: 1000,
      }}
    />
  </ViroNode>
</ViroScene>
```
<img width="326" alt="screenshot 2018-07-09 18 33 51" src="https://user-images.githubusercontent.com/76200/42484205-ab423f96-83a6-11e8-9928-d1d573696f36.png">

**Comment by dthian** [comment]
Note, this is an issue with enabling HDR. One solution is to provide the same rendering configuration options that we have in ViroCore, so as to enable developers to turn on/off: 
hdr / bloom / shadows and pbr.

This issue will be updated once it has been pushed into release.

**Comment by dam00n** [comment]
Toggle for enabling/disabling HDR, Shadows and PBR added in latest release, ViroReact 2.9

Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

Documentation here -> https://docs.viromedia.com/v2.9.0/docs/viroarscenenavigator#section-optional-props
