### ISSUE TITLE
[Question] Running sample code as a stand alone project (with no Testbed app)

### ISSUE THREAD

**Issue by HLneoh** [viromedia/viro#358]
I have followed all the steps mentioned in the github. However, i got the following error. Can anyone help, please? @manbod @dam00n @dthian @radvani @VikAdvani 

![screenshot_20180714-135532_virosample-ar](https://user-images.githubusercontent.com/25906607/42730786-184fd8d6-8830-11e8-8908-e06349a50d54.jpg)

**Comment by manbod** [comment]
Hi @HLneoh ,
Are you still running into this issue? Going by other github issues you opened (https://github.com/viromedia/viro/issues/349) are you running the steps mentioned on the github page on a windows machine? I just ran through the steps written on the github page and the project seems to work fine. I suspect there might be something missing in your react-native installation. Try going through steps to install react-native correctly from here https://facebook.github.io/react-native/docs/getting-started.html. Found a little detailed installed steps on this helpful blog -> https://medium.com/@roydejong/preparing-windows-for-react-native-development-44a78cd68346 Make sure a simple react-native (not using Viro) works correctly on your setup. 

Once that works, if you are still running into issues building code samples in this repository try running the following manual steps to build, install and run these samples ->
1. Make sure your ANDROID_HOME environment variable is set correctly
2. Ensure you have added ANDROID_HOME/platform-tools and ANDROID_HOME/tools to your PATH environment variable correctly.
3. To build the android app
    ```
     cd android
     ./gradlew clean
     ./gradlew assembleArDebug
    ```
4. If the build completed succesfully, the apk would be located at `/viro/android/app/build/outputs/apk/gvr/release/app-ar-debug.apk`; install this apk onto your android device.
5. Connect your android device to your computer and run `adb reverse tcp:8081 tcp:8081` to reverse tether your device to your computer.
6. Go to the root of the project (`/viro`, not `/viro/android`) and start your packager server by running `npm start`
7. If npm start command ran successfully -> you should see a "Loading dependency graph..." message at the bottom when it runs.
8. Now start the app. If you have your API_KEY updated in App.js, you should see your VR helloworld scene working.

Let us know if you run troubles while following these steps.

Good luck!

**Comment by dam00n** [comment]
Closing this issue as solution was provided. Please re-open and add additional comments if you are still having issues.
