### ISSUE TITLE
ViroARImageMarker question - Object follow and move with the target

### ISSUE THREAD

**Issue by NLegendre** [viromedia/viro#359]
Hi,

I'm using ViroARImageMarker to display a simple 3d object above the target (like your Tesla example). But when I move the target, the 3d object stay still.

My question: is it possible to define the object so it follow the target ?

Thanks

**Comment by dam00n** [comment]
We use ARKit and ARCore for image recognition. Currently moving targets is not supported by either platform. But ARKit 2.0 (currently in developer preview) does enable moving targets. We are working on integrating ARKit 2.0 with Viro now.

**Comment by NLegendre** [comment]
Ok, thank you for the answer !
Great job on Viro btw :)
