### ISSUE TITLE
How to get data from MySQL database to react native?

### ISSUE THREAD

**Issue by HLneoh** [viromedia/viro#362]
Hi guys, I wish to use MySQL database to store all the data used for my VR feature. May I know how can I get the data from MySQL database (PHP) to react native? Also, do I really need to host the PHP globally in order to get the MySQL data? Can I host it locally?

**Comment by manbod** [comment]
Hi @HLneoh ,
By MySQL database, are you talking about an on-device database storage or host it on a server somewhere, where the app can connect over the network? In any case, connecting to a database is outside of Viro's functionalities. I'd suggest searching for the right third party database solutions for react-native. This stackoverflow post has a few suggestions I'd start with - https://stackoverflow.com/questions/43904877/can-i-connect-my-reactive-app-with-mysql-database

A quick note - unsure of what your use case is (are you going to be inserting into this database? is the app going to use this database in a read-only fashion?...) We recently open sourced our Figment AR App. Find download links and source code here -> https://github.com/viromedia/figment-ar . Although this may or may not apply for your app's use case, to avoid dealing with complexity of connecting with with a database we rely on simple JSON data model in code (https://github.com/viromedia/figment-ar/tree/master/js/model). This data is retrieved and rendered with code in [js/component/ModelItemRenderer.js](https://github.com/viromedia/figment-ar/blob/master/js/component/ModelItemRender.js) and similarly in PortalItemRenderer.js and EffectsItemRenderer.js for Portals and Effects in the app. We encourage you to go through the code base and tweaking it for your use case.

Good luck,

**Comment by dam00n** [comment]
Closing this issue as solution was provided. Please re-open if you still have issues.
