### ISSUE TITLE
Setting up Viro for android with react-native

### ISSUE THREAD

**Issue by bleudreams** [viromedia/viro#366]
Greetings Everyone,

Over the last couple of days I have experienced significant issues setting up viro for a react-native application in android studio.

I was able to setup viro to work in ios but am just having the darndest time with android.

Has anyone successfully setup viro for android or run into issues?

KRH

**Comment by manbod** [comment]
Hey @bleudreams ,
I think we followed up on our slack channel regarding your issues running viro on android simulator. We've updated our documentation with the callout that we don't support Android simulator. Let us know if you run into issues running on an android device.

Thanks,
