### ISSUE TITLE
Set animation duration in Viro3DObject for skeletal animations in VRX files

### ISSUE THREAD

**Issue by shaneahern** [viromedia/viro#368]
We'd like to be able to specify the duration of a named skelatal animaiton in a FBX/VRX file, that would have the effect of speeding up or slowing down the animation time specified for the animation in the file. So for example if the time built into the animation for an animation named "Take 001" is 4 seconds, if duration was set to 2 seconds the animation would render at 200% speed so that it takes 2 seconds to complete, or if set to 8 seconds, would render at 50% speed so taht it takes 8 seconds to complete.

Idea would be to add a property named something like "duration" that would determine the duration of the animation such that the speed of the animation would be adjusted so that the time elapsed for the animation to complete would equal the time specified in the duration property:

```
<Viro3DObject source={require('./res/model.vrx')}
           type="VRX"
           animation={{name:'Take 001',
                      run:true,
                      loop:true,
                      duration:8000,
                      delay:1000}}
/>
```

**Comment by dthian** [comment]
Hey @shaneahern, thanks for filing this feature request! I've created a story capturing this ask on our backlog and we will be actively working on it. Do let us know if you are blocked by / need this feature before a certain date!

**Comment by dam00n** [comment]
This prop has been added in the latest release, ViroReact 2.9

Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

Documentation here -> https://docs.viromedia.com/v2.9.0/docs/viro3dobject#section-optional-props
