### ISSUE TITLE
[Feature Request] Multiple Portal Entrances for One ViroPortalScene

### ISSUE THREAD

**Issue by baiton** [viromedia/viro#371]
I am currently making a building to scale in an ViroPortalScene and was wondering If I could make it so that I had a portal that would take me to the top of the building and another that would take me to the bottom of the building.  In the end I would like to see this become a Shared Experience with ARkit 2.0.  I'll attach a photo illustrating what I am trying to describe this concept.
![multiportal scene](https://user-images.githubusercontent.com/25060891/43344005-4451d51c-91b6-11e8-8b90-fae23946fb12.jpg)

**Comment by baiton** [comment]
In theory I see that one portal element being the "Primary" which sets the base location information and then another portal that works more similar to a normal ViroElement.  I say this because currently the portal entrance is the origin of the ViroPortalScene content.  So the position of my box and all other portal contents will be relative to the Primary Portal.  This "Secondary" portal would need to have attributes for it's position inside and outside of the portal.  The "inside position attribute" would be relative to the original door and the "outside position attribute" would be relative to the launch of the app like all other elements.

Thanks for any attempts that are made!

**Comment by achuvm** [comment]
Hi @baiton,

We don't currently support this out of the box, but there are a few things you can do to emulate this.

The easiest way would be to simply have 2 `ViroPortalScene`s with 2 `ViroPortal`s representing each viewpoint.

If you wanted to create a "shared" experience, then you would simply apply any offsets you want and send them to the other client.

However, this is likely in AR, so it'd be very strange to have 2 people standing next to one another in the real-world but be in different virtual positions. (ie. 2 `ViroPortals` 1 ft apart in the real world, but 10 ft apart in the virtual).

**Comment by baiton** [comment]
I think I see what you are saying so if I say drop a ball in one portal scene then I should just make a similar ball in another portal scene drop at the same time, clever.  I will definitely give that a go.
