### ISSUE TITLE
[Feature Request] APNG support

### ISSUE THREAD

**Issue by Maxence-Machu** [viromedia/viro#374]
Hi everyone, 

Does Viro supports the apng files (Animated PNG) in order to animate a texture ? 

Maxence.

**Comment by dam00n** [comment]
We do not support APNG at this time. We can add it to our backlog. Will leave this issue open and update it when we have more info.

**Comment by vpallegar** [comment]
To followup here - Are there any plans to support APNG in the near future?  I am looking to utilize it to implement sequenced png animations in my AR scene.

**Comment by dam00n** [comment]
Hi @vpallegar we don't have near term plans for APNG support. Is it possible to use animated gif's for your feature instead -> https://docs.viromedia.com/docs/viroanimatedimage
