### ISSUE TITLE
Add external libs

### ISSUE THREAD

**Issue by bendeve** [viromedia/viro#378]
Hello, first thank you for your great work.

I have a working ViroReact project, which I run with the Viro Meia app (npm start).

I'm trying to add a lib (react-native-image-crop-picker) in my project. Then if I try to start my project, I've got an error, link with the new lib seems not to be done. 

Whereas If I launch my project without the Viro Media app but directly on my phone (react-native run-android) the new lib works well ! 

(I have the feeling that the project needs to be recompile, i've tried ./gradlew clean assembleDebug without success)

Am I doing something wrong ? 

Thank you.

**Comment by dam00n** [comment]
Hi @bendeve, what you are experiencing is expected. The Viro Media testbed app has a specific set of libs packaged with it. When you use external libs not included in the testbed app, you will get an error as you experienced. To continue developing with external libs, continue to launch/build your project directly on your phone.
