### ISSUE TITLE
[Question] - Nearest feature point on click?

### ISSUE THREAD

**Issue by markoradak** [viromedia/viro#38]
Using hit tests, is there a way to find a nearest feature point to where user touched the screen, and then attach an object to that point?

**Comment by VikAdvani** [comment]
Hi @markoradak, to clarify, after setting the initial position object , if you set dragType to "FixedToWorld", that **will** let the user drag the object to the nearest feature point. So basically we do support your use case with dragging but not yet tapping.

**Comment by markoradak** [comment]
Hi @VikAdvani, yeah - I got it to work with dragging, but was wondering if tapping is supported as well. Do you want me to leave this issue open for future reference, or you would prefer to close it?

**Comment by VikAdvani** [comment]
Hi @markoradak, leave this issue open for now as we are adding support for tapping. Thanks!
