### ISSUE TITLE
ViroReact 2.9.0 Xcode build failed

### ISSUE THREAD

**Issue by parideis** [viromedia/viro#383]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. OS: Mac
2. Platform: iOS
3. Version: ViroReact version: 2.9.0 and React Native version: 0.55.1 
4. Device(s): iPhone 7s

## Description
After upgrading from ViroReact 2.8.1 to 2.9.0 I get this error while building during link process with Xcode:

> Undefined symbols for architecture arm64:
>   "VROText::VROText(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, VROFontStyle, VROFontWeight, VROVector4f, float, VROTextOuterStroke, int, VROVector4f, float, float, VROTextHorizontalAlignment, VROTextVerticalAlignment, VROLineBreakMode, VROTextClipMode, int, std::__1::shared_ptr<VRODriver>)", referenced from:
>       std::__1::shared_ptr<VROText> std::__1::shared_ptr<VROText>::make_shared<std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, int&, VROFontStyle, VROFontWeight, VROVector4f&, float, VROTextOuterStroke, int, VROVector4f&, float&, float&, VROTextHorizontalAlignment, VROTextVerticalAlignment, VROLineBreakMode, VROTextClipMode, int, std::__1::shared_ptr<VRODriver> >(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&, int&&&, VROFontStyle&&, VROFontWeight&&, VROVector4f&&&, float&&, VROTextOuterStroke&&, int&&, VROVector4f&&&, float&&&, float&&&, VROTextHorizontalAlignment&&, VROTextVerticalAlignment&&, VROLineBreakMode&&, VROTextClipMode&&, int&&, std::__1::shared_ptr<VRODriver>&&) in libViroReact.a(VRTText.o)
>   "VRONodeCamera::setRefNodeToCopyRotation(std::__1::shared_ptr<VRONode>)", referenced from:
>       -[VRTCamera initWithBridge:] in libViroReact.a(VRTCamera.o)
>   "VRONode::setHighAccuracyEvents(bool)", referenced from:
>       -[VRTNode setHighAccuracyEvents:] in libViroReact.a(VRTNode.o)
>   "VROPolygon::createPolygon(std::__1::vector<VROVector3f, std::__1::allocator<VROVector3f> >, std::__1::vector<std::__1::vector<VROVector3f, std::__1::allocator<VROVector3f> >, std::__1::allocator<std::__1::vector<VROVector3f, std::__1::allocator<VROVector3f> > > >, float, float, float, float)", referenced from:
>       -[VRTPolygon updateGeometry] in libViroReact.a(VRTPolygon.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I also did a `Clean Build Folder...`.
After downgrading to ViroReact 2.8.1 the build succeeded.

**Comment by oOMoeOo** [comment]
I'm experiencing the same error:

`
Undefined symbols for architecture x86_64:
  "VRONode::setHighAccuracyGaze(bool)", referenced from:
      -[VRTNode setHighAccuracyGaze:] in libViroReact.a(VRTNode.o)
  "VROText::createText(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, VROFontStyle, VROFontWeight, VROVector4f, float, float, VROTextHorizontalAlignment, VROTextVerticalAlignment, VROLineBreakMode, VROTextClipMode, int, std::__1::shared_ptr<VRODriver>)", referenced from:
      -[VRTText updateLabel] in libViroReact.a(VRTText.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
Any ideas on how to fix this?

**Comment by niallfarrell91** [comment]
Im also seeing this after upgrading. Guess il stick with 2.8.2 for now

**Comment by manbod** [comment]
Hey guys, we just released ViroReact’s new version - `2.9.1`, that addresses the above iOS build issues folks were running into while building simulator / static lib targets. Installation / update instructions here -> https://docs.viromedia.com/docs/releases. `2.9.1` should be back to being stable for various iOS build targets.
