### ISSUE TITLE
Disable ViroButton 

### ISSUE THREAD

**Issue by AntoniaBe** [viromedia/viro#384]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. OS: Windows
2. Platform: Android 
3. Version: ViroReact version: 2.9.0 , React Native version: 0.55.1 
4. Device(s): Samsung Galaxy S8

## Description
Hi all,
is it possible to disable the ViroButton component when I touched it? I cant find anything in the docs. 
thanks!

**Comment by manbod** [comment]
Hi @AntoniaBe ,
Not entirely sure about your use case, but depending on your expected UX for *disabling* a `ViroButton` you'll have to rely on a combination of following:
1. Implement an `_onClickState` function and pass that to the `ViroButton`'s `onClickState` prop. Set state in your `_onClickState` function that sets your ViroButton to render as disabled, as per expected UX behavior.
```javascript
_onClickState(stateValue, position, source)  {
    if(stateValue == 3) {
        // Clicked, set your state here
    }
}
```
2. Implement logic to change the `ViroButton` image source to be `disabled` upon setting state above.

Docs -> https://docs.viromedia.com/docs/virobutton . There's no out-of-box method to disable a ViroButton at the moment.

Hope this helps.
Thanks!
