### ISSUE TITLE
ViroText positioning in ViroFlexView 

### ISSUE THREAD

**Issue by bendeve** [viromedia/viro#385]
Hello,

I am currently trying to do this very simple interface with ViroFlexBox : 

img|text
text

This is my code : 

```
<ViroFlexView 
	height={500}
	width={1000}
	position={[-2500,0,-2500]}
	transformBehaviors={["billboard"]}
	backgroundColor={'red'}
	key={element[0]}
>
	<ViroFlexView backgroundColor={'green'} style={{flex:0.2,flexDirection: 'row'}} >
		<ViroFlexView backgroundColor={'white'} style={{flex:0.1}} >
			<ViroImage style={{flex:1}} source={icon} />
		</ViroFlexView>
		<ViroFlexView backgroundColor={'yellow'} style={{flex:0.9,flexDirection: 'row'}} >
			...
		</ViroFlexView>
	</ViroFlexView>
	<ViroFlexView backgroundColor={'grey'} style={{flex:0.8,flexDirection: 'row'}} >
		<ViroText	 //<========== positioning  this one			
			text={'Hello'} 
			style={{textAlignVertical: 'center', textAlign: 'center', color: '#ff0000', flex:1}}
			scale={[80, 80, 80]}
			fontSize={100}
			/>
		</ViroFlexView>
	</ViroFlexView>
</ViroFlexView>
```

Each block is well placed, but I have a problem with the text (look at **positioning  this one** in code). My text is positioned in the grey box only when it is ventically and horizontally centred (like in my example). I mean the start of my ViroText is totally out of his parent's box. 
Actually what I expected is : no need to add textAlignVertical: 'center', textAlign: 'center' and the text starts top left of his parent's grey ViroFlexView. 

Am I doing something wrong ?

**Comment by VikAdvani** [comment]
Hi @bendeve, 
This appears to be a bug with ViroText within flex views. We've reproduced the issue and will look into providing a fix. When a fix is available, I'll update the issue here. Thanks for finding this 👍

**Comment by VikAdvani** [comment]
Hi @bendeve,
I figured out the issue. The following code will work as expected:
```
        <ViroFlexView
	         height={2.5}
	         width={5}
	         position={[0,0,-10]}
	         transformBehaviors={["billboard"]}
	         backgroundColor={'red'}>
        	<ViroFlexView backgroundColor={'green'} style={{flex:0.2,flexDirection: 'row'}} >
          		<ViroFlexView backgroundColor={'white'} style={{flex:0.1}} >
          			<ViroImage style={{flex:1}} source={require('./res/poi_dot.png')} />
          		</ViroFlexView>
          		<ViroFlexView backgroundColor={'yellow'} style={{flex:0.9,flexDirection: 'row'}} >
          		</ViroFlexView>
        	</ViroFlexView>
        	<ViroFlexView backgroundColor={'grey'} style={{flex:0.8,flexDirection: 'row'}} >
        		<ViroText
              style={{color: '#ff0000', flex:1}}
        			text={'Hello'}
        			fontSize={30} />
        	</ViroFlexView>
        </ViroFlexView>
```

The issue with the flexview that you are currently using is the following:
1) The height and width are 500 and 1000 and the position is -2500. These parameters are in meters so this makes the flexview huge while pushing the flexview very very far away. As you can see in my example I made the flexview 2.5x5 meters and it positioned 10 meters away. 

2) Because of this in your text you scale up the text by 80x so the text is visible. This makes the overall text area scale up way beyond the flexview container. As a result, the text is positioned way above the flexview with the default alignment parameters. One guideline is to never use scale or position parameters within a flexview container as the flex parameters will scale the object itself. 

To fix the the issues above I simply 1)moved the entire flexview closer and scaled down its width and height and 2)scaled the text up by using font size instead of the scale parameter.

Now if you try the the different alignment parameters they should work as expected. 

Hope that helps, if you have any other questions let us know. Thanks.

**Comment by bendeve** [comment]
Hi VikAdvani,
Thank you for your analysis. 
If my ViroFlexView is so far away it's because it represents a mountain peak. So I really need to keep this values. 
So, because I can't move the entire flexbox closer, I have to increase the fontSize again. But a too large fontSize use a lot processor/memory I think. If I remember I had tested a very large fontSize but the application didn't launch at all.

**Comment by VikAdvani** [comment]
What you can do is perhaps the following:
```
<ViroNode position={[-2500,0,-2500]} transformBehaviors={["billboard"]} scale={[200, 200, 200]} >
<ViroFlexView
	         height={2.5}
	         width={5}
	         position={[0,0,0]}
	         backgroundColor={'red'}>
        	<ViroFlexView backgroundColor={'green'} style={{flex:0.2,flexDirection: 'row'}} >
          		<ViroFlexView backgroundColor={'white'} style={{flex:0.1}} >
          			<ViroImage style={{flex:1}} source={require('./res/poi_dot.png')} />
          		</ViroFlexView>
          		<ViroFlexView backgroundColor={'yellow'} style={{flex:0.9,flexDirection: 'row'}} >
          		</ViroFlexView>
        	</ViroFlexView>
        	<ViroFlexView backgroundColor={'grey'} style={{flex:0.8,flexDirection: 'row'}} >
        		<ViroText
              style={{color: '#ff0000', flex:1}}
        			text={'Hello'}
        			fontSize={30} />
        	</ViroFlexView>
        </ViroFlexView>
</ViroNode>
```

What I do above is I keep the flexview the same when laying it out and wrap it in a containing node. I scale up the containing node by 200x. This will scale up your flexview and everything inside it, hopefully making your font visible. Try this and see what results you get :)

**Comment by bendeve** [comment]
It seems to be working. Thank you :)

**Comment by krishanjangir** [comment]
@VikAdvani @ViroHalliday 


Actually my fonts are not working fine, if i am changing font size and flex it goes disappear.
Also please help me to set image round (Border Radius)

Actula result

![1538209511850](https://user-images.githubusercontent.com/24914330/46243256-dbfa1580-c3ef-11e8-944e-142ed376521e.png)

Expecting

![screenshot_20180928-090453](https://user-images.githubusercontent.com/24914330/46243401-858dd680-c3f1-11e8-9e82-dbb253f1e263.png)



  <ViroFlexView position={[0, -1, -1.5]} backgroundColor={'purple'} onClick={this._onClick(item)} >

          {item.m_file != '' ?
            <ViroFlexView width={0.7} height={1} backgroundColor={'pink'} style={{ flexDirection: 'column' }} >
              <ViroFlexView backgroundColor={'pink'} style={{ flex: 0.2, flexDirection: 'row' }} >
                <ViroFlexView backgroundColor={'white'} style={{ flex: 0.2 }} >
                  <ViroImage borderRadius={30} style={{ flex: 1 }} source={{ uri: item.u_avatar }} />
                </ViroFlexView>
                <ViroFlexView backgroundColor={'grey'} style={{ flex: 0.2, flexDirection: 'column' }} >
                  <ViroText
                    style={{ flex: 1, color: 'purple' }}
                    text={item.u_name}
                    fontSize={9} />
                  <ViroText
                    backgroundColor={'pink'}
                    style={{ flex: 1, color: 'purple' }}
                    text={item.u_username}
                    fontSize={9} />
                </ViroFlexView>
              </ViroFlexView>
               <ViroFlexView backgroundColor={'white'} style={{ flex: 0.7 }} >
                  <ViroImage borderRadius={30} style={{ flex: 1 }} source={{ uri: item.m_file }} />
                </ViroFlexView> 
              <ViroFlexView backgroundColor={'green'} style={{ flex: 0.1, flexDirection: 'column' }} >
                <ViroText
                  backgroundColor={'pink'}
                  style={{ flex: 1, color: 'purple' }}
                  text={item.m_message}
                  fontSize={9} />
              </ViroFlexView>
            </ViroFlexView>

            : 
          <ViroFlexView width={0.7} height={0.8} backgroundColor={'pink'} style={{ flexDirection: 'column' }} >
              <ViroFlexView backgroundColor={'pink'} style={{ flex: 0.2, flexDirection: 'row' }} >
                  <ViroImage borderRadius={30} style={{ flex: 1 }} source={{ uri: item.u_avatar }} />
            </ViroFlexView>
          }

        </ViroFlexView>

**Comment by VikAdvani** [comment]
Hi @krishanjangir, 
I reworked your flexview a little bit to get it closer to what you want, I fixed some flex view widths, increased the font size, added some margin padding, and scaled the overall width and height of the flexview up. 

 In order to add a border radius to the flexview, you can try to set a rounded corner image as a material on the ViroFlexView itself.(ie, <ViroFlexView materials="bg">) where materials would look like :
```
ViroMaterials.createMaterials({
  bg: {
    diffuseTexture: require('./res/rounded_corner_bg.jpg')
  },
```

The reworked flexview is below:
```
<ViroFlexView width={2.1} position={[0,0,-4]} height={3} backgroundColor={'pink'} style={{ flexDirection: 'column' }} >
       <ViroFlexView backgroundColor={'pink'} style={{ flex: 0.2, flexDirection: 'row' }} >
             <ViroFlexView backgroundColor={'white'} style={{ flex: 0.2 }} >
                 <ViroImage borderRadius={30} style={{ flex: 1 }} source={{ uri: "https://lh3.googleusercontent.com/dB3Dvgf3VIglusoGJAfpNUAANhTXW8K9mvIsiIPkhJUAbAKGKJcEMPTf0mkSexzLM5o=w300" }} />
             </ViroFlexView>
             <ViroFlexView backgroundColor={'grey'} style={{ flex: 0.8, flexDirection: 'column' }} >
                 <ViroText
                 style={{ flex: 0.5, color: 'purple',  marginLeft: .1, }}
                 text={"Vik"}
                 fontSize={12} />
                 <ViroText
                 backgroundColor={'pink'}
                 style={{ flex: 0.5, color: 'purple',  marginLeft: .1, }}
                 text={"UserName00"}
                 fontSize={12} />
             </ViroFlexView>
       </ViroFlexView>
            <ViroFlexView backgroundColor={'white'} style={{ flex: 0.6 }} >
                <ViroImage borderRadius={30} style={{ flex: 1 }} source={{ uri: "https://lh3.googleusercontent.com/dB3Dvgf3VIglusoGJAfpNUAANhTXW8K9mvIsiIPkhJUAbAKGKJcEMPTf0mkSexzLM5o=w300" }} />
             </ViroFlexView>
           <ViroFlexView backgroundColor={'green'} style={{ flex: 0.3, flexDirection: 'column' }} >
               <ViroText
               backgroundColor={'pink'}
               style={{ flex: 1, color: 'purple', marginLeft:.2 }}
               text={"The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog."}
               fontSize={12} />
           </ViroFlexView>
</ViroFlexView>
```
Below is how it looks:
![flexview_example](https://user-images.githubusercontent.com/14915233/46315667-e3055d00-c582-11e8-9a9e-bb176e848c4a.jpg)

**Comment by krishanjangir** [comment]
> Hi @krishanjangir,
> I reworked your flexview a little bit to get it closer to what you want, I fixed some flex view widths, increased the font size, added some margin padding, and scaled the overall width and height of the flexview up.
> 
> In order to add a border radius to the flexview, you can try to set a rounded corner image as a material on the ViroFlexView itself.(ie, ) where materials would look like :
> 
> ```
> ViroMaterials.createMaterials({
>   bg: {
>     diffuseTexture: require('./res/rounded_corner_bg.jpg')
>   },
> ```
> The reworked flexview is below:
> 
> ```
> <ViroFlexView width={2.1} position={[0,0,-4]} height={3} backgroundColor={'pink'} style={{ flexDirection: 'column' }} >
>        <ViroFlexView backgroundColor={'pink'} style={{ flex: 0.2, flexDirection: 'row' }} >
>              <ViroFlexView backgroundColor={'white'} style={{ flex: 0.2 }} >
>                  <ViroImage borderRadius={30} style={{ flex: 1 }} source={{ uri: "https://lh3.googleusercontent.com/dB3Dvgf3VIglusoGJAfpNUAANhTXW8K9mvIsiIPkhJUAbAKGKJcEMPTf0mkSexzLM5o=w300" }} />
>              </ViroFlexView>
>              <ViroFlexView backgroundColor={'grey'} style={{ flex: 0.8, flexDirection: 'column' }} >
>                  <ViroText
>                  style={{ flex: 0.5, color: 'purple',  marginLeft: .1, }}
>                  text={"Vik"}
>                  fontSize={12} />
>                  <ViroText
>                  backgroundColor={'pink'}
>                  style={{ flex: 0.5, color: 'purple',  marginLeft: .1, }}
>                  text={"UserName00"}
>                  fontSize={12} />
>              </ViroFlexView>
>        </ViroFlexView>
>             <ViroFlexView backgroundColor={'white'} style={{ flex: 0.6 }} >
>                 <ViroImage borderRadius={30} style={{ flex: 1 }} source={{ uri: "https://lh3.googleusercontent.com/dB3Dvgf3VIglusoGJAfpNUAANhTXW8K9mvIsiIPkhJUAbAKGKJcEMPTf0mkSexzLM5o=w300" }} />
>              </ViroFlexView>
>            <ViroFlexView backgroundColor={'green'} style={{ flex: 0.3, flexDirection: 'column' }} >
>                <ViroText
>                backgroundColor={'pink'}
>                style={{ flex: 1, color: 'purple', marginLeft:.2 }}
>                text={"The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog."}
>                fontSize={12} />
>            </ViroFlexView>
> </ViroFlexView>
> ```
> Below is how it looks:
> ![flexview_example](https://user-images.githubusercontent.com/14915233/46315667-e3055d00-c582-11e8-9a9e-bb176e848c4a.jpg)

@VikAdvani  Thanks, Actually i suggest the VIRO to my client and now i can it was my good decision. My application is working awesome.

Thanks @VikAdvani  , Thanks a lot.

**Comment by krishanjangir** [comment]
@VikAdvani 

i am not able to found
   borderRadius={30} in viroimage props

https://docs.viromedia.com/docs/viroimage

I am not able to set corner radius of images.

And i can see your images are already with corner radius.

https://lh3.googleusercontent.com/dB3Dvgf3VIglusoGJAfpNUAANhTXW8K9mvIsiIPkhJUAbAKGKJcEMPTf0mkSexzLM5o=w300

Please see this, i need to set corner radius of ViroFLexView and Images both.

**Comment by krishanjangir** [comment]
@VikAdvani 

Thanks, Thanks a lot.
I am able to set BG corner radius image.

But there is no way to set round image of user's profile pic.

Is there any way to set position ='absolute' (Like react native) component.
So that i can set use's (Square pic) and then my own rounded pic on that.

![1538727934202](https://user-images.githubusercontent.com/24914330/46524647-1ad41380-c8a7-11e8-877e-88be545bdb62.png)


See in above image can i put circle(Just left to k@k.com) on top of users profile pic.

**Comment by krishanjangir** [comment]
@VikAdvani 

Friend i am able to make the design using  'materials' now i am setting users image in 'materials' and putting white transparent circle image on that.

But in this way i am not able to make the white BG transparent...
![2a03939a-18f3-4012-b4fe-3707c69ccd05](https://user-images.githubusercontent.com/24914330/46726086-32dad700-cc9b-11e8-99e5-1118e6a8e568.jpg)

    ViroMaterials.createMaterials({
        circle: {
          diffuseTexture: { uri: item.u_avatar }
        }
      })

<ViroFlexView position={[x, 0, -5]} width={2.7} height={hgt} onClick={this._onClick(item)} >

          {item.m_file != '' ?

            <ViroFlexView materials="bg" style={{ flex: 1, flexDirection: 'column', backgroundColor: 'transparent' }} >
              <ViroFlexView style={{ flex: 0.17, marginLeft: 60, flexDirection: 'row' }} >

                <ViroFlexView width={.50} height={.50} materials='circle' style={{ marginLeft: 40, marginTop: 35, marginBottom: 10 }} >
                  <ViroImage width={.51} height={.51} source={border_circle_area} />
                </ViroFlexView>

                <ViroFlexView style={{ marginLeft: 60, marginTop: 30, flex: 0.7, flexDirection: 'column' }} >

                  <ViroText
                    text={item.u_name}
                    textAlign="left"
                    textAlignVertical="bottom"
                    textLineBreakMode="justify"
                    textClipMode="clipToBounds"
                    width={1} height={.17}
                    style={{ marginTop: 15, fontFamily: font.robotoregular, color: colors.blackc }}
                    fontSize={fontsize}
                  />
                  <ViroText
                    text={item.u_username}
                    textAlign="left"
                    textAlignVertical="top"
                    textLineBreakMode="justify"
                    textClipMode="clipToBounds"
                    width={1} height={.8}
                    style={{ marginTop: 5, paddingTop: 3, fontFamily: font.robotoregular, color: colors.blackc }}
                    fontSize={fontsize}
                  />
                </ViroFlexView>
              </ViroFlexView>
              {/* // resizeMode: PropTypes.oneOf(['ScaleToFill','ScaleToFit','StretchToFill']), */}
              <ViroImage resizeMode='StretchToFill' position={[0, 0, 0]} style={{ flex: 0.7 }}
                source={{ uri: item.m_thumbnail }} />
              <ViroText
                style={{ flex: 0.15, marginLeft: 40, marginTop: 10, fontFamily: font.robotoregular, color: colors.blackc }}
                text={item.m_message}
                extrusionDepth={0}

                fontSize={fontsize} />
              <ViroText
                style={{ flex: 0.06, marginLeft: 40, fontFamily: font.robotoregular, color: colors.blackc }}
                text={item.m_created}
                extrusionDepth={0}
                textAlign='left'
                textAlignVertical='top'
                fontSize={fontsizeDate} />
            </ViroFlexView>



I am trying to found some solution, if you found some easy solution please reply.


Thanks

**Comment by VikAdvani** [comment]
Hi @krishanjangir,
If you use a background image with an alpha channel that should work. So the transparency will be baked into the background image itself, like the rounded corners.

**Comment by krishanjangir** [comment]
@VikAdvani 

 I am creating multiple AR mesages and i need to show user profile on top but need to make it round so i am putting white blank as circle from center on top of user image.

 But in my case ViroMaterials are not updating according for loop.You can view complete code in renderAndroid method in below class.
https://drive.google.com/file/d/1bZwbSomEcf4BdTHL52fS90T_SH4dLtWa/view?usp=sharing

I have tried to deleteMaterials but it's not working.

In the attached screen shot the right message is from other user and this user's profile pic should be updated but it's not happening.
Left user is k1@k.com and his profile pic is fine but the right user is k@k.com his profile pic should be other but it's showing the first time ViroMaterials for all other user in loop.

     return this.props.arSceneNavigator.viroAppProps.initialArr.map((item) => {


     // ViroMaterials.deleteMaterials(['circle'])
      var point = this._transformPointToAR(item.m_lat, item.m_lng);
      ViroMaterials.createMaterials({
        'circle': {
          diffuseTexture: item.u_avatar == '' ? img_profile : { uri: item.u_avatar }
        }
      })

     return (
        <ViroFlexView transformBehaviors={["billboard"]} position={[x, y, z]} width={2.5} height={hgt}
          onClick={this._onClick(item)}
          onHover={(isHovering, position, source) => { this._onHover(isHovering, position, source, item) }}
        >
            <ViroFlexView materials="bg" style={{ flex: 1, flexDirection: 'column', backgroundColor: 'transparent' }} >
              <ViroFlexView style={{ flex: 0.22, marginLeft: 60, flexDirection: 'row' }} >
                   <ViroFlexView width={.43} height={.43} materials='circle'
                         style={{ marginLeft: 40, marginTop: 35, marginBottom: 10 }} >
                    <ViroImage width={.43} height={.43} source={border_circle_area} />
                   </ViroFlexView>
              </ViroFlexView>
            </ViroFlexView>
       </ViroFlexView>
    )
    }

![ebc7184b-c999-401b-bf52-de7bf8dbd76c](https://user-images.githubusercontent.com/24914330/49575944-fe695b80-f969-11e8-9d1e-fe6995db77c8.jpg)
