### ISSUE TITLE
Cannot install Cocoapods for Viro

### ISSUE THREAD

**Issue by alexborton** [viromedia/viro#386]
## Environment
1. OS: Mac
2. Platform: iOS
3. Version: ViroReact version 2.9 and React Native 0.55.3 
4. Device(s): NA

## Description
I've tried installing the Viro via the static instructions [here](https://docs.viromedia.com/docs/no_use_frameworks) (my current app does not use `use_frameworks!`). When i try to pod install, i get the following error;

```
CocoaPods could not find compatible versions for pod "ViroKit_static_lib":
  In Podfile:
    ViroKit_static_lib (from `../node_modules/react-viro/ios/dist/ViroRenderer/static_lib`)

Specs satisfying the `ViroKit_static_lib (from `../node_modules/react-viro/ios/dist/ViroRenderer/static_lib`)` dependency were found, but they required a higher minimum deployment target.
```

I have node_modules installed and checked the path - it exists ;)

**Comment by alexborton** [comment]
30 seconds after posting, i realised that my `platform :ios` was at 8.0

I checked in the podspec and realised the Viro is at 9.3

It might be worth adding that to your docs 👍 

`platform :ios, '9.3'`

**Comment by manbod** [comment]
Glad you got it working! Will update our docs mention `platform :ios, '9.3'` 👍

**Comment by manbod** [comment]
Also, FYI - we had reports of the `ViroKit_static_lib` failing to build on v`2.9.0`, from other devs. We just released a new version `2.9.1` addressing those issues. Recommend updating your project to the new version

**Comment by alexborton** [comment]
Thank you for the feedback - I have actually been having a number of issues. I reverted back to 2.8.1 as that was mentioned to be more stable. I won't list the issues in here as i don't want to ramble. I'll open new issues if/when i reach a dead end :)

**Comment by ckOfor** [comment]
What's the solution to this ?

**Comment by gHashTag** [comment]
@ckOfor 
platform :ios, '9.3'
