### ISSUE TITLE
[Question] - Plane styling

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#39]
First of all, well done with the lib. The docs are very comprehensive.

I have a question regarding the `ViroARPlaneSelector`. Is there a way to style (assign color, opacity or image overlay) the `ViroARPlane`?

Thank you in advance.

Cheers,
Tom

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

Glad you found the docs helpful.

Currently the `ViroARPlaneSelector` doesn't allow you to modify it, **but** it is actually a wholly React-Native component so you can copy the component into your project and modify it to your liking.

You can find the file at `<project_root>/node_modules/react-viro/components/AR/ViroARPlaneSelector.js`.

We may add the ability to change these properties in a future release w/o modifying the source itself.

Let us know if you need any help with that!

**Comment by dittmarconsulting** [comment]
That's cool @achuvm.

I'm going to copy the source code to my project and use the new component in my project. I'll let you know how I go. I probably won't have time to PR tough.
