### ISSUE TITLE
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native/Libraries/StyleSheet/normalizeColor` from `/Volumes/WORK/react-native-app/node_modules/antd-mobile-rn/lib/segmented-control/segmented.android.js`: Module `react-native/Libraries/StyleSheet/normalizeColor` does not exist in the Haste module map 

### ISSUE THREAD

**Issue by crimsonsuv** [viromedia/viro#390]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native/Libraries/StyleSheet/normalizeColor` from `/Volumes/WORK/react-native-app/node_modules/antd-mobile-rn/lib/segmented-control/segmented.android.js`: Module `react-native/Libraries/StyleSheet/normalizeColor` does not exist in the Haste module map 

System: Mac OS

**Comment by dam00n** [comment]
This might be a React Native issue. See this thread for possible solution -> https://github.com/ant-design/ant-design-mobile-rn/issues/56

**Comment by WillyRamirez** [comment]
I think this is caused because ViroReact is not yet compatible with the latest version of react-native, in which they moved this file

**Comment by dam00n** [comment]
Thanks for the heads up @WillyRamirez. Were you able to resolve this by downgrading to RN v0.55.1 or moving the file in later versions?

@crimsonsuv what version of RN are you using? ViroReact has been tested and compatible with React Native v0.55.1

**Comment by WillyRamirez** [comment]
@dam00n yes I got it working on 0.55.1, however, that was a very bad version of RN, with a lot of "deprecated" warnings. I'll look a little deeper into it tomorrow and see if I can find an easy fix for it to work on 0.57.0. I'll keep you posted if I find something.

**Comment by WillyRamirez** [comment]
@krishanjangir  no, because [this guy](https://github.com/viromedia/viro/issues/412#issuecomment-422481825) beat me to it:
https://github.com/viromedia/viro/issues/412#issuecomment-422481825
