### ISSUE TITLE
Flipping vrModeEnabled flag causes crash.

### ISSUE THREAD

**Issue by VikAdvani** [viromedia/viro#394]
A crash occurs when switching from 360 mode to VR on Android and iOS using the vrModeEnabled flag in the VR Scene Navigator.

**Comment by VikAdvani** [comment]
Current workaround is to exit the navigator and launch again into the navigator with a new flag value.

**Comment by nushydude** [comment]
@VikAdvani 
by **exit the navigator**, do you mean unmount the component it? 

either way, any suggestions on how to retain the scene orientation when swapping between VR and 360 to give a seamless switching experience?

**Comment by VikAdvani** [comment]
Hi @nushydude,
>by exit the navigator, do you mean unmount the VRSceneNavigator component?

Yep, unmount then mount again with the changed flag.

>either way, any suggestions on how to retain the scene orientation when swapping between VR and 360 to give a seamless switching experience?

You can retrieve the forward and rotation vector of the camera on exit and then enter back into the scene and reset the camera to those stored values. 

This can be achieved by invoking getCameraOrientationAsync() on ViroScene(https://docs.viromedia.com/docs/viroscene) before exiting, storing those values, and then on scene start using a ViroCamera component to set the position and orientation of the stored camera values.

**Comment by nushydude** [comment]
@VikAdvani Thanks a bunch. I'll give it a shot.
