### ISSUE TITLE
app crash after build upload 

### ISSUE THREAD

**Issue by hiteshagja** [viromedia/viro#397]
when I'm uploading my build for testing it successfully uploaded but when I open the app the app crashed everytime,and when I'm integrating react-viro in my existing app it gives error like invalid binary so please help in this 
im using latest version of react-viro
    "react": "16.3.1",
    "react-native": "0.55.1",
    "react-viro": "^2.9.1"

**Comment by manbod** [comment]
Hi @hiteshagja ,
Thanks for reaching out to us. We would need a little more info to be able to look into this. Please fill in details for everything in the checklist below so we know what environment you are running. Also, getting a crash log from your device when the app crashes would be helpful. 


  - [ ] Review the documentation: https://docs.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/viro
  - [ ] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac, Windows, Linux
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on?
3. Version: ViroReact version and React Native version 
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.
