### ISSUE TITLE
Unable to load .MTL file in Viro3DObject materials

### ISSUE THREAD

**Issue by alexborton** [viromedia/viro#398]
## Environment
1. Development OS: Mac
2. Device OS & Version: iOS 6 plus, 11.4.1
3. Version: Viro v2.9.1 react-native 0.55.3

## Description
I have a working prototype of Viro3DObject using my own .OBJ. To get the prototype working, i setup a simple material to colour it. 

When i try to use the .MTL file that shipped with the OBJ, the app crashes as soon as i place the object in space (selectable plane). It gives an error about `JSON value 'xx' of type NSNumber cannot be converted to NSString`

![image from ios](https://user-images.githubusercontent.com/1439507/44540433-b0a04e80-a6fe-11e8-99d5-576e92d00263.png)

This is what my code looks like within my AR screen;

```
      <ViroARScene onTrackingUpdated={this.onInitialized} >
        <ViroAmbientLight color="#ffffff" />
        <ViroARPlaneSelector minHeight={.1} minWidth={.1}>
          <Viro3DObject
            position={[0,0.01,0]}
            scale={[.0007,.0007,.0007]}
            source={testObj}
            materials={[require('./test.mtl')]}
            type="OBJ"
          />
        </ViroARPlaneSelector>
      </ViroARScene>
```

The .MTL file that is being required looks like this;

```
# 3ds Max Wavefront OBJ Exporter v0.97b - (c)2007 guruware
# File Created: 16.08.2018 09:21:04

newmtl wire_177028149
	Ns 32
	d 1
	Tr 0
	Tf 1 1 1
	illum 2
	Ka 0.694118 0.109804 0.584314
	Kd 0.694118 0.109804 0.584314
	Ks 0.350000 0.350000 0.350000

newmtl wire_134110008
	Ns 32
	d 1
	Tr 0
	Tf 1 1 1
	illum 2
	Ka 0.525490 0.431373 0.031373
	Kd 0.525490 0.431373 0.031373
	Ks 0.350000 0.350000 0.350000

newmtl wire_224086086
	Ns 32
	d 1
	Tr 0
	Tf 1 1 1
	illum 2
	Ka 0.878431 0.337255 0.337255
	Kd 0.878431 0.337255 0.337255
	Ks 0.350000 0.350000 0.350000

newmtl wire_225198087
	Ns 32
	d 1
	Tr 0
	Tf 1 1 1
	illum 2
	Ka 0.882353 0.776471 0.341176
	Kd 0.882353 0.776471 0.341176
	Ks 0.350000 0.350000 0.350000

newmtl wire_134006006
	Ns 32
	d 1
	Tr 0
	Tf 1 1 1
	illum 2
	Ka 0.525490 0.023529 0.023529
	Kd 0.525490 0.023529 0.023529
	Ks 0.350000 0.350000 0.350000
```

As you can see, this is a generated file and not knowing much about MTL/OBJ i wouldn't know how to debug it.

**Comment by dam00n** [comment]
Hi @alexborton can you send us the model via email -> support@viromedia.com so we can look at the model ourselves.

Also, do you have the value anywhere else in your code? It is possible this is not a model issue based on the error that was returned.

**Comment by alexborton** [comment]
@dam00n unfortunately I can’t share the object as it’s not my property :( 

Is there anything else you can suggest in the way of debugging this issue?

That value that it references does not appear anywhere else in the code. It doesn’t even seem to appear in the MTL file. But I can say with 98% certainty that the issue only arises when the mtl file is referenced in the object. Otherwise, the object appears exactly as you would expect it.

**Comment by tetreault** [comment]
@dam00n I'm having a similar issue, except Viro is just crashing on my end with a 3d model I bought on TurboSquid. 

Here's the StackTrace: 

``` 
[73590:0x103000600]    21027 ms: Mark-sweep 929.8 (1048.9) -> 929.8 (1000.4) MB, 100.7 / 0.0 ms  (average mu = 0.887, current mu = 0.001) last resort GC in old space requested
[73590:0x103000600]    21140 ms: Mark-sweep 929.8 (1000.4) -> 929.8 (986.9) MB, 113.4 / 0.0 ms  (average mu = 0.772, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x292dc05041bd]
Security context: 0x2243cb51e589 <JSObject>
    1: _send [0x224305231139] [internal/child_process.js:715] [bytecode=0x22430522ca39 offset=606](this=0x224323ce0371 <ChildProcess map = 0x22434760d469>,message=0x224339e57f21 <JSArray[4]>,handle=0x2243b2b022e1 <undefined>,options=0x2243ffe3e109 <Object map = 0x22434760d9e9>,callback=0x2243b2b022e1 <undefined>)
    2: send [0x2243052310e1] [internal/child_...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 2: node::OnFatalError(char const*, char const*) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 4: v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 5: v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 6: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 7: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 8: v8::String::Utf8Length() const [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
 9: node::StringBytes::Size(v8::Isolate*, v8::Local<v8::Value>, node::encoding) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
10: int node::StreamBase::WriteString<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
11: void node::StreamBase::JSMethod<node::LibuvStreamWrap, &(int node::StreamBase::WriteString<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&))>(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
12: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
13: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
14: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/stephentetreault/.nvm/versions/node/v10.4.0/bin/node]
15: 0x292dc05041bd
16: 0x292dc0513429
17: 0x292dc0513429
18: 0x292dc050c223
Abort trap: 6
```

I can send you the model at that same email if that is okay.

**Comment by dam00n** [comment]
Sure, send the model to support@viromedia.com

Our 3D modeler is out this week, so if it is a problem with the model itself he will take a look next week.

**Comment by tetreault** [comment]
done thx for the fast reply @dam00n !

**Comment by dam00n** [comment]
Just taking a quick look and a couple of the materials are very large in size. Consider shrinking them as they don't appear to need to be >50MB. Attached a couple downsized ones I did using Preview on Mac
![bottle_reflection](https://user-images.githubusercontent.com/450239/48085507-50726200-e1af-11e8-81d7-374a6cf43103.png)
![plastic_bump](https://user-images.githubusercontent.com/450239/48085509-52d4bc00-e1af-11e8-990f-c873e9da769c.png)

**Comment by tetreault** [comment]
I too noticed one PNG was massive, which probably explains why there was a crash? I've also been looking through prior github issues on viro 3d objects to see if im missing anything. 

One thing to note, If i convert the FBX file for this i have to VRX it just shows essentially a sort of 2d polygon sphere. If i try this the OBJ way, it doesn't load anything except two circles of color. I can provide some screenshots shortly and will also try these new files you provided. Thanks again for the assistance @dam00n !

**Comment by tetreault** [comment]
This is what I see when trying to load the VRX file. It occurs with the original large PNGs and also the reduced size PNGs you sent over. 

![image from ios](https://user-images.githubusercontent.com/5934354/48085807-4f4e2e80-e1c9-11e8-889c-7b3dc59f609c.png)

**Comment by dam00n** [comment]
I was able to get the bottle to appear. Pasted my code below for the Viro3DObject component and the ViroMaterials.

![img_1621](https://user-images.githubusercontent.com/450239/48087461-371fe480-e1b4-11e8-91fb-3e0ff8af7db9.jpg)

<Viro3DObject
              source={require('./res/bottle/Metal_Bottle_With_Sprayer_Cap_Generic.vrx')}
              scale={[.03, .03, .03]}
              position={[0, 0, -2]}
              type="VRX"
              materials="bottle"
              />

ViroMaterials.createMaterials({
                bottle: {
                  lightingModel: "Lambert",
                  diffuseTexture: require('./res/bottle/bottle_diffuse.png'),
                  normalTexture: require('./res/bottle/bottle_reflection.png'),
                  roughnessTexture: require('./res/bottle/plastic_bump.png'),
                },
              });

**Comment by tetreault** [comment]
amazing, thanks @dam00n. Apologies i'm a super noob at AR/3D stuff so I completely missed the `ViroMaterials.createMaterials({})` part because it wasn't in the doc: https://docs.viromedia.com/v2.11.0/docs/3d-objects

Looking forwarf to messing with this more now, thanks so much!

**Comment by dam00n** [comment]
No problem. 3D stuff gets easier as you try it more. Here is a link to our guide on materials -> https://docs.viromedia.com/docs/3d-scene-lighting#materials
