### ISSUE TITLE
ViroSpinner w/Viro360Video

### ISSUE THREAD

**Issue by atlance01** [viromedia/viro#4]
With the 360Video, there are only a few callbacks. I really wanna use the ViroSpinner, to showing that the video is loading when changing scenes but there's not a callback method that seems to be very useful. For instance, the Viro360Image has callbacks for onLoadStart and onLoadHide. Unless there's another way you'd suggest hiding the Spinner once the video begins to play?

Thanks!

**Comment by radvani** [comment]
Hi! For the time being, you can try using the onUpdateTime callback on Viro360Video. This callback is invoked each time the video progresses one second. You can use it to hide your spinner when the video playback reaches 1 second in. Let us know if this works for you; we'll evaluate adding some more callbacks to make this easier.

**Comment by atlance01** [comment]
@radvani 
This worked pretty well - I ended up having to put a delay timer on the Update callback because it was still being called immediately. Thanks!
