### ISSUE TITLE
[Question] - rawFeaturePoints

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#40]
Hi there,

Is there a way to display the raw feature point clouds as described [here](https://developer.apple.com/documentation/arkit/arframe/2887449-rawfeaturepoints)

The reason why these points might be useful is when `ViroARPlaneSelector` can NOT detect a `ViroARPlane` because the internal method to detect a plane from the amount of points might have a certain threshold. It would be great to loop over these points to lower the threshold for plane detection.

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

Unfortunately we don't expose this functionality right now in our API.

You can consider using the `performARHitTestWithRay|Position` that we have in `ViroARScene` here: http://docs.viromedia.com/v2.0.0/docs/viroarscene#methods

That'll return you a list of detected points along the ray from the camera which you can then filter. An example of this can be found in our ARHitTestExample here: https://github.com/viromedia/ViroARSampleApp/blob/master/js/ARHitTestSample.js#L163

This is something that we do want to expose in the future though.

Let us know if you have any other questions!

**Comment by dittmarconsulting** [comment]
Hi @achuvm,

Again, thanks for the super fast reply.

I'll also try this solution and report back to you.

Cheers,
Tom

**Comment by dittmarconsulting** [comment]
@achuvm,

That works beautifully.
