### ISSUE TITLE
Sample Project Error - No propType for native prop

### ISSUE THREAD

**Issue by dcdrg** [viromedia/viro#404]
Tried to run the sample project from https://docs.viromedia.com/docs/quick-start

When opening it in Testbed on an Android 7.0 device and choosing VR I get a red error screen with the following:

`Error: 'ViroText' has no propType for native prop 'VRTText.renderingOrder' of native type 'number'
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

This error is located at:
in VRTText (at ViroText.js:251)
in ViroText (at HelloWorldScene.js:25)
in VRTScene (at ViroScene.js:195)
in ViroScene (at HelloWorldScene.js:23)
in HelloWorldScene (at ViroVRSceneNavigator.js:408)
...`

It says I should update both, but how can I do that?
Is there another problem?

When I delete this line from HelloWorldScene.js it shows no error and displays the 360° image:
`<ViroText text="Hello World!" width={2} height={2} position={[0, 0, -2]} style={styles.helloWorldTextStyle} />`
However, I would like to integrate text.

----------------
Versions:
react-native-cli: 2.0.1
react-native: 0.55.1
react-viro-cli: 2.9.1
ngrok version 2.2.8

**Comment by dam00n** [comment]
We updated the Viro platform to 2.10 yesterday along with the sample projects. Can you make sure you are on the latest? Release notes here -> https://docs.viromedia.com/docs/releases

**Comment by dcdrg** [comment]
Thank you, it works now after upgrading to 2.10!
