### ISSUE TITLE
ARScene casue app crash when having tab navigation on android 

### ISSUE THREAD

**Issue by realchiu** [viromedia/viro#406]
## Environment
Please provide the following information about your environment:
1. Development OS: Mac, Windows, Linux
====> Linux

2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on?
====> Android 8.1.0

3. Version: ViroReact version and React Native version 
====> ViroReact 2.10.0 and React Native 0.55.4

4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
====> Nokia 7 plus (The one with android one)

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
=====>
I am using "createBottomTabNavigator, createStackNavigator" in "react-navigation".

I have the following structure:
```
StackANavigator = createStackNavigator({
  QQ: QQView, //QQView has nothing doing with react viro 
  AR: ARSceneNavigator, //(which is ViroARSceneNavigator with initial scene ARView)
}, {
  initialRouteName: 'QQscene'
})
StackBNavigator = {another stack navigator with some route in it}
```

And the main struture is :
```
createBottomTabNavigator({
  A: StackANavigator,
  B: StackBNavigator,
})
```

When I go to AR in ARSceneNavigator, it successfully rendered the ARscene with helloWorld text(I have tried also for some other object it was also successful). Without popping ARscene from StackANavigator, I switched to StackBNavigator on tabBar. But then when I switch back to StackANavigator on tabBar, my app crashed. 

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.
==== > 
Go into StackANavigator -> push AR -> switch to StackBNavigator by tabBarNavigator -> switch back to StackANavigator ->  app crash. (100% crash by this procedure).

I have seen a similar problem(#388), and I tried to set tabbarPosition to bottom explicitly but It didn't work(originally it is at the bottom, and I haven't specify it).

Appreciate if anyone could help.

**Comment by achuvm** [comment]
Hi @realchiu,

The solution referenced by #388 is to use `createMaterialTopTabNavigator` (documentation [here](https://reactnavigation.org/docs/en/material-top-tab-navigator.html)) and then specify the `tabBarPosition` to be `bottom`.

Let us know if that works.

Thanks,

**Comment by realchiu** [comment]
Is there any other solution rather than changing to createMaterialTopTabNavigator?
As my app has been published and AR will be new feature in next update. I hope to have solution which does not require me to change any existing working code( even though I am able to change it without affecting any functionality).
I am hoping you can like give a fix to make it compatible

**Comment by realchiu** [comment]
Is there any other solution rather than changing to createMaterialTopTabNavigator?
As my app has been published and AR will be new feature in next update. I hope to have solution which does not require me to change any existing working code( even though I am able to change it without affecting any functionality).
I am hoping you may give a fix to make it compatible with tabNavigator which can help other apps using createBottomTabNavigator to integrate with react viro(if there is any app).

Anyway if there are really no other solutions,  I will change it to createMaterialTopTabNavigator.  Just hope there can be solutions in thr future.

**Comment by realchiu** [comment]
@achuvm My ARscene will not crash the app when createMaterialTopTabNavigator with position: 'bottom' is used. And everything look the same. Thank you very much

**Comment by nhatvuminh** [comment]
Good news! I'm trying with createBottomTabNavigator and react-navigation. In TabNavigator, I'm set 

> unmountOnBlur: true

crash is gone. Hope this help! :)

**Comment by Roopal-dev** [comment]
I am getting crash when using stack navigator inside the tab navigator.Happens when going back to previous screen.
Any help would be appreciated.
Using :
   "@react-navigation/native": "^5.9.4",
   "@react-navigation/material-top-tabs": "^5.3.15",
   "@react-navigation/stack": "^5.14.5",
   "react-native": "0.64.2",
  "@viro-community/react-viro": "git+https://github.com/virocommunity/viro.git",

**Comment by DorelisMarcelo** [comment]
https://reactnavigation.org/docs/navigation-lifecycle/

Control the life cycle of the component by my own works perfect. Well, actually I have a previous screen to get to this one inside the same tab, since what I do is scan some qr to know which scene to show latter, that allowed me to set if show the first screen or the result of this one. So in my case, what was happening is that one of the props was reset when unmounted and when you go back to the AR screen, AR doesn't find that prop and crash.


```
export function Qr_3d(){

  const [showScanner,setShowScanner] = useState(true)
  const [scannerResult,setScannerResult] = useState(null)  
  useFocusEffect(
    React.useCallback(() => {

      return () => {
        setShowScanner(true)
      };
    }, [setShowScanner])
  )


  return (
      showScanner ? (
        
        <QrScanner onRead={(data) =>{
          setScannerResult(data)
          setShowScanner(false)
        }} />
      ):(
        <Qr_result_ar idElement={scannerResult} />
      )
    );
  
}
```
