### ISSUE TITLE
Viro & NativeBase

### ISSUE THREAD

**Issue by stu236** [viromedia/viro#407]
## Environment
Please provide the following information about your environment:
1. Development OS: Mac & Windows
2. Device OS & Version: Android 8.0.0 & iOS 11.4.1
3. Version: ViroReact 2.10.0 and React Native 0.55.1
4. Device(s): iOS & Android

## Description
I am trying to use NativeBase along side ViroReact.

I have created a ReactViro app using the instruction outlined in the [documentation](https://docs.viromedia.com/docs/quick-start).

I then install Native Base using the following commands:

`npm install native-base --save` and `react-native link`

I then run: `npm start`

## Sample code

```javascript
import React, { Component } from 'react';

import { CheckBox } from 'native-base';

export default class ViroSample extends Component {
  render() {
    return <CheckBox />;
  }
}

module.exports = ViroSample
```

## Output

Once I load the App in the Viro Media's Testbed, I get the following errors:

**iOS**: `Unrecognized font family 'Ionicons'`

**Android**: App renders a Chinese character instead of the icon.

**Comment by VikAdvani** [comment]
Hi @stu236,
Native base is a custom native module so it won't work from the Testbed app. You'll need to create a iOS or Android Studio project and install native base into that project. This is the only way to use native modules like Native base with Viro React.

Here's how you do that with iOS XCode: https://docs.viromedia.com/docs/starting-a-new-viro-project-1

Here's how you do that with Android Studio: https://docs.viromedia.com/docs/installing-viro-android

Let us know if this makes sense or if you have any more questions. Thanks!

**Comment by stu236** [comment]
Hey, meant to comment earlier.

These instructions worked great and all works well.

Thanks!
