### ISSUE TITLE
Issue when Rendering some transparent GIFs

### ISSUE THREAD

**Issue by dthian** [viromedia/viro#409]
There seems to be an issue when rendering some transparent GIFs in the scene. 

For example, the GIF below conflicts with GIF transparent optimizations and thus continuously render's it's previous frame in the scene. 

![girl](https://user-images.githubusercontent.com/1904934/45320927-caaca000-b4f8-11e8-98ff-7e6cdc285fc2.gif)

**Comment by dam00n** [comment]
This has been fixed in the latest release, ViroReact v2.11.0

Release notes and upgrade instructions -> https://github.com/viromedia/viro/issues/409
