### ISSUE TITLE
undefined is not an object (evaluating 'nativeVersion.major')

### ISSUE THREAD

**Issue by jonlaing** [viromedia/viro#41]
Was trying to run the sample app as per the instructions on your website. I haven't changed anything in it, just downloaded it and ran it.

I'm running iOS 11.0.1 on an iPhone 6.

This is the stack trace:

```
undefined is not an object (evaluating 'nativeVersion.major')

<unknown>
    index.ios.bundle?platform=ios&dev=true:13908:55
loadModuleImplementation
    index.ios.bundle?platform=ios&dev=true:121:12
guardedLoadModule
    index.ios.bundle?platform=ios&dev=true:78:45
global code
    index.ios.bundle?platform=ios&dev=true:67839:9
```

**Comment by jonlaing** [comment]
I also tried blowing away my `node_modules` and reinstalling everything.

I did change one thing, now that I think about it. I had an error trying to run `npm start` because it couldn't find the react-native packager at `node_modules/react-native/packager/packager.sh`, so I changed my `package.json` to look at `node_modules/react-native/scripts/packager.sh`. 

Not sure if that's relevant information.

**Comment by jonlaing** [comment]
Yeah, I have no idea what happened. I must have been on an older version of node (I use nvm for work, so who knows what version I was on). I made sure I was on the latest version, reinstalled everything and tried it again and it worked fine.

**Comment by ConnorWhelan11** [comment]
I had the same error after upgrading my react-native version to the latest. After upgrading node/npm (was on v6.11.0 of node for some reason, am now on v8.9.0), deleting node_modules, and then reinstalling everything, the error went away.

**Comment by achuvm** [comment]
Hey @ConnorWhelan11,

Thanks for the update, just FYI, the Viro platform doesn't work with the latest React Native v0.49.3. The current version of Viro has been tested and works with React Native v0.47.2. We'll have v0.49.3 support in our next release slated for the middle of this month.

Andy

**Comment by vetonbytyci** [comment]
https://facebook.github.io/react-native/docs/upgrading.html

**Comment by dam00n** [comment]
Update: The latest version of ViroReact (v2.1.0 released on 11/16/17) is compatible with React Native v0.49.3. Read our release notes for more details -> https://docs.viromedia.com/docs/releases#section-react-viro-v2-1-0-react-viro-cli-v2-1-0-compatible-with-react-native-v0-49-3-

**Comment by Paari** [comment]
Running `npm install` worked for me.
