### ISSUE TITLE
could make an oculus go app compatible with viroReact

### ISSUE THREAD

**Issue by intimateo** [viromedia/viro#410]
I read that GearVR app its compatible with oculus go, it's possible with viroReact?

**Comment by dam00n** [comment]
Not sure if the GearVR app would just work as we have not tried using ViroReact with Oculus Go. We have an open issue regarding this -> https://github.com/viromedia/viro/issues/264

**Comment by dam00n** [comment]
Closing this issue for #264 which we will use to track
