### ISSUE TITLE
json parse error, unrecognized token '<'

### ISSUE THREAD

**Issue by okonye** [viromedia/viro#411]
- [ ] Review the documentation: https://docs.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/viro
  - [ ] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development Windows
2. android studio and react native

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
JSON Parse error: Unrecognized token '<'
tryCallOne
    C:\reactproject\busReservation\node_modules\promise\setimmediate\core.js:37:14
<unknown>
    C:\reactproject\busReservation\node_modules\promise\setimmediate\core.js:123:25
<unknown>
    C:\reactproject\busReservation\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:295:23
_callTimer
    C:\reactproject\busReservation\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:152:6
_callImmediatesPass
    C:\reactproject\busReservation\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:200:17
callImmediates
    C:\reactproject\busReservation\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:464:11
__callImmediates
    C:\reactproject\busReservation\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:327:4
<unknown>
    C:\reactproject\busReservation\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:145:6
__guardSafe
    C:\reactproject\busReservation\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:6
flushedQueue
    C:\reactproject\busReservation\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:144:17
invokeCallbackAndReturnFlushedQueue
    C:\reactproject\busReservation\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:140:11

**Comment by dam00n** [comment]
This does not appear to be a ViroReact issue. Have you tried searching for similar errors/issues on the React Native github?

**Comment by okonye** [comment]
Okay thanks
