### ISSUE TITLE
Crash when conditionally rendering ViroARSceneNavigator

### ISSUE THREAD

**Issue by kesha-antonov** [viromedia/viro#418]
Hello!

  - [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS version 12.0
3. Version: ViroReact 2.10.0 and React Native 0.57.0
4. Device(s): iPhone SE

## Description
When I render ```ViroARSceneNavigator``` first time - all OK. When I conditionally remove ```ViroARSceneNavigator``` and render null for that scene it Crashes.

<img width="1044" alt="screen shot 2018-09-17 at 18 20 30" src="https://user-images.githubusercontent.com/11584712/45632637-73816f00-baa6-11e8-9e7e-af8e6de167ac.png">

**Comment by VikAdvani** [comment]
Hi @kesha-antonov, we haven't tested Viro with React Native Version 0.57 yet. If you downgrade to React Native 0.55 do you still see this issue? We are hoping to support 0.57 shortly.

**Comment by kesha-antonov** [comment]
> Hi @kesha-antonov, we haven't tested Viro with React Native Version 0.57 yet. If you downgrade to React Native 0.55 do you still see this issue? We are hoping to support 0.57 shortly.

I'll wait for release with ARKit 2.0 next week. I hope you will use 0.57 there
