### ISSUE TITLE
When new version with ARKit 2.0 will be released?

### ISSUE THREAD

**Issue by kesha-antonov** [viromedia/viro#419]
Hello!

Can't wait to try new release!
When it's gonna be? What date?

Thanks!

P.S. Is this right place to ask? Do you have anywhere open-sourced repo of Viro code?

**Comment by dam00n** [comment]
Working on adding it to our next release, which we are targeting for mid next week.

There is no open-sourced repro of Viro code

**Comment by kesha-antonov** [comment]
@dam00n Thanks!
