### ISSUE TITLE
[Feature Request] AR Mode: Access to Camera ProjectPoints or Camera Projection Matrix

### ISSUE THREAD

**Issue by jimcamel** [viromedia/viro#422]
Hi,

I'm working on a client project where I need to determine the screen space position of virtual content attached to an AR ImageMarker to trigger specific behaviour. ARKit (and I'm guessing ARCore as well, although this project is iOS only) provides access to the camera projection matrix and also the function ProjectPoints to calculate the position of a world point in screen space:

https://developer.apple.com/documentation/arkit/arcamera/2887458-projectionmatrix

It would be really helpful to have access to either the camera projection matrix, even better, the ProjectPoints function. These functions are commonly used for a bunch of different applications (so much so that every graphics/computer vision library I've ever seen provides some form of them).

Cheers,
Adrian

**Comment by achuvm** [comment]
Hi @jimcamel,

Thanks for the feature request, we'll add it in our next release for ViroReact, we do have it exposed in our ViroCore library, so it should be easy enough. We'll update this issue when we release it.

Quick question, is this holding up your development? 

Thanks,

**Comment by jimcamel** [comment]
Excellent, that's a great help, thanks very much.

It's not holding up development at this stage (there are a number of other things to work on in the mean time), although it is required for a core component of the project. Is there an estimated date for when the next release of ViroReact will be available?

Cheers,
Adrian

**Comment by jimcamel** [comment]
Hi, is there any chance of getting an alpha version of the library with this functionality earlier? The project isn't due to go live until mid November, but the sooner we are able to test this functionality in our app framework the better.

Cheers,
Adrian

**Comment by VikAdvani** [comment]
Hi @jimcamel, we are working on this feature currently. Once it's avail we can provide an alpha build. That'll likely be ready sometime next week :)

**Comment by jimcamel** [comment]
Perfect, thanks. I've managed to rig up a temporary solution with OpenCV in the meantime, but having it all integrated in the Viro React library will be much better. I look forward to the alpha. Thanks :)

**Comment by manbod** [comment]
Hi @jimcamel ,
We added project/unproject methods to our `ViroARSceneNavigator`. Docs here -> https://docs.viromedia.com/docs/viroarscenenavigator . Let us know if you have more questions.
