### ISSUE TITLE
[android] isARSupportedOnDevice returns true on unsupported ARCore device (Redmi 4X)

### ISSUE THREAD

**Issue by kesha-antonov** [viromedia/viro#428]
Hello!

## Environment
1. Development OS: Mac
2. Device OS & Version: Android OS version 7.1.2
3. Version: ViroReact 2.11.0 and React Native 0.57.1
4. Device(s): Redmi 4X

## Description
When I start app I run ```ViroUtils.isARSupportedOnDevice```. It says that ARCore is supported on a device. But sometimes it returns that ARCore is not supported.

On first open of app it returs ```supported```, on subsequent app reloads it returns  ```not supported```.

**Comment by kesha-antonov** [comment]
https://stackoverflow.com/questions/48545349/how-to-check-if-arcore-lib-apk-installed-on-device
https://developers.google.com/ar/develop/java/enable-arcore

Maybe those links can help

**Comment by kesha-antonov** [comment]
Double check seems to work. Only > 5secs
```
this.checkIsARSupported()
    // NOTE: DOUBLE CHECK
    setTimeout(() => {
      this.checkIsARSupported()
    }, 5000)
```

**Comment by manbod** [comment]
We have updated our `isARSupportedOnDevice()` method as per ARCore's enum values. Updated docs here -> https://docs.viromedia.com/docs/isarsupportedondevice .  Let us know if you still run into issues.
