### ISSUE TITLE
[Question] - ViroSurface onlick data

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#43]
Hi @achuvm,

Thank you for your help so far. I'm learning more an more about the library and I love it.

I have a question regarding the data I'm receiving when I click on the ViroSurface. Here the [video](https://www.dropbox.com/s/qmkhcvlom26w29r/click-on-plane.mov?dl=0)

When I click on a grid intersection I almost get the same data that looks like X,Y,Z coordinates. What do these numbers actually represent?

Thanks,
Tom

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

We're glad to hear you like the library!

Unfortunately it looks like our documentation is a bit out of date, but you're right in that you are actually receiving X, Y, Z coordinates which represents the position (in world space) where your onClick ray intersected with the surface. One would use this to maybe place an object at the location where a user tapped, etc.

You can see this in `ViroSurface.js`, the onClick looks like this:

```
  _onClick: function(event: Event) {
    this.props.onClick && this.props.onClick(event.nativeEvent.position, event.nativeEvent.source);
  },
```

Thanks,
Andy

**Comment by dittmarconsulting** [comment]
Thanks for the info Andy. Cool stuff
