### ISSUE TITLE
FBX to VRX segmentation fault

### ISSUE THREAD

**Issue by sharathprabhal** [viromedia/viro#435]
## Environment
Please provide the following information about your environment:
OS: `OSX 10.13.6` 
react-viro: `2.11.0`

## Description
Getting a segmentation fault when running this FBX in the `ViroFBX` tool. FBX loads fine in FBX Review.

```
2018-10-07 22:13:33.564 ViroFBX[3677:353448] "Loading file [model.fbx]"
2018-10-07 22:13:33.566 ViroFBX[3677:353448] "Import successful"
2018-10-07 22:13:33.636 ViroFBX[3677:353448] "   Original up axis 2, sign 1"
2018-10-07 22:13:33.636 ViroFBX[3677:353448] "   Original forward axis 2, sign 1"
2018-10-07 22:13:33.636 ViroFBX[3677:353448] "   Coordinate system 0"
2018-10-07 22:13:33.636 ViroFBX[3677:353448] "Triangulating scene..."
2018-10-07 22:13:33.944 ViroFBX[3677:353448] "Exporting FBX..."
2018-10-07 22:13:33.944 ViroFBX[3677:353448] "Exporting skeleton"
   Exporting skeleton node [mixamorig:Hips]
      Exporting skeleton node [mixamorig:Spine]
         Exporting skeleton node [mixamorig:Spine1]
            Exporting skeleton node [mixamorig:Spine2]
               Exporting skeleton node [mixamorig:Neck]
                  Exporting skeleton node [mixamorig:Head]
                     Exporting skeleton node [mixamorig:HeadTop_End]
               Exporting skeleton node [mixamorig:LeftShoulder]
                  Exporting skeleton node [mixamorig:LeftArm]
                     Exporting skeleton node [mixamorig:LeftForeArm]
                        Exporting skeleton node [mixamorig:LeftHand]
                           Exporting skeleton node [mixamorig:LeftHandThumb1]
                              Exporting skeleton node [mixamorig:LeftHandThumb2]
                                 Exporting skeleton node [mixamorig:LeftHandThumb3]
                                    Exporting skeleton node [mixamorig:LeftHandThumb4]
                           Exporting skeleton node [mixamorig:LeftHandIndex1]
                              Exporting skeleton node [mixamorig:LeftHandIndex2]
                                 Exporting skeleton node [mixamorig:LeftHandIndex3]
                                    Exporting skeleton node [mixamorig:LeftHandIndex4]
               Exporting skeleton node [mixamorig:RightShoulder]
                  Exporting skeleton node [mixamorig:RightArm]
                     Exporting skeleton node [mixamorig:RightForeArm]
                        Exporting skeleton node [mixamorig:RightHand]
                           Exporting skeleton node [mixamorig:RightHandThumb1]
                              Exporting skeleton node [mixamorig:RightHandThumb2]
                                 Exporting skeleton node [mixamorig:RightHandThumb3]
                                    Exporting skeleton node [mixamorig:RightHandThumb4]
                           Exporting skeleton node [mixamorig:RightHandIndex1]
                              Exporting skeleton node [mixamorig:RightHandIndex2]
                                 Exporting skeleton node [mixamorig:RightHandIndex3]
                                    Exporting skeleton node [mixamorig:RightHandIndex4]
      Exporting skeleton node [mixamorig:LeftUpLeg]
         Exporting skeleton node [mixamorig:LeftLeg]
            Exporting skeleton node [mixamorig:LeftFoot]
               Exporting skeleton node [mixamorig:LeftToeBase]
                  Exporting skeleton node [mixamorig:LeftToe_End]
      Exporting skeleton node [mixamorig:RightUpLeg]
         Exporting skeleton node [mixamorig:RightLeg]
            Exporting skeleton node [mixamorig:RightFoot]
               Exporting skeleton node [mixamorig:RightToeBase]
                  Exporting skeleton node [mixamorig:RightToe_End]
2018-10-07 22:13:33.945 ViroFBX[3677:353448] "Exporting node [default], type [mesh]"
2018-10-07 22:13:33.945 ViroFBX[3677:353448] "   Exporting geometry"
[1]    3677 segmentation fault
```

## Reproducible Demo

FBX: 
[model.fbx.zip](https://github.com/viromedia/viro/files/2454582/model.fbx.zip)

**Comment by dthian** [comment]
Hey @sharathprabhal, thanks for reaching out. Upon closer examination of the "santa-like" model, it seems like there are no textured uv coordinates set on this model - is this desired?

**Comment by sharathprabhal** [comment]
@dthian  I haven't set it yet since I was still experimenting. Is that causing it to fail? Since it opened fine in FBX Review, I expected it to load without texture in the app as well. 

PS: my 3d model knowledge is very minimal

**Comment by dthian** [comment]
@sharathprabhal without uv texture coordinates, you will not be able to apply textures (like clothing images / Santa's hat / boots / etc) on the Santa model. You may only be able to apply a single color **to the entire model.**

This is a bug in the script, but after it's fixed, it'll probably not give you the desire visual output (The Santa model will be completely white). 

Instead of working with an improperly configured model, I strongly recommend that the model's mesh be properly uv-ed such that it will match the desired visual output you are seeking for your app, rather than attempting to plug in half-baked models.

**Comment by sharathprabhal** [comment]
Thanks for the feedback @dthian, I will get started on that. For my understanding, is the current bug(seg fault) because of the missing uv ? Or is the bug unrelated? If unrelated, can you please provide an ETA for the fix. Thanks.

**Comment by dthian** [comment]
Hey @sharathprabhal, can you try out your model with this [script](https://drive.google.com/open?id=10A4nIwMD97QIm9SxPsnxDNtj9ZHpsszN) and see if that properly renders in Viro? Thanks!

**Comment by dthian** [comment]
Hey @sharathprabhal, the current bug is because the mesh is not uv-mapped. Usually, properly configured 3d models are uv-mapped so that modelers / artist can apply image textures / materials onto the model (even if it's a single plain color).

The fix is to continue generating the model without the mapped uvs, but that **will** yield visual side effects. I've made modifications to the [script](https://drive.google.com/open?id=10A4nIwMD97QIm9SxPsnxDNtj9ZHpsszN) to continue mesh generation without uvs. You can try that out and see how it looks visually in Viro.
