### ISSUE TITLE
[Question] Dynamically download VRX files from external API and load it at runtime

### ISSUE THREAD

**Issue by KalebPortillo** [viromedia/viro#439]
Hello there, 
I need to make a application that reaches a list of objects from an API, so when the user choose on of these objects the app download its 3d object (in this case a vrx file) and then load it at the AR scene.
Is it possible using ViroReact in both android and ios builds?

Thanks in advance!

**Comment by dam00n** [comment]
Yes, this is possible for ViroReact on both Android and iOS. You can use a url for your asset -> {uri:"http://example.org/myobject.obj"}

https://docs.viromedia.com/docs/viro3dobject

**Comment by KalebPortillo** [comment]
Thanks @dam00n 
It worked!
A another question similar to the original one, is it possible also to load a ImageMarker dynamically from api?

For example, here in this example in the docs 

```
ViroARTrackingTargets.createTargets({
  "targetOne" : {
    source : require('./res/targetOne.jpg'),
    orientation : "Up",
    physicalWidth : 0.1 // real world width in meters
  },
});
```

Instead require a local file in `source`, also load a external `uri` ?

Thanks again!

**Comment by KalebPortillo** [comment]
It works, thanks for all the help!
