### ISSUE TITLE
[Question] - Running app without ngrok tunnel

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#44]
Hi @achuvm,

Another question. 

Is it possible to run the Viro library without ngrok at all?

Thanks,
Tom

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

Yes, it's possible to run Viro w/o ngrok.

If you're using the Viro Media App:
On iOS:
1. If your phone and computer are on the same network, you can type in your local IP address.

On Android:
1. You can also use your local IP address.
2. You can reverse tether using the command `adb reverse tcp:8081 tcp:8081` and simply use the localhost address: `127.0.0.1` in the Viro Media App.

If you're building your app through Xcode:
1. in `AppDelegate.m`, change the line `BOOL usingNgrok = YES;` to `BOOL usingNgrok = NO;`, this will default to using local IP (this is automatically detected and "sent" to the built app).

If you're building your app through Android Studio:
1. You should reverse tether using the command `adb reverse tcp:8081 tcp:8081` and simply build and run the application.

Let me know if you need help or more clarification!

Andy

**Comment by dittmarconsulting** [comment]
Thank you very much for the fast reply.

I was after the Xcode switch but I'm sure others will be interested in the other solutions as well.

It's especially important to turn off the tunnel to enable remote debugging unless that's possible with ngrok.

Thanks again,
Tom

**Comment by mypark** [comment]
I'm assuming that ngrok will not on release/production builds - how is that configuration handled?  Is that in the docs somewhere?

**Comment by achuvm** [comment]
Hi @mypark,

The use of a packager server vs bundled Javascript assets is a feature of React Native. We just added the ngrok bit to overcome a few issues, but the deployment/release process is the same as React Native.

Instructions for Android can be found here:
https://facebook.github.io/react-native/docs/signed-apk-android.html

iOS:
I can't find the instructions for iOS, but they're the same as any other iOS app out there, simply change the Scheme's Build Configuration to `Release`:
https://stackoverflow.com/questions/5706548/how-do-i-create-a-release-build-in-xcode

Let us know if you have any issues
