### ISSUE TITLE
Is it possible to scan QR-codes within Viro?

### ISSUE THREAD

**Issue by kesha-antonov** [viromedia/viro#440]
Without using other modules.

**Comment by achuvm** [comment]
Hi @kesha-antonov,

Are you talking about scanning in terms of recognition or scanning in terms of extracting the encoded information?

For recognition, it *might* be possible with the ViroARImageMarker, but for extraction, we don't support that natively without another library.

Thanks,

**Comment by mOcentury** [comment]
Hi @achuvm, 

I am also interested to integrate QR scanning in my Viro app too. 

Could you enlighten me on how to detect and obtain the QR codes in the AR scene so that it could be pass to another library to decode the data?

**Comment by achuvm** [comment]
Hi @mOcentury,

The platform will only be able to detect a specific code. It won't be able to detect generic QR codes in of itself.

What you might be able to do is to take a screenshot periodically and pass that into a QR decoder.

Thanks,
