### ISSUE TITLE
Couldn't find API_KEY_HERE in App.js in viro sample

### ISSUE THREAD

**Issue by tejeshb** [viromedia/viro#441]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac, Windows, Linux
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on?
3. Version: ViroReact version and React Native version 
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by tejeshb** [comment]
1. Os : Mac
2. IOS version 11.2

**Comment by dam00n** [comment]
Line 29

**Comment by MiLeung** [comment]
@dam00n Why does viro need an API key in order to work? Does it need an online connection to work?

**Comment by dam00n** [comment]
The API key is used for internal metrics and if needed, license enforcement. The API key is a soft check, so the renderer will keep running if the app is offline and only fails if the key is proven to be invalid. If your device is offline and we can’t validate the key we allow the app to continue to run.

**Comment by MiLeung** [comment]
What do you mean by "license enforcement"? Will developers be charged a fee after a certain amount of usage?

**Comment by MiLeung** [comment]
@dam00n What do you mean by "license enforcement"? Will developers be charged a fee after a certain amount of usage?

**Comment by dam00n** [comment]
Here is a link to our license -> https://docs.viromedia.com/docs/license

Developers will not be charged a fee based on usage. The Viro platform is free with no limits on distribution, we do ask for attribution. 

By license enforcement, which we expect to be a rare, it would be cases where someone is egregiously violating our license.
