### ISSUE TITLE
How to show +z object (User's Back) when user rotates camera

### ISSUE THREAD

**Issue by krishanjangir** [viromedia/viro#444]
I have successfully integrated Viro in my project.

Followed below code and able to put object
https://github.com/viromedia/viro/issues/131

As in front of camera it's -Z and i am getting X and Z

    var objFinalPosZ = objPoint.y - devicePoint.y;
    // var objFinalPosZ = objPoint.z - devicePoint.z;
    var objFinalPosX = objPoint.x - devicePoint.x;
    //flip the z, as negative z(is in front of us which is north, pos z is behind(south).
    return ({ x: objFinalPosX, z: -objFinalPosZ });

But the issue is i am not able to show the object those are behind my camera view

![screenshot_20181025-143147](https://user-images.githubusercontent.com/24914330/47489357-14143d00-d864-11e8-890e-43b1ad5d7d7c.png)

See in image i am in mid of two object i am able to view the -Z object but not able to view +z objects.
Is there any way i can rerender view if my camera rotates 180 degree.

**Comment by VikAdvani** [comment]
Hi @krishanjangir, when you rotate the phone around(which implicitly changes the camera), the you should be facing +z and the object should show automatically. Perhaps I'm misunderstanding your question. Are you looking to have both of them display at once? Did you put in logic to handle compass calibration?  Let me know, thanks.

**Comment by krishanjangir** [comment]
To view both at once i have changed your logic

        if (objFinalPosZ > 0){ 
          objFinalPosZ = -objFinalPosZ   // putting +z back object in front
        }
       return ({ x: objFinalPosX, z: objFinalPosZ });
  
But i am using your code->
      //flip the z, as negative z(is in front of us which is north, pos z is behind(south).
      return ({ x: objFinalPosX, z: -objFinalPosZ });

on camera rotation +z and the object should show automatically.  ->  But this is not happening in my case.

see video
      https://drive.google.com/file/d/1IjeDXn4rKQd56UIFTkRdVoEcHmP5-ZG-/view?usp=sharing

No i haven't implemented logic to handle compass calibration

**Comment by VikAdvani** [comment]
HI @krishanjangir, 
I see what the issue is. To fix the object not appearing when you turn around, you'll need to billboard it. Billboarding tells the object to always face the camera, this way in doesn't matter where the camera is, as the object will rotate to face. In your case, the object is facing 'away' from you when you turn around and therefore is not being drawn. 

It seems like you are you are using a flexview, so for your top most flexview set the **transformBehaviors** property like below:
```
<ViroFlexView transformBehaviors={["billboard"]} .... />
```

That should fix the object not showing up when you turn around. 

Regarding compass logic, if your device has no accelerometer or orientation sensor I'm not sure currently what can be done regarding orientation.

**Comment by krishanjangir** [comment]
It's not working for me, 
I have purchased new device which have accelerometer and Compass both.
https://www.motorola.in/products/motorola-one-power
And i am able to install below applications successfully on it.

     https://play.google.com/store/apps/details?id=com.vicdmitrienko.log.accelerometer

     https://play.google.com/store/apps/details?id=com.vincentlee.compass

But the strange thing happens Viro Media Application is not working on this.
I have tried this
       https://play.google.com/store/apps/details?id=com.viromedia.viromedia

While the same above Viro Media application is working fine on my other below Android phone(Older device) which doesn't have compass.
     https://www.motorola.in/products/moto-g-plus-gen-5-special-edition
