### ISSUE TITLE
Doesn't work on Xiaomi S2. But should!

### ISSUE THREAD

**Issue by kesha-antonov** [viromedia/viro#445]
Hello!
Please help. We have lots of downloads but on many android devices Viro is not working.
One of them is Xiaomi S2 to which I have access right now.
I've checked other apps with this device - AR is working in them.

https://docs.viromedia.com/docs/isarsupportedondevice
Returns that AR is not supported.

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android 8.1.0
3. Version: ViroReact 2.11.0 and React Native 0.57.2
4. Device(s): Xiaomi S2

**Comment by kesha-antonov** [comment]
<img width="1335" alt="screenshot 2018-10-26 at 20 59 00" src="https://user-images.githubusercontent.com/11584712/47584139-093fd200-d962-11e8-9323-a68dfa366f19.png">
![img_0915](https://user-images.githubusercontent.com/11584712/47583902-6edf8e80-d961-11e8-8880-621cfd36532c.JPG)
![img_0916](https://user-images.githubusercontent.com/11584712/47583903-6edf8e80-d961-11e8-8684-4feb7bcb4251.JPG)
![img_0917](https://user-images.githubusercontent.com/11584712/47583904-6f782500-d961-11e8-8c29-7f04fce59692.JPG)

**Comment by VikAdvani** [comment]
Hi @kesha-antonov, 
One thing you might want to try (which you did in a previous issue), is to check the method **checkIsARSupported()** multiple times perhaps more than twice.

We suspect the reason could be the device is returning 'unknown' which we currently translate to 'not supported'. In a future release we plan to make this call async which will lead to more accurate results. 

Another way, although def not ideal is to use react-native-device-info and check the device model against the arcore supported device list. 

We'll dig into this more and fix the issue in a future release. When we do, we'll update you here.

**Comment by kesha-antonov** [comment]
@VikAdvani Hi!
Do you use this code ?
android: https://developers.google.com/ar/develop/java/enable-arcore#runtime
ios: https://developer.apple.com/documentation/arkit/arconfiguration/2923553-issupported

Yes, about Xiaomi S2 I think you're right.
But now I've received 1 star review about iPhone SE.

**Comment by kesha-antonov** [comment]
@VikAdvani 
And what's the reason not to open source repo?
I think we could speed up development with the help of community

**Comment by manbod** [comment]
Hi @kesha-antonov ,
We just released ViroReact v2.12.0 where we updated our `isARSupportedOnDevice()` function to return a `reason` in `notSupportedCallback(). Updated docs here -> https://docs.viromedia.com/docs/isarsupportedondevice

**Comment by kesha-antonov** [comment]
Thanks! @manbod
