### ISSUE TITLE
ReferenceError: Can't find variable: ViroSurface

### ISSUE THREAD

**Issue by lordaltair** [viromedia/viro#449]
Hi, I have an issue when I'm trying to use ViroSurface in my code. I want to add a shadow of my object to the surface. You can see the code below:
`<ViroSurface
            position={[0, 0, 0]}
            rotation={[-90, 0, 0]}
            width={4} height={4}
            arShadowReceiver={true} />`
My development OS is Windows10. The Device is Iphone7 and the iOS version is 11.3.1. ViroReact version is v2.3.0 and React Native version is 0.57.4.

You can see the error below:

![photo_2018-11-01_20-22-19](https://user-images.githubusercontent.com/20206984/47866396-e6a33280-de13-11e8-8339-1017af635a6e.jpg)

**Comment by achuvm** [comment]
Hey @lordaltair,

Have you properly imported the component at the top of your file?

```
import {
  ViroQuad,
} from 'react-viro';
```

Also, we've since renamed `ViroSurface` to `ViroQuad` and the `ViroSurface` component will eventually be deprecated.

**Comment by lordaltair** [comment]
> Hey @lordaltair,
> 
> Have you properly imported the component at the top of your file?
> 
> ```
> import {
>   ViroQuad,
> } from 'react-viro';
> ```
> Also, we've since renamed `ViroSurface` to `ViroQuad` and the `ViroSurface` component will eventually be deprecated.

Hi @achuvm

That solved the problem thank you so much!

**Comment by achuvm** [comment]
Glad that worked! Looking forward to seeing what you build!
