### ISSUE TITLE
Recent update Bug

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#45]
Hi, I've seen that you updated your project.

I have couple of problems while launching my project such as "No dimension set for key window"
I don't know what's happening .

And another previous one which said :

var PropTypes = require('react/lib/ReactPropTypes');

Any help would be great.

Thanks

Michael

**Comment by achuvm** [comment]
Hi @Zirconiumirish,

The first error you have seems to be a React Native upgrade issue as reported here:
https://github.com/facebook/react-native/issues/13758

Some things you can try:
- wipe out and reinstall your node_modules
- clear watchman cache: `watchman watch-del-all`
- restart your packager server w/ reset-cache option:`npm start -- --reset-cache`

As for your second issue, React/React Native deprecated `ReactPropTypes` and instead uses the `prop-types` npm module.

1) make sure you have the `prop-types` module/directory in your `node_modules`
2) replace `var PropTypes = require('react/lib/ReactPropTypes');` with `import PropTypes from 'prop-types';`

Let us know if that doesn't work for you,

Andy

**Comment by Zirconiumirish** [comment]
All done thanks for your information Andy =)
