### ISSUE TITLE
Is adding ARCore Cloud Anchor support on your roadmap? 

### ISSUE THREAD

**Issue by DaireNiC** [viromedia/viro#451]
Cheers! 💃

**Comment by dam00n** [comment]
We support ARCore cloud anchors on ViroCore our Java library for Android -> http://virocore.viromedia.com/docs/ar-cloud

We do not have near term plans to add this feature to ViroReact

**Comment by Raghav29Sharma** [comment]
> We support ARCore cloud anchors on ViroCore our Java library for Android -> http://virocore.viromedia.com/docs/ar-cloud
> 
> We do not have near term plans to add this feature to ViroReact

Is this not yet implemented?

**Comment by devpascoe** [comment]
Now?
