### ISSUE TITLE
3D model changing colors when using startVideoRecording

### ISSUE THREAD

**Issue by Tino-F** [viromedia/viro#455]
- [x] Review the documentation: https://docs.viromedia.com/
  - [X] Search for existing issues: https://github.com/viromedia/viro
  - [X] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: 
Mac
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on?
IOS 12.1
3. Version: ViroReact version and React Native version 
React Native: 0.55.1
ViroReact: 2.11.0
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
IPhone X, IPhone 6s

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
When I execute the startVideoRecording function, my 3D model becomes a darker color. (It goes from yellow to orange). The opacity on the model is set to 0.3, and is a lot more noticeable than when it's set to 1. When I execute stopVideoRecording, the model turns back to its original shade.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.
```
//Start & Stop recording functions

startRecording () {

    let fileName = 'CustomApp-Video-' + Date.now();
    this.props.sceneNavigator.startVideoRecording( fileName, false, err => {

      Alert.alert( 'Unable to capture video.' );
      console.log( err );

    });

  }

  stopRecording () {

    this.props.sceneNavigator.stopVideoRecording()
    .then( tempVideo => {
      if ( tempVideo.success ) {

        if ( tempVideo.url !== null && tempVideo.url !== undefined ) {

          this.props.setVideoURI( 'file:///' + tempVideo.url );

        }

      } else {

        Alert.alert('Unable to capture video.');
        console.log(tempVideo.errorCode);

      }
    });

  }

...

<ViroDirectionalLight
              position={[0, 0, 0]}
              color="#ffffff"
              direction={[0, -.4, 0]}
              attenuationStartDistance={10}
              attenuationEndDistance={50}
              castsShadow={true}
              shadowMapSize={2048}
              shadowNearZ={2}
              shadowFarZ={5}
              shadowOpacity={.7}
              intensity={5000}/>

            <ViroAmbientLight
              color="#ffffff"
              intensity={2000}
              position={[0,0,0]}/>

            <ViroOmniLight
              intensity={13000}
              position={[0, 0.3, 0]}
              color={"#fff8c2"}
              attenuationStartDistance={20}
              attenuationEndDistance={30}/>

            <ViroSpotLight
              color="#ffffff"
              attenuationStartDistance={5}
              attenuationEndDistance={10}
              position={[0, 0, 0]}
              direction={[0, -1, 0]}
              innerAngle={0}
              outerAngle={35}
              intensity={12000}
              />

<Viro3DObject source={require('../assets/models/fire.vrx')}
              position={[-0.03, -2.6, 0.0]}
              scale={[0.01, 0.01, 0.01]}
              type="VRX"
              animation={{name:'OSG_Scene', run: true, loop: true}}
              opacity={0.4}/>
```
The vrx model does not have any texture files.

**Comment by VikAdvani** [comment]
Hi @Tino-F, 
Do you have hdr enabled on the scene navigator? If you have time, can you attach a video or gif of the effect you are seeing? Thanks.

**Comment by Tino-F** [comment]
![hdr_issue_compressed4](https://user-images.githubusercontent.com/16110443/48590395-f424e600-e904-11e8-82d1-bb530de8c25d.gif)

Sorry for the late response, but here is a gif of the issue

**Comment by radvani** [comment]
Hi @Tino-F, we fixed an issue in the latest ViroReact that should make this now work even with HDR enabled. You can give that a try as well.
