### ISSUE TITLE
Overlapping ViroImage elements cause glitchy graphics 

### ISSUE THREAD

**Issue by tetreault** [viromedia/viro#458]
## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iPhone X iOS 12.1
3. Version: ViroReact version 2.11.0 and React Native version 0.55.1
4. Device(s): iPhone X (in testbed app)

## Description
I'm just making the prototype of something small and don't have final assets yet. So I'm using some assets grabbed from the internet. One asset is a spray paint can, the other is a small PNG of mist. In the final assets there will be a static spray can image, and a 2nd "active state" spray can asset which will be a GIF of the same spray can spraying this mist. 

In my prototype I'm seeing glitching out of overlapping ViroImage elements. Please see attached video. 

## Reproducible Demo

The component which loads the AR scene (used in ViroARSceneNavigator):

```javascript
import React, { Component } from "react";
import { Alert } from "react-native";
import {
  ViroARScene,
  ViroARCamera,
  ViroAmbientLight,
  ViroImage
} from "react-viro";

export default class StaticARSprayCan extends Component {
  constructor() {
    super();
  }

  render() {
    return (
      <ViroARScene>
        <ViroAmbientLight color="#ffffff" />
        <ViroARCamera>
          <ViroImage
            height={0.4}
            width={0.4}
            position={[0, -0.25, -0.5]}
            placeholderSource={require("../res/static-spray-can.png")}
            source={require("../res/static-spray-can.png")}
            onClick={() => {
              Alert.alert(
                "onClick Title",
                "onClick alert message",
                [
                  {
                    text: "Cancel",
                    onPress: () => console.log("Cancel Pressed"),
                    style: "cancel"
                  },
                  { text: "OK", onPress: () => console.log("OK Pressed") }
                ],
                { cancelable: false }
              );
            }}
          />
          <ViroImage
            height={0.4}
            width={0.4}
            position={[0, 0.03, -0.5]}
            placeholderSource={require("../res/spray-particle.png")}
            source={require("../res/spray-particle.png")}
         />
        </ViroARCamera>
      </ViroARScene>
    );
  }
}
```

Here's a [dropbox link to a video](https://www.dropbox.com/s/3c31vczf8fqv63i/File%20from%20iOS.MP4?dl=0) I recorded on the iphone showing what I mean

**Comment by tetreault** [comment]
To expand on the use case I'm aiming for, i've expanded this demo. I'm now swapping out two ViroImage assets on click (its rough, i think i need to add in onclickstate to emulate onPress since that's not exposed to ViroImage or Image from RN). 

Do you have any advice on how I can make this cleaner? there's some lag, presumably because it takes a second to swap the image source. On press i'd like to swap the assets and on press end i want it to revert to the prior asset. It swaps between two PNGs right now, a "inactive" spray can and an "active" spray can. 

Here's a [dropbox link](https://www.dropbox.com/s/xctz9lq9qfynnue/File%20from%20iOS%20copy.MP4?dl=0) to a screen recording I made to hopefully highlight what I'm aiming for. Thanks for your time!

**Comment by dthian** [comment]
Hey @tetreault, thanks for reaching out. 

> In my prototype I'm seeing glitching out of overlapping ViroImage elements. 
This is probably happening as your images are overlapping in the same Z plane (notice that they are both placed at z = -0.5) and are thus Z fighting. To resolve the flickering, simply add a tiny offset on one element from the other.

> Do you have any advice on how I can make this cleaner? there's some lag, presumably because it takes a second to swap the image source.
If you are developing in debug mode, this lag is most likely the time it takes to download the image asset from the react native server on your computer, as you switch assets - you may not see this in a release build once where all the assets will be on-device in the app. 

Having said that, you can try mitigate the above by loading both ViroImages at once, and hiding one of them by setting it's opacity to 0. Both images will still be loaded (so there will be no visual lag time), and you can toggle the opacity visibility through states.

**Comment by tetreault** [comment]
Awesome thanks for the feedback @dthian ! I recall seeing something about that in the docs and I'll return to them!

I can mark this as closed, since now I have the prototype where I'm switching assets on click, but really need to do so on press instead. I documented some of what I ran into when trying to use View with PanResponder or TouchableWithoutFeedback, but would love to hear if you have any further high level advice on what I'm trying to accomplish there in my second comment. 

Thank you for your time!

**Comment by dthian** [comment]
Thanks @tetreault,

>  I documented some of what I ran into when trying to use View with PanResponder or TouchableWithoutFeedback, but would love to hear if you have any further high level advice on what I'm trying to accomplish there in my second comment.

Currently, you can only child/add Viro Views under existing Viro Views. However, you **cannot** chid/add ReactNative Views under Viro Views (mixing 2d under 3D views), as you have done so above by adding a View with touchableWithoutFeedback. This is done primarily because Layout/styles/prop configurations for a React Native view in a 3d space may not make sense.

Having said that, you should be able to use Viro views like ViroText / ViroFlexViews to achieve the same result. For your use case above, you can simply do the below pseudo code, where we group 2 ViroImageViews under a ViroNode that has a click listener to toggle between your "sprayIsActive" image.

```
<ViroNode position={positionOfImages} onClick={this._toggleImages} >
<ViroImage .../>
<ViroImage ..../>
<ViroNode>
```

**Comment by tetreault** [comment]
This is great thanks again @dthian it didn't occur to me for some reason to try ViroNode and your reasoning behind the errors I get makes sense. I notice there's not an "onPress" event specified but I'm assuming I can whip something up using onTouch. 

Thanks again!
