### ISSUE TITLE
Can i use ViroReact for a React js (PWA) application instead of a react-native aplication 

### ISSUE THREAD

**Issue by booleanaVillegas** [viromedia/viro#459]
I want to use the Viro Image recognition to Trigger a function on my app when the user points to an image (Heart, smiley face, or some target) , I don't want to render a 3D model or anything, i just want to redirect somewhere inside the app. 

Is it possible to use it with React instead or react native? Do you know if i should be using other library instead?

**Comment by achuvm** [comment]
Hi,

You can accomplish this by simply adding a `<ViroImageMarker />` component and adding an `onAnchorFound` callback. Then when that image is found, the callback will be triggered and you can do whatever you want at that point.

Unfortunately our platform only works with React Native and is meant only for mobile applications. I'm not aware of any React libraries that do the same (it would require browser support for ARcore and ARKit).

**Comment by tetreault** [comment]
hi @booleanaVillegas I've had some success messing with this web-based AR library and i'm not sure it exactly fits your use case but its worth checking out https://github.com/jeromeetienne/AR.js
