### ISSUE TITLE
2 ARImageMarkers. One is not recognized.

### ISSUE THREAD

**Issue by kesha-antonov** [viromedia/viro#460]
## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android OS 8.1.0, 
3. Version: ViroReact 2.11.0, React Native 0.57.4
4. Device(s): Xiaomi Mi 8, iPhone SE

## Description
Hey!
I have 2 markers:
1) recognizable: http://89.223.95.41/media/markers/shket_01.jpg
2) not recognizable: http://89.223.95.41/media/markers/shkret_02.jpg

On iOS both markers work.

Can't figure out what's wrong. Can you help please?

**Comment by dam00n** [comment]
This sounds like an issue with ARCore augmented images. Based on our experience it is not quite at the level of ARKit Image Recognition. ARCore does provide a tool that gives a score for your images -> https://developers.google.com/ar/develop/c/augmented-images/

That might help identify the issue.

**Comment by kesha-antonov** [comment]
@dam00n Thanks!

**Comment by kesha-antonov** [comment]
score img 1 - 5
score img 1 - "Failed to get enough keypoints from target image"

@dam00n Seems that you're right
