### ISSUE TITLE
Android API key validation failed?

### ISSUE THREAD

**Issue by yjoo9317** [viromedia/viro#461]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android 8
3. Version: ViroCore 1.11
4. Device(s): Pixel

## Description
I added API_KEY to AndroidManifest.xml.
After running it, it crashed right away with this runtime error:    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/auth/CognitoCachingCredentialsProvider;
        at com.viro.core.internal.keys.KeyValidator.<init>(KeyValidator.java:38)
        at com.viro.core.ViroView.init(ViroView.java:178)
        at com.viro.core.ViroView.<init>(ViroView.java:153)

It seems like whenever I try to create ViroView, there is a step to check the credential.

So it fails at
`CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(context, "us-west-2:4079eab2-c426-4a9a-a9e7-c4a38ad886eb", Regions.US_WEST_2);`
from KeyValidator.java

Then the question is how I can avoid that problem..

## Reproducible Demo
It is crashing whenever it starts.

**Comment by dthian** [comment]
Hey @yjoo9317, thanks for filing the bug. Can you share the details on how you have set up your workspace? Were you simply cloning the ViroCore Sample code? Or did you download a new ViroCore Hello World project?

**Comment by yjoo9317** [comment]
No. I was setting up just a simple app. Basically, I was trying to setup the view pointing to my_sample.obj file and I was trying to start from there. But while creating the view, it crashed at the above stack.

**Comment by dthian** [comment]
Thanks @yjoo9317. 

> I was setting up just a simple app. 

By the above, what instructions have you followed to ensure that you have included the **right Viro libraries and _it's dependencies_** when setting up your Android application? 

I strongly suggest ensuring that you double check both the build gradle settings **and** the android manifests in your Android app workspace to ensure that it is the same (or at least contains) settings as the ones in [ViroCore HelloWorld](https://virocore.viromedia.com/docs/getting-started) or our [ViroCore Code samples](https://github.com/viromedia/virocore), so as to ensure that you **are not missing any of the required dependencies.**

If you are creating a new simple app, I would suggest using the ViroCore HelloWorld project as your starting base, as it would already contain all the required dependencies for Viro to function properly.

**Comment by yjoo9317** [comment]
Thanks dthian..

That hello world project link was not within my watch somehow. I figured that some aws libraries are needed and I included jar files that seemed related to the error. 
After seeing the helloworld project, I found 2 more libraries were needed.
Thanks for the help.
