### ISSUE TITLE
Rendering a Viro3DObject crashes on Adreno 320

### ISSUE THREAD

**Issue by slycoder** [viromedia/viro#465]
## Environment

1. Development OS: Mac
2. Device OS & Version: Android 6.0.
3. Version: ViroReact 2.11.0, React Native 0.57.4. 
4. Device(s): MotoX (XT1053) /w Adreno 320 gpu.

## Description

The following crash occurs whenever a `Viro3DObject` is mounted:
https://gist.github.com/slycoder/07fad4b3b805e97edfcbbf79804c484d

This only occurs on certain devices.  The Adreno 3xx is known to have lots of issues that require workarounds, e.g.,

https://github.com/godotengine/godot/pull/14902

**Comment by radvani** [comment]
Hi @slycoder, yes this appears to be a shader compilation failure on Adreno 320. We actually use an entirely separate group of shaders for Adreno 320 because of all of its compatibility problems; this crash must be related to one of those. Thanks, we'll keep this bug updated with information.

**Comment by slycoder** [comment]
Yeah, given how crazily bad the Adreno 3xx is, it almost seems like false advertising for them to call it openGL 3.0 compatible =).

**Comment by radvani** [comment]
We just fixed this issue and it will be available in our release later this week. (Keep in mind though that for Adreno 320 we run in a stripped down 'compatibility mode' where most lighting effects are disabled). Thanks!

**Comment by manbod** [comment]
Hi @slycoder ,
We just released ViroReact version 2.12.0, that resolves this issue. Check it at -> https://docs.viromedia.com/docs/releases. Closing this issue. Let us know if you still see the same.
