### ISSUE TITLE
3d object anti aliasing

### ISSUE THREAD

**Issue by yjoo9317** [viromedia/viro#469]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android 6 or higher
3. Version: ViroCore 1.11
4. Device(s): Galaxy 

## Description
How can I enable anti aliasing for 3d model rendering?
The loaded model's round shape is a bit bulky and I've been looking for previous issues or questions, but I wan't lucky to find a way to do that.

Thanks for the help.

## Reproducible Demo
I loaded model (obj with textures) and added it to the scene.
See how it renders.

**Comment by radvani** [comment]
Are you using AR, VR, or just the standard 3D scene view?

**Comment by yjoo9317** [comment]
Well, I am using 3d scene view without AR and VR.
Maybe I can attach the partial view later that can tell anti aliasing is
not turned on.
