### ISSUE TITLE
Gear VR Remote ? Compatibility

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#47]
Hello I was wondering if it's compatible with the remote of the Gear VR Headset ?

I already try with the Daydream and work properly but note with the Gear

Thanks

Michael

**Comment by dam00n** [comment]
We don't yet support the Gear VR remote/controller. It is on our backlog but don't have a date for when it will be ready. Will keep you updated.

**Comment by Zirconiumirish** [comment]
Thanks for this info


Michael
