### ISSUE TITLE
OnFuse method is not calling with some parameters

### ISSUE THREAD

**Issue by krishanjangir** [viromedia/viro#473]
I need to call function _onFuse but its not calling , also it is showing some error. [ts] ';' expected. [1005]

       onFuse={() => {{callback:this._onFuse(item),timeToFuse:500}}}

**Comment by krishanjangir** [comment]
I tried below code but failed

      onFuse={{callback: (source) => {this._onFuse(source)},timeToFuse: 1000}}

**Comment by dthian** [comment]
> But most of time it's not calling, please let me know what's the issue

Please provide more information here, in particular we'll need to know:
1) **User-actionable repro steps** on what you were doing to the app / control when the bug occurred.
2) From the above repro steps, how you have determined that it is not calling. 
3) Provide full sample code of the control that you have in your scene.
4) Video recording of the bug (sounds like the above may be a positional issue). You can use [this app](https://play.google.com/store/apps/details?id=com.littlea.ezscreencorder&hl=en_US) to record the video, and send it to us via [support](https://viromedia.com/contact-1/) with a link to this issue.

We'll take a look once you have answered all the questions above, thanks!

**Comment by krishanjangir** [comment]
_onFuse(item) {
 
    Alert.alert('fuse')
    // this.setState({isPaused:false,
    //   m_id:item.m_id
    // })
    },

     _onHover(isHovering, position, source, item) {

    if (item.m_codec == '.mp4') {

      if (isHovering) {
        // user is hovering over the box
        // Alert.alert('Hover')
        this.setState({
          isPaused: false,
          m_id: item.m_id
        })
      } else {
        // user is no longer hovering over the box
        this.setState({
          isPaused: true,
          m_id: -1
        })
        // Alert.alert('Un-Hover')
      }
       }

      },


     <ViroFlexView transformBehaviors={["billboard"]} position={[x, y, z]} width={2.7} height={hgt}
        onClick={this._onClick(item)}
        >


            <ViroFlexView materials="bg" style={{ flex: 1, flexDirection: 'column', backgroundColor: 'transparent' }} >
              <ViroFlexView style={{ flex: 0.17, marginLeft: 60, flexDirection: 'row' }} >

                <ViroFlexView width={.50} height={.50} materials='circle' style={{ marginLeft: 40, marginTop: 35, marginBottom: 10 }} >
                  <ViroImage width={.51} height={.51} source={border_circle_area} />
                </ViroFlexView>

                <ViroFlexView style={{ marginLeft: 60, marginTop: 30, flex: 0.7, flexDirection: 'column' }} >

                  <ViroText
                    text={item.u_name}
                    textAlign="left"
                    textAlignVertical="bottom"
                    textLineBreakMode="justify"
                    textClipMode="clipToBounds"
                    width={1} height={.17}
                    style={{ marginTop: 15, fontFamily: font.robotoregular, color: colors.blackc }}
                    fontSize={fontsize}
                  />
                  <ViroText
                    text={item.u_username}
                    textAlign="left"
                    textAlignVertical="top"
                    textLineBreakMode="justify"
                    textClipMode="clipToBounds"
                    width={1} height={.8}
                    style={{ marginTop: 5, paddingTop: 3, fontFamily: font.robotoregular, color: colors.blackc }}
                    fontSize={fontsize}
                  />
                </ViroFlexView>
              </ViroFlexView>

              {item.m_codec == '.mp4' ? <ViroVideo style={{ flex: 0.7 }}

                source={{ uri: item.m_file }}

              **_// Running code
               paused={this.state.isPaused == false && this.state.m_id == item.m_id ? true : false}
               loop={true}
               onHover={(isHovering, position, source) => {this._onHover(isHovering, position, 
                 source,item)}}
              // Running code

               onFuse=  {{callback: (source) => {this._onFuse(source)},timeToFuse: 1000}} 

              // onFuse =   {{callback:Alert.alert('Alert onFuse')}}
              //onFuse= {()=>Alert.alert('onFuse')}
              //onFuse={()=>{Alert.alert('onFuse'), timeToFuse=1500}}
              //onFuse={(source) => {this._onFuse(item)}}_**

              />
                :
                <ViroImage resizeMode='StretchToFill' position={[0, 0, 0]} style={{ flex: 0.7 }}
                  source={{ uri: item.m_thumbnail }} />

              }

              <ViroText
                style={{ flex: 0.15, marginLeft: 40, marginTop: 10, fontFamily: font.robotoregular, color: colors.blackc }}
                text={item.m_message}
                extrusionDepth={0}

                fontSize={fontsize} />
              <ViroText
                style={{ flex: 0.06, marginLeft: 40, fontFamily: font.robotoregular, color: colors.blackc }}
                text={this.UTCtoLocalDate(item.m_created)}
                extrusionDepth={0}
                textAlign='left'
                textAlignVertical='top'
                fontSize={fontsizeDate} />
            </ViroFlexView>
          
          

        </ViroFlexView>

**Comment by dthian** [comment]
Hey @krishanjangir, quick question - could you try removing any transformBehaviors={["billboard"]} from the code (mitigate it by manually rotating the video towards the user instead) and see if the fuse works? Thanks!

**Comment by krishanjangir** [comment]
@dthian   I have downgrade to Viro version to 2.11.0 also but it's not working. Also using single ViroFlexView but still 'onFuse' function is not calling. I think my code is wrong my callback and  timeToFuse are wrong.
     
     render() {
    return (

    <ViroARScene >

    <ViroFlexView
      backgroundColor='green'
      width={2} height={2}
      position={[0,0,-5]}
      onFuse=  {{callback: (source) => {this._onFuse(source)},timeToFuse: 1000}} 
    />

     </ViroARScene>
     );
    },

**Comment by dthian** [comment]
Hey @krishanjangir, from the video in #478 above, it looks like the hover is working. 
If this is still an issue, please provide a video demonstrating situations where the hover is **not** working. Thanks!

**Comment by dthian** [comment]
Hey @krishanjangir, the onFuse event **isn't officially support in AR** (it's more so a Google GVR event where the reticle in the middle of the screen fuses). 

Having said that, wouldn't it be possible to determine hoverOn-hoverOff events and create a countdown timer that when reached executes your _onFuse() function? This should effectively achieve the same thing.
