### ISSUE TITLE
"ViroARPlane" can't detect the "HorizontalDownward" and "Vertical" plane!

### ISSUE THREAD

**Issue by foreee** [viromedia/viro#479]
## Environment
Please provide the following information about your environment:
1. Development OS: Windows
2. Device OS & Version: Android9.0
3. Version: ViroReact version 2.12.0 ,React Native version 0.55.1
4. Device(s):  HUAWEI P20 EML-AL00

## Description
Using the compoment "ViroARPlaneSelector" or "ViroARPlane" **can** detect the "Horizontal" and "HorizontalUpward" plane, but  **can not** detect the "HorizontalDownward" and "Vertical" plane

## Code
 My code is as follow , is any wrong?
`<ViroARPlaneSelector 
minHeight={0.1} 
minWidth={0.1} 
alignment="HorizontalDownward" 
onAnchorFound={this._onAnchorFound}/>`

**Comment by achuvm** [comment]
Hi @foreee,

Can you try setting the `anchorDetectionTypes` property of `ViroARPlane` to `{["PlanesHorizontal", "PlanesVertical"]}`?

Thanks,

**Comment by achuvm** [comment]
Hi @foreee,

How feature-rich or feature-less is your ceiling? If the surface is relatively featureless, then the AR systems will have issues detecting it as a surface (this is why surface tracking doesn't work that well on concrete or patterned carpets). If you want, try adding some "features" to your ceiling such as images, etc. From what we can tell, the feature does work.

Thanks,

**Comment by nmck** [comment]
I am having the same issue as @foreee, I placed some images on the ceiling and it is not detecting any planes. I enabled the point cloud to see how many points are being detected, its looks as though there is a reasonable amount but there are no planes being detected.
