### ISSUE TITLE
[QUESTION] Set ViroARTrackingTargets source from variable

### ISSUE THREAD

**Issue by Cchumi** [viromedia/viro#485]
Hi

I hope you can help me.

I have a list of project and when I click on one of them I go to the detail page which is the ViroReact.
Actually I have one case with my business card inspire by your example.

What I am trying to achieve is to give the Image Marker as a variable inside my Scene.

I pass my props inside 

`     <ViroARSceneNavigator

          initialScene={{
            scene: require('../js/NewSceneContent.js'),
passProps:{
params:params, 
name:name,
imageTarget:imageTarget}
}
}
          apiKey={apiKey} 
          />`

But I try to access this props inside my NewSceneContent.js which is declared as 👍 
`'use strict';

import React, { Component } from 'react';

import {StyleSheet} from 'react-native';

import {
  ViroARScene,
  ViroText,
  ViroConstants,
  ViroARTrackingTargets,
  ViroARImageMarker,
  ViroQuad,
  ViroNode,
} from 'react-viro';

export default class TemplateSceneAr extends Component {
//const imageMarker = this.props.imageMarker
  constructor(props) {
    super(props);

    // Set initial state here
    this.state = {
      text : "Initializing AR...",
      addImageMarker : false,
      imageMarker: this.props.itemId,
    };
//alert(this.state.imageMarker);
//var test = this.state.imageMarker;
//alert(test);
    // bind 'this' to functions
    this._onInitialized = this._onInitialized.bind(this);
    this._getImageMarker = this._getImageMarker.bind(this);
    this._getQuad = this._getQuad.bind(this);
    this._foundAnchor = this._foundAnchor.bind(this);
    this._updateAnchor = this._updateAnchor.bind(this);
  }

  componentDidMount() {
 //alert( this.props.itemId);
alert(this.props.itemId);
var test = this.props.itemId;
   //alert(imageMarker)
    setTimeout(()=>{
      this.setState({
        addImageMarker : true,
      })
    }, 10000)
   // alert(`${this.props.navigation.state}`);
  }

  render() {
    return (

//alert(this.props.navigation.state)
      <ViroARScene onTrackingUpdated={this._onInitialized} >
        <ViroText text={this.state.text} scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
        {this._getImageMarker()}
        {this._getQuad()}
      </ViroARScene>
    );
  }

  _getImageMarker() {
    //alert(this.props.imageMarker);
    if (!this.state.addImageMarker) {
      return;
    }

    return (
      <ViroARImageMarker target={"mi_poster"} onAnchorFound={this._foundAnchor} onAnchorUpdated={this._updateAnchor} />
    )
  }

  _getQuad() {
    if (!this.state.foundAnchor) {
      return
    }
    return (
      <ViroNode position={this.state.foundAnchor.position} rotation={this.state.foundAnchor.rotation}>
      <ViroQuad rotation={[-90,0,0]} scale={[.7158, 1.066, 1]}/>
      </ViroNode>
    )
  }

  _foundAnchor(anchor) {
    this.setState({
      foundAnchor : anchor
    })
  }

  _updateAnchor(anchor) {
    this.setState({
      foundAnchor : anchor
    })
  }

  _onInitialized(state, reason) {

    if (state == ViroConstants.TRACKING_NORMAL) {
      this.setState({
        text : "Hello World!"
      });
    } else if (state == ViroConstants.TRACKING_NONE) {
      // Handle loss of tracking
    }
  }
}
//const essai = 'https://s3-us-west-2.amazonaws.com/viro/MI_assets/mi_2.png';
ViroARTrackingTargets.createTargets({
  mi_poster : {
    source : {
     //uri :'https://s3-us-west-2.amazonaws.com/viro/MI_assets/mi_2.png'
      uri :  HERE I WANT MY VARIABLE
    },
    //source : require('./res/mi_2.png'),
    orientation : 'Up',
    physicalWidth : 0.6858, // 27" poster
  }
})

var styles = StyleSheet.create({
  helloWorldTextStyle: {
    fontFamily: 'Arial',
    fontSize: 30,
    color: '#ffffff',
    textAlignVertical: 'center',
    textAlign: 'center',  
  },
});

module.exports = TemplateSceneAr;`

Someone could explain to me how can I  achieve that ?

Thanks guys

**Comment by Cchumi** [comment]
Ok I got it I just create function in the class where I can access my json data. It's solved.

**Comment by faizan1990** [comment]
Can you please provide a stand-alone source code for `ViroARTrackingTargets` that I can replicate on my end? I am having issues passing the object to render. Thanks.
