### ISSUE TITLE
ViroVideo fullscreen option ?

### ISSUE THREAD

**Issue by Cchumi** [viromedia/viro#486]
Hi 

I develop my solution based on this fantastic library and I search a way from my scene where a video is playing to have a control to switch in native ios or android fullscreen mode.

I don't see in the doc a fullscreen option. But perhaps it is native and I don't find the right way to do this.

Someone can help me about this ?

Thanks

**Comment by ctrlventure** [comment]
I'm also interested in making ViroVideo fullscreen, is there a way to do this?

**Comment by Cchumi** [comment]
Hi I don’t know how you code your scene. 
But in my case I use react native video. 
I use then Viro props to get back on my AR scene navigator file the url of my video then pass it in my video declaration and enter in full screen and play it. Next is just to use your element to close that video
