### ISSUE TITLE
[Question] - What component is similar to SCNVector3?

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#49]
Hi @achuvm,

I'm wondering whether there is something like the [SCNVector3](https://developer.apple.com/documentation/scenekit/scnvector3) I can use with the Viro lib?

I build a simple app in XCode using this function to calculate the length of two selected points on a plane:

```
func calculateDistance(from: SCNVector3, to: SCNVector3) -> Float {
  let x = from.x - to.x
  let y = from.y - to.y
  let z = from.z - to.z
  return sqrtf( (x * x) + (y * y) + (z * z))
}
```

Is that possible with the Viro library?

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

We ourselves haven't used any Javascript library for vectors, but seeing as vectors are simply data objects with defined properties, any Javascript implementation should work.

You can also use a 3-element array, or taking advantage of Javascript's everything-is-an-object-map "feature", you can simply do:

```
var vec1;
vec1.x = 1;
vec1.y = 2;
vec1.z = 3;
```

Thanks,

Andy

**Comment by dittmarconsulting** [comment]
@achuvm of course.

I didn't think of that. 

Thank you for pointing me in the right direction.
