### ISSUE TITLE
Particle emitter inside portal not rerendering after toggling visible state

### ISSUE THREAD

**Issue by tmigone** [viromedia/viro#494]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on? Running iOS 12.1.1
3. Version: ViroReact version and React Native version 
react-native-cli: 2.0.1
react-native: 0.55.1
react-viro-cli: 2.12.0
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
iPad 6th gen

## Description
I'm using an ARPortal inside an ARImageMarker. Everything works fine except for particles.
The issue im having is the following.

The first time I scan my marker, all objects and particles work as intended. 
I added a button to my app that basically sets the ViroNode visible to FALSE. I use this a way to reset the portal positioning. Only after re-scanning the marker will the ViroNode visible flag get set to TRUE again. 
After i press the button and re-scan the marker, the portal and other objects reappear, however the particles don't. I checked with react debug and the particle system has the run flag set to true, visible flag set to true. Nothing wrong in there (even tried resetting those flags).

## Reproducible Demo
Here is part of the code. I intentionally removed lights from the scene so it doesn't get more cluttered.

`

<ViroARScene>
        <ViroARImageMarker pauseUpdates={this.state.pauseUpdates} target={'logo'} onAnchorFound={this._onAnchorFound} onAnchorUpdated={this._onAnchorUpdated} onAnchorUpdated={this._onAnchorUpdated} onAnchorRemoved={this._onAnchorRemoved}>
          <ViroNode ref={this.mainNode} scale={[1, 1, 1]} position={[0, 0, 0]}>
            <ViroPortalScene passable={false} rotation={[270, 0, 90]}>

              <ViroPortal position={[0, 0, 0]} scale={[.3, .3, .3]}>
                <Viro3DObject scale={[3, 3.9, 4]} rotation={[0, 0, 0]} position={[0, -3.2, 0]} source={require('../../../res/portal/portal.glb')} type='GLB'/>
              </ViroPortal>

              <Viro360Image isHdr={true} rotation={[0, 15, 0]} source={require('../../../res/escenas/skies_hdr.hdr')} />

              <Viro3DObject
                position={[-2.5, -5.7, -0.5]}
                rotation={[0, 105, 0]}
                scale={[1, 1, 1]}
                source={require('../../../res/escenas/nieve2.glb')}
                onLoadStart={this._onLoadStart}
                onLoadEnd={this._onLoadEnd}
                onError={this._onError}
                type='GLB'
              />
              <ViroParticleEmitter
                position={[-5, 5, 0]}
                duration={2000}
                visible={true}
                delay={0}
                run={true}
                loop={true}
                fixedToEmitter={true}

                image={{
                  source:require("../../../res/particle_snow.png"),
                  height:0.007,
                  width:0.007,
                  bloomThreshold:1.0
                }}

                spawnBehavior={{
                  particleLifetime:[4000,4000],
                  emissionRatePerSecond:[150, 200],
                  spawnVolume:{
                    shape:"box",
                    params:[20, 1, 20],
                    spawnOnSurface:false
                  },
                  maxParticles:800
                }}

                particleAppearance={{
                  opacity:{
                    initialRange:[0, 0],
                    factor:"Time",
                    interpolation:[
                      {endValue:0.5, interval:[0,500]},
                      {endValue:1.0, interval:[4000,5000]}
                    ]
                  },

                  rotation:{
                    initialRange:[0, 360],
                    factor:"Time",
                    interpolation:[
                      {endValue:1080, interval:[0,5000]},
                    ]
                  },

                  scale:{
                    initialRange:[[5,5,5], [10,10,10]],
                    factor:"Time",
                    interpolation:[
                      {endValue:[3,3,3], interval:[0,4000]},
                      {endValue:[0,0,0], interval:[4000,5000]}
                    ]
                  },
                }}

                particlePhysics={{
                  velocity:{
                  initialRange:[[-2,-.5,0], [2,-3.5,0]]}
                }}
              />

            </ViroPortalScene>
          </ViroNode>

        </ViroARImageMarker>

      </ViroARScene>
`

**Comment by VikAdvani** [comment]
Hi @tomasmigone,
We were able to reproduce this bug. We'll attempt to have a fix in the next release. In the meantime a workaround that may work is to use the opacity flag instead of the visible flag. Set the opacity on the parent node to 1 for 'visible' and 0 to make it 'invisible'.

**Comment by tomasmigone** [comment]
Hi! Thanks for the reply during this time of the year!

Just tested your suggested workaround and it works great in my case.
Another possible workaround, which is what we ended up doing, is to work with the scale value. Basically set scale to [0, 0, 0] to "hide" the node and scale to [1, 1, 1] to show it. Not sure if this approach is less performant than the opacity one, but as far as we can tell there are no issues.

Thanks again
