### ISSUE TITLE
Cannot read 3D Object: Unexpected token '#', expected ';'

### ISSUE THREAD

**Issue by Dihan101** [viromedia/viro#495]
Environment:
react-native: 0.57.7
react-viro: 2.12.0

I just followed this step: [Integrating with React Native](https://docs.viromedia.com/docs/integrating-with-react-native-projects) and luckily it worked but unfortunately it always give me an error when reading my .obj and .mtl files. I already also put my apiKey to my ViroScene.
It always give me `Unexpected token`.

<img width="1031" alt="screen shot 2019-01-03 at 6 01 06 pm" src="https://user-images.githubusercontent.com/14257120/50632934-679db800-0f84-11e9-8f1f-fb4df41323af.png">

**Comment by VikAdvani** [comment]
Hi @Dihan101, your obj file is not be parsing correctly. Can you try another obj file from our samples and see if that works. If those work, that points to your obj file being exporting incorrectly for Viro. How did you go about creating your .obj file?

**Comment by Dihan101** [comment]
Hi @VikAdvani 
I'm sorry if my response was too late. You're right! my obj was not in a right content so I tried another files and it worked. Thank you so much for the concern.

**Comment by Dhruv-88** [comment]
update your metro.config file and rebuild your application



/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

 const { getDefaultConfig } = require("metro-config");

 module.exports = (async () => {
   const {
     resolver: { assetExts }
   } = await getDefaultConfig();
 
   return {
     transformer: {
       getTransformOptions: async () => ({
         transform: {
           experimentalImportSupport: false,
           inlineRequires: true,
         },
       }),
     },
     resolver: {
       assetExts: [...assetExts, "obj", "mtl", "JPG", "vrx", "hdr", "gltf", "glb", "bin", "arobject", "gif"]
     }
   }
 })();
