### ISSUE TITLE
ViroFBX segfault on FBX exported from mixamo.com

### ISSUE THREAD

**Issue by Buthrakaur** [viromedia/viro#497]
## Description
I imported model from https://www.turbosquid.com/3d-models/free-female-character-rigged-biped-3d-model/569036 to mixamo.com, applied some animation and downloaded FBX file. I checked the FBX file in Autodesk FBX Review utility and it displays and animates without any issues, but running the ViroFBX tool leads to segfault 11 error.

## Reproducible Demo

- Download FBX model from https://drive.google.com/file/d/1GWCFX4D3-nxu_lHelgywQvsWHIB20fPC/view?usp=sharing
- run `./ViroFBX girl.fbx girl.vrx` leads to segfault 11 crash

**Comment by VikAdvani** [comment]
Hi @Buthrakaur, thanks for reporting this. I've reproduced the segfault for this model. We will attempt to fix this in a future release. In the meantime you can try converting the fbx file to a gltf model to see if that works for you.

**Comment by Buthrakaur** [comment]
Hi @VikAdvani , thanks for the advice, but according to https://docs.viromedia.com/v2.12.0/docs/3d-objects gLTF support is limited to static non-animated models only - is that right? We use mixamo to get the animated humanoid model so this wouldn't make sense if I understand the limitation well..

**Comment by VikAdvani** [comment]
HI @Buthrakaur, 
Yikes, the documentation is incorrect on that point, I'll update our documentation! We started supporting GLTF skeletal animations in ViroReact 2.8. 

If your model uses morph or blend animations however, those currently don't work in FBX or GLTF.

**Comment by thiagoloop4** [comment]
Hi @VikAdvani , any updates on the fix of the segfault 11 crash? And do you know any good platform to convert the fbx file to gltf ? Thanks!
