### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by mr-aam** [viromedia/viro#501]
hi , please help me 

C:\Users\KavIran\viro>npm start

> ViroCodeSamples@0.0.1 prestart C:\Users\KavIran\viro
> ./node_modules/react-viro/bin/run_ngrok.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ViroCodeSamples@0.0.1 prestart: `./node_modules/react-viro/bin/run_ngrok.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ViroCodeSamples@0.0.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KavIran\AppData\Roaming\npm-cache\_logs\2019-01-07T19_11_55_005Z-debug.log

**Comment by ThailanHigor** [comment]
remove the line: 

`"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",`

 from your package.json

**Comment by mr-aam** [comment]
tnx , it's worked

**Comment by ThailanHigor** [comment]
You're welcome

**Comment by ajth789** [comment]
Hey, I am getting exactly the same error but there is no 

`"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",`

in my package.json file. Any other suggestions?

**Comment by ThailanHigor** [comment]
Great @ajth789 !

**Comment by ravindrandandala** [comment]
Hi,

I'm facing the same problem and below is the error description

**(python3.6) D:\AI_smart_Mirror\MagicMirror>npm start

> magicmirror@2.7.1 start D:\AI_smart_Mirror\MagicMirror
> sh run-start.sh

'sh' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.7.1 start: `sh run-start.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.7.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SONY\AppData\Roaming\npm-cache\_logs\2019-04-09T11_39_47_8
10Z-debug.log**

I'm unable to find "ngrok.sh" line in package.json.  Please let me know what I should do here to come out of this.

**Comment by harshakollipara** [comment]
> remove the line:
> 
> `"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",`
> 
> from your package.json

Hi , 
I am getting below error after removing that line from package.json. help me out in these.

error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.

**Comment by temurchichua** [comment]
> > remove the line:
> > `"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",`
> > from your package.json
> 
> Hi ,
> I am getting below error after removing that line from package.json. help me out in these.
> 
> error Invalid regular expression: /(._\**fixtures**\._|node_modules[\]react[\]dist[\]._|website\node_modules\._|heapCapture\bundle.js|._\**tests**\._)$/: Unterminated character class. Run CLI with --verbose flag for more details.

I'm getting exactly the same error.

**Comment by bimix** [comment]
> remove the line:
> 
> `"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",`
> 
> from your package.json

you cant just remove the code and make it work. That line is there for a reason!

**Comment by harshit-externlabs** [comment]
> > remove the line:
> > `"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",`
> > from your package.json
> 
> Hi ,
> I am getting below error after removing that line from package.json. help me out in these.
> 
> error Invalid regular expression: /(._\**fixtures**\._|node_modules[\]react[\]dist[\]._|website\node_modules\._|heapCapture\bundle.js|._\**tests**\._)$/: Unterminated character class. Run CLI with --verbose flag for more details.

Just find the blacklist.js file in metro-config>src>defaults(if present) node module or the metro node module and fix the regular expression with the following code: 
`var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];`

**Comment by salmabs** [comment]
> > remove the line:
> > `"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",`
> > from your package.json
> 
> Hi ,
> I am getting below error after removing that line from package.json. help me out in these.
> 
> error Invalid regular expression: /(._\**fixtures**\._|node_modules[\]react[\]dist[\]._|website\node_modules\._|heapCapture\bundle.js|._\**tests**\._)$/: Unterminated character class. Run CLI with --verbose flag for more details.

i got the same error ..
go to node_modules\metro-config\src\defaults\blacklist.js\sharedblacklist  
and change 
var sharedBlacklist ...
to : 

 var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
