### ISSUE TITLE
Invarient Voilation: View config not found for name VRTImage

### ISSUE THREAD

**Issue by kashish006** [viromedia/viro#504]
## Environment
1. Development OS: Mac,  Android P
3. Version: ViroReact version 2.12.0 and React Native version 0.55.1
4. Device(s): One plus 6T

## Description
After generating the android package from command line react-native run-android, app is throwing error - 
Invarient Voilation: View config not found for name VRTImage

## Reproducible Demo
Create a sample android packange by running react-native run-android. Open a android app in device, you will get this error.
![whatsapp image 2019-01-10 at 12 39 13 am](https://user-images.githubusercontent.com/8686147/50922793-57e50e80-1471-11e9-8445-4f27a7ba1d62.jpeg)

**Comment by manbod** [comment]
Hi @kashish006 ,
The error you are seeing indicates `react-viro` components are not linked properly in your project setup. Can you `ls` into the generated project directory and see `setup-ide.sh`? If yes, you most likely forgot to run `setup-ide.sh --android` after generating the package (`setup-ide.sh --all` for both android and iOS). After you run this command, if you open `android/app/build.gradle`, the file should show the following product flavors
```
    productFlavors {
        ar {
            resValue 'string', 'app_name', 'ViroSample-ar'
            buildConfigField 'String', 'VR_PLATFORM', '"GVR"' //default to GVR
        }
        gvr {
            resValue 'string', 'app_name', 'ViroSample-gvr'
            buildConfigField 'String', 'VR_PLATFORM', '"GVR"'
        }
        ovr {
            resValue 'string', 'app_name', 'ViroSample-ovr'
            applicationIdSuffix '.ovr'
            buildConfigField 'String', 'VR_PLATFORM', '"OVR_MOBILE"'
        }
    }
```

Let us know if running `setup-ide.sh --android` command doesn't fix this issue for you.

Thanks.
