### ISSUE TITLE
play videos from the filesystem

### ISSUE THREAD

**Issue by intimateo** [viromedia/viro#505]
I want to download video file from internet to the local storage in the device and play that video on Viro360Video, is it possible?

**Comment by faisal3413** [comment]
Hi @intimateo try something like below

` let storedContentUri = await AsyncStorage.getItem('test2');

    if(storedContentUri == null){
     await RNFetchBlob
      .config({
        fileCache : true,
        // by adding this option, the temp files will have a file extension
        appendExt : 'mp4'
      })
      .fetch('GET', 'https://url.mp4', {
        //some headers ..
      })
      .then((res) => {
        // the temp file path with file extension `mp4`
      
        // Beware that when using a file path as Image source on Android,
        // you must prepend "file://"" before the file path

        storedContentUri =  (Platform.OS === 'android' ? 'file://' + res.path() : '' + res.path());
        console.log('AR',storedContentUri);
        AsyncStorage.setItem('test2',storedContentUri);
      })
    }

    let newState = Object.assign({}, this.state);
     newState.viroAppProps.video = storedContentUri;
     this.setState(newState);`
