### ISSUE TITLE
ViroText Bounding box in ViroFlexView

### ISSUE THREAD

**Issue by Geli25** [viromedia/viro#506]
Hello,

I cannot seem to change the bounding box size in ViroText when it's placed within a ViroFlexView in AR. When I try to set the width the correct text flashes and disappears. Right now the text is overflowing while I want to make it fit into the FlexView.

This is what I see:
![img_0005](https://user-images.githubusercontent.com/32779450/51067486-d57b5c80-15e0-11e9-94bb-c81b4e78117c.PNG)

Right now I am scaling the font down while using a big font size so that it shows, however, the bounding box problem persists even if I don't do so. Wondering what could be a solution to this.

Thanks for your help!

And this is my code:
`        <ViroFlexView
            height={1}
            width={1.5}
            position={[0, 0, -5]}
            backgroundColor={'rgba(0,255,255,0.1)'}>
        <ViroText
            scale={[0.1, 0.1, 0.1]}
            textLineBreakMode="charwrap"
            textClipMode="None"
            text="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
            textAlign='left'
            style={styles.helloWorldTextStyle}
        />
        </ViroFlexView>
)

var styles = StyleSheet.create({
    helloWorldTextStyle: {
        fontFamily: 'Arial',
        fontSize: 50,
        color: '#000000',
        textAlignVertical: 'center',
    })`

Update: I have now realized that the problem is using scale + width. If I do not scale it, it seems to show in the correct location, however, the text itself becomes blurry. Scaling+width also seems to affect how big the bounding box is, because the new line starts much later if I do not scale it. Is there a fix for this?

**Comment by VikAdvani** [comment]
Hi @Geli25, 
I was able to get your text fitting in the bounding box with the following code:
```
  <ViroFlexView
      height={2}
      width={3.5}
      position={[0, 0, -5]}
      backgroundColor={'rgba(0,255,255,0.9)'}>
        <ViroText
        style={{flex: 1}}
        textLineBreakMode="CharWrap"
        textClipMode="None"
        text="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
        textAlign='left' />
      </ViroFlexView>
```
I had to increase the height and width. In general for flexbox views, **I'd stay away from using scale on subcomponents**, as the flexbox parent will scale the child components to what they should be given the parents width and height. 

So to sum up to fit a text into a flexview parent boundary do the following:
1) Adjust the width and height of the parent flexview.
2) Once you have a fit you can adjust the scale of the ViroFlexView but not the ViroText that is within it.

In terms of the blurriness this is something you will have to play with it,  try different fonts and font sizes. If you are unable to get a proper fit of text within the flexview boundary you want, try to use  a page system where you clip the text and have the user tap to see more.

**Comment by Geli25** [comment]
@VikAdvani Thanks for your help, I was scaling the font because it was blurry and using a large font size and scaling it down seems to display the text the clearest, so in general I cannot use the text bounding box in a flex view because it's tied to the parent, and I within a flex view I cannot use scale for the text?

I guess an alternative option would be to display text as a pre-rendered image instead?

Thanks.

**Comment by Geli25** [comment]
I also have another question regarding ViroSound/SpatialSound. It doesn't seem to play at all. I've put it inside of a ViroNode with two FlexViews. The source link is correct but no sound plays. Should I open a new issue?

Thanks.

```
        <ViroNode>
        <ViroFlexView
            materials="card"
            height={4}
            width={4.5}
            position={[0, 0, -10]}>
            <ViroImage
                height={2}
                width={3.5}
                source={require("./res/recipes.png")}
            />
            <ViroAnimatedImage
                style={{marginLeft:0.2}}
                height={0.9}
                width={1.5}
                source={require("./res/giphyfab.gif")}
            />
        </ViroFlexView>
        <ViroFlexView
            height={3}
            width={3.5}
            position={[-5, 0, -10]}>
            <ViroImage
                opacity={0.95}
                height={3}
                width={3.5}
                source={require("./res/dummy.png")}
            />
        </ViroFlexView>
        <ViroSpatialSound source={require("./res/jazz.mp3")} />
        </ViroNode>
)}}
```

**Comment by dam00n** [comment]
Yes can you open a new issue. Also close this issue if the original problem was resolved. Thanks
