### ISSUE TITLE
Billboard ViroText gets blurry and is leaning to one side

### ISSUE THREAD

**Issue by nasmuris** [viromedia/viro#507]
## Environment
1. Development OS: Mac, Windows, Linux
2. Device OS & Version: iOS12.1
3. Version: ViroReact 2.12 and React Native 0.55.3
4. Device(s): iPhone 6S

## Description
As you can see on the screenshot below, I've got a Marker with text that is somehow leaning to the side and even the text, the Marker is implemented like this:
`<ViroNode transformBehaviors="billboard">
       <ViroImage
          height={markerSize}
          width={markerSize}
          source={markerIcons[marker.icon]}
          position={[0, 0, 0]}
        />
        <ViroText
          text={marker.name}
          textAlign="center"
          textAlignVertical="bottom"
          textLineBreakMode="WordWrap"
          textClipMode="ClipToBounds"
          outerStroke={{ type: 'Outline', width: 5, color: '#FFF' }}
          color="#000"
          width={markerSize / 5}
          height={2}
          style={{ ...brandFontBold, fontSize: 60 }}
          position={[0, markerSize / 10, 0]}
        />
</ViroNode>`
Can you please explain me, what is causing the leaning? As you can see on the screenshot, it happens only for some Markers, the green one is OK. Also, why the text gets so blurry? I understand blurry poor resolution image, but should text be vector? 
Thanks in advance
![181229_735](https://user-images.githubusercontent.com/22944924/51103374-c106b200-17e2-11e9-80ee-c3464893dfcd.png)

**Comment by VikAdvani** [comment]
Hi @nasmuris,
What component is the marker contained in? The marker seems to adopting the rotation of whatever component it is within( a plane or ARMarkerImage or whatever else), thereby causing the tilt.

The blurriness in font in the green marker is due to the distance away from the user. You can try and play with this by scaling the marker to be bigger the further it is away it is or displaying a more readable font at that distance.

**Comment by nasmuris** [comment]
@VikAdvani The Marker is just ViroNode containing ViroText and ViroImage, all markers are contained in another ViroNode with position={[0,0,0]} and rotation={[0,userHeading,0]}, this one is placed straight in ViroARScene, I'm not adjusting Z-axis rotation of any node, the weird thing is, even if there was some bad rotation handling of parent nodes, all of the marker nodes has the same parent, hence I'd assume they would have the same X/Z rotation (Y is ruled by "billboard" if I'm right), but as you can see, only the closest marker gets this weird Z-rotation

**Comment by VikAdvani** [comment]
Hi @nasmuris, 
>>All markers are contained in another ViroNode with position={[0,0,0]} and rotation={[0,userHeading,0]},

 Just to make sure I understand correctly, do all markers have the same parent node? If so, is there a reason for that? I'm wondering if the rotation of the parent with  _rotation={[0,userHeading,0]}_ is somehow causing the strange tilt when combined with the billboarding of the children nodes. 

Try the following to see you can isolate the issue:
1) Remove the rotation={[0,userHeading,0]} from the parent node, see if the tilt shows up.
2) Remove billboarding of the children but keep  rotation={[0,userHeading,0]} see if the tilt shows up.
3) Remove billboarding and the rotation={[0,userHeading,0]}  of the parent node to see if the tilt shows up.

This will help to at least isolate the issue that can then help lead to a solution.

**Comment by radvani** [comment]
Closed due to inactivity.
