### ISSUE TITLE
Unable to resolve module after update viro to 2.13.0

### ISSUE THREAD

**Issue by whekwan** [viromedia/viro#509]
- [Y] Review the documentation: https://docs.viromedia.com/
  - [Y] Search for existing issues: https://github.com/viromedia/viro
  - [Y] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac, Windows, Linux
2. Device OS & Version: iOS 12.1
3. Version: ViroReact version:2.13 React Native 0.57.1
4. Device(s): iPhone X, iPhone 6s

## Description
I am using Viro3DObject component with some obj file since viro 2.12 , there is an error messages after I update to 2.13: "unable to resolve module './res/circle.obj'", and I have checked the path is correct and the `rn-cli.config` are also included the obj file type. 

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by manbod** [comment]
Hi @whekwan ,
You're seeing the `unable to resolve module .obj` error mostly because there's no `metro.config.js`. `react-viro-2.13.0` started using RN 57.1 which uses the new metro bundler which relies on this new `metro.config.js`. See **Upgrade Instructions** for **ViroReact v2.13.0** here -> https://docs.viromedia.com/docs/releases. 7th instruction walks you through metro.config.js creation and it's contents. If not done already, I'd recommend running through rest of the instructions for upgrades, since due to the underlying react-native version changes we have a few more instructions than usual for react-viro upgrades.

Let us know if you face any other issues.

Thanks

**Comment by jasontan87** [comment]
Hi @manbod ,

I having the same issues on unable to resolve modules .vrx error. I had follow the instructions base on your link. but i still having the same error message.

I had also created metro.config.js and input the content accordingly.

Thanks

**Comment by dam00n** [comment]
Are you sure your files are in the correct path? 3D models are working correctly on the latest version of the platform according to our tests.

**Comment by pnguyen1901** [comment]
Change the content of your **metro.config.js** to this. It should work. Worked for me!

const { getDefaultConfig } = require("metro-config");
module.exports = (async () => {
  const {
    resolver: { assetExts }
  } = await getDefaultConfig();

  return {
    resolver: {
      assetExts: [...assetExts, "obj", "mtl", "JPG", "vrx", "hdr", "gltf", "glb", "bin", "arobject", "gif"]
    },
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
    },
  };
})();

**Comment by GretaSimonyan** [comment]
<img width="736" alt="Screen Shot 2021-12-01 at 11 14 27 AM" src="https://user-images.githubusercontent.com/57007626/144188937-ca1f059d-6e49-4669-a727-8692050b8fa0.png">

and after changed the content of metro.config.js , i got this error

**Comment by GretaSimonyan** [comment]
Never mind i already fix the issue 
I use 
- [ ] "react": "17.0.2",
- [ ]  "react-native": "0.66.3",
and i just needed add **_rn-cli.config.js_** file which showing [here](https://docs.viromedia.com/docs/importing-assets#adding-asset-types)
