### ISSUE TITLE
Viromedia camera recording using front camera

### ISSUE THREAD

**Issue by jasontan87** [viromedia/viro#510]
Hi Guys, 

Is there a ways to use use device front camera for recording in viromedia?

Appreciate if anyone can assist me on this.

Thank you.

Regards,
Jason

**Comment by dam00n** [comment]
The Viro platform does not support front facing camera at this time. There is an open issue for the feature request, that you can track here -> https://github.com/viromedia/viro/issues/352

**Comment by SebLambla** [comment]
Still no update about this?
