### ISSUE TITLE
How to check the user current position in AR World?

### ISSUE THREAD

**Issue by whekwan** [viromedia/viro#517]
Hello guys, I am new to use ViroReact, I would like to know how can I know the user current Position in AR world after I rendered the AR Scene?

**Comment by achuvm** [comment]
Hi @whekwan,

You can use the `ViroARScene`'s `getCameraOrientationAsync()` function:
https://docs.viromedia.com/docs/viroarscene#methods

A slightly convoluted example of that can be found here:
https://github.com/viromedia/viro/blob/master/js/ARPhysicsSample/BasicPhysicsSample.js#L205

Hope this helps

**Comment by Peege151** [comment]
the github link 404s
