### ISSUE TITLE
Question: How to create those info points like in HumanBody sample?

### ISSUE THREAD

**Issue by andorfermichael** [viromedia/viro#524]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Description
I am really interested in how those info points  (I am not sure how the real term is) e.g. Aorta were created. I could not find any piece of code which I could refer to them.

[HumanBody](https://github.com/viromedia/viro/blob/master/js/HumanBody/heart_demo.gif)

**Comment by dam00n** [comment]
Check out the 360PhotoTour sample. That has a couple examples of info cards that can be modified similar to the heart labels -> https://github.com/viromedia/viro/tree/master/js/360PhotoTour

**Comment by andorfermichael** [comment]
I will try that. Having said that it would be really cool, if you could provide that version of the heart example.
