### ISSUE TITLE
Black screeen for AR Hello World 

### ISSUE THREAD

**Issue by faelsoto** [viromedia/viro#525]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Ubuntu 17.10
2. Device OS & Version: Android 7.1.1
3. Version: 
```
== Versions ==
react-viro-cli: 2.13.0
react-native-cli: 2.0.1
react-native: 0.57.7
```

4. Device(s): Moto Force Z2

## Description
I can't get the demo repo to work, I've set everything up as instructed, including the releases notes ones, as well as some fixes in order to make it work since I'm not on MacOS. I'm connecting to the ngrok URL but I only get a black screen.

The same happens with the AR Hello World demo included with the app. However the VR demos work just fine.

## Reproducible Demo
N/A

**Comment by andorfermichael** [comment]
Did you set the API key correctly?

**Comment by faelsoto** [comment]
Yes, I have.
