### ISSUE TITLE
[Question] How to know that the image tracking target finished loading, ready to track

### ISSUE THREAD

**Issue by seanyusa** [viromedia/viro#529]
Trying to figure out, is there a way to know when a **remote image resource** has finished loading as the source for a `ViroARTrackingTarget`?

```
ViroARTrackingTargets.createTargets({
      targetOne: {
        source: {uri: "https://images.com/photos/photo.jpeg"},
        orientation: "Up",
        physicalWidth: this.props.arSceneNavigator.viroAppProps.width, 
      },
    });
```

`<ViroARImageMarker target={"targetOne"} />`

How do I know that target one has finished loading and can start to find the ImageMarker?

Thanks in advance!

**Comment by dam00n** [comment]
Hey @seanyusa, unfortunately there is not a way to know when a remote image resource has finished loading.

**Comment by seanyusa** [comment]
@dam00n Gotcha, thanks for the help.
