### ISSUE TITLE
How to add 2D UI elements

### ISSUE THREAD

**Issue by manbod** [viromedia/viro#53]
Hello,
I am developing an AR app using Viro and I have trouble adding fixed 2d UI 
elements that are not in the 3d scene (like the record button in the 
figment app).
Can React Native elements (like <button>) work in Viro apps?

**Comment by manbod** [comment]
Yes, it's absolutely possible to add any React Native elements (like <button> in Viro Apps. Here's a link to a sample app we created (it's like a lighter version of Figment app).  https://github.com/viromedia/ViroARSampleApp . if you see in the render() function of index.ios.js here - you'll see the <ViroARSceneNavigator> is included in a top level <View> container. And this outer level container has a few 2D react native components included below the ViroARSceneNavigator. Pasting them below:

{renderIf(this.state.isLoading,
  <View style={{position:'absolute', left:0, right:0, top:0, bottom:0, alignItems: 'center', justifyContent:'center'}}>
    <ActivityIndicator size='large' animating={this.state.isLoading} color='#ffffff'/>
  </View>)
}

<View style={{position: 'absolute',  left: 0, right: 0, bottom: 77, alignItems: 'center'}}>
  <TouchableHighlight style={localStyles.buttons}
    onPress={this._onDisplayDialog}
    underlayColor={'#00000000'} >
    <Image source={require("./js/res/btn_mode_objects.png")} />
  </TouchableHighlight>
</View>

Hope this helps. Let us know if you have any questions. Happy hacking!

**Comment by baiton** [comment]
I cannot seem to make this work.  When I wrap a View tag around the ViroARSceneNavigator provided by the Viro Quick Start setup.

The first display page is made entirely of react native elements that show two options.  One for if you would prefer AR the other for if you VR.  However, when I then try to make a react native button that persists while running the AR app I crash and end up on my home screen.

I have tried wrapping the components themselves in View tags,  I have tried wrapping the navigator with view tags.  I am not seeing any clear documentation on how to create a react-native element that displays while looking at the AR project.

**Comment by stewheart123** [comment]
Does this example still actually work? I get the following error every time..

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ViroSampleAR@0.0.1 prestart: `./node_modules/react-viro/bin/run_ngrok.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ViroSampleAR@0.0.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by stewheart123** [comment]
hello?

**Comment by abhishekchatrath** [comment]
@stewheart123 

> Does this example still actually work? I get the following error every time..
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ViroSampleAR@0.0.1 prestart: `./node_modules/react-viro/bin/run_ngrok.sh`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ViroSampleAR@0.0.1 prestart script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

---

This error is shown when you don't have ngrok (pronounced "en-grock") installed and used as a dependency for your application. It is a service that creates secure tunnels to your localhost on the web (think easy hosting for development).

**Comment by abhishekchatrath** [comment]
@manbod 

> Hello,
> I am developing an AR app using Viro and I have trouble adding fixed 2d UI
> elements that are not in the 3d scene (like the record button in the
> figment app).
> Can React Native elements (like ) work in Viro apps?

---

ViroReact has helpful documentation addressing this very aspect:  [https://docs.viromedia.com/docs/flexbox-ui-layouts](url)
