### ISSUE TITLE
How to remove Marker and it's contents

### ISSUE THREAD

**Issue by thecoconutstudio** [viromedia/viro#530]
I have set up a scene with two different image markers in. Both work fine independently, but as I want to use the two markers in the same magazine I need a way to remove the marker and it's contents when the page it turned. I'm presuming `onAnchorRemoved` is the answer but I can't work out how to implement it?

          <ViroARScene>
          <ViroARImageMarker target={"videoMarker"} onAnchorFound={this._onAnchorFound1}>
            <ViroVideo source={this.state.productVideo} volume={1} rotation={[-90, 0, 0]}
                       position={[-0.001, 0, 0 ]}  width={0.192} height={0.182 } loop={true}
                      />
          </ViroARImageMarker>

          <ViroARImageMarker target={"shoeMarker"} onAnchorFound={this._onAnchorFound2}>
            <ViroNode  transformBehaviors={["billboardY"]} >
              <ViroSphere materials={["white_sphere"]}
                          heightSegmentCount={20} widthSegmentCount={20} radius={.02}
                          position={[-0.05, .45, 0]}
                          onClick={this._selectWhite}
                          animation={{name:"tapAnimation", run:this.state.tapWhite, onFinish:this._animateFinished}}
                          shadowCastingBitMask={0} />

              <ViroSphere materials={["blue_sphere"]}
                          heightSegmentCount={20} widthSegmentCount={20} radius={.02}
                          position={[0, .45, 0]}
                          onClick={this._selectBlue}
                          animation={{name:"tapAnimation", run:this.state.tapBlue, onFinish:this._animateFinished}}
                          shadowCastingBitMask={0} />

              <ViroSphere materials={["red_sphere"]}
                          heightSegmentCount={20} widthSegmentCount={20} radius={.02}
                          position={[0.05, .45, 0]}
                          onClick={this._selectRed}
                          animation={{name:"tapAnimation", run:this.state.tapRed, onFinish:this._animateFinished}}
                          shadowCastingBitMask={0} />
            </ViroNode>

            <Viro3DObject
                source={require('./res/hiking/hiking_boot_obj2.obj')}
                resources={[require('./res/hiking/hiking_boot_obj2.mtl'),
                ]}
                type="OBJ"
                materials={this.state.texture}
                scale={[0.2, 0.2, 0.2]}
                rotation={[0, 70, 0]}
                position={[0, 0, 0.1]}

                animation={{name:"scaleCar", run:this.state.animateCar,}}
            />

            <ViroImage resizeMode="ScaleToFill"
                       position={[-0.05, 0.15, -0.1]}
                       scale={[.1, .1, .1]}
                       source={require("./res/title.png")}
            />

            <ViroImage
                height={0.1}
                width={0.1}
                onClick={this._toggleHeel}
                position={[0.08,0.06,0.05]}
                source={require("./res/hotspot.png")}
            />
            <ViroImage opacity={0 }  resizeMode="ScaleToFill"
                       position={[0.13, 0.13 , 0.05]}
                       scale={[.2, .2, .2]}
                       source={require("./res/text_heel.png")}
                       animation={{
                         name: this.state.transTextHeel,
                         run: this.state.fadeInTextHeel}}
            />

            <ViroImage
                height={0.1}
                width={0.1}
                onClick={this._toggleMembrane}
                position={[-0.08,0.06,0.15]}
                source={require("./res/hotspot.png")}
            />
            <ViroImage opacity={0}  resizeMode="ScaleToFill"
                       position={[-0.13, 0.13 , 0.15]}
                       scale={[.2, .2, .2]}
                       source={require("./res/text_membrane.png")}
                       animation={{
                         name: this.state.transTextMembrane,
                         run: this.state.fadeInTextMem}}
            />

            <ViroSpotLight
                innerAngle={5}
                outerAngle={25}
                direction={[0,-1,0]}
                position={[0, 5, 1]}
                color="#ffffff"
                castsShadow={false}
                shadowMapSize={2048}
                shadowNearZ={2}
                shadowFarZ={7}
                shadowOpacity={.7} />

            <ViroQuad
                rotation={[-90, 0, 0]}
                position={[0, -0.001, 0]}
                width={2.5} height={2.5}
                arShadowReceiver={true} />

          </ViroARImageMarker>
        </ViroARScene>`

**Comment by thecoconutstudio** [comment]
Ok I what you are saying.

onFoundMarker2 - Hide Marker 1 Content.

Which works fine, but what if the User goes back to Marker 1, `onAnchorFound` only gets called once?

**Comment by thecoconutstudio** [comment]
..Will it work on Android?

**Comment by faisal3413** [comment]
@thecoconutstudio yes it will work on both platforms. Also, you can use `onAnchorUpdated` callback.
