### ISSUE TITLE
[Question] Ability to only track one image?

### ISSUE THREAD

**Issue by seanyusa** [viromedia/viro#531]
Hi,

I was wonder, if I say 3 images that I want to track (like 3 different logos or something) but I only want to allow one to be tracked at a time (whichever is found first). Is there anyway for this kind of behavior?

Thanks in advance!

**Comment by achuvm** [comment]
Hi @seanyusa,

You can simply add the 3 image markers and if/when the 1st one is found (`onAnchorFound`) you can either remove the other 2, or *only* add your content to the one that's found.

Thanks,

**Comment by seanyusa** [comment]
@achuvm great that makes sense, we've implemented and it's working. Thanks!

Do you know the performance of having many image tracking markers? Is it much difference comparing say 3 markers to 10?

**Comment by dam00n** [comment]
Hi @seanyusa, we have not seen too much difference in performance from 3 - 10 markers. But performance can decrease based on what you are placing in the scene itself. For instance, increasing the number of complex 3D models in the same scene could result in performance slow down.
