### ISSUE TITLE
Add support for new versions of React and React Native

### ISSUE THREAD

**Issue by andorfermichael** [viromedia/viro#534]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
3. Version: 2.13 and 0.58.3

## Description
Please upgrade to new versions of React (16.7.X) and React Native (0.58.X)

**Comment by loic-lopez** [comment]
Many functions are deprecated likes this one `createStrictShapeTypeChecker`

**Comment by tzpr** [comment]
I just started learning ViroReact and noticed that the Quick Start Tutorial fails to start with React Native 0.58.3. The example code uses some modules that are not available in the RN 0.58.3. Like `react-native/Libraries/StyleSheet/StyleSheetPropType` and `react-native/Libraries/StyleSheet/ColorPropType`

**Comment by aedwards12** [comment]
Im having the same issues as @tzprm using RN 0.58.4

**Comment by KimAM** [comment]
Is there any ETA on the next version, and which RN-version do you then plan to support?

**Comment by dam00n** [comment]
We plan to upgrade to RN 0.59. Next release is scheduled for mid-April. We still need to scope the work for the changes but that is the date we are pushing for.

**Comment by Buthrakaur** [comment]
Hi @dam00n , could you share status of the next release, please?

**Comment by dam00n** [comment]
We are doing final testing of the next release today and tomorrow. We then need to submit the testbed app to iOS for approval (24-48 hours) and then the next version will be released. Barring unforseen issues with our test pass, we expect to release by end of this week.

**Comment by dam00n** [comment]
ViroReact v2.14.0 is now live. This version supports RN 0.59.3. We also upgraded to ARCore 1.7. Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases (edited) 

Please note, the latest testbed app will be compatible with the latest version of ViroReact and RN. If you do not wish to upgrade at this time, do not update the Viro Media testbed app on your device.
