### ISSUE TITLE
[Question] - Distance between 2 horizontal planes

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#54]
Hi @achuvm,

I can't figure out how I can calculate the Z distance between 2 horizontal planes.

The first plane I create with the `onPlaneSelected` plane of the `ViroARPlaneSelector` which would be Z = 0. The second plane I create from the `performARHitTestWithRay`, which works great as well.

So the assumption is that both planes are perfectly parallel to each other. I get the X,Y,Z position from the `performARHitTestWithRay(<getCameraOrientationAsync>.forward)` and I can calculate the vector length between the first detected plane and the second `hit-tested` plane but I can nit figure out how I can get the Z-distance between the planes.

Do you have an idea how that can be accomplished?

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

I'm not exactly clear what you mean by the Z distance between the 2 horizontal planes. It sounds like you have 2 positions in the form [x, y, z]. If you want to figure out the Z-distance between them, you could take the difference of the two Z values, ie. `z1 - z2` given positions`[x1, y1, z1]` and `[x2, y2, z2]`. 

Let me know if this isn't what you're trying to compute.

Thanks,

**Comment by dittmarconsulting** [comment]
Hi @achuvm,

Here a quick [sketch](https://www.dropbox.com/s/y82dljwc4ln8ede/File%2016-10-17%2C%204%2012%2025%20pm.jpeg) of what I want to do.

**Comment by achuvm** [comment]
Hmm, according to your sketch I think you want the Y distance, our coordinate system is arranged like the following:

![camera diagram](https://files.readme.io/b891975-viro_camera_diagram.png)

**Comment by dittmarconsulting** [comment]
OF COURSE.

That makes so much sense looking at the `onClick` positions:

```
[0.10103973001241684, -0.20621559023857117, -0.303336501121521]
[-0.006059763953089714, -0.20531690120697021, -0.2372504025697708]
[-0.03331034630537033, -0.20122702419757843, -0.25008729100227356]
...
```

I totally forgot that the camera coordinate system is +90 deg rotated to the world coordinate system where Z is the vertical axis. 

Again, thanks for pointing that out @achuvm .

**Comment by sjt145** [comment]
Hello @dittmarconsulting ,
I too want to find distance between two object i.e distance between my mobile and the object targeted in the camera. It will be really helpful if you can provide code of what you did.
Thank you

**Comment by thecoconutstudio** [comment]
@dittmarconsulting Did you manage to solve this issue, it would be great to some sample code

**Comment by colouredFunk** [comment]
@dittmarconsulting Did you manage to solve this issue, it would be great to see some of the code ? Thanks

**Comment by fdhcastillo** [comment]
same question here :(

**Comment by joshdillner** [comment]
For anyone looking for how to measure distance between two nodes:

https://gist.github.com/joshdillner/bb8bf7825aa5274ab190afb33a4b5b91
