### ISSUE TITLE
Invariant Violation error rendering ViroARSceneNavigator

### ISSUE THREAD

**Issue by SteponasIvasovas** [viromedia/viro#544]
Hello, so i managed successfully build my app with reactviro, launched ios simulator and put some simple code just to make sure it doesn't crash before moving on to working with real devices, but unfortunately it crashes i am not sure what i am doing wrong, i get this error screen :
![image](https://user-images.githubusercontent.com/35025648/52569279-7b58fb80-2e19-11e9-8544-770da366cc99.png)

and this is my render method:
`
  render() {

    return (
      <ViroARSceneNavigator
        apiKey="my_api_key_here"
        initialScene={{
          scene: (
            <ViroARScene>
              <ViroText text="Hello" position={[0, 0, -1]} />
            </ViroARScene>
          ),
        }}
      />
    );

  }
`

Can someone explain what i am doing wrong ?

**Comment by SteponasIvasovas** [comment]
Sorted out this by creating a class that would render ViroARScene and then passed that to class to ViroARSceneNavigator:
` class TestViro extends React.Component {
  render() {
    return (
      <ViroARScene>
        <ViroText text="Hello" />
      </ViroARScene>
    );
  }
}
`

    return (
      <ViroARSceneNavigator
        apiKey="my_api_key_here"
        initialScene={{
          scene: TestViro,
        }}
      />
    );

Still it's weird to me that i have to do this

**Comment by Peege151** [comment]
Good you got it solved!

For me I had to to just run the start up script in the root of the project directory as explained in issue 769 [https://github.com/viromedia/viro/issues/769](url)
