### ISSUE TITLE
Problem with loading VRX files 

### ISSUE THREAD

**Issue by shajadi** [viromedia/viro#546]
## Environment

1. Development OS: Mac
2. Device OS & Version: iOS version 12.1.2
3. Version: "react": "16.6.1",
    "react-native": "0.57.7",
    "react-viro": "2.13.0"
4. Device(s): iPhone 8
## Description

I posted this issue in "pile-blocks-ar (https://github.com/vnovick/pile-blocks-ar/issues/2)" but i think here is a better place to post it, I am trying to run the application and I changed the package.json versions to the newest ones which react-viro offers. I am not being able to load the application due to problem resolving .vrx modules

===

error: bundling failed: Error: Unable to resolve module `./res/tetris/blocks_1.vrx` from `/Users/###/pile-blocks-ar-master/js/GameSceneAR.js`: The module `./res/tetris/blocks_1.vrx` could not be found from `/Users/###/pile-blocks-ar-master/js/GameSceneAR.js`. Indeed, none of these files exist:

* `/Users/###/pile-blocks-ar-master/js/res/tetris/blocks_1.vrx
  ...

===
## Reproducible Demo
Only by running the application with newer version, I keep getting react-native version mismatch error if I don't bump up the versions.

Thanks in advance

**Comment by dam00n** [comment]
Hi @shajadi, have you done step 7 on the upgrade instructions in the release notes -> https://docs.viromedia.com/docs/releases

7. If not already present at project root, create a file named metro.config.js and save it with the following contents...

**Comment by shajadi** [comment]
Hi, Thanks for the heads up, I was missing that file :)
