### ISSUE TITLE
[improvements] Migrate to AndroidX

### ISSUE THREAD

**Issue by loic-lopez** [viromedia/viro#548]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Description
At the moment it is possible to use react-viro for AndroidX?

thanks for reply.

**Comment by achuvm** [comment]
Hi, the latest React-Viro Release 2.15.0 has now been upgraded to AndroidX, see the documentation here:

https://docs.viromedia.com/docs/releases
