### ISSUE TITLE
glTF/GLB models do not render in AR

### ISSUE THREAD

**Issue by silvainSayduck** [viromedia/viro#551]
## Environment
Please provide the following information about your environment:
1. Development OS: macOS Mojave 10.14.2
2. Device OS & Version: iOS version 12.2
3. Version: ViroReact version 2.13.0 and React Native version 0.57.7 
4. Device(s): iPhone 7

-----

`glb` or `gltf` models do not render in AR. This very simple self-contained `glb` file does not use any textures, has only one mesh and is fully valid according to glTF 2.0 specs. It does not render, even after successful loading: https://s3.amazonaws.com/static.sayduck.com/2019.02.18.Sayduck_app_tests/2019.02.18.couch_right.glb

Here is my minimal React code:
```js
class ArScene extends React.Component {
  constructor() {
    super();

    this._onTrackingUpdated = this._onTrackingUpdated.bind(this);
  };

  state = {
    initialized: false,
  };

  _onTrackingUpdated(state, reason) {
    const { initialized } = this.state;
    // if the state changes to "TRACKING_NORMAL" for the first time, then
    // that means the AR session has initialized!
    if (!initialized && state === ViroConstants.TRACKING_NORMAL) {
      this.setState({
        initialized : true,
      });
    }
    if (initialized) {
      if (state === ViroConstants.TRACKING_NONE) {
        // Handle loss of tracking
      }
    }
  };

  _onLoadStart(event) {
     console.log("loading has started", event.nativeEvent.target);
  };

  _onLoadEnd(event) {
     console.log("loading has finished", event.nativeEvent.target);
  };

  _onError(event) {
    console.log("loading failed", event.nativeEvent);
  };

  render() {
    const { initialized } = this.state;
    console.log(initialized);
    return (
      <ViroARScene onTrackingUpdated={this._onTrackingUpdated} >
        <Viro3DObject
          source={{ uri: 'https://s3.amazonaws.com/static.sayduck.com/2019.02.18.Sayduck_app_tests/2019.02.18.couch_right.glb' }}
          type="GLB"
          scale={[ 1, 1, 1 ]}
          position={[ 0, 0, 0 ]}
          onLoadStart={this._onLoadStart}
          onLoadEnd={this._onLoadEnd}
          onError={this._onError}
        />
      </ViroARScene>
    );
  };
};
```

I can see in the console that `initialized` becomes `true`, that `loading has started` and `loading has finished` and there are no errors from the `onError` callback. If I add a `ViroText`, it is visible and tracked properly.

**Comment by dam00n** [comment]
You need to add a light to your scene. Also you should position the model in front of the camera, otherwise you will be inside the model. See code below

```
<ViroARScene onTrackingUpdated={this._onTrackingUpdated} >
      <ViroAmbientLight color="#ffffff" intensity={200}/>
        <Viro3DObject
          source={{ uri: 'https://s3.amazonaws.com/static.sayduck.com/2019.02.18.Sayduck_app_tests/2019.02.18.couch_right.glb' }}
          type="GLB"
          scale={[ 1, 1, 1 ]}
          position={[ 0, 0, -1 ]}
          onLoadStart={this._onLoadStart}
          onLoadEnd={this._onLoadEnd}
          onError={this._onError}
        />
      </ViroARScene>

**Comment by silvainSayduck** [comment]
Awesome, thanks! I was really expecting the object to appear black with no light, so that's why I did not bother. But it seems in this situation, it is just transparent (or not in the scene even maybe).

Thanks again!

**Comment by silvainSayduck** [comment]
Hi,

I'm opening this issue again, because now, textures do not load and the product appear completely black for another glb (also valid against glTF 2.0 specs). I do not see any errors when loading the product, and I have an Ambient Light and an Environment map in the scene (the previous glb without textures now appears as it should).

https://s3.amazonaws.com/static.sayduck.com/2019.02.18.Sayduck_app_tests/2018.08.14.Harney_citron_green.glb

**Comment by silvainSayduck** [comment]
Hi,

I'm opening this issue again, because now, textures do not load and the product appear completely black for another glb (also valid against glTF 2.0 specs). I do not see any errors when loading the product, and I have an Ambient Light and an Environment map in the scene (the previous glb without textures now appears as it should).

https://s3.amazonaws.com/static.sayduck.com/2019.02.18.Sayduck_app_tests/2019.02.21.Teabox.glb

**Comment by dam00n** [comment]
Hi @silvainSayduck, your model shows up black on our end also. But it might be an issue with the model. In our testing, we use sample models posted by Khronos Group and those are appearing correctly. For instance check out BoomBox.glb here -> https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBox

Can you take another look at your model, perhaps there is a setting on export that needs to be added?

**Comment by silvainSayduck** [comment]
Thanks for the heads up, I will try with some other models too!

But this is quite tricky for GLB in general then, since my example passes validation without even so much as an "info" message. See the [official glTF validator](https://github.khronos.org/glTF-Validator/).

**Comment by dam00n** [comment]
We have filed a bug on our end for this model and will see if there are issues on our end as it is conflicting that it shows up on the official validator but not on Viro. Will update when we have more info

**Comment by dthian** [comment]
Hey @silvainSayduck, is it possible to provide the .gltf version of the file? (interested to see what the gltf json manifest is like and if there are possible issues).

**Comment by silvainSayduck** [comment]
Absolutely! Here is a [version with embedded assets](https://s3.amazonaws.com/static.sayduck.com/2019.02.18.Sayduck_app_tests/2019.02.22.Teabox.gltf) and here is a [version with external assets](https://s3.amazonaws.com/static.sayduck.com/2019.02.18.Sayduck_app_tests/2019.02.22.Teabox_separate.zip).

FYI: this command line tool is very nice and easy to use for that kind of tasks: https://github.com/AnalyticalGraphicsInc/gltf-pipeline.

**Comment by Turtleted21** [comment]
Hi,
I try to load a gltf model : 

```<Viro3DObject
    source={require("./res/busterDrone.gltf")}
    resources={[require('./res/busterDrone.bin'),
                require('./res/body_albedo2048.png'),
                require('./res/body_emissive.jpg'),
                 require('./res/body_normal.jpg')]}   
    position={[1, 3, -5]}
    scale={[2, 2, 2]}
    rotation={[45, 0, 0]}
    type="GLTF"/>
```
I have the model, light and diffuse, but look flat, no normal or emissive, I do someting wrong?

Thanks

**Comment by dam00n** [comment]
@Turtleted21 try adding more lighting to your scene. Something like below...

```<ViroARScene>
        <ViroOmniLight
                  intensity={300}
                  position={[-10, 10, 10]}
                  color={"#FFFFFF"}
                  attenuationStartDistance={0}
                  attenuationEndDistance={20} />
             <ViroOmniLight
                  intensity={300}
                  position={[10, -10, 10]}
                  color={"#FFFFFF"}
                  attenuationStartDistance={0}
                  attenuationEndDistance={20} />
            <ViroOmniLight
                  intensity={300}
                  position={[10, -10, 10]}
                  color={"#FFFFFF"}
                  attenuationStartDistance={0}
                  attenuationEndDistance={20} />
             <ViroOmniLight
                  intensity={300}
                  position={[-10, -10, 10]}
                  color={"#FFFFFF"}
                  attenuationStartDistance={0}
                  attenuationEndDistance={20} />
         <Viro3DObject
            source={require('./res/gltf/BoomBox.glb')}
            position={[0, 0, -1]}
            scale={[10, 10, 10]}
            type="GLB"
             />

**Comment by Turtleted21** [comment]
ok thanks looking good now, just no emissive map.

**Comment by dthian** [comment]
Hey @Turtleted21, unfortunately we don't natively support emissive maps at this time for 3d models. You might be able to get around this by manually setting the bloom properties on a given material.

**Comment by dthian** [comment]
Hey @silvainSayduck, I've taken a look at the TeaBox gltf model and also see the incorrect black box on my end. Upon a deeper look, it looks like the root cause is because of the applied AmbientOcclusion textures on the model. When I disable the ambient occlusion textures, the TeaBox renders as expected.

According to the [gLTF Spec for occlusionTexture](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialocclusiontexture):
> The occlusion values are sampled from the R channel. Higher values indicate areas that should receive full indirect lighting and lower values indicate no indirect lighting. 

However, looking at your TeaBox model, it looks like the occlusion textures that are included **instead** have 0 values for the red channels. Hence, this would result in a dark box as you are seeing above. 

Thus, can you confirm if your TeaBox model **matches the gLTF spec as desired**? Thanks!

**Comment by silvainSayduck** [comment]
Hi @dthian 

Thanks for looking into this. It seems that you are correct, and in fact, the occlusion map is completely black... I am not sure how this product looks correct in the [Three.js glTF Viewer](https://gltf-viewer.donmccurdy.com) though.

In any case, I now believe you are correct and the behavior is according to the specs, since the occlusion channel is completely black. This was just a test model exported from Substance Painter, so I am not sure why or how it is done like this.

Thanks again for the support, I hope you can soon take a look at [the issue regarding reflections using glTF](https://github.com/viromedia/viro/issues/561) too.

**Comment by silvainSayduck** [comment]
> unfortunately we don't natively support emissive maps at this time for 3d models

This seems to be the case for emissive color too. Would there be any timeline for adding support for emissive to glTF models?

**Comment by silvainSayduck** [comment]
@dthian @dam00n maybe you missed my last comment? Thanks in advance for the information!
