### ISSUE TITLE
Multiple ViroARTrackingTargets in react viro

### ISSUE THREAD

**Issue by 030131550542** [viromedia/viro#552]
I have faced with this problem. I want create multi image detection application. So I am downloading images from url and alocate them to arrays. So I want create multiple ViroARTrackingTargets. How to do it? Anyone help!

**Comment by dthian** [comment]
Hey @030131550542, please refer to our [documentation](https://docs.viromedia.com/docs/quick-start) when determining which component to use for building an AR experience, where we have multiple guides that may help you out. 

For example, there is a [guide that deals with image markers](https://docs.viromedia.com/docs/ar-image-recognition). You can also refer to our code samples repo [here](https://github.com/viromedia/viro/blob/master/js/ARBusinessCard/BusinessCard.js) for more examples.

**If you are looking for developers to write code for you**, you may be able to find developers who have previously developed with Viro in our [Slack channel](https://virodevelopers.slack.com/join/shared_invite/enQtMzI3MzgwNDM2NDM5LTBiOTRkMDg0Zjc0ODIyYTAxZDczYzFmODJhMDUxZjVhOTk0NGVhMjNlZTY0ZjkxNjMzZGEyNDNlYzc4ZTkzNzQ).

Also, please use github issues for reporting bugs on the platform, **not** for requesting written code for your business application, thanks!
