### ISSUE TITLE
Creating pointer image to real world location

### ISSUE THREAD

**Issue by markfrance** [viromedia/viro#556]
I am able to place objects in real world lat long positions using mercator transform math. However, I need the image at that location to be the same size regardless of how far away the device is from the position. 
This image would be used as a marker to point to locations over 100m away. What would be the best way to achieve this using viro react?

**Comment by dam00n** [comment]
You could find the distance between the 2 positions, your image [x0, y0, z0] and the camera/device [x1, y1, z1], then the distance between the two are:

√( (x0 - x1)2 + (y0 - y1)2 + (z0 - z1)2)

You can grab the camera's position through `ViroARScene`'s `onCameraTransformUpdate` which returns an object w/ the following info:

```
{
  position : [x, y, z],
  rotation : [x, y, z],
  forward : [x, y, z],
  up : [x, y, z]
}
```
You should be able to use the distance to scale the image up relative to the distance from the camera.
