### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by naorzr** [viromedia/viro#557]
Hey guys,
Are there any plans to add TS support for this lib?

Thanks for the great work

**Comment by dam00n** [comment]
Thanks for the kind words. Unfortunately, at this time, we do not have any plans for Typescript support.

**Comment by Hless** [comment]
@naorzr If you still need this, I have generated typescript definitions using react-docgen. It has a complete definitions of all components albeit not very accurate on the return types of some methods (in that case it produces any).

**Comment by naorzr** [comment]
@Hless I longer do, but thanks for the follow up! cheers 🎉
