### ISSUE TITLE
[Question] What are the current limitations of this platform?

### ISSUE THREAD

**Issue by tedjames** [viromedia/viro#56]
Hey guys,

I'm trying to better understand the limitations of Viro, how one would go about making a first-person shooter with Viro and if this platform would be appropriate / scale for an experience as described below.

I'd like to build a VR-based fps game consisting of obj's and animated fbx's for character models all produced within Blender. The main character node would basically be an fbx model w/ several animations for reloading. walking, shooting, etc and I'm assuming that a ViroCamera would be fixed to that particular node in order to produce that FPS perspective. I see raycasting / collision detection is supported so I assume basic shooting mechanics would work. 

The majority of the game would take place in a colosseum/arena where robots and drone progressively spawn in waves, approach and surround the user until they are close enough to attack at which point the user begins to lose health points.

The main objective of this game would be to destroy all enemy robots/drones using various weapons that you unlock, craft, or pick up throughout the game such as swords, pistols, rifles, etc.  

Does this sound like something Viro could help me produce? Or this something best handled by a game engine like Unity?

**Comment by VikAdvani** [comment]
Hi @tedjames, everything you mention is technically possible in our platform. That being said, Viro is an application framework, so FPS was not a use case we optimized for. If you are a React Native/Javascript developer, then it’s worth trying Viro as you will be able to build a lot faster. But if you are already familiar with Unity/Unreal, then you should consider those platforms as they are tailored for games like first person shooters.

**Comment by tedjames** [comment]
Thanks for clearing that up @VikAdvani! I'm going to give Viro a try then since I've never touched Unity or Unreal. I plan on upping my Blender skills and making some smaller games with Viro before progressing to a first person shooter.

**Comment by dthian** [comment]
Hi @tedjames, just an fyi [here](https://github.com/viromedia/viro/blob/master/js/PhysicsSample/BasicPhysicsSample.js) is a good sample code that may be helpful for "shooting and applying a force from your controller".
