### ISSUE TITLE
Using react-native-sensors with Viro project

### ISSUE THREAD

**Issue by markfrance** [viromedia/viro#560]
I'm trying to add gyroscope functionality to my react viro app created using the viro hello world project.

When running the app after installing react-native-sensors I get 'Native modules for sensors not available. Did react-native link run successfully?'

react-native link did run successfully and I tried following steps to link manually too. Is there a compatibility issue with packages like this? 

I noticed there was an issue with react-native-maps and Viro, is this the same sort of issue or is it something different that I need to do?
https://github.com/viromedia/viro/issues/254#issue-318164505

**Comment by dam00n** [comment]
Hi @markfrance, if you are using the Viro testbed app for development, it does not support new modules/components.

To use a module like react-native-sensors, you will have to compile and run your app using Android Studio or XCode.

**Comment by CosminNechifor** [comment]
Hi @markfrance you could link Viro manually to your React Project by following this guide https://docs.viromedia.com/docs/integrating-existing-projects-android or you could simply add the differences from this gist: https://gist.github.com/manbod/5a7f7d0511ff4b4c7f78086ee4706932#file-android_setup-diff and then as @dam00n said you will have to compile and run your app on your phisical device.
