### ISSUE TITLE
2D button overlay help

### ISSUE THREAD

**Issue by Geli25** [viromedia/viro#565]
Hi, 

I have been trying to mimick the ARSample app by making a "back" button UI on the top but I have not been able to include one yet. Once I put the ARNavigator inside a View the camera view is completely blocked. I am just wondering what I may be doing wrong? I have checked the other issues related to this as well, but just wanted some help. 

```      
<View styles={localStyles.outer}>
        <ViroARSceneNavigator {...this.state.sharedProps}
          style={localStyles.arView}
          initialScene={{ scene: InitialARScene }}
          viroAppProps={this.state.viroAppProps} />
        <View style={{ position: 'absolute', left: 0, right: 0, bottom: 77, alignItems: 'center'}}>
        <TouchableHighlight style={localStyles.buttons}
          onPress={this._exitViro}
          underlayColor={'#68a0ff'} >
          <Text style={localStyles.buttonText}>Go back</Text>
          </TouchableHighlight>
        </View>
      </View>
```

Thanks!

**Comment by Geli25** [comment]
Update: I was able to have a button on the top by removing the View and using a React.Fragment to wrap around the components. But there's a white bar on the top where the button is. How do I get rid of it and have a nice floating 2D UI that's embedded within the camera view? Like how it is with back arrow button the AR Sample App in the ViroMedia app.

**Comment by dam00n** [comment]
Check out our open sourced app Figment AR. You can see how we implemented floating buttons there -> https://github.com/viromedia/figment-ar

**Comment by Geli25** [comment]
Thanks! I was able to get it working. I will close this issue now.

**Comment by AWZRD** [comment]
For those who end up running into this issue, 
`
      <View style={{ flex: 1 }}>
        <ViroARSceneNavigator
          style={{ flex: 1 }}
          ref={this.navigatorRef}
          autofocus={true}
          initialScene={{
            scene: HelloWorldSceneAR,
            passProps: { image: that.image /*passes image callback function*/ }
          }}
        />
        <View style={{ position: 'absolute', left: 0, right: 0, bottom: 60, justifyContent: 'center', alignItems: 'center'}}>
     
        </View>
      </View>
`
Make sure your view has an absolute position after ViroARSceneNavigator

**Comment by AWZRD** [comment]
For those who run into this issue, make sure your view has absolute position
