### ISSUE TITLE
Any thoughts on a Flutter release?

### ISSUE THREAD

**Issue by kevinrodriguez-io** [viromedia/viro#567]
Hi guys

I'm opening this issue just to know if you have any support planned for Flutter;
Flutter has already support for embedding Native iOS/Android views, (You can take Flutter Google Maps as an example).

Flutter projects support iOS Cocoapods and I'm pretty sure they do support additional Android libraries.

The idea would be a port from ViroReact, and I'm pretty sure it's a possible thing to do.

I'd be willing to help :smile:

**Comment by dam00n** [comment]
Hi Kevin, thanks for reaching out and for the offer to help. At this time, we are focused on our two core products, ViroReact and ViroCore (Java). But Flutter is something we will consider for the future if we add more language support. Will definitely hit you up then. Again, thanks for the suggestion and offer to help.

**Comment by aytunch** [comment]
I think it is time for Flutter support :)
Even RN now is taking advantage of Skia
