### ISSUE TITLE
Feature Request: Support for Gif and animated Gif

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#57]
Hi, is there any way to add some gif images ?

I have seen that react native support it but it's not animated once built.

Thanks for your help

Michael

**Comment by VikAdvani** [comment]
Hi @Zirconiumirish,
Viro currently doesn't support gif images. We plan to add support in the future. We'll keep this issue open and update it once support is added.

**Comment by dam00n** [comment]
Animated Gifs support added in ViroReact 2.10 -> Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

**Comment by SobanQureshi** [comment]
> Animated Gifs support added in ViroReact 2.10 -> Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

How will we use animated gif in AR scene
