### ISSUE TITLE
Remote source file for Viro3DObject doesn't work on Android

### ISSUE THREAD

**Issue by kuzkokov** [viromedia/viro#572]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android 8.1.0
3. Version: ViroReact 2.13.0 and React Native 0.57.7 
4. Device(s): Huawei Honor 10

## Description
Hello! I'm trying to implement a simple AR feature in my app: showing 3d model on the `ViroARScene` using `Viro3DObject`. So far it worked fine with local `.obj` models, but now I'm trying to use the remote one, and an object doesn't appear on the screen on Android device. It appears on the iPhone emulator though.
I'm not sure how can I even debug it. Both `onLoadStart` and `onLoadEnd` callbacks are running, and onError is not. Maybe you have any thoughts?

## Reproducible Demo
Here is my component with model: https://pastebin.com/AudjGiGh

**Comment by masierraf** [comment]
@kuzkokov Did you find a solution to your problem? i got same problem and nothing yet

**Comment by kuzkokov** [comment]
@masierraf hi!
well, it appears that onLoadingEnd was working correctly, and the problem was with lightnings. Try to use different lightnings, and maybe the model will appear.
But as I understand, and as it's mentioned in docs, remote files could have only .obj extension

**Comment by dthian** [comment]
> remote files could have only .obj extension

Hi @kuzkokov, where do you see this mentioned again? You should able to load remote files of type .obj / .vrx / .gltf.

**Comment by masierraf** [comment]
My problem was the size of the models because when it size is under 5MB everything goes well but when it size is 6Mb or more the time of loading models is to long. any idea to solve this?
