### ISSUE TITLE
ARcore Trackable on ViroReact

### ISSUE THREAD

**Issue by fraviloria** [viromedia/viro#576]
Can we use ARcore Trackable function on Android as continuous image tracking of iOS ?

**Comment by fraviloria** [comment]
Hello Viro,

Would we like to know if the new ViroReact Version 2.14.0 was included ARCore trackable feature for an android ??

**Comment by dam00n** [comment]
"ARCore cannot track a moving image, but it can resume tracking that image after it stops moving." -> https://developers.google.com/ar/develop/c/augmented-images/

**Comment by fraviloria** [comment]
So.., this feature is only for face tracking? —> https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/Trackable
