### ISSUE TITLE
ARCore with React Native?

### ISSUE THREAD

**Issue by jalqueza** [viromedia/viro#577]
Curious to know if it's possible to use the ARCore trackable feature for an android application in react native.

**Comment by fraviloria** [comment]
Hello Viro,

Would we like to know if the new ViroReact Version 2.14.0 was include ARCore trackable feature for an android ??

**Comment by achuvm** [comment]
Hi, Viro React v2.15.0 has been upgraded to support ARCore 1.10.0 w/ the continuous image tracking.

https://docs.viromedia.com/docs/releases
