### ISSUE TITLE
Render Viro3DObject from remote location

### ISSUE THREAD

**Issue by masierraf** [viromedia/viro#579]
- [X] Review the documentation: https://docs.viromedia.com/
  - [X] Search for existing issues: https://github.com/viromedia/viro
  - [X] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac Mojave 10.14.3 
2. Device OS & Version: Android 9.0 and Android 8.0
3. Version: ViroReact 2.13.0 and React Native: 0.57.7 
4. Device(s): Huawei Mate 20 Pro and Samsung Galaxy S8

## Description
Im trying render a 3d Object with  Viro3DObject using url for source and resources and it doesn't work, before try with url tried with local files and it works fine so trying find a solution i found that can be problem of the http url but it doesn't work neither.

## Reproducible Demo

My dependences are:

```js
"dependencies": {
    "axios": "0.18.0",
    "jwt-decode": "2.2.0",
    "native-base": "^2.11.0",
    "react": "16.6.1",
    "react-native": "0.57.7",
    "react-native-fast-image": "^5.2.0",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-swiper": "^1.5.14",
    "react-navigation": "3.5.1",
    "react-viro": "2.13.0"
  }
```

and the way that i try to render objects is like this: 

```html
<ViroARScene onTrackingUpdated={this._onInitialized}>
        <ViroAmbientLight color="#FFFFFF" />
        <Viro3DObject
         source={{ uri: "http://example.com/uploads/object.obj" }}
            resources={[
              { uri: "http://example.com/uploads/object.mtl" },
              { uri: "http://example.com/uploads/objectTex1.jpg" },
              { uri: "http://example.com/uploads/objectTex2.jpg" }
            ]}
          highAccuracyEvents={true}
          position={[1, 3, -5]}
          scale={[2, 2, 2]}
          rotation={[45, 0, 0]}
          type="OBJ"
          transformBehaviors={["billboard"]}
        />
      </ViroARScene>
```

the render works when i use require() like this:
```html
<ViroARScene onTrackingUpdated={this._onInitialized}>
        <ViroAmbientLight color="#FFFFFF" />
        <Viro3DObject
          source={require("./../public/models/object.obj")}
          resources={[
            require("./../public/models/object.mtl"),
            require("./../public/models/objectTex1.jpg"),
            require("./../public/models/objectTex2.jpg")
          ]}
          highAccuracyEvents={true}
          position={[1, 3, -5]}
          scale={[2, 2, 2]}
          rotation={[45, 0, 0]}
          type="OBJ"
          transformBehaviors={["billboard"]}
        />
      </ViroARScene>
```

I've been searching some information almost a week and nothing, i hope someone can help me.

Thanks and sorry for my english.

**Comment by osho1278** [comment]
any update on this ?  i am also struck here

**Comment by masierraf** [comment]
@osho1278 In my case it was that the files were very heavy and took too long to load, I made some modifications to the files by lowering the quality of the textures and that made them load faster, however they continue to take approximately 10 seconds depending of internet speed (I have 10 mb). 

I've been trying with model glb (another format of objects) but remotly it doen't work for me.

**Comment by osho1278** [comment]
@masierraf i want to add some uri in resources ...any help with that ?
```

<Viro3DObject
          source={require("./../public/models/object.obj")}
          resources={[
            uri:'http://path-to-mtl-files'
            
          ]}
          highAccuracyEvents={true}
          position={[1, 3, -5]}
          scale={[2, 2, 2]}
          rotation={[45, 0, 0]}
          type="OBJ"
          transformBehaviors={["billboard"]}
        />
```

**Comment by AliKHODR** [comment]
@osho1278 @masierraf Hey, i have the same problem, did anyone find a solution?

**Comment by jp928** [comment]
+ 1 here.

**Comment by jp928** [comment]
For me, I am curious how to refer a internet image in mtl file.
If I open the .mtl file in text editor it would like something below:

```
# Blender MTL File: 'plant.blend'
# Material Count: 1

newmtl palnt
Ns 323.999994
Ka 1.000000 1.000000 1.000000
Kd 0.457530 0.457530 0.457530
Ks 0.077952 0.077952 0.077952
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Bump C:\\Users\\NKUR\\AppData\\Local\\Temp\\Rar$DIa5356.8244\\texture\\palnt_N.png
map_Kd C:\\Users\\NKUR\\AppData\\Local\\Temp\\Rar$DIa5356.8244\\texture\\palnt_B.png
map_Ns C:\\Users\\NKUR\\AppData\\Local\\Temp\\Rar$DIa5356.8244\\texture\\palnt_R.png
refl C:\\Users\\NKUR\\AppData\\Local\\Temp\\Rar$DIa5356.8244\\texture\\palnt_M.png
```

It looks like the images have to to a path.

**Comment by sanoopks** [comment]
Same here, stuck on how to load resources from a remote location.

**Comment by sascha-kaleidoscode** [comment]
Did anyone ever find a solution for that?

**Comment by osho1278** [comment]
yes .. i was able to do it ...
try with obj files and keep file size short

**Comment by Jaiswal-Siddhant** [comment]
I had same problem so I converted OBJ and MTL file to single GLB and placed it in models folder in server following is code to send an GLB model from server: 

## Server
```Node
const express = require('express');
const app = express();
const port = 3000;
const path = require('path');

app.get('/:model', (req, res) => {
    console.log(req.params.model);
    res.status(200).sendFile(path.join(__dirname, `./models/${req.params.model}.glb`));
})
app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```

## Client 
```Node
<Viro3DObject
    source={{ uri:  'http://YOUR_IP_ADDR:PORT/model/Headphones' }}
    scale={[0.05, 0.05, 0.05]}
    position={[0.0, 0.0, -5]}
    type="GLB"/>
```

**Comment by zolboo918** [comment]
Did anyone find a solution?

**Comment by sanoopks** [comment]
@zolboo918 Are you looking for solution to load 3d object from remote location or material file from remote location. I mean the mtl file for obj. 

Could you tell me which 3d format are you using?

**Comment by zolboo918** [comment]
@sanoopks, thanks for replying. I am using VRX model and VRX file loaded from remote fine. But without resource files my 3D animated object is not colored and looking white. VRX file with the same directory resource files is looking good.  How should i render my VRX 3D model with color?
