### ISSUE TITLE
Ngrok dependency prevents react-viro install

### ISSUE THREAD

**Issue by lexieheinle** [viromedia/viro#58]
Hello,
I'm unable to `npm install react-viro` due to the postinstall of ngrok globally erroring out due to insufficient permissions.  From #44, it seems like I can use viro without ngrok. How do I install viro given that the install fails on the postinstall process?

**Comment by achuvm** [comment]
Hi @lexieheinle,

Thanks for bringing this to our attention.

Unfortunately we install `ngrok` as a post-processing step, so `react-viro` fails to install when that step fails. So you'll have to install react-viro manually by following the steps below:

1. Go to your new project, when the install failed, it should have installed `react-native`, you can check this by seeing that `<project_name>/node_modules/react-native` is there.
2. From within the root of your project, run `npm install -S -E react-viro --ignore-scripts` which will install `react-viro` without installing `ngrok`. This should install the latest `react-viro` version (2.0.1) and add it to your `package.json`.

Now, we need to run the extra commands that the `react-viro init` script failed to run. Run these commands from the root of your project:
1. `./node_modules/react-viro/bin/javascript-setup.sh <project_name> false` where project name is the name of your project (it should match `react-viro init <project_name>`)
2. `cp ./node_modules/react-viro/bin/setup-ide.sh .`
3. `chmod +x setup-ide.sh`
4. `mkdir bin`
5. `cp ./node_modules/react-viro/bin/ViroFBX bin`

That should now set up your project to work with `react-viro`. If you want to use Android Studio or Xcode vs. our testbed application, you'll need to run the `setup-ide.sh` script.

Let me know if that doesn't work! We'll look to making it fail more gracefully in the future. Thanks!

Andy

**Comment by achuvm** [comment]
Hi @lexieheinle,

Thanks for reporting this issue to us, we've since fixed the issue. The `npm install` command should no longer fail if our attempt to install ngrok globally fails.

Closing this issue now, feel free to re-open if you have more comments or feel free to create a new issue.

**Comment by mypark** [comment]
I'm getting this issue again - was working on my other computer ... is it the react-viro client version number that's the issue? 

react-viro-cli 2.6.1

**Comment by mypark** [comment]
I installed ngrok globally and that seems to have fixed the issue.
