### ISSUE TITLE
[Question] - Abstract out ViroMaterials.createMaterials() in separate file

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#59]
Hi @achuvm,

I'm wondering whether it's possible to have all ViroMaterials in a separate file?

In RN one can do something like that:
```
const Styles = React.StyleSheet.create({
   style1: { },
   style2: { }
)}

export default Styles
```
to abstract the styles out of the component. Later the user can import and use these styles in any other component:
```
import Styles from '../path/to/Styles'
<View style = {Styles.style1} />
```

Since the `material` property only accepts a string
```
<ViroSurface
   rotation={[-90,0,0]}
   width={.2}
   height={.2}
   materials={'myMaterial'} />
```
I'm not sure how to that can be accomplished. 

Thanks in advance,
Thomas

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

Actually, yes. The material registration logic is actually global and lives for the duration of your application, so you can register all your materials at the start and then refer to them simply by the string from anywhere.

Thanks,

Andy

**Comment by dittmarconsulting** [comment]
Hi Andy,

That's cool.

Just by importing it the materials are available throughout the project. 

```
 /*eslint-disable no-unused-vars*/
import Materials from '../components/Materials'
```
