### ISSUE TITLE
App (iOS) freezes with worldAlignment="GravityAndHeading" and Compass Calibration turned off

### ISSUE THREAD

**Issue by sanderwapstra** [viromedia/viro#595]
If a user has the setting `Settings > Privacy > System Services > Compass Calibration` turned off in their iPhone the camera freezes without a message. Is this something that should be checked in Viro?

```
<ViroARSceneNavigator
    worldAlignment="GravityAndHeading"
    apiKey={KEY}
    initialScene={{...}}
/>
```

Excerpt from errors in xcode:
```
ARDeviceOrientationSensor: error received from motion manager:
Error Domain=CMErrorDomain Code=102 “Failed to get true north.”
UserInfo={NSLocalizedRecoverySuggestion=Location Services must be available and enabled for System Services > Compass Calibration.
NSLocalizedFailureReason=Unable to access location.
Error Domain=com.apple.arkit.error Code=102 “Required sensor failed.” UserInfo=NSLocalizedFailureReason=A sensor failed to deliver the required input.
NSLocalizedFailureReason=Unable to access location.
NSLocalizedRecoverySuggestion=Make sure that the application has the required privacy settings.
NSLocalizedDescription=Required sensor failed.
```

**Comment by dam00n** [comment]
This appears to be an issue with ARKit needing compass to be on -> https://stackoverflow.com/questions/49058263/arkit-setting-worldtrackingconfiguration-to-gravityandheading-produces-error

You should check to see if the setting is off and prompt the user to turn it on before starting your AR scene.

**Comment by sanderwapstra** [comment]
@dam00n Is this something you can check in React Native? Thanks for your help!

**Comment by dam00n** [comment]
Here is a good resource for checking permission in RN -> https://github.com/yonahforst/react-native-permissions

**Comment by sanderwapstra** [comment]
We already had [react-native-simple-compass](https://github.com/vnil/react-native-simple-compass) installed which returns `-1` when Compass Calibration is turned off and used that for now. Thanks @dam00n!
