### ISSUE TITLE
Does Viro-React allow for extended tracking?

### ISSUE THREAD

**Issue by jungley** [viromedia/viro#596]
Hi does Viro-React allow for extended image tracking? 

The scenario is that the user scans an image, and a 3D environment is instantiated on the marker. 
When the camera the stops tracking the marker the 3D environment should not be lost and the user should still be able to track the 3d model that was instantiated on scanning the marker.

Is this possible?

**Comment by jungley** [comment]
Yes it is allowed. Sorry if this was a pedestrian question I am new to Viro.

**Comment by fixed-term-tylernguyen** [comment]
How were you able to resolve this?
