### ISSUE TITLE
Not able to Generate Signed APK

### ISSUE THREAD

**Issue by krishanjangir** [viromedia/viro#603]
Not able to generate Signed APK getting below error.    
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-viro": "2.14.0"

Unable to resolve module 

      `react-native/Libraries/DeprecatedPropTypes/DeprecatedStyleSheetPropType` from 
      `/Users/krish/Documents/work/odoori/odoori/node_modules/react- 
        viro/components/ViroImage.js`: Module `react- 
        native/Libraries/DeprecatedPropTypes/DeprecatedStyleSheetPropType` 

does not exist in the Haste module map

**Comment by ajaxsys** [comment]
Maybe 2.14.0 only work with react-native 0.59?

**Comment by krishanjangir** [comment]
i have upgraded my react version now working fine.
