### ISSUE TITLE
Document usage of AWS libraries?

### ISSUE THREAD

**Issue by cristianoccazinsp** [viromedia/viro#613]
I'm curious about what's the usage of AWS DynamoDB and Cognito. Are you using this to validate your API keys? What else are you sending to AWS?

**Comment by dam00n** [comment]
Yes, we use these libraries to validate our API keys.

**Comment by radvani** [comment]
To clarify, nothing else is sent to AWS; these services are purely used for API validation.

**Comment by zamphear** [comment]
Can you clarify also how often you validate the api key?  Sorry for replying to a closed thread.

**Comment by dam00n** [comment]
https://github.com/viromedia/viro/issues/610
