### ISSUE TITLE
Dynamic object targets not working.  

### ISSUE THREAD

**Issue by yashank09** [viromedia/viro#622]
Hello! 
I'm using a `JSON` object to feed `ViroARTrackingTargets` in order to dynamically arrange my markers. I followed this very informative issue [https://github.com/viromedia/viro/issues/272](url) however I keep getting an error which I have figured has to do with the `required` property of `createTargets.source`. Is there any way I could not enforce the required property or send it through my JSON ? Or is it just the way i'm implementing this feature that's giving me bugs?  

JSON : 
`[
  {
    "id": "target_1",
    "source": "./assets/abc.jpg",
    "physicalWidth": 1,
    "orientation": "UP"
  },
  ...
]`

App.js : 
`componentDidMount() {
    ViroARTrackingTargets.createTargets(
      fakeData.map(art => {
        art.id = {
          source: art.source,
          physicalWidth: art.physicalWidth,
          orientation: art.orientation
        };
      })
    );
  }`

I'm using Viro-react with the following versions -
"react": "16.8.3",
"react-native": "0.59.3",
"react-viro": "2.14.0"

**Comment by JackSoby** [comment]
I am having this same issue @yashank09 Did you find a solution?
