### ISSUE TITLE
glTF roughnessFactor/metallicFactor ignored when a metallicRoughnessTexture is used

### ISSUE THREAD

**Issue by silvainSayduck** [viromedia/viro#623]
On the latest version of Viro (2.14.0), there are still inconsistencies with the glTF specifications: basically the `roughnessFactor` or `metallicFactor` are ignored when a `metallicRoughnessTexture` is used.

See the below test case for `metallicFactor`:

![](https://i.imgur.com/luOx991.png)

From left to right:
1. No `metallicRoughnessTexture`, `metallicFactor` is set to 0
2. A white texture is used for the metalness, resulting in a fully white `metallicRoughnessTexture`, `metallicFactor` is set to 0
3. A black texture is used for the metalness, resulting in a fully yellow `metallicRoughnessTexture` (blue channel is zeroed), `metallicFactor` is set to 0
4. A white texture is used for the roughness, resulting in a fully white `metallicRoughnessTexture`, `metallicFactor` is set to 0
5. A white texture is used for both metalness and roughness, resulting in a fully white `metallicRoughnessTexture`, `metallicFactor` is set to 0
6. A white texture is used for the roughness, a black texture is used for the metalness, resulting in a fully yellow `metallicRoughnessTexture` (blue channel is zeroed), `metallicFactor` is set to 0

Considering that `metallicFactor` is always set to 0, those six cubes should always appear exactly the same according to the glTF specifications, and they should be non-metallic.

We can see from the image that when a blue channel is present on the `metallicRoughnessTexture`, the cube is metallic, regardless of the fact that the `metallicFactor` is set to 0. So cubes 2, 4 and 5 are wrong.

This is quite problematic as it cannot be easily worked-around. For example in the case of a model with a roughness texture, but where metalness is defined from the `metallicFactor` without any texture. Currently, those models are always fully metallic, which is incorrect.

Here is the [glTF of the cubes](https://staging-cdn.sayduck.io/a/shared_assets/files/000/024/593/0956377290f071991999a19a1a6e21f79f633ca3d18c0cadb70b4f2c332d3319-original.gltf?v=1557836853), and a screenshot from the [three.js glTF online Viewer](https://gltf-viewer.donmccurdy.com/):

![](https://i.imgur.com/7nDZeR0.png)

**Comment by dam00n** [comment]
This issue has been fixed in the latest release, ViroReact 2.15.0

Release Notes -> https://docs.viromedia.com/docs/releases

**Comment by silvainSayduck** [comment]
I can confirm after a short test that this now seems to work as expected! I will update if something comes up after more in-depth testing.

Thanks a lot for the great work.
