### ISSUE TITLE
Request For Cardboard Button On Player Screen

### ISSUE THREAD

**Issue by tuananhcwrs** [viromedia/viro#631]
## Description
Hello Viro team,

I would like to ask for a feature that already existing in Google VR Video (Or in youtube). There you will see that there is a cardboard button (a cardboard icon ^_^ ).

The cardboard button/icon will display when the video play in mono mode (still 360 and users move their phone around to see), user click on it to switch to VR mode. Does it sound promising?

Or you think that tapping on the screen to switch mode is good enough?

Thanks.

**Comment by tuananhcwrs** [comment]
Hello @dthian ,

What do you think about this request?

**Comment by dthian** [comment]
> The cardboard button/icon will display when the video play in mono mode (still 360 and users move their phone around to see), user click on it to switch to VR mode. Does it sound promising?

The above sounds like an awesome video application that developers can build.  Sure, you can use the Viro platform sdk to build this experience - we should be able to support this case.

> What do you think about this request?

Unfortunately, Viro is not a dev shop at the moment - our main focus is to add support and fix issue that are found on the platform, and we are not an "applications building team", but more like a "Frameworks team". One thing you can try is to reach out to other devs in our Slack channel and see if they might be willing to build such an application for you.

**Comment by tuananhcwrs** [comment]
Thank @dthian for your information.
