### ISSUE TITLE
Pinch to Zoom problem with pivot scale 

### ISSUE THREAD

**Issue by masierraf** [viromedia/viro#632]
- [ X] Review the documentation: https://docs.viromedia.com/
  - [ X] Search for existing issues: https://github.com/viromedia/viro
  - [ X] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android OS 9.0
3. Version: ViroReact 2.14.0 and React Native 0.59.3 
4. Device(s): Huawei Mate 20 Pro and Samsung Galaxy s8

## Description
I'm using the figment application to try to make a similar application, but when I do pinch to zoom on the 3d object, the zoom works but it does not take the center of the object using one of the sides of the object to do the scaling which makes the position of the object change.

I tried putting prop pivotScale but it did not work or I could not make it work

## Reproducible Demo
This is my code:

``` javascript

  _refARObject = component => {
    this.arObject = component;
  };

  render() {
    const { dish } = this.props;

    return (
      <ViroARScene
        onTrackingUpdated={this._onInitialized}
        ref={component => (this.arscene = component)}
        minHeight={0.22}
        minWidth={0.22}
      >
        <ViroARPlaneSelector
          
          minHeight={0.22}
          minWidth={0.22}
          onPlaneSelected={() => this.props.anchorFound()}
        >
          <ViroAmbientLight color="#FFFFFF" />
          <ViroNode
            position={this.state.positionRoot}
            scale={this.state.scale}
            rotation={this.state.rotation}
            ref={this._refARObject}
            onDrag={() => {}}
            dragType={"FixedDistance"}
          >
            <ViroNode position={this.state.position}>
              <Viro3DObject
                source={{ uri: dish.obj }}
                type="OBJ"
                resources={[
                  { uri: dish.mtl },
                  { uri:  dish.tex1 },
                  { uri: dish.tex2 }
                ]}
                onPinch={this._onPinch}
                onError={err => console.log("error: ", err)}
                onLoadStart={this._onLoadStart}
                onLoadEnd={this._onLoadEnd}
              />
            </ViroNode>
          </ViroNode>
        </ViroARPlaneSelector>
      </ViroARScene>
    );
  }

  _onPinch = (pinchState, scaleFactor, source) => {
    let newScale = [
      this.state.scale[0] * scaleFactor,
      this.state.scale[1] * scaleFactor,
      this.state.scale[2] * scaleFactor
    ];

    if (pinchState == 3) {
      this.setState({
        scale: newScale
      });

      return;
    }


    this.arObject.setNativeProps({ scale: newScale });
  };

```

Gif Demo:

![20190519_214027](https://user-images.githubusercontent.com/5935896/57997442-814a2280-7a81-11e9-92f3-43b4c090fe64.gif)

**Comment by masierraf** [comment]
Any ideas?

**Comment by dam00n** [comment]
Could this be related to the origin of the OBJ model? If you reset the origin of the model to the center does the scaling work as you expect?

**Comment by dthian** [comment]
@masierraf you are scaling the container that has a 3D model positioned in **with an offset** within that container. So when you scale that container, the offset will scale as well, causing the object to shift. 

Instead of scaling the container, scale the 3d object instead.

**Comment by masierraf** [comment]
> Could this be related to the origin of the OBJ model? If you reset the origin of the model to the center does the scaling work as you expect?

@dam00n do you mean that maybe the problem is the obj creation?

**Comment by masierraf** [comment]
> @masierraf you are scaling the container that has a 3D model positioned in **with an offset** within that container. So when you scale that container, the offset will scale as well, causing the object to shift.
> 
> Instead of scaling the container, scale the 3d object instead.

@dthian I will try it and will comment you if worked or not. I mean i've trying so many ways to make it works as I saw in figment app maybe the problems are because that idea.

**Comment by masierraf** [comment]
> > @masierraf you are scaling the container that has a 3D model positioned in **with an offset** within that container. So when you scale that container, the offset will scale as well, causing the object to shift.
> > Instead of scaling the container, scale the 3d object instead.
> 
> @dthian I will try it and will comment you if worked or not. I mean i've trying so many ways to make it works as I saw in figment app maybe the problems are because that idea.

I did it but it did't worked,  when i drag the object with DragType FixedDistance and do Pinch to zoom  get a scaling different, so my question now is how can i know that my obj has the correct settings?

This is what i have:

SIDE:
![obj_side](https://user-images.githubusercontent.com/5935896/58190268-fdef2380-7c70-11e9-8910-9b317f6db9cb.jpeg)


OVER:
![obj_over](https://user-images.githubusercontent.com/5935896/58190273-00517d80-7c71-11e9-969f-95f73c0a1037.jpeg)

**Comment by ydv0121** [comment]
@masierraf how did you solve this? can you guide me in this please?

**Comment by masierraf** [comment]
@ydv0121 well, I do not did the models I only used it, my partner used maya software (i never used it) to setting the epicenter correctly but I don’t know how exactly he did it.
