### ISSUE TITLE
[Question] - Offset ViroARPlane

### ISSUE THREAD

**Issue by dittmarconsulting** [viromedia/viro#64]
Hi @achuvm,

Is it possible to offset the `ViroARPlane`?

In my app I get the ground surface via `ViroARPlane`. After that I do 4 a hit tests on a second surface to average the Y coordinate, which works very well.

As far as I understand the VIRO lib, objects can only be positioned on a `ViroARPlane`. Hence, I want to place a new `ViroARPlane` on the second surface so that I can position other elements on top of it.

Is there a way to accomplish that?

Thanks

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

If you have a position in 3D space that you want to use, you can use a [ViroNode](http://docs.viromedia.com/docs/viroview) to anchor elements relative to that position.

Let me know if that's what you're looking for.

Andy

**Comment by dittmarconsulting** [comment]
Hi Andy,

All I have is the Y position relative to the original ground plane. Something like that:

![plane_offset](https://user-images.githubusercontent.com/19203201/31869461-f18228a6-b7f3-11e7-87a2-1324215d8b31.jpg)

while the blue surface is the discovered surface and the pink surface is the hit-tested surface.

I want to further hit-test on the pink surface to position elements on it. Hence, I don't have the 3D points only the Y-coordinate.

I hope that makes sense.

**Comment by achuvm** [comment]
Hi @dittmarconsulting,

This is essentially doing a ray-plane intersection calculation and its formula can be found here: https://www.cs.princeton.edu/courses/archive/fall00/cs426/lectures/raycast/sld017.htm

However, if you add a component to the pink surface (say a `ViroSurface`), if you add an `onClick` handler to that component, the function will be invoked like so: `onClick(position, source)` where position is the `[x, y, z]` intersection point. This point will be on the pink surface, if you don't *want* to add a surface, you can always add a `ViroSurface` with a diffuse color of `#ffffff00`, thus making an invisible surface (the alpha channel is set to 0).

Let me know if that makes sense,

Andy

**Comment by dittmarconsulting** [comment]
Thanks Andy,

I will try that tomorrow and report back to you.

Cheers,
Thomas

**Comment by dittmarconsulting** [comment]
That works great but I found the ray-plane intersection calculation interesting as well. I might need that later on.

Thanks Andy
