### ISSUE TITLE
Cannot use React Native elements

### ISSUE THREAD

**Issue by yashank09** [viromedia/viro#640]
I'm unable to use any react-native element like View or Text, and I also can't use any theme library. Is this a Viro-React bug or something special needs to be done inorder to use them ? I'm using Viro-React with testbed app. 

Error I get - 'Cannot add non-component child of type - ReactView'

Any help?

**Comment by masierraf** [comment]
Are you putting the components in Scene or are you putting it in SceneNavigator? 

Im using native-base but i guess that with react-native-elements will works too.


```javascript
<View>
<ViroARSceneNavigator
   {...this.state.sharedProps}
   initialScene={{
   scene: HelloWorldSceneAR
   }}
   ref={this._setARNavigatorRef}
   autofocus={true}
   />
   <View
      style={{
      position: "absolute",
      flex: 1,
       flexDirection: "row",
       justifyContent: "space-around",
       top: 30,
       width
        }}
       >
         <Text
            style={{ color: "white", fontSize: 14, fontWeight: "bold" }}
           > ...
           </Text>
    </View>
</View>
```

**Comment by dthian** [comment]
Thanks all, unfortunately we do not support the rendering of non-Viro elements within the AR/VR environments, as they do not necessarily translate properly into 3d space.

However, having said that, you should be able to use ViroTexts or ViroFlexViews to achieve the same effect.

**Comment by yashank09** [comment]
Thanks for the replies guys. So from my understanding, there is no way we can use a CSS library with viro-react then? Also, on using ViroFlexView along with ViroText, i'm getting some very shaky AR interface. This is why I wanted to use native elements. Any fixes for this ? If not, this issue can be closed.

**Comment by VikAdvani** [comment]
Hi @yashank09,
You can use native elements for 2d overlays with Viro React  *but* only Viro elements are allowed within the **ViroARSceneNavigator** for 3d UI/UX.

Here's an example of an app that uses native elements for the 2D UI:
https://github.com/viromedia/ViroARSampleApp

**Comment by yashank09** [comment]
@VikAdvani Thank you for the quick response! So basically we are able to use native elements in the components before we launch the AR scene ?  Once in the scene we have our viro elements that we can use ?
