### ISSUE TITLE
Better search engine in docs

### ISSUE THREAD

**Issue by keyserfaty** [viromedia/viro#643]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Description
Hi, was wondering if you are open to replacing the search mechanism you have on the docs site with something like Algolia. I usually find it hard to find what I'm looking for. Algolia is usually free for open source projects. I'm happy to open a PR if you'd like to.

**Comment by radvani** [comment]
Hi @keyserfaty, there may be an easy way we've discovered to add Algolia support. We'll keep you updated here.

**Comment by radvani** [comment]
Our new documentation sites (released today) feature search integration using Algolia:

https://docs.viromedia.com/docs
