### ISSUE TITLE
Viro won't start recording

### ISSUE THREAD

**Issue by Tino-F** [viromedia/viro#644]
- [X] Review the documentation: https://docs.viromedia.com/
  - [X] Search for existing issues: https://github.com/viromedia/viro
  - [X] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: IPhone 7, IOS 12.2
3. Version: ViroReact version and React Native version 
"react-viro": "2.14.0",
"react-native": "0.59.3",
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc) IPhone 7

## Description

When I try to use the `startVideoRecording` funtion, it doesn't actually start recording so when I stop recording, I get the 5 error code (meaning that recording was never started). The function is being ran and I have verified it, but it won't start recording. I have microphone and camera permissions already and am able to take pictures. I also don't get any error message when running the `startVideoRecording` function, so I tried "catching" the error, but I still couldn't get it.

## Reproducible Demo

```
startRecording( onErr ) {

    if ( !this.viroRef || !this.viroRef.sceneNavigator || !this.viroRef.sceneNavigator.startVideoRecording ) {

      onErr('viroRef has not been loaded');

    } else {

      let now = new Date();
      now = now.toISOString();
      now = now.replace( /\:|\./g, '-');
      let fileName = this.props._id + '_' + now;

      try {
        this.viroRef.sceneNavigator.startVideoRecording( fileName, false, onErr )
      } catch ( err ) {
        console.log('recording error:', err);
      }

    }

  }

async stopRecording() {
    let video = await this.viroRef.sceneNavigator.stopVideoRecording();
    return video;
  }
```

**Comment by Tino-F** [comment]
I fixed the issue. It actually was recording, but because it triggered a state update in the parent component, it reloaded the AR scene and stopped the recording session. Thanks for all the help everyone!

**Comment by anusha-fission** [comment]
@Tino-F is the recorded .mp4 file getting saved for the first time in iOS. I am getting error code 0 for the first time recording after that it works fine.

Any sample code for recording a video would be helpful for me if you could share it.

Thanks in advance!
