### ISSUE TITLE
YouTube Video as AR Content

### ISSUE THREAD

**Issue by ornelasEduardo** [viromedia/viro#649]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS 12.3.1
3. Version: ViroReact v2.13.0, React Native v0.57.7
4. Device(s): iPhone 8 Plus

## Description
Hello! I was wondering if there was a way to use a YouTube video as the content revealed when an image is recognized in AR? I know that `ViroVideo` only accepts a static path to a static video so I tried solving this by rendering a WebView instead of `ViroVideo` if the path to the video was a YouTube link but I was getting the following error:

`Exception thrown while executing UI block: -[RCTView setSuperview:]: unrecognized selector sent to instance 0x11f634f00`

Which seems like it's saying that using a RN component is an invalid child for `ViroARImageMarker`

So, is there any way to have a YouTube video be the content that is displayed when an image is detected in AR?

## Reproducible Demo
```
<ViroARImageMarker>
    <WebView
        source={{
            html: '
                <iframe 
                    width="400px" 
                    height="200px" 
                    src="https://www.youtube.com/embed/cqyziA30whE" 
                    frameborder="0" 
                    allow="autoplay; 
                    encrypted-media" allowfullscreen
                >
                </iframe>'
        }}
        style={{marginTop: 20}}
    />
</ViroARImageMarker>
```

**Comment by dam00n** [comment]
Unfortunately it is not possible to use a youtube video URL within a ViroVideo and the web view is not supported as you discovered. RN components can not be used within a ViroScene.
