### ISSUE TITLE
How to refer sub-object or sub-group within an object file

### ISSUE THREAD

**Issue by faizan1990** [viromedia/viro#652]
I have an OBJ file then I am trying to render using `Viro3DObject`. I want to know is there any method or property anywhere in Viro React that allows me to refer one of the multiple sub-objects or sub-groups (identified by `o` or `g` in the obj file)?

My goal is to be able to pop up a text when a user taps on a certain sub-object. For example, there's an object with following sub-objects / meshes:

```
obj1
obj2
obj3
obj4
```

I want Viro React to tell me which one of these sub-objects the user has touched. I have used `onClick` and `onClickState` methods. It returns the X,Y,Z coordinates of the touched point but not the object name as defined in OBJ file. Is there any other method that does so?

Any help will be much appreciated.

Thanks.

**Comment by dam00n** [comment]
Hi @faizan1990, this is not possible with ViroReact. The onClick is the best option but as you noted is provides X,Y,Z and not the subobject name.
