### ISSUE TITLE
use_frameworks! conflict with (FirebaseCore)

### ISSUE THREAD

**Issue by stricker26** [viromedia/viro#656]
## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: (10.14.5)
3. Version: ViroReact version (2.14.0) and React Native version (0.58.6)
4. Device(s): iPhone 6, 8, X

## Description
Error: The ‘XXX’ target has transitive dependencies that include static frameworks: (FirebaseCore).

Excluding use_frameworks! affects building project.

**Comment by achuvm** [comment]
Hi, see our documentation here regarding the use of the static library:

https://docs.viromedia.com/docs/no_use_frameworks
