### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by keyserfaty** [viromedia/viro#657]
Seems to be a lot of unanswered questions/bug reports lately. Anyone working on this project anymore?

**Comment by cuongtora1996** [comment]
I did want to ask a question before I see this.

**Comment by radvani** [comment]
Yes, we're releasing again shortly with assorted bug fixes. We'll also be cleaning up issues; we don't have the bandwidth to get to all "how to" issues but we do add all bugs to our backlog and try to address as soon as possible.
