### ISSUE TITLE
HLS in Android

### ISSUE THREAD

**Issue by newbot23** [viromedia/viro#66]
HLS works fine in iOS - normal stream and even adaptive. 
HSL does not work in Android. 

Error: 
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

Streams: 
Adaptive: http://player.vimeo.com/external/231992762.m3u8?s=ad80951022693de245a532b4c01bde2808e01636
HLS 640x386: https://skyfire.vimeocdn.com/1508921023-0x8bda84f05b98b5781572ad893f98684382851cd1/231992762/video/821174298/playlist.m3u8

According to ExoPlayer Documentation (https://google.github.io/ExoPlayer/guide.html#preparing-the-player): "The ExoPlayer library provides MediaSource implementations for DASH (DashMediaSource), SmoothStreaming (SsMediaSource), HLS (HlsMediaSource) and regular media files (ExtractorMediaSource)"

Seems to me that Viro uses ExtractorMediaSource, so we can't use HLS right now. 

Could you please give us a hint, how could we get HLS stream to play now in Android?

**Comment by VikAdvani** [comment]
Hi @newbot23, thanks for alerting us to this issue! Currently there isn't a way to do this on android. That being said we've added this issue in our backlog and will update this thread when we fix it which should be in our next release.

**Comment by newbot23** [comment]
Hi @VikAdvani, thanks for your quick reply! Would you please tell us whether we should expect the fix this month, next month or probably this year? It's very important feature for us, so we can't launch our product (more information via pm) without that. So we need to make a decision whether we can wait till your next release.

**Comment by VikAdvani** [comment]
Hi @newbot23, we looked into this and we'll be able to get the fix into our next release which will be in mid november.  Hopefully that works for you :)

**Comment by newbot23** [comment]
Hi @VikAdvani, thanks for your feedback and time, mid November is OK for us, so we will wait till that:)

**Comment by newbot23** [comment]
Hi @VikAdvani, thanks for the update! HLS does work now, so we are more than happy:)
