### ISSUE TITLE
Viro360image and Viro360Video low quality on ViroPortal

### ISSUE THREAD

**Issue by DiiegoLopez** [viromedia/viro#663]
When i try to use my own 360 images or videos on ViroPortal the quality is a bit low, it is a problem with the ViroPortal or do i need higher resolution images and videos?

**Comment by dam00n** [comment]
We have not seen any issue with resolution on the ViroPortal component. We are not doing any processing of the 360 photo. Try a higher resolution if you can. Many site recommend 4k or 8k for 360 photo viewing.
