### ISSUE TITLE
Remote location glb does not render

### ISSUE THREAD

**Issue by masierraf** [viromedia/viro#664]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android OS 9.0 & Android 8.0
3. Version: ViroReact version 2.14.0 and React Native version  0.59.3
4. Device(s): Huawei Mate 20 Pro & Samsung Galaxy S8

## Description
I've been used obj files to render my models but a few days ago I created a glb file to test it and it worked with a local location. 
```javascript
 require("./../../../public/face.glb")
```

The problems appears when i want to use a remote location, the models just doesnt appears and i dont get any error.

this is my code

```javascript
<ViroNode position={this.state.position}>
            <ViroAmbientLight color="#fff" />
            <Viro3DObject
              //source={require("./../../../public/face.glb")}
              source={{ uri: model_url }}
              //type="OBJ"
              type="GLB"
              highAccuracyEvents={true}
              //resources={resources}
              onPinch={this._onPinch}
              onError={err => console.log("error: ", err)}
              onLoadStart={this._onLoadStart}
              onLoadEnd={this._onLoadEnd}
              scale={this.state.scale}
              rotation={this.state.rotation}
              ref={this._refARObject}
              onDrag={() => {}}
              dragType={"FixedDistance"}
              animation={{ name: "rotateObj", run: true, loop: true }}
            />
          </ViroNode>
```

I comment the lines that i changed to test it.

This is my model
[face.zip](https://github.com/viromedia/viro/files/3356076/face.zip)

**Comment by hajtuJ** [comment]
To see error use `onError={err => console.log("error: ", err.nativeEvent.error)}`
