### ISSUE TITLE
Failed to load bundle in react native

### ISSUE THREAD

**Issue by vaisakhcp** [viromedia/viro#666]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `./hooks/useDispatch` from `/Users/pumba/Documents/Workspace/CodeBase/TazweedBusiness/node_modules/react-redux/lib/index.js`: The module `./hooks/useDispatch` could not be found from `/Users/pumba/Documents/Workspace/CodeBase/TazweedBusiness/node_modules/react-redux/lib/index.js`. Indeed, none of these files exist:
  * `/Users/pumba/Documents/Workspace/CodeBase/TazweedBusiness/node_modules/react-redux/lib/hooks/useDispatch(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/pumba/Documents/Workspace/CodeBase/TazweedBusiness/node_modules/react-redux/lib/hooks/useDispatch/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)` (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.213
    RCTCxxBridge.mm:414
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread

**Comment by Tino-F** [comment]
Looks like an issue with Redux, not Viro
