### ISSUE TITLE
Is VIRO compatible with Epson's MOVERIO BT-300?

### ISSUE THREAD

**Issue by danbugs** [viromedia/viro#672]
## Environment
1. Developing on macOS Mojave version 10.14.5.
2. Version 10.14.5.
3. Running `react-viro --version` I get:
```
react-viro-cli: 2.14.0
react-native-cli: 2.0.1
react-native: 0.59.3
```
4. Trying to compile the application for Epson's MOVERIO BT-300 smart glasses (app was tested in an iPhone X and works fine).

## Description && Reproducible Demo

1. I connected the smart glasses to my computer.
2. I ran `react-native run-android` to start to install the application on the device. 
3. Right off the bat, I get this error:
<img width="587" alt="Screen Shot 2019-07-16 at 7 22 29 PM" src="https://user-images.githubusercontent.com/39843321/61334146-98965980-a7ff-11e9-8421-fbc07189aa87.png">

However, I managed to fix this by removing the following lines of code and removing the references of wherever I used the created materials.
```
ViroMaterials.createMaterials({
   grid: {
     diffuseTexture: require('./res/grid_bg.jpg'),
   }
})
```

4. Now I got another error:
<img width="590" alt="Screen Shot 2019-07-16 at 7 23 41 PM" src="https://user-images.githubusercontent.com/39843321/61334191-c7143480-a7ff-11e9-82f4-a5c97fb3ef28.png">

I also managed to fix this by removing the following lines of code and removing the references of wherever I used the created animations.
```
ViroAnimations.registerAnimations({
   rotate: {
     properties: {
       rotateY: "+=90"
     },
     duration: 250, //.25 seconds
   },
});
```

5. After this, I actually managed to get a pleasant screen as you can see, here:
<img width="588" alt="Screen Shot 2019-07-16 at 7 24 07 PM" src="https://user-images.githubusercontent.com/39843321/61334273-2114fa00-a800-11e9-9ef8-f51566d075c8.png">

6. However, if I select AR, I get:
<img width="585" alt="Screen Shot 2019-07-16 at 7 24 20 PM" src="https://user-images.githubusercontent.com/39843321/61334302-4144b900-a800-11e9-8646-57ba3e25ed78.png">

7. And, if I select VR, I get:
<img width="587" alt="Screen Shot 2019-07-16 at 7 30 39 PM" src="https://user-images.githubusercontent.com/39843321/61334317-4a358a80-a800-11e9-9b42-75fa52106b89.png">

This kinda indicates that even the most default components don't work these smart glasses, which is a bit odd considering that, to my understanding, it is simply another Android system.

## Questions
- Generally, am I doing anything wrong? 
- If there is support, how can I make this work?
- If there isn't support, will you plan to add it?
- Can I hack this to make it work?

## Code 

```
'use strict';

import React, { Component } from 'react';

import {StyleSheet} from 'react-native';

import {
  ViroARScene,
  ViroText,
  ViroConstants,
  ViroBox,
  Viro3DObject,
  ViroSpotLight,
  ViroAnimations,
  ViroDirectionalLight
} from 'react-viro';

export default class HelloWorldSceneAR extends Component {

  constructor() {
    super();

    // Set initial state here
    this.state = {
      text : "Initializing AR..."
    };

    // bind 'this' to functions
    this._onInitialized = this._onInitialized.bind(this);
  }

  render() {
    return (
      <ViroARScene onTrackingUpdated={this._onInitialized} >
        {/* <ViroNode position={[0,-1,0]} dragType="FixedToWorld" onDrag = {() => {}}>
          <Viro3DObject
              source={require('./res/emoji_smile/emoji_smile.vrx')}
              materials={["grid"]}
              position={[-.5, .5, -1]}
              scale={[.2, .2, .2]}
              type="VRX" />
        </ViroNode> */}
        <Viro3DObject
          source={require('./res/model.obj')}
          position={[0, -.5, -1]}
          scale={[.001, .001, .001]}
          diffuseColor={"#f0f"}
          animation={{name: "rotate", run: true, loop: true}}
          type="OBJ"
        />
        <ViroText text={this.state.text} scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle}/>
        <ViroDirectionalLight
            color="#ffffff"
            direction={[0, -1, 0]}
        />
        <ViroSpotLight innerAngle={5} outerAngle={90} direction={[0,-1,-.2]}
          position={[0, 3, 1]} color="#ffffff" castsShadow={true} />
      </ViroARScene>
    );
  }

  _onInitialized(state, reason) {
    if (state == ViroConstants.TRACKING_NORMAL) {
      this.setState({
        text : "Hello World!"
      });
    } else if (state == ViroConstants.TRACKING_NONE) {
      // Handle loss of tracking
    }
  }
}

var styles = StyleSheet.create({
  helloWorldTextStyle: {
    fontFamily: 'Arial',
    fontSize: 30,
    color: '#ffffff',
    textAlignVertical: 'center',
    textAlign: 'center',  
  },
});

// ViroMaterials.createMaterials({
//   grid: {
//     diffuseTexture: require('./res/grid_bg.jpg'),
//   }
// })

// ViroAnimations.registerAnimations({
//   rotate: {
//     properties: {
//       rotateY: "+=90"
//     },
//     duration: 250, //.25 seconds
//   },
// });

module.exports = HelloWorldSceneAR;
```

**Comment by AleeeKoi** [comment]
@danbugs is it?
