### ISSUE TITLE
ViroPortal 3D Object Design

### ISSUE THREAD

**Issue by mazhang2718** [viromedia/viro#678]
I am trying to create a custom 3D .obj for use with the ViroPortal component. Are there any specifications available for creating the portal design? I'm currently having trouble making it so that the AR Scene is visible through the object that I am currently using. Thanks!

**Comment by saboteur111** [comment]
The way you set your scene to be visible through the portal object is making sure the portal itself has an alpha texture with 0% opacity/transparency. Anywhere on your object with 0% alpha will make the AR scene visible through it.

**Comment by saboteur111** [comment]
Also, please reference this post: https://blog.viromedia.com/how-to-build-ar-portals-in-5-mins-w-react-native-viro-ar-b939850def94

**Comment by mazhang2718** [comment]
That worked, thanks!
