### ISSUE TITLE
Coordinates based anchors

### ISSUE THREAD

**Issue by Francesco122** [viromedia/viro#679]
Hi all, does Viro React allow to create Anchors based on world coordinates like you do in ArCore with the instruction createAnchor(Pose) documented at https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/Anchor ?
I have to firmly show a 3d object in a specific place in the real world and I can't figure out how to do it with viro's ArPlanes system of anchoring.

**Comment by radvani** [comment]
Yes, you can use one of ARScene's createAnchoredNode methods. See [here]([https://developer.viromedia.com/virocore/reference/com/viro/core/ARScene.html#createAnchoredNode(com.viro.core.Vector)]).

**Comment by Francesco122** [comment]
Thank you for your fast reply **radvani** but I was looking for a pure javascript cross-platform solution. 
Is there a way to do that by means of just React Viro apis?

**Comment by radvani** [comment]
Right, sorry I got mixed up there between Javascript and Java. For React Viro, any time you make a ViroNode a direct child of your ViroARScene, it will automatically (under the hood) anchor the node using the ARCore createAnchor(Pose) API you referenced above.

**Comment by Francesco122** [comment]
Ok I'll try right now, thank you very much.
