### ISSUE TITLE
3D PLA Animation

### ISSUE THREAD

**Issue by mazhang2718** [viromedia/viro#691]
Hello, we are trying to implement some 3D Animation into a scene. Our animator program delivered a .fbx file with a .pla folder containing .mc and .xml files. Is there a way to use the information contained in the .pla folder to make the animation work? Or does all 3D animation need to be contained in .fbx files?

**Comment by dam00n** [comment]
Viro does not support pla files. The 3D animation needs to be contained in with FBX or GLTF files.
