### ISSUE TITLE
Local object assets are throwing Error: Duplicate resources

### ISSUE THREAD

**Issue by sercanov** [viromedia/viro#698]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.19 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.3 => 0.60.3

## Description

Local object assets ( .OBJ, .MTL ) are failing when building for release. It's probably related to https://github.com/facebook/react-native/issues/22234 tried `react.gradle` `doLast` hacking but still no luck. It works on debug mode.

Tried both `assembleGvrRelease` and `assembleArRelease`

Also I'm using react-native 0.60.3 which requires gradle 3.4.1

Any ideas ? 

Execution failed for task ':app:mergeArReleaseResources'.
> [raw/assets_res_salad_salad] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_salad_salad.mtl      [raw/assets_res_salad_salad] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_salad_salad.obj: Error: Duplicate resources
  [raw/assets_res_steak_steak] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_steak_steak.mtl      [raw/assets_res_steak_steak] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_steak_steak.obj: Error: Duplicate resources
  [raw/assets_res_salmon_salmon] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_salmon_salmon.mtl  [raw/assets_res_salmon_salmon] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_salmon_salmon.obj: Error: Duplicate resources
  [raw/assets_res_cake1_cake1] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_cake1_cake1.mtl      [raw/assets_res_cake1_cake1] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_cake1_cake1.obj: Error: Duplicate resources
  [raw/assets_res_cake2_cake2] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_cake2_cake2.obj      [raw/assets_res_cake2_cake2] /Users/sercanov/Projects/ARt/diner/DinerApp/android/app/src/main/res/raw/assets_res_cake2_cake2.mtl: Error: Duplicate resources

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by sercanov** [comment]
Okay, this isn't related to Viro, it's related to react-native.

**Comment by sumetENG45** [comment]
@sercanov what is solution you use for this issue?

**Comment by sercanov** [comment]
hey @sumetENG45 it's related to this https://github.com/facebook/react-native/issues/22234

**Comment by creimers** [comment]
I was able to solve the problem applying [this solution.](https://github.com/facebook/react-native/issues/22234#issuecomment-613439045)
