### ISSUE TITLE
Viro React Video - any way to display full screen instead of left/right split view?

### ISSUE THREAD

**Issue by jaguardigital** [viromedia/viro#700]
Hi

We're using ViroReact on MacOS using Visual Studio Code to create an App for displaying 360 videos from a Kaltura server, and when we use the Testbed in the Viro Media App in iPhone, it works perfectly. 

We have only one question: is there any way to display the video in full screen instead of the default left/right cardboard style? Our client doesn't want the videos to be displayed splitted.

Thanks for any help you may give us.

**Comment by dam00n** [comment]
https://github.com/viromedia/viro/issues/12

**Comment by jaguardigital** [comment]
thanks! We couldn't find it in the video documentation
