### ISSUE TITLE
Viro360Image is taking a few seconds to load

### ISSUE THREAD

**Issue by cfilipek** [viromedia/viro#702]
Viro360Image is taking a few seconds to load... is there a way to set an onload end and then display a loading screen when this is false and then all the rest of my viroScene when this is true? like so:
<img width="604" alt="Screen Shot 2019-08-21 at 8 50 42 AM" src="https://user-images.githubusercontent.com/31299149/63433234-cbc89b80-c3f0-11e9-8b8a-41f33fa3ad5e.png">

**Comment by cfilipek** [comment]
I'm getting the error that "Text strings must be defined within a <Text> component

**Comment by dthian** [comment]
Hey @cfilipek, it is definitely possible to display a ViroText "loading...." screen that then disappears when the Viro360Image tex is loaded (by toggling visibility or animating opacity). All this should be handled by the application.

From the above, it looks like you are trying to mix and encapsulate 2D React components (React.Fragment) within Viro3D ones - this is currently not supported as React's 2D elements aren't configured to be placed in a 3D environment and thus it would make sense in it's current state.

However, having said that, we have ViroFlexViews and Text views that should do the trick.

**Comment by cfilipek** [comment]
Great thank you-- I'll give that a try! It's interesting because React.Fragment was working before I added the conditional

**Comment by cfilipek** [comment]
Sweet we got it to work through our redux store. Thanks for letting me know that it was indeed possible! 👍
