### ISSUE TITLE
console.log is not working when running viro media app

### ISSUE THREAD

**Issue by cfilipek** [viromedia/viro#704]
Hi again, so I am having trouble getting my console.logs to show up or really work at all. I am wondering where I should see them? Is it supposed to be in the terminal where I run npm start and get my ngrok code?

I am placing the console log inside an onclick function much like the Viro documentation. I can provide a screenshot if necessary!

**Comment by tomascg2309** [comment]
Hello! I'm also new on using viro and I figured out how to see the console.log results. If you are running the testdeb application, shake your phone and activate the option **remote JS remotely**, it will open a new tab on your browser. Once there, inspect the page and go to the console and check what you are looking for.
Hope it could help you!

**Comment by cfilipek** [comment]
Thank you! Yes we had tried to use debug JS remotely before. But I think our problem was that we were attempting it from an android phone. I just tried it again and it worked!! Thanks 👍
