### ISSUE TITLE
Materials for ViroQuad don't render

### ISSUE THREAD

**Issue by tomascg2309** [viromedia/viro#705]
## Environment
1. Development OS: Windows
2. Device OS & Version: Windows 10 Home 64-bit
3. Version: ViroReact 2.16.0 and React Native 0.59.3
4. Device(s): iPhone6s iOS version 12.4

## Description
Hey guys! I'm trying to render a ViroQuad after a marker is detected, but materials are not rendering, so I can't see the ViroQuad. Extra: Shadows are visible.

## Reproducible Demo

  render() {
    return (
      <ViroARScene>
        <ViroARImageMarker
          target={"myTarget"}
          onAnchorFound={this._onAnchorFound}
          pauseUpdates={this.state.pauseUpdates}
        >
          ... some code

          <Viro3DObject
            source={require('./res/objects/Munny.obj')}
            type="OBJ"
            scale={[.005, .005, .005]}
            rotation={[0,-90,0]}
            materials={this.state.texture}
            animation={{ name: this.state.currentMunnyAnimation, run: this.state.animateMunny, loop: this.state.loopMunnyAnimation, onFinish: this._changeMunnyAnimation, interruptible: true }}
            onClick={this._toggleButtons}
          />

          <ViroText
            text="A geeky creative agency"
            style={styles.default_text}
            width={1000}
            materials={["white_mtl"]}
            scale={[0,0,0]}
            position={[0,0,.05]}
            extrusionDepth={4} 
            animation={{ name: this.state.currentTextAnimation, run: this.state.animateText, loop: true, onFinish: this._changeTextAnimation, interruptible: true }}
          />
          
          <ViroSpotLight
            innerAngle={5}
            outerAngle={60}
            direction={[1,-1,-1]}
            position={[-1,3,3]}
            color="#ffffff"
            castsShadow={true}
            shadowMapSize={2048}
            shadowNearZ={2}
            shadowFarZ={7}
            shadowOpacity={.2}
            intensity={100}
          />

          <ViroQuad
            rotation={[-90, 0, 0]}
            position={[0, -0.001, 0]}
            width={.5} height={.5}
            arShadowReceiver={true}
            materials={["bone"]}
          />
          
        </ViroARImageMarker>
      </ViroARScene>
    );
  }
	... more code
}

![WhatsApp Image 2019-08-23 at 13 05 43](https://user-images.githubusercontent.com/44789618/63613707-fbb99f80-c5a6-11e9-807c-1024f8af0bdf.jpeg)

Thank you very much in advance!
Cheers!

**Comment by dthian** [comment]
Can you provide how the code where you've defined the "bone" material that you are setting on the quad?

**Comment by tomascg2309** [comment]
Sure! It is:
bone: {
    diffuseColor: "rgb(245,245,220)",
    lightingModel: "PBR",
  }

**Comment by dthian** [comment]
Interesting, so I don't think you can re-use the "AR Shadow Quad" that you have above (and apply another material on it). This is because that quad's material is already being used to generate the fake shadow that you see.

You can try using a separate second quad for your material instead (one without any arShadowReceiver references)

**Comment by tomascg2309** [comment]
ok, now it works perfect! thank you for the advice!
