### ISSUE TITLE
Flickering/glitching markers in location based AR

### ISSUE THREAD

**Issue by sanderwapstra** [viromedia/viro#710]
![ezgif-3-4bcc168e0e70](https://user-images.githubusercontent.com/20322474/63836399-ca135080-c979-11e9-950c-75a390592ea9.gif)

We are building a location based feature in an app and with help of #131 this works really nice.

One issue we have is glitching markers and I don’t know what's causing it. I’ve seen the tickets #458 and #111 but we're still experiencing flickering/glitching. See attached video, this explains it better.

My markers look like this:
```
                        <ViroFlexView
                            key={`container_${index}_${highlight.arData.distance}`}
                            materials="marker"
                            height={1}
                            width={1}
                            scale={[highlight.arData.scale, highlight.arData.scale, highlight.arData.scale]}
                            position={[highlight.arData.x, 0, highlight.arData.z]}
                            style={styles.highlight}
                            transformBehaviors={['billboard']}
                        >
                            <ViroImage height={0.49} width={0.49} source={{ uri: highlight.vr_image }} />

                            <ViroText
                                key={`text_${index}_${highlight.arData.distance}`}
                                text={highlight.arData.prettyDistance}
                                style={styles.highlightText}
                                scale={[0.2, 0.2, 0.2]}
                            />
                        </ViroFlexView>
```

The scale is to ensure a marker doesn’t get smaller than 2 and larger than 5. 
```
const DISTANCE_MIN = 2;
const DISTANCE_MAX = 5;
```
```
    getScale(highlight, min, max) {
        const scaleRatio =
            ((DISTANCE_MAX - DISTANCE_MIN) * (highlight.arData.distance - min)) / (max - min) + DISTANCE_MIN;

        return highlight.arData.distance / scaleRatio;
    }
```

Any idea what could cause this? Let me know if I need to provide more information or share more code. Thanks you!

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Latest
3. Version:
react 16.8.3
react-native 0.59.3
react-viro: 2.14.0
4. Device(s): Samsung S8, iPhone X (less flickering than Samsung)

**Comment by marvinernst-cognitio** [comment]
How did you solve this problem because i got same problem..

**Comment by sanderwapstra** [comment]
@marvinernst-cognitio It was a problem with the marker data, not the above code. I had double markers and they were at the same position. This caused the glitches.
