### ISSUE TITLE
Documentation falsly claiming Viro AR under Android does not support autofocus

### ISSUE THREAD

**Issue by bonflintstone** [viromedia/viro#714]
I am skipping the requirements as this is solely an issue with the documentation.

https://docs.viromedia.com/docs/viroarimagemarker claims auto focus is not possible under android, but in fact it has been added to ar core and also viro a while ago and is available and documented in ViroARSceneNavigator.

**Comment by dam00n** [comment]
Thank you for this correction. Documentation has been updated as noted.
