### ISSUE TITLE
[Feature Request] - Text shadow style support for <ViroText>

### ISSUE THREAD

**Issue by robwebdev** [viromedia/viro#72]
It would be great to be able to add a text shadow style to ViroText components so that white text can be readable over light backgrounds.

**Comment by VikAdvani** [comment]
Hi @robwebdev, thanks for the feature request. We'll update this issue when we ship this feature.

**Comment by dam00n** [comment]
Outline and drop shadow for text has been added in the latest update, ViroReact 2.9

Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

Documentation here -> https://docs.viromedia.com/v2.9.0/docs/virotext2#section-outline-and-drop-shadow
