### ISSUE TITLE
3DObject resources with file system path / uri doesn't work

### ISSUE THREAD

**Issue by sercanov** [viromedia/viro#754]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
3. Version: ViroReact 2.16.0 and React Native 0.61.1 
4. Device(s): iPhone 8

## Description
VRT3DObject `resources` source doesn't work with file system path like below: 

```javascript
<Viro3DObject
type="OBJ"
source={{
uri:"/var/mobile/Containers/Data/Application/C544EBCA-4173-4693-91C3-5AEC8519785B/Documents/models/5d5e5075dc0c6d00bae8d140/object.obj" 
}}
resources={[
{uri:"/var/mobile/Containers/Data/Application/C544EBCA-4173-4693-91C3-5AEC8519785B/Documents/models/5d5e5075dc0c6d00bae8d140/material.mtl" }, 
{url: "/var/mobile/Containers/Data/Application/C544EBCA-4173-4693-91C3-5AEC8519785B/Documents/models/5d5e5075dc0c6d00bae8d140/texture.jpg"}
]} 
```
Object works okay, It renders the physical object but it's white, without textures.

Also, opaque types works perfectly. `require('assets/material.mtl') `

**Comment by sercanov** [comment]
It may be related to; https://github.com/viromedia/viro/issues/488 https://github.com/viromedia/viro/issues/11

**Comment by sercanov** [comment]
Well, false alarm. File system path as source is working.
It was related to .mtl file name in .obj file 😅

**Comment by soadtechdev** [comment]
@sercanov Hello, I would like to know what problem we had with the name of the mtl and obj, I have the same problem, it loads the object but blank
