### ISSUE TITLE
Converting FBX file to VRX format, detailed instructions

### ISSUE THREAD

**Issue by dam00n** [viromedia/viro#76]
Hello, I've looked at the page http://docs.viromedia.com/docs/3d-objects but am still not clear on the steps to convert fbx to vrx using the ViroFBX script. Do you have more detailed instruction on how to use the script to convert fbx files? Thanks.

**Comment by dam00n** [comment]
Here are some more detailed instructions which hopefully help.

1. Run the script from the bin directory -> i.e. [Project Name]/bin. 

2. In the documentation we provide the following example script

./ViroFBX js/res/model.fbx js/res/model.vrx

Example script broken down
- ./ViroFBX runs the script
- js/res/model.fbx is the location of the fbx file you want to convert
- js/res/model.vrx is the name and location of the vrx file that will be export

**Comment by aca-hakan-pinar** [comment]
Where can I download the converter?

**Comment by Ayzekberk** [comment]
> Here are some more detailed instructions which hopefully help.
> 
> 1. Run the script from the bin directory -> i.e. [Project Name]/bin.
> 2. In the documentation we provide the following example script
> 
> ./ViroFBX js/res/model.fbx js/res/model.vrx
> 
> Example script broken down
> 
> * ./ViroFBX runs the script
> * js/res/model.fbx is the location of the fbx file you want to convert
> * js/res/model.vrx is the name and location of the vrx file that will be export

thank you man !

**Comment by waqaskhanroghani** [comment]
There is no bin directory in my project where i run the following command  
./ViroFBX path/to/model.fbx path/to/model.vrx

**Comment by vinaycoder404** [comment]
whin i run command its not creating file insted its opening ViroFBX file
