### ISSUE TITLE
API key is invalid or missing

### ISSUE THREAD

**Issue by Kartik199** [viromedia/viro#799]
The new open sourced version of Viro React(2.17.0) doesn't provide or ask API but when it's deployed in a phone, it pops an error message saying "Your API key is missing or invalid!!". And the "Get API key" page is also removed. How to resolve this? 

I started using Viro just after it got out sourced. So, currently, I don't have an API key.

**Comment by DianaCruz16** [comment]
I have the same issue... any help?

**Comment by Kartik199** [comment]
Just update the viro version to 2.17 and above and it justs works fine
thereafter

**Comment by nuribom01** [comment]
I also have the same issue.
I use the following source.
https://github.com/viromedia/viro/tree/master/code-samples

Execute the following in code-samples.

$npm start
$react-native run-android --variant=gvrDebug

However, immediately after running the app,'your api key is missing/invalid' is displayed and it cannot be executed.
If the viro version is not 2.17, how can I update it to 2.17 and use it in this source?

Plz, help me
