### ISSUE TITLE
AR Initiation Error: Invariant Violation: requireNativeComponent: "VRTText" was not found. VR Initiation Error: Invariant Violation: requireNativeComponent: "VRT360Image" was not found in UIManager.

### ISSUE THREAD

**Issue by neha-swapnil** [viromedia/viro#804]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases
![Screenshot_1578367140](https://user-images.githubusercontent.com/27182388/71865936-86e89b80-312a-11ea-8e8d-c9c1471c80ad.png)
![Screenshot_1578367156](https://user-images.githubusercontent.com/27182388/71865937-86e89b80-312a-11ea-9ae8-4ccec503ff2b.png)

## Environment
Please provide the following information about your environment:
1. Development OS: Windows
2. Device OS & Version: Color OS & Android OS version (9.0 pie)
3. Version: ViroReact 0.59.3 version  and React Native 2.0.1 version 
4. Device(s): ReaalMe 5 Pro

## Description
I have followed all the steps from the official website but this error is not going away.

If I follow this, "[List of changes to make to a react-native package to correctly link react-viro. ](https://gist.github.com/manbod/5a7f7d0511ff4b4c7f78086ee4706932)" my gradle fails and the application kind-of crashes.

Please Help, Thank You.

**Comment by neha-swapnil** [comment]
@dam00n @dthian @radvani @ascorbic 

Tagging for visibility.

**Comment by ascorbic** [comment]
@neha-swapnil Why are you tagging me?

**Comment by neha-swapnil** [comment]
@ascorbic 

Your name popped up for you might have committed to the viro repositories previously.

**Comment by ascorbic** [comment]
I once submitted a small PR. I don't work for Viro. In any case, it's bad form to tag people into issues "for visibility". The people who need to know will already have been notified about the issue.

**Comment by neha-swapnil** [comment]
Sorry for that.

**Comment by vadermemo** [comment]
same issue here:

"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-viro": "2.17.0"
  },

MacOS Catalina 10.15.2

**Comment by problemSolver9000** [comment]
@neha-swapnil did you ever solve this? I'm seeing this

**Comment by Peege151** [comment]
I too am seeing this.  

App built in Xcode (wahoo) but then when the AR scene starts I see this.

**Comment by dthian** [comment]
If setting up a native project, don't forget to run the native setup instructions: [Android](https://docs.viromedia.com/docs/installing-viro-android), [iOS](https://docs.viromedia.com/docs/starting-a-new-viro-project-1).

**Comment by Peege151** [comment]
@dthian Yes!! That was it, I basically followed the instructions over here at issue [https://github.com/viromedia/viro/issues/769](url) . Basically I had gotten comfortable in the Viro-Media environment that when I went to build it I forgot about those steps.  Thank you!

**Comment by MaksymMalin** [comment]
same /CAnnot get it work on windows but alo need to update gradlew becaue of 14 version of java. IT runs and show UImanager error.

**Comment by Ahmadbkar** [comment]
Help me please i got the same error
