### ISSUE TITLE
Build app for offline use

### ISSUE THREAD

**Issue by BryanHY** [viromedia/viro#805]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS 13.2.2
3. Version: ViroReact version (2.17.0) and React Native version (0.59.9)
4. Device(s): iPad 7th generation

## Description
I am trying to build my app for release and install it on my iPad for offline use. Would like to know how I can do that. Thank you.

**Comment by Kartik199** [comment]
Did you get to know how to use it offline?
