### ISSUE TITLE
Generate ViroReact application APK (production release deployment package)

### ISSUE THREAD

**Issue by kanaseranjit** [viromedia/viro#826]
Hi,

# Environment
1. Development OS: Windows
2. Device OS & Version: Android 10
3. Version: ViroReact version  and React Native version 
4. Device(s): Samsung Tablet

# Steps
We are developing AR application using ViroReact. We are able to run that in android device using Testbed mode of ViroMedia application

Note: We are using default ViroReact sample AR application generated by below provided steps.
https://docs.viromedia.com/docs/quick-start-windows
react-native init ViroSample --version=0.59.3
 
Now we need to build .apk (installation package) for android production release. We dont want to publish it on Playstore, want to use it for testing purpose only before that.

We are following all the steps from below URLs for generating APK for our application.

https://facebook.github.io/react-native/docs/signed-apk-android
https://docs.viromedia.com/docs/android-distribution

We are able to generate APK file using those steps and application is getting installed properly.

When we open that app in Samsung Tab we are able to see first screen with AR and VR navigation buttons and when we click on AR button then application getting crashed. Error log is as below,

15551 15574 E ReactNativeJS: Invariant Violation: requireNativeComponent: "VRTText" was not found in the UIManager.
15551 15574 E ReactNativeJS:
15551 15574 E ReactNativeJS: This error is located at:
15551 15574 E ReactNativeJS:     in VRTText
15551 15574 E ReactNativeJS:     in ViroText
15551 15574 E ReactNativeJS:     in VRTARScene
15551 15574 E ReactNativeJS:     in ViroARScene
15551 15574 E ReactNativeJS:     in n
15551 15574 E ReactNativeJS:     in VRTARSceneNavigator
15551 15574 E ReactNativeJS:     in ViroARSceneNavigator
15551 15574 E ReactNativeJS:     in n
15551 15574 E ReactNativeJS:     in RCTView
15551 15574 E ReactNativeJS:     in RCTView

Please let us know steps to resolve this issue.

Thanks in advance...

**Comment by dthian** [comment]
Sounds like you might not have followed the steps for setting up ViroReact for Android? 
https://docs.viromedia.com/docs/installing-viro-android

**Comment by kanaseranjit** [comment]
@dthian Thanks for your reply 

we didnt able to fix this issue by this changes.

then we downloaded viroreact latest sample application from git and then integrated our code requirements into it. That code package is able to build and generate APK.

Thanks,

**Comment by dthian** [comment]
Thanks, closing issue as it is fixed.
