### ISSUE TITLE
How to pass data/params through ViroARSceneNavigator 

### ISSUE THREAD

**Issue by vivikenen** [viromedia/viro#83]
Hi,
Just wondering how to pass data/params through ViroARSceneNavigator?
Is it same as react-navigation?

**Comment by achuvm** [comment]
Hi @vivikenen,

See this related question:

https://github.com/viromedia/viro/issues/62

If you're interested in data-storage in React Native in general, refer to this post:

https://github.com/viromedia/viro/issues/29#issuecomment-319602465

Let me know if you have any more questions!

Andy

**Comment by vivikenen** [comment]
Hi Andy, 
Thx for your replay~

[Pass props through the ViroSceneNavigator (#62)](https://github.com/viromedia/viro/issues/62) works fine for me 

Vivikenken
