### ISSUE TITLE
Not able to run the app on an iOS device

### ISSUE THREAD

**Issue by zOok91** [viromedia/viro#854]
## Environment
1. Development OS: Mac
2. Device OS & Version: iOS version (13.3.1)  Xcode - Version 11.4.1
3. Version: 
         react-viro-cli: 2.17.0
         react-native-cli: 2.0.1
         react-native: 0.59.9
4. Device(s):  iPhone 8 plus, iPhone 11 pro

## Description
This is the first time I am trying to setup react-viro and I am able to setup the development environment and able to see the demo AR/VR app on the testbed as well as on the Simulator when I build it through Xcode but I am getting an error when I try to run it on any iOS device.

Steps that i followed from the docs after installing all the required dependecies-
  ```
  react-viro init ViroSample
  cd ViroSample
   npm install
  ./setup-ide.sh --ios
```
   I open the ViroSample.xcworkspace in Xcode and build it and the build succeeds but it does not open in my phone, it just freezes on the white screen with the name of the app and in Xcode I get this error-

<img width="850" alt="Screenshot 2020-05-04 at 11 44 17 AM" src="https://user-images.githubusercontent.com/20403227/80948450-2aa93600-8e03-11ea-93f3-77db0b34a5c5.png">

After checking through other issues reported, tried the https://docs.viromedia.com/docs/no_use_frameworks and after that it gives me this error

<img width="852" alt="Screenshot 2020-05-04 at 11 54 26 AM" src="https://user-images.githubusercontent.com/20403227/80948544-6217e280-8e03-11ea-915c-9fed6b2f3cd7.png">

I would really appreciate any help at all.
## Reproducible Demo
I am not adding any new packages, just creating the demo app using **react-viro init**

**Comment by nazmifeeroz** [comment]
hi @zOok91 
the react-viro doesn't seem to be maintained well.
use this package instead, 
https://github.com/citychallenge/viro
This works for me on iOS and android.

**Comment by BackOrder** [comment]
I'm also having issues on both Android and iOS (iPhone 7). It crashes on iOS and a black screen on Android.

**Comment by zOok91** [comment]
After reading through almost all the possible solutions on the internet, finally what worked for me was to update my IOs version from `13.3.1` to `13.4.1`. I am able to build the app through Xcode and it runs on my Iphone 8 plus now.

Closing this as this is resolved for me.

**Comment by zOok91** [comment]
@BackOrder What exactly is happening in your case when you try to run it on your Iphone ? Also, were you able to run it on your Iphone through the testbed app ?
