### ISSUE TITLE
React Viro don't work ios 13.5

### ISSUE THREAD

**Issue by Hayk-Zohrabyan** [viromedia/viro#873]
Hello.
I install the react-viro, but it does not work.
When the camera opens, the application closes, no errors.
I installed the application again as written in the documentation, but still the same ... does not work!

ios - 13.5.1
react-native - 0.62.2
react - 16.13.1

**Comment by danielpettifer** [comment]
@Hayk-Zohrabyan I had the same issue when opening the demo apps and accessing the camera however building a new app worked as expected on my iphone

**Comment by Hayk-Zohrabyan** [comment]
@danielpettifer I tried this application on different versions of the iPhone (ios 13.5.1), it still does not work (AR). When I open the application, it automatically closes.

https://apps.apple.com/us/app/viro-media/id1163100576
https://drive.google.com/file/d/13r11WAZiGRutIl7sVj_y4cbHI8a9Z3-D/view?usp=sharing

The same thing happens when I open a new application React Viro.

**Comment by Turtleted21** [comment]
because UIWebView https://github.com/viromedia/viro/issues/852

**Comment by ranjanpoudel1234** [comment]
I just upgraded my device to 13.5.1 and I am using react-native 0.61.5, no issues on my end.
