### ISSUE TITLE
build apk release

### ISSUE THREAD

**Issue by AliKHODR** [viromedia/viro#878]
##  Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version:  Android version 8.0.0
3. Version: ViroReact 2.17.0 and React Native 0.59.9 

## Description
i built an AR application and now i want to generate an apk release but i'm having this error : 
`
> Failed to notify project evaluation listener.
   > 'org.gradle.api.file.DirectoryProperty org.gradle.api.file.ProjectLayout.directoryProperty(org.gradle.api.provider.Provider)'`
## build.gradle : 
![Capture d’écran 2020-06-23 à 14 45 05](https://user-images.githubusercontent.com/55912430/85405292-7b662100-b560-11ea-94b9-24f903e3fbc9.png)
## gradle-wrapper.properties : 
![Capture d’écran 2020-06-23 à 14 44 30](https://user-images.githubusercontent.com/55912430/85405302-7ef9a800-b560-11ea-9e9b-e44ce5e7f4f7.png)

**Comment by sanddy-man** [comment]
@AliKHODR 
Did your resolve your issue?
