### ISSUE TITLE
ARCore Augmented Faces 

### ISSUE THREAD

**Issue by wilhart** [viromedia/viro#894]
I want to know wheter Viroreact support augmented faces from ARcore or not?

**Comment by doranteseduardo** [comment]
It seems like this repository is no longer mantainer so many developers created their own branches.
As far as I know, at least here are no plans to add augmented faces.

But as Viro relays on ARCore and ARKit and they support Augmented Faces, you could add that by yourself.

**Comment by CodingWithNobody** [comment]
Try this https://www.youtube.com/watch?v=2TkKFLvPA7E

**Comment by fukemy** [comment]
thanks @doranteseduardo, seem this lib is DEAD
