### ISSUE TITLE
3D Model Shows Up in Black

### ISSUE THREAD

**Issue by fcpau4** [viromedia/viro#90]
Hey guys! I am doing an AR app using Viromedia. Now I am trying to import my own 3d model to the app, which has been previously exported from Maya. I succeeded and I managed to see the 3d-model on the screen but the thing is that It all shows up completely in black. I read some issues revolving around the same problem... they say that the materials and textures might haven't been properly linked to the 3d model while exporting it. It's likely that it's down to this cause. If so, what should I do to link all the files properly? If you have other ideas about what the issue could be let me know, all suggestions are welcome! Thx in advance

**Comment by achuvm** [comment]
Hi @fcpau4,

First things first, have you tried adding an ambient light to the scene?

Something like this:
```
<ViroAmbientLight color="#ffffff" />
```

Let us know if that works for you, if not, we can debug some more.

Andy

**Comment by fcpau4** [comment]
Yes I did it. Before I forgot to say that Ive tried to import it in obj/mtl format but also with fbx/vrx. Here a capture of the code... pretty simple
<img width="1440" alt="captura de pantalla 2017-11-22 a les 10 46 35" src="https://user-images.githubusercontent.com/22548607/33120638-ff25f186-cf72-11e7-88fe-5f49b9a53a57.png">

**Comment by achuvm** [comment]
Hi @fcpau4,

Hmm that's interesting.

I notice that your resources are separated from your `vrx` file. The `vrx`/`fbx` file usually references its materials/textures relatively. Can you try placing the materials in the same directory as your `vrx` file?

Andy

**Comment by fcpau4** [comment]
Hey Andy! I ve just tried it and it didn't work :'(

**Comment by fcpau4** [comment]
@achuvm I've reimported the files, this time in obj/mtl (and with all the textures in the same folder as these two files), but my little monster is still in black... Let me know if you have any idea about what could be the issue. Thx!

**Comment by fcpau4** [comment]
![img_1208](https://user-images.githubusercontent.com/22548607/33209326-881d3a46-d115-11e7-9407-c31de7ec7ea7.JPG)

Here it is :) It should be glowing in pink...but nope

**Comment by dam00n** [comment]
Hi @fcpau4, sorry for the issues. Do you think you can send us the model so we can investigate some more? Thanks - Danny

**Comment by fcpau4** [comment]
Ok! Can I send it to the notifications email?

**Comment by dam00n** [comment]
You can email it to me directly, dmoon@viromedia.com. Thanks. Also if you have a screenshot of how it should look, can you attach that also? - Danny

**Comment by fcpau4** [comment]
Yes, sure! In 20 minutes I will send it to your email. Thank you Danny!

Cheers,

Pau

**Comment by dam00n** [comment]
Hi Pau, not sure if you sent the file over but I have not received it yet. If you are having issue due to file size, try using GDrive or Dropbox and send me the link. Thanks - Danny

**Comment by dam00n** [comment]
We were able to load the OBJ you provided in Maya, but it appeared black. This is due to material balls not pointing to textures. We assigned the material balls to their correct textures. Emailed you the updated model.

**Comment by dam00n** [comment]
Closing this issue as a solution was provided via email with a new model
