### ISSUE TITLE
Getting unable to resolve module create-react-class error

### ISSUE THREAD

**Issue by sankar9659** [viromedia/viro#908]
I m new to react native tring to add react-viro package in my project, I have created a sample project with react-native init sample command, and added the react viro package
The versions are,
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-viro": "2.17.0"
  },

when I run the app getting this error,

error: Error: Unable to resolve module `create-react-class` from `node_modules\react-viro\components\ViroSceneNavigator.js`: create-react-class could not be found within the project.

I have tried this linking process also,
https://docs.viromedia.com/docs/integrating-existing-projects-android
but still getting error.
Does this package supports for react native 0.63.3

**Comment by doranteseduardo** [comment]
Same as in #909
