### ISSUE TITLE
Unable to resolve module create-react-class error

### ISSUE THREAD

**Issue by sankar9659** [viromedia/viro#909]
I m new to react native tring to add react-viro package in my project, I have created a sample project with react-native init sample command, and added the react viro package
The versions are,

"dependencies": {
"react": "16.13.1",
"react-native": "0.63.3",
"react-viro": "2.17.0"
},

when I run the app getting this error,

error: Error: Unable to resolve module create-react-class from node_modules\react-viro\components\ViroSceneNavigator.js: create-react-class could not be found within the project.

I have tried this linking process also,
https://docs.viromedia.com/docs/integrating-existing-projects-android
but still getting error.
Does this package supports for react native 0.63.3

**Comment by doranteseduardo** [comment]
If I am correct (let me know if not) in React 16 the ::createClass syntax got deprecated.
Instead you can run `npm install --save create-react-class` from your project's root folder.

**Comment by sankar9659** [comment]
Invariant Violation: requireNativeComponent: "VRTText" was not found in the UIManager.

Tried this command  "setup-ide.sh --android"  doesn't help
My code is
import {
  ViroARScene,
  ViroText,
  ViroConstants,
} from 'react-viro';

 <ViroARScene onTrackingUpdated={this._onInitialized} >
          <ViroText text='hi' scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
        </ViroARScene>

**Comment by sankar9659** [comment]
@doranteseduardo 

shold i follow these steps for android?

**Comment by doranteseduardo** [comment]
I do not suggest you to use that if you want to use viro with the latest RN versions.
Better link manually.

[Start from here](https://docs.viromedia.com/docs/integrating-existing-projects-android#updating-your-application-file)

**Comment by sankar9659** [comment]
> I do not suggest you to use that if you want to use viro with the latest RN versions.
> Better link manually.
> 
> [Start from here](https://docs.viromedia.com/docs/integrating-existing-projects-android#updating-your-application-file)

Thanks let me try

**Comment by sankar9659** [comment]
I have installed the package and linked by adding these lines,

`android/build.gradlew-- changed the sdk version
minSdkVersion = 21  

android/app/build.gradlew -- added these lines in dependencies

    implementation project(':gvr_common')
    implementation project(':arcore_client')
    implementation project(path: ':react_viro')
    implementation project(path: ':viro_renderer')
    implementation 'com.google.android.exoplayer:exoplayer:2.7.1'
    implementation 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
    implementation 'com.amazonaws:aws-android-sdk-core:2.7.7'
    implementation 'com.amazonaws:aws-android-sdk-ddb:2.7.7'
    implementation 'com.amazonaws:aws-android-sdk-ddb-mapper:2.7.7'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.7.7'
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.7.7'
    implementation 'com.android.support:appcompat-v7:28.0.0'


android/app/src/main/androidmanifest.xml - inside the application added this lines,
android:usesCleartextTraffic="true"
  <meta-data android:name="com.google.ar.core" android:value="optional" />

<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true"
      android:theme="@style/AppTheme"
      >
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
             <category android:name="com.google.intent.category.CARDBOARD" />   
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data android:name="com.google.ar.core" android:value="optional" />

    </application>
      

In mainapplication.java -- added this line 

import com.viromedia.bridge.ReactViroPackage;
packages.add(new ReactViroPackage(ReactViroPackage.ViroPlatform.GVR));  


In settings.gradlew added this line:

include ':react_viro', ':arcore_client', ':gvr_common', ':viro_renderer'
project(':arcore_client').projectDir = new File('../node_modules/react-viro/android/arcore_client')
project(':gvr_common').projectDir = new File('../node_modules/react-viro/android/gvr_common')
project(':viro_renderer').projectDir = new File('../node_modules/react-viro/android/viro_renderer')
project(':react_viro').projectDir = new File('../node_modules/react-viro/android/react_viro')



My code is in app.js:

'use strict';

import React, {Component} from 'react';

import {StyleSheet, View} from 'react-native';

import {ViroARScene, ViroText, ViroConstants} from 'react-viro';

export default class HelloWorldSceneAR extends Component {
  constructor() {
    super();

    // Set initial state here
    this.state = {
      text: 'Initializing AR...',
    };

    // bind 'this' to functions
    this._onInitialized = this._onInitialized.bind(this);
  }

  render() {
    return(
  
  <ViroARScene onTrackingUpdated={this._onInitialized}>
         <ViroText
           text={this.state.text}
           scale={[0.5, 0.5, 0.5]}
           position={[0, 0, -1]}
           style={styles.helloWorldTextStyle}
         />
  </ViroARScene>
    )
   

      
    // );
  }

  _onInitialized(state, reason) {
    console.log('state',state)
    if (state == ViroConstants.TRACKING_NORMAL) {
      this.setState({
        text: 'Hello World!',
      });
    } else if (state == ViroConstants.TRACKING_NONE) {
      // Handle loss of tracking
    }
  }
}

var styles = StyleSheet.create({
  helloWorldTextStyle: {
    fontFamily: 'Arial',
    fontSize: 30,
    color: '#ffffff',
    textAlignVertical: 'center',
    textAlign: 'center',
  },
});

module.exports = HelloWorldSceneAR;

`


I'm getting a blank screen in my device, what is the issue in that,

Thanks

**Comment by doranteseduardo** [comment]
Are you asking for Camera permission?

**Comment by sankar9659** [comment]
Yes, I have added camera permission in the android manifest.xml

 `<uses-permission android:name="android.permission.CAMERA" />`

**Comment by sankar9659** [comment]
I want to achieve AR functionality.

But in this documentation, for AR functionality they have given just > symbol.

https://docs.viromedia.com/docs/integrating-existing-projects-android#updating-your-application-file

**Comment by sankar9659** [comment]
![image](https://user-images.githubusercontent.com/58698022/96265620-46844b00-0fe3-11eb-8055-cc1f6c0267fb.png)

**Comment by doranteseduardo** [comment]
No, I mean, asking for permission on runtime.
You could use react-native-permissions to achieve that.

**Comment by Rakesh14345** [comment]
Hi, i'm new to React-Native. I'm using this package and linked all libraries as you suggested. This is my package.json details
   "create-react-class": "^15.7.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-permissions": "^2.2.2",
    "react-viro": "2.17.0",

All linking were done and no errors were found. In Androidmanifest.xml file when i add   
<meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only"/> and check in my mobile S10+ it asks to insert mobile to Gear VR.

But at the same time i have doubt, What line should be added in the manifest file for AR operations? Currently i'm using this line 
   <meta-data android:name="com.google.ar.core" android:value="optional" /> but only seeing blank white screen on my mobile. It doesn't even ask me camera permission. Help me fix this issue. Thanks in Advance.

**Comment by Rakesh14345** [comment]
Can you give me sample code, regarding the lines which i need to insert in files?

**Comment by doranteseduardo** [comment]
Some permissions like Camera, Microphone and Location require the app to promt a message to the user asking for permissions, that's what's react-native-permissions is for.

You have to do that process in your React scene, using react-native-permissions to get Camera access, through the **check** and **request** methods.

**Comment by Rakesh14345** [comment]
I also tried with react-native-permissions and also i could receive permissions, but thing is i could see only blank screen after granting permissions.
<meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only"/> this is one we should add for achieving VR

What should be added in AndroidManifest file for achieving AR?

**Comment by jahau** [comment]
I've tried also fixed this by running `npm install --save create-react-class`

Also `react-native run-android --variant=gvrDebug` is executed without any problems now but when the app starts to open on phone, the app just flashes without starting properly. Any ideas?

**Comment by sankar9659** [comment]
Issue fixed Thanks a lot @doranteseduardo
