### ISSUE TITLE
No member named '__rip' in '__darwin_arm_thread_state64'

### ISSUE THREAD

**Issue by bharath989** [viromedia/viro#91]
![screen shot 2017-11-23 at 12 03 44 pm](https://user-images.githubusercontent.com/18612249/33160944-71a76004-d046-11e7-8bbf-6bf645cb546b.png)

I am missing something.

**Comment by achuvm** [comment]
Hi @bharath989,

This looks like an issue with glog & react-native.

Here's a thread with the exact same issue:
https://github.com/facebook/react-native/issues/16106

It sounds like they recommend using XCode 9.

Let us know if you still run into the issue,

Andy

**Comment by bharath989** [comment]
I am using Xcode 9. Still the problem persists

**Comment by bharath989** [comment]
I changed the name from Xcode 9 to Xcode and I don't have any other Xcode versions installed. I am struck here from many hours. Couldn't fix this

**Comment by achuvm** [comment]
Hi @bharath989,

This isn't an error we've seen before.

Can you try this:
- close XCode
- removing your node modules
-  then running `npm install` to reinstall the modules.
- `cd ios`
- `pod install`
- `open <your_project>.xcworkspace`

Let us know what you get out of that.

Andy

**Comment by bharath989** [comment]
Thanks Andy.. Issue is fixed but I have some questions regarding the application. So where to ask the questions about the app.

**Comment by achuvm** [comment]
Hi @bharath989,

I'm glad that worked for you!

If you want to contact us privately, feel free to use our contact us form on our website here:

https://viromedia.com/contact-1/

Andy

**Comment by bharath989** [comment]
Thanks Andy for the info
