### ISSUE TITLE
The development server returned response error code: 404, index.delta?platform=android

### ISSUE THREAD

**Issue by Jeeva111** [viromedia/viro#911]
Environment
1. Development OS: Windows
2. Device OS & Version: Android OS version (10) 
3. Version: ViroReact version (2.17.0) and React Native version (0.63.3)
4. Device(s): issue on (i.e. Vivo)

## Description
Date 06-10-20 Created an new project using
1. npx react-native init ReactAR
2. npm install -S -E react-viro
3. Copy the files from node_modules\react-viro\bin\files\javascript\* to the root of your directory.
4. Installed viro media on my device (Vivo) 
5. npm start
6. After enter my local ip or ngrok ip i got this
![Screenshot_20201006_130757](https://user-images.githubusercontent.com/25759317/95172749-68a4ee80-07d5-11eb-9947-ac783be9a94f.jpg)
7. Everything ok for lan i'm check other projects works good

**Comment by Jeeva111** [comment]
Works good on react-native 0.59.9 and nodejs v10 doesn't working on latest react-native

**Comment by pran01** [comment]
So I have to degrade my react-native version and node version so much for this? Weird😕
