### ISSUE TITLE
How to check target in rectangle in the middle of the screen

### ISSUE THREAD

**Issue by ThanhNghia944** [viromedia/viro#912]
Hi @dthian and everyone, let me ask how to check the target in the rectangle in the middle of the screen
I used ViroARImageMarker and the onHover function when the target was hovering, but I don't know how to check when the target is in my rectangle.
   because each time the app recognizes the target func on the Hover there is a different position.
 **<ViroARImageMarker target={"test"} 
          onAnchorFound={
            (event) =>   { 
              console.log('event',event)
          }}
          onHover = { (hover, position, source) => {
            console.log('eventonHover',hover)
            console.log('eventonHover position',position)
            //HOW TO CHECK IF HOVER = true
          }}
        >**
![aaa](https://user-images.githubusercontent.com/53257922/95615097-d715d500-0a91-11eb-9d3b-8fc232801f77.jpg)

**Comment by cenaHara** [comment]
I am also looking for such a solution, is there a way

**Comment by cenaHara** [comment]
@VikAdvani @ThanhNghia944  @dthian  Can you help me pls
