### ISSUE TITLE
Blackscreen showing when using ViroARSceneNavigator in react native 0.63.3 on Android 10

### ISSUE THREAD

**Issue by rgouzal** [viromedia/viro#913]
When using ViroARSceneNavigator in react native 0.63.3 I get a black screen showing only and i can't see the Ar objects like text for example I tried the same code for AR hello world.  At first I had the library crashing my app until I've been told by someone to better use **@citychallenge/react-viro** and the crash disappeared after installing it but now I see a black screen. 
How to solve this?

**React: 16.3.1**
**React Native: 0.63.3**
**React Viro: 2.17.4**
**OS: Android 10**
**Device: Samsung M31**

**Comment by kevinrodriguez-io** [comment]
Did you check you're importing arcore on your manifest?

**Comment by rgouzal** [comment]
> Did you check you're importing arcore on your manifest?

@kevinrodriguez-io Yes that was it. Thank you.

**Comment by sankar9659** [comment]
@kevinrodriguez-io  and @rgouzal  can you give the linking code for AR? (build.gradle file and android manifest file).
App not crashing and no errors, but getting a white screen. 

My android manifest file like this,

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.gallery_app_ar">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <category android:name="com.google.intent.category.CARDBOARD" />
            <category android:name="com.google.intent.category.DAYDREAM" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
     <meta-data android:name="com.google.ar.core" android:value="optional" />
    </application>

</manifest>
