### ISSUE TITLE
Are <ViroSkyBox /> Coordinates Able To Accept URIs

### ISSUE THREAD

**Issue by mikeyamato** [viromedia/viro#92]
Rather than pointing to static images located on the client am I able to apply URIs to the cube map? If so how should I structure it?

```
{
  nx:{uri: http://www.petwave.com/~/media/Images/Center/Care-and-Nutrition/Cat/Kittensv2/Kitten-3.ashx},
  px:{uri: http://www.petwave.com/~/media/Images/Center/Care-and-Nutrition/Cat/Kittensv2/Kitten-3.ashx},
  ny:{uri: http://www.petwave.com/~/media/Images/Center/Care-and-Nutrition/Cat/Kittensv2/Kitten-3.ashx},
  py:{uri: http://www.petwave.com/~/media/Images/Center/Care-and-Nutrition/Cat/Kittensv2/Kitten-3.ashx},
  nz:{uri: http://www.petwave.com/~/media/Images/Center/Care-and-Nutrition/Cat/Kittensv2/Kitten-3.ashx},
  pz:{uri: http://www.petwave.com/~/media/Images/Center/Care-and-Nutrition/Cat/Kittensv2/Kitten-3.ashx}
}
```
I did try the above setup with no luck.

**Comment by VikAdvani** [comment]
Hi @mikeyamato,
You should be able to load skybox images from a URI. The one restriction is the image needs have square dimensions, so the width and height need to be same. I tried the example above, and the Kitten-3 image width is 800 and the height is 533 which is why the URI's aren't working. If you point to an image with the same width/height it should work.

**Comment by mikeyamato** [comment]
@VikAdvani pardon the delay in getting back to you. I am unable to confirm success with using an URI yet. I have hit a snag. I update a few npm packages thinking that may help and now Xcode is giving me a "workspace intergrity" error. Looking at my package.json dependencies, are there items I need to downgrade? e.g. react-native

```
{
	"name": "ViroSample",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "^16.0.0",
		"react-native": "^0.50.0",
		"react-viro": "2.0.1",
		"watchman": "^0.1.8"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"eslint-config-airbnb": "^16.1.0",
		"eslint-plugin-import": "^2.8.0",
		"eslint-plugin-jsx-a11y": "^6.0.2",
		"eslint-plugin-react": "^7.4.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}
```
<img width="278" alt="screen shot 2017-11-23 at 12 41 25 pm" src="https://user-images.githubusercontent.com/27756216/33188095-c02136b0-d04b-11e7-9493-01b084c22f93.png">

**Comment by mikeyamato** [comment]
@VikAdvani I managed to resolve the issue. Can I ask how I should structure the <ViroSkyBox /> so that I can use it with URIs? The following methods were unsuccessful (I tried others, but none worked). 

```
          <ViroSkyBox source={
            nx:{uri:image},
            px:{uri:image},
            ny:{uri:image},
            py:{uri:image},
            nz:{uri:image},
            pz:{uri:image}
          } />
```
```
          <ViroSkyBox source={
            {nx:uri:image},
            {px:uri:image},
            {ny:uri:image},
            {py:uri:image},
            {nz:uri:image},
            {pz:uri:image}
          } />
```
```
          <ViroSkyBox source={
            nx:uri:image,
            px:uri:image,
            ny:uri:image,
            py:uri:image,
            nz:uri:image,
            pz:uri:image
          } />
```

**Comment by dthian** [comment]
Hi @mikeyamato, as seen under example use at https://docs.viromedia.com/docs/viroskybox1, the format of passing a uri source to a skyBox is as follows:
<ViroSkyBox source={{
               nx:image,
              px:image,
              ny:image,
              py:image,
              nz:image,
              pz:image}} />

**Comment by dthian** [comment]
Hi @mikeyamato, as seen under example use at https://docs.viromedia.com/docs/viroskybox1, the format of passing a uri source to a skyBox is as follows:


var image = [
 {uri:"https://pathToImage1.png"},
 {uri:"https://pathToImage2.png"},
 {uri:"https://pathToImage3.png"},
 {uri:"https://pathToImage4.png"},
 {uri:"https://pathToImage5.png"},
 {uri:"https://pathToImage6.png"},
];

Where
`
<ViroSkyBox source={{ 
nx:image[0], 
px:image[1], 
ny:image[2], 
py:image[3], 
nz:image[4], 
pz:image[5]}} 
/>
`

Like wise, you can also insert the uri's inline:
`
<ViroSkyBox source={{ 
nx:{uri:"https://pathToImage0.png"}, 
px:{uri:"https://pathToImage1.png"} 
ny:{uri:"https://pathToImage2.png"}, 
py:{uri:"https://pathToImage3.png"}, 
nz:{uri:"https://pathToImage4.png"}, 
pz:{uri:"https://pathToImage5.png"}}} 
/>
`
Hope that helps!

**Comment by mikeyamato** [comment]
Hi @dthian thanks for clarifying.

This isn't my week as I hit another [issue](https://github.com/facebook/react-native/issues/16287). When I try and run the 'ViroSample' (Hello World) in Xcode I'm being told that...

> -[UIApplication applicationState] must be used from main thread only

Since RN can't go beyond 0.49.3 to work with Viro, how can this be fixed manually?

**Comment by mikeyamato** [comment]
@dthian, 

The manual fix can be found [here](https://github.com/facebook/react-native/commit/e8c83d180f1691baf61a68323d95299354c7bde6).
