### ISSUE TITLE
React viro app keeps stopping on android device

### ISSUE THREAD

**Issue by arashmad** [viromedia/viro#928]
Following [this tutorial](https://reactnative.dev/docs/environment-setup), I create a boiler plate react native app using `nxp` command line . Then I added react-viro by `npm install -S -E react-viro` and finally configured project through [this document](https://docs.viromedia.com/docs/integrating-existing-projects-android). 
Now I can build app successfully and run it on real device so that the default menu of ViroSample app appears:

![Screenshot_۲۰۲۰۱۲۲۷-۱۰۳۷۱۴_rn_ar](https://user-images.githubusercontent.com/25149765/103165907-a17fbd00-4832-11eb-9116-2c7cd9a365e1.jpg)

But if I go to any of AR or VR menus, it crashes and I get Keeps Stopping.
Now I've realized there are some incompatible version installed for project. When I execute `npm list --depth`, I see this:
```
npm ERR! peer dep missing: react@16.8.3, required by react-viro@2.17.0
npm ERR! peer dep missing: react-native@0.59.9, required by react-viro@2.17.0
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.00-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1      
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.00-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
```
Should I downgrading installed version of mention libraries?

This is part of my `package.json`:
```
"dependencies": {
    "create-react-class": "^15.7.0",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-viro": "2.17.0"
  },
```

**Comment by asadadams** [comment]
Did you figure out the solution to the issue
