### ISSUE TITLE
Svg linking problems in Viro app.

### ISSUE THREAD

**Issue by AndreHjalmarsson** [viromedia/viro#93]
I'm trying to run my project in the viro app Testbed but get the error: "No component found for view with name "RNSVGLinearGradient".

I have linked the svg library and it is working when I use Xcode together with an emulator. I've also had it working together with Android studio and its' emulator. This problem only occurs when I run it via the Viro Media app.

Is there anything obvious I'm missing here?

Managed to solve this issue at last, seems the issue had to do with some Xcode settings.

**Comment by fixed-term-tylernguyen** [comment]
How were you able to link SVG with Viro components?
