### ISSUE TITLE
Invariant Violation: requireNativeComponent: "VRTText" was not found in the UIManager.

### ISSUE THREAD

**Issue by temurchichua** [viromedia/viro#930]
- [ *] Review the documentation: https://docs.viromedia.com/
  - [* ] Search for existing issues: https://github.com/viromedia/viro
  - [* ] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Windows
2. Device OS & Version: What Android OS 

## Description
I've fallowed all the instructions and tried everything I found on google but I'm still getting this error after I launch the Quick Start app from Android Studio:

E/ReactNativeJS: Invariant Violation: requireNativeComponent: "VRTText" was not found in the UIManager.
    
    This error is located at:
        in VRTText (at ViroText.js:252)
        in ViroText (at HelloWorldSceneAR.js:30)
        in VRTARScene (at ViroARScene.js:332)
        in ViroARScene (at HelloWorldSceneAR.js:29)
        in HelloWorldSceneAR (at ViroARSceneNavigator.js:469)
        in VRTARSceneNavigator (at ViroARSceneNavigator.js:493)
        in ViroARSceneNavigator (at App.js:102)
        in ViroSample (at renderApplication.js:35)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:98)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:115)
        in AppContainer (at renderApplication.js:34)
E/ReactNativeJS: Invariant Violation: requireNativeComponent: "VRTText" was not found in the UIManager.
    
    This error is located at:
        in VRTText (at ViroText.js:252)
        in ViroText (at HelloWorldSceneAR.js:30)
        in VRTARScene (at ViroARScene.js:332)
        in ViroARScene (at HelloWorldSceneAR.js:29)
        in HelloWorldSceneAR (at ViroARSceneNavigator.js:469)
        in VRTARSceneNavigator (at ViroARSceneNavigator.js:493)
        in ViroARSceneNavigator (at App.js:102)
        in ViroSample (at renderApplication.js:35)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:98)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:115)
        in AppContainer (at renderApplication.js:34)
I/com.virosample: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)

**Comment by temurchichua** [comment]
I've done everything right. It came out that all I needed to do was `file` > `Invalidate Caches / Restart` and it worked.

These are the references I used:

- https://docs.viromedia.com/docs/installing-viro-android#5-enable-developer-mode-on-android-device
- https://docs.viromedia.com/docs/integrating-existing-projects-android#updating-settingsgradle
- https://gist.github.com/manbod/5a7f7d0511ff4b4c7f78086ee4706932

**Comment by monkeyK1n9** [comment]
> I've done everything right. It came out that all I needed to do was `file` > `Invalidate Caches / Restart` and it worked.
> 
> These are the references I used:
> 
> * https://docs.viromedia.com/docs/installing-viro-android#5-enable-developer-mode-on-android-device
> * https://docs.viromedia.com/docs/integrating-existing-projects-android#updating-settingsgradle
> * https://gist.github.com/manbod/5a7f7d0511ff4b4c7f78086ee4706932

The links are broken. I having the same issue, please how did you solve it precisely?

**Comment by iamalinski** [comment]
I have a solution here: https://github.com/viromedia/viro/issues/748#issuecomment-1933535988
