### ISSUE TITLE
Invalid UIAccessibilityTraits

### ISSUE THREAD

**Issue by phillsv87** [viromedia/viro#933]
- [ X] Review the documentation: https://docs.viromedia.com/
  - [ X] Search for existing issues: https://github.com/viromedia/viro
  - [ X] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
1. Development OS: Mac
2. Device OS & Version: iOS 14.3
3. Version: ViroReact 2.17.0 / static lib,  React Native 0.63.4
4. Device(s): iPhone 11 Pro

## Description
Anytime a Switch component is rendered an "Invalid UIAccessibilityTraits" error occurs. I believe this is caused by the ViroViewManager. On line 42 of ( https://github.com/viromedia/viro/blob/master/ios/ViroReact/ViroViewManager.mm ) the enum converter for UIAccessibilityTraits is redefined and **does not include the 'switch' trait**. I think the enum converter definition should look like the default ReactNative definition - line 24 of https://github.com/facebook/react-native/blob/ea93151f21003df6f65dd173dd5dcb3135b0ae94/React/Views/RCTViewManager.m

(note) - I am statically linking the Viro library as describe here - https://docs.viromedia.com/docs/no_use_frameworks

![Error](https://user-images.githubusercontent.com/25496447/105120168-c10bad80-5a9f-11eb-9962-b5b7e7a9c657.png)

## Reproducible Demo
I have created a simple repo demoing the issue with 2 branches, one with Viro displaying the error and another without Viro and working as normal.

Example of error with Viro - https://github.com/phillsv87/ViroReact-Accessibility-Traits-Bug

Example of no error and no Viro - https://github.com/phillsv87/ViroReact-Accessibility-Traits-Bug/tree/no-viro

**Comment by phillsv87** [comment]
Hello???

**Comment by phillsv87** [comment]
So I fixed the glitch.

![fixed the glitch](https://i.imgur.com/DsfufGe.jpeg)

I removed Viro from my project.

Viro is out of date and it seams there are no active maintainers for the project.

**Comment by onmotion** [comment]
If anyone else needs to fix this problem, just add `accessibilityRole='button'` to the Switch component.

**Comment by qasimmehdi** [comment]
I am having the same issue with react-native-tab-view after I run pod install for viro. On Android it is working fine.
Error:
Invalid UIAccessibilityTraits 'tab'

**Comment by qasimmehdi** [comment]
I fixed the issue by forking react-native-tav-view and replacing accessibilityRole="tab" by "button"

**Comment by Weixuanf** [comment]
@onmotion Can you elaborate where is this  Switch component? I'm using viro-react and react-navigation in my project, having the same problem...

**Comment by marvinernst-cognitio** [comment]
@Weixuanf You have to edit Line 294 in `/node_modules/@react-navigation/bottom-tabs/src/views/BottomTabBar.tsx`
