### ISSUE TITLE
onTrackingInitialized does not seems to be called on HelloWorldSceneAR - iPhone 8

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#94]
I am testing out the React Native AR example. Seems to work fine showing the "Initializing AR..." text, but it never changes to "Hello World", so it does not seems like onTrackingInitialized is being called (iPhone 8)

**Comment by VikAdvani** [comment]
Hi @cjrorvik, what version of iOS are you running on the iPhone 8. ARKit only works on iOS 11 and higher. Do you have iOS 11 installed on the iPhone 8?

**Comment by cjrorvik** [comment]
Yup, iOS 11.1 installed

**Comment by cjrorvik** [comment]
iOS 11.1.2 update worked! ;)

**Comment by dam00n** [comment]
Awesome, glad it is working now, closing this issue.
