### ISSUE TITLE
AR crash when loading GLB model

### ISSUE THREAD

**Issue by sebastiaorodriguesdev** [viromedia/viro#946]
Since I'm working on windows and can't use the FBX to VRX converter thought I'd use GLB model so I can animate it, but when it starts loading viro media crashes. I'm running Android 11, React 7.7.6. and I'm using a Samsung Galaxy S10+ to run the program.
The code below is the code I'm using to use the GLB 3DModel.
`render() {
    return (
      <ViroARScene onTrackingUpdated={this._onInitialized} >
        <ViroAmbientLight color="white"/>
          <Viro3DObject 
                        source = {require ('./assets/F016.glb')}   
                        
                        type = "GLB"   
                        scale = {[0.5, 0.5, 0.5]}
                        position = {[0, 0, -10]}
                        onLoadStart={this._onLoadStart}
                        onLoadEnd={this._onLoadEnd}
                        onError={this._onError}

          />     
      </ViroARScene>
    );
  }
`

**Comment by AlexisHolyoak** [comment]
Hello, how did you fix this? I am having same issue now
