### ISSUE TITLE
Invariant Violation: requireNativeComponent: "VRTAmbientLight" was not found in the UIManager

### ISSUE THREAD

**Issue by Sandeep155Vibhuti** [viromedia/viro#952]
![ErrorImg](https://user-images.githubusercontent.com/75908175/121156662-83e56380-c866-11eb-8447-939442ae57d9.png)

"react": "17.0.1",
"react-native": "0.64.2",
"react-viro": "2.17.0",

**Comment by Roopal-dev** [comment]
Please Update to the Community Version of the Viro-react for react-native Latest Version Support. below is the Link : ->
https://github.com/ViroCommunity/viro
