### ISSUE TITLE
After Choosing Desired Experience (AR/VR), Screen is Completely White

### ISSUE THREAD

**Issue by mikeyamato** [viromedia/viro#97]
After selecting "AR" from the menu I see nothing but a white screen when pushed through Xcode. 

Here are the steps I took to get here:
Installed based on the [quick start guide instructions](https://docs.viromedia.com/docs/quick-start) >> pushed the app onto my iPhone via Xcode >> selected AR (AR or VR) >> white screen appeared.

Funny thing is that this worked when I went through ngrok. 

Note: I was experiencing this exact issue on my other Viro app that I had built further along. I deleted it thinking that there was something wrong with my setup. But this appears even after setting up Viro for the 'first' time.  

**package.json**
```
{
	"name": "ViroSample",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"prestart": "./node_modules/react-viro/bin/run_ngrok.sh",
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-beta.5",
		"react-native": "0.49.3",
		"react-viro": "2.1.0"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-beta.5"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

![img_0056](https://user-images.githubusercontent.com/27756216/33235605-2bdb0b38-d1f0-11e7-8a29-0326074c6aac.PNG)

**Comment by VikAdvani** [comment]
Hi @mikeyamato, did you run the setup-ide.sh script?  That script will properly setup the project with Viro and remove the warnings you are seeing and remove the white screen. 

On iOS you'll run the script on the terminal command line in the root directory of the project. You'd type './setup-ide.sh ios'. 

More info can be found in our guide to setting up XCode with Viro: https://docs.viromedia.com/docs/starting-a-new-viro-project-1

Let me know if that helps!

**Comment by mikeyamato** [comment]
other than [turning off bitcode](https://medium.com/@president/how-to-disable-bitcode-or-enable-bitcode-in-xcode-7-5d59b13d9230), everything is now working! thank you.
